### PR TITLE
fixes #5724: compare normalized file paths

### LINKED ISSUE #5681: Check for equality on ran statement breaks when changelog has "classpath:" as logicalFilePath
### Search first

- [X] I searched and no similar issues were found

### Description

The changes from #5141 changed the way changeset paths are checked for equality. Due to the newly introduced compatibility for older versions, there is an edge case that throws an InvalidPathException.

### Steps To Reproduce

Let the RanChangeSet receive a filePath that is different (even normalised) from the changelog and contains "classpath:"
See: https://github.com/Alf-Melmac/liquibase-issue-changeset-with-classpath
`java.nio.file.InvalidPathException: Illegal char <:> at index 9: classpath:/db/file.log`

### Expected/Desired Behavior

There is no exception thrown while starting the application with logical file paths containing a classpath definition

### Liquibase Version

Starting 4.25.0 up to 4.26.0

### Database Vendor & Version

_No response_

### Liquibase Integration

_No response_

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### LINKED ISSUE #5724: changeset with relative path deployed with liquibase 4.6.0 to 4.23.1 are replayed with liquibase > 4.23.1
### Search first

- [X] I searched and no similar issues were found

### Description

We have changeset with relativePath. They were deployed with liquibase 4.8.0 (but all versions between 4.6.0 and 4.23.0 are concerned).
When we tried to upgrade to liquibase 4.24.0 (same result with 4.25 & 4.26), these changesets were replayed.

### Steps To Reproduce

I use docker for this : 
```bash
# Start a postgres database
docker run -d --rm -it --name postgres -e POSTGRES_USER=myusername -e POSTGRES_PASSWORD=mypassword -p 5412:5432 postgres:12
```

```bash
# execute liquibase with any version from to 4.23.0
docker run --rm -it -v ${PWD}:/liquibase/changelog liquibase/liquibase:4.8.0 --changelogFile=changelog-master.yaml --classpath=/liquibase/changelog --url=jdbc:postgresql://host.docker.internal:5412/postgres\?user=myusername\&password=mypassword update
```

```bash
# check the databasechangelog table
postgres=# select id,filename from databasechangelog;
            id             |          filename
---------------------------+----------------------------
 model-create-table-person | model/changelog-table.yaml
(1 row)
```

```bash
# execute liquibase with any version from 4.23.1 to 4.26.0
docker run --rm -it -v ${PWD}:/liquibase/changelog liquibase/liquibase:4.26.0 --changelogFile=changelog-master.yaml --classpath=/liquibase/changelog --url=jdbc:postgresql://host.docker.internal:5412/postgres\?user=myusername\&password=mypassword update

...
Running Changeset: model/foo/../bar/../changelog-table.yaml::model-create-table-person::12345

UPDATE SUMMARY
Run:                          1
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:            1

ERROR: Exception Details
ERROR: Exception Primary Class:  PSQLException
ERROR: Exception Primary Reason: ERROR: relation "tb_person" already exists
ERROR: Exception Primary Source: PostgreSQL 12.18 (Debian 12.18-1.pgdg120+2)
```

### Expected/Desired Behavior

we expect : 
```
UPDATE SUMMARY
Run:                          0
Previously run:               1
Filtered out:                 0
-------------------------------
Total change sets:            1
```

### Liquibase Version

>= 4.23.2

### Database Vendor & Version

offline, postgresql

### Liquibase Integration

cli, docker, build with source code

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

linux

### Additional Context

create changelog-master.yaml file
```yaml
databaseChangeLog:
- include:
    file: model/foo/../bar/../changelog-table.yaml
    relativeToChangelogFile: true
```

create a model directory and add changelog-table.yaml file
```yaml
databaseChangeLog:
- changeSet:
    id: model-create-table-person
    author: "12345"
    changes:
    - createTable:
        tableName: TB_PERSON
        remarks: Person Table.
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: PK_PERSON
            name: PERSON_ID
            type: BIGINT
            remarks: PK
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by jgarec**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

fixes #5724 
fixes #5681 

To handle previous changeset deployed with 4.6.0 <= liquibase < 4.23.1; where filename contains relatives paths , this PR now compares filenames of incoming changeset and already executed changeset in the same way. 

## Things to worry about

Check current PR #5681 which impact the same code.

### CODE REVIEW

**Comment by filipelautert** [comment]
@jgarec thanks for the detailed issue and PR . I ran some tests and it failed on Windows, so I pushed some reordering to your fix and now it seems fine.

@Alf-Melmac this PR also fixes https://github.com/liquibase/liquibase/issues/5681 . I copied your new test from https://github.com/liquibase/liquibase/pull/5682 to this branch and it works as now we remove the `classpath `and `:` from the string as it was before. I also managed to reproduce your issue from https://github.com/Alf-Melmac/liquibase-issue-changeset-with-classpath and using this branch I get now: `ERROR: relation "test_table" already exists`. 

If both of you could give this PR another round of test I would be grateful.

**Comment by Alf-Melmac** [comment]
@filipelautert Thanks! The removal of Paths.get looks promising. I'll check against the production setup tomorrow.

**Comment by jgarec** [comment]
@filipelautert, Still ok for me with your fix 👍

**Comment by Alf-Melmac** [comment]
Can confirm that it also works in the actual project 👍

**Review by filipelautert — APPROVED** [review]

**Review by tati-qalified — APPROVED** [review]
I've tested multiple path types with different liquibase versions (4.9.1, 4.16.1, 4.24.0), to see if this build would recognise the path formats.

As far as I can tell, it works as expected. 
Here are some of the recognised syntaxes:
- `changelog.xml` or `./changelog.xml`
- `../changelog.xml`
- `folder1/subfolder/../changelog.xml` or `./folder1/subfolder/../changelog.xml`
- `classpath:/folder1/changelog.xml`
- `classpath:/folder1/subfolder/../changelog.xml`
- same but setting a searchpath instead of using `classpath:`

If there are any other formats I should test, let me know.

**Pull request merged**
