### PR TITLE
Fix BLOBs in loadData for MySQL/MariaDB 

### LINKED ISSUE #2519: bug: LoadData - MariaDB - does not work with BLOB column type
## Environment

**Liquibase Version**: 4.7.0

**Liquibase Integration & Version**: spring boot 2.7.0-M1, but is reproducible by cli

**Liquibase Extension(s) & Version**:

**Database Vendor & Version**: 10.5.11-MariaDB

**Operating System Type & Version**: does not matter

## Description
When we use `loadData` and there exists a BLOB column, then no data are populated in the DB at all. Even no exception is thrown, but in `databasechangelog` table the changeset is set as run.

## Steps To Reproduce

lets have `test.changelog.yaml`:
```
databaseChangeLog:
  - changeSet:
      id: "create-table"
      author: test
      changes:
        - createTable:
            tableName: person
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                  name: sys_pk
                  type: INT
              - column:
                  constraints:
                    nullable: false
                    unique: true
                  name: sys_id
                  type: BINARY(16)
              - column:
                  name: email
                  type: VARCHAR(320)
  - changeSet:
      id: "populate-data"
      author: test
      changes:
        - loadData:
            #            usePreparedStatements: false # cannot use this, because BLOB has needsPreparedStatement = true (see LoadDataChange::generateStatements)
            commentLineStartsWith: '#'
            encoding: UTF-8
            file: test.csv
            quotchar: '"'
            separator: ','
            tableName: person
            relativeToChangelogFile: true
            columns:
              - column:
                  header: sys_id
                  name: sys_id
                  type: BLOB
              - column:
                  header: email
                  name: email
                  type: STRING
```
and `test.csv` file:
```
sys_id,email
GlZze9T4EeurnDxSgk2x5A==,user01@example.com
GlZ0idT4EeurnDxSgk2x5A==,BRazo@example.com
GlZ16dT4EeurnDxSgk2x5A==,FBronson@example.com
GlZ3NdT4EeurnDxSgk2x5A==,RQuirk@example.com
GlZ4qNT4EeurnDxSgk2x5A==,WTownes@example.com
```

Values of sys_id contain BASE64 encoded binary UUIDs.

## Actual Behavior
- changeset `populate data` is marked as successful in `databasechangelog` table
- no data are pupulated in database
- no exception or warning can be found in log

## Expected/Desired Behavior
- changeset `populate data` is marked as successful in `databasechangelog` table
- data are pupulated in database

## Additional Context
- in https://github.com/liquibase/liquibase/issues/1551 there is suggestion to use `usePreparedStatements: false` but this does not help because BLOB type sets needsPreparedStatement = true (see `LoadDataChange::generateStatements`)
- this issue is probably caused by https://github.com/liquibase/liquibase/pull/2215 - a50e90b4c526521b516e548250c0fdeb415c3d92
- the logic in `LoadDataChange::generateStatements` collects data in `preparedStatements` list, but in the end the logic returns value based on variable `statements` (which is empty list), so all the prepared statemenets are "ignored" and nothing gets executed later.

```
            if (anyPreparedStatements) {
                // If we have only prepared statements and the database supports batching, let's roll
                if (databaseSupportsBatchUpdates && statements.isEmpty() && (!preparedStatements.isEmpty())) {
                    if (database instanceof PostgresDatabase) {
                        // we don't do batch updates for Postgres but we still send as a prepared statement, see LB-744
                        return preparedStatements.toArray(new SqlStatement[preparedStatements.size()]);
                    } else {
                        return new SqlStatement[]{
                                new BatchDmlExecutablePreparedStatement(
                                        database, getCatalogName(), getSchemaName(),
                                        getTableName(), columns,
                                        getChangeSet(), Scope.getCurrentScope().getResourceAccessor(),
                                        preparedStatements)
                        };
                    }
                } else {
                    return statements.toArray(new SqlStatement[statements.size()]); //##### all the statements are in variable "preparedStatements" but here variable "statements is used"
                }
            } else {
             ...
```

### PR DESCRIPTION
**Pull request by MichaelCkr**
## Environment

**Liquibase Version**: 4.6.2, 4.8.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**:  -

**Database Vendor & Version**: MariaDB 10.3.27

**Operating System Type & Version**: linux

## Pull Request Type

- [x] Bug fix (non-breaking change which fixes an issue.)
- [ ] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

closes #2519 

## Description

When we use ``loadData`` and there exists a BLOB column (``preparedStatement`` necessary), then no data are populated in the DB at all. Even no exception is thrown, but in ``databasechangelog`` table the changeset is set as run.

## Steps To Reproduce

see #2519 

## Actual Behavior

- changeset with ``loadData`` is marked as successful in ``databasechangelog`` table
- no data are populated in database
- no exception or warning can be found in log

## Expected/Desired Behavior

- changeset with ``loadData`` is marked as successful in ``databasechangelog`` table
- data are populated in database

## Screenshots (if appropriate)

-

## Additional Context

see #2519 and #2215 

I'm not sure, if the intention of #2215, increasing the performance of MySql data loading, is still fulfilled with this change. The probably slow batch update is not used, but prepared statements are used.

## Fast Track PR Acceptance Checklist:

- [x] Build is successful and all new and existing tests pass
- [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
- [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
- [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
- [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

### CODE REVIEW

**Comment by kataggart** [comment]
@MichaelCkr Thanks for your work here! We will review and move it through the process.

**Comment by MichaelCkr** [comment]
I have no clue, why the java 17 integration test failed regarding my changes. I'm quite sure, this is not related, therefore I have done a rebase on the current master.

Rebuild would be nice.

**Comment by MichaelCkr** [comment]
@nvoxland If possible, could you please set the SafeToBuild label again or sth similar to trigger another build?

**Comment by nvoxland** [comment]
Code review and test results:

It looks like the if statement this PR removes shouldn't have been there. It probably got left from a bad merge, and the performance issue it's trying to address is handled correctly already on line 521. Having the if statement there made it so we didn't load anything which is obviously wrong.

I created #liquibase/liquibase-test-harness#216 to test the change

Things to be aware of
- Impacts mysql and mariadb

Things to worry about
- Nothing

**Review by suryaaki2 — APPROVED** [review]

**Comment by MichaelCkr** [comment]
Thank you very much for adding the test, I [commented](https://github.com/liquibase/liquibase-test-harness/pull/216#issuecomment-1104060356) on your [PR](https://github.com/liquibase/liquibase-test-harness/pull/216).

The failure in the "Run Test Harness" check seems not to be related to my change, is it?

**Comment by nvoxland** [comment]
Correct, @MichaelCkr the failure in the test is not related to your PR. The automation that pulls the correct build of liquibase to test isn't correctly handling PRs from forks. I'm looking into that.

**Comment by MichaelCkr** [comment]
Simple workaround would be, to merge my commit into another bugfix branch within the original liquibase repo (and open another PR from the newly created branch to master).

**Comment by XDelphiGrl** [comment]
@nvoxland, there were MariaDB failures in the test-harness run. Can you take a look, please?

[Test Harness Results](https://github.com/liquibase/liquibase-test-harness/runs/6278554732?check_suite_focus=true)

**Comment by MichaelCkr** [comment]
Note for myself: [[Test Harness Results](https://github.com/liquibase/liquibase-test-harness/runs/6278554732?check_suite_focus=true)](https://github.com/liquibase/liquibase-test-harness/actions/workflows/main.yml?query=branch%3Abugfix%2F%232519_fixed-loadDataChange-for-MySQL-regarding-preparedStatements)

(I'm quite curios, how these checks may run against my branch. :) )

**Comment by nvoxland** [comment]
@MichaelCkr there is a build job in liquibase/liquibase-test-harness which can pull snapshot builds from liquibase PRs. We trigger that job as part of the PR build process

**Review by XDelphiGrl — CHANGES_REQUESTED** [review]
I've requested changes in the associated liquibase-test-harness PR. When those are done, let me know and I can take a look and finalize my review for this PR. 

CC @nvoxland , @MichaelCkr

**Review by XDelphiGrl — APPROVED** [review]
* Fix removes an IF that applied only to MySQL and excluded MariaDB (and others).
* Validating test cases added to test harness for MariaDB and MySQL.
  * The requested test harness PR changes are complete.
* No additional testing required.

APPROVED


[Passing Test Harness Execution](https://github.com/liquibase/liquibase/actions/runs/2336615738)
[Passing Functional Tests](https://github.com/liquibase/liquibase-pro-tests/actions/runs/2336711260)

**Comment by MichaelCkr** [comment]
Thanks for adding the Test Harness Tests, the review and the merge.

**Pull request merged**
