### PR TITLE
Fixed #4489: SQL Anywhere incorrectly reports VARCHAR(n CHAR) as VARCHAR(n)

### LINKED ISSUE #4489: SQL Anywhere incorrectly reports VARCHAR(n CHAR) as VARCHAR(n)
### Search first

- [X] I searched and no similar issues were found

### Description

SQL Anywhere is able to limit CHAR and VARCHAR columns to a width either denoted in bytes or in characters. As characters can be wider than one byte, the difference is crucial.

SQL Anywhere lists the difference in a vendor-specific meta table, but it fails to do so using JDBC DatabaseMetaData. As a result, Liquibase cannot "see" wether the width is in bytes or in characters. Hence, when rebuilding a database from a previously generated changelog, all width is in bytes but not in characters then.

The cause of this trouble is a bug in the proprietary closed-source JDBC driver reported by me today to SAP. Nevertheless, Liquibase needs a workaround to deal with this driver bug, at least until there is a fixed driver.

### Steps To Reproduce

```bash
liquibase generateChangelog
dberase -c DBF=mydb.db, ...
liquibase update
```

### Expected/Desired Behavior

`CHAR(n CHAR)` and `VARCHAR(n CHAR)` fields should be discovered as char-sized, not as byte-sized.

### Liquibase Version

master

### Database Vendor & Version

SAP SQL Anywhere 17.0.11

### Liquibase Integration

N/A

### Liquibase Extensions

N/A

### OS and/or Infrastructure Type/Provider

Windows 10 Pro (German)

### Additional Context

N/A

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by mkarg**
## Description
Fixes #4489 

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Cause: There is no way to detect the size unit in the JDBC standard.

Solution: Using a native query to detect the size unit.

## Things to be aware of

N/A

## Things to worry about

N/A

## Additional Context

N/A

### CODE REVIEW

**Comment by mkarg** [comment]
@nvoxland Kindly requesting your review. :-)

**Review by filipelautert — APPROVED** [review]
Seems fine, new native sql for sql anywhere. Thanks!

**Review by suryaaki2 — APPROVED** [review]

**Review by nvoxland — APPROVED** [review]

**Comment by mkarg** [comment]
This is a showstopper at least for SQL Anywhere.

**Comment by rberezen** [comment]
This pull request addresses the issue in Liquibase where the detection of CHAR(n CHAR) and VARCHAR(n CHAR) fields as byte-sized instead of char-sized caused problems in SQL Anywhere.

- Functional and test harness executions passing.
- No additional testing required.

APPROVED

**Review by rberezen — APPROVED** [review]

**Pull request merged**
