### PR TITLE
Added default values to private Scope constructor

### LINKED ISSUE #3554: ScopeManager is STILL getting confused when dealing with a heavy thread load
## Environment

**Liquibase Version**: 4.17

**Liquibase Integration & Version**:  gradle

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Microsoft SQL Server

**Operating System Type & Version**: linux kubernetes pods

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>

## Description

The same as https://github.com/liquibase/liquibase/issues/2248 which I reported and thought was fixed in 4.17. 
 We deployed today to production and I'm seeing many Kibana messages like
`liquibase.exception.LiquibaseException: java.lang.RuntimeException: Cannot end scope pymuajkpzs when currently at scope pyeogsnvjy 	at liquibase.Liquibase.runInScope(Liquibase.java:2452) 	at liquibase.Liquibase.update(Liquibase.java:236) 	at liquibase.Liquibase.update(Liquibase.java:221) 	at liquibase.Liquibase.update(Liquibase.java:207) 	at liquibase.Liquibase.update(Liquibase.java:197) 	at com.concur.reportdbservice.manager.ReportingSchemaMgr.update(ReportingSchemaMgr.java:69) 	at com.concur.reportdbservice.service.ReportingSchemaService.updateDatabase(ReportingSchemaService.java:56) 	at com.concur.reportdbservice.service.MigTaskService.entityMigrate(MigTaskService.java:51) 	at com.concur.reportdbservice.thread.MigMigrateJob.executeJob(MigMigrateJob.java:27) 	at com.concur.reportdbservice.thread.Job.run(Job.java:46) 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) 	at java.base/java.lang.Thread.run(Unknown Source) Caused by: java.lang.RuntimeException: Cannot end scope pymuajkpzs when currently at scope pyeogsnvjy 	at liquibase.Scope.exit(Scope.java:230) 	at liquibase.Scope.child(Scope.java:191) 	at liquibase.Scope.child(Scope.java:179) 	at liquibase.Scope.child(Scope.java:158) 	at liquibase.Liquibase.runInScope(Liquibase.java:2447) 	... 14 more
--`

Obviously with varying scope names.
## Steps To Reproduce
Same as https://github.com/liquibase/liquibase/issues/2248

## Actual Behavior
Same as https://github.com/liquibase/liquibase/issues/2248

## Expected/Desired Behavior
Same as https://github.com/liquibase/liquibase/issues/2248

### PR DESCRIPTION
**Pull request by MarkTJohnson**
Since that constructor is the only used for creating the root scope, the scopeId was previously left null.  The change is to set that value to the string "root".  This is to prevent a NPE when the Scope.exit is called on the root scope.

Closes #3554

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Changes make sense to me. Our code doesn't seem to hit the spot where it's a problem having scopeId==null but #3554 seems to and this should fix it.

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Comment by MarkTJohnson** [comment]
Thank you @MalloD12 !  Hopefully this will fix the problem and I will no longer have to maintain 2 different code bases.  One set of our code is used by gov't entities and they required us moving to a newer version which was fine since that environment didn't have nearly the load that our commercial environment has.  Commercial has been stuck on 3.10 because of the threading issues I have brought up.

**Review by MalloD12 — APPROVED** [review]
**Approved**.

## Review and testing results:

Changes looks good to me. I tried to updated an existent unit test to validate new set up, but I could see it behaves differently depending on the OS. So decided to leave it as it was. 

### Things to be aware of:
- None

### Things to worry about:
- None

**Review by XDelphiGrl — APPROVED** [review]
Liquibase v4.17 introduced a `ThreadScopeManager` to handle synchronization of threads but this did not fully resolve problems handling multithreading . The problem manifests as runtime exceptions that Liquibase "cannot end scope X when currently at scope Y." This PR fixes the issue by defining the scopeId as "root" instead of leaving it undefined.
* Functional and test harness executions passing.
* No additional testing required.

@MarkTJohnson - thank you for the PR!

APPROVED

**Review by filipelautert — APPROVED** [review]
Thanks @MarkTJohnson  ! Hopefully you can join your codebases after we release 4.19.1

**Pull request merged**
