### PR TITLE
More efficient XML resource loading

### LINKED ISSUE #1815: Too many open files error on application server: LiquibaseEntityResolver opens too many file descriptors and never closes them
## Environment
* Java version: OpenJDK 11
* Liquibase Version: newest (4.3.3)
* Liquibase Integration & Version:  Java API (we're using new `new Liquibase().listUnrunChangeSets` manually). It's called from within a webapp with Jetty 9 / Tomcat 8 / Tomcat 9 / JSF 2.3 / Weld 3.1.7.
* Database Vendor & Version: tested with MySQL 8 and PostgreSQL 12, but probably independent of DBMS
* Operating System Type & Version: Ubuntu (tested on 18.04 and 20.10)

## Description
Symptoms are the same as #1449, but not sure if it's the same cause (we're not using Spring). When running Liquibase, it opens many file decriptors and never closes them. They only get closed when the Garbabe  Collector runs, which may be a long in the future. This results in our application server crashing.

I first observed this on a test environment server with Tomcat 8 after upgrading vom liquibase 3 to liquibase 4. The webapp failed to start, and the log contained many `too many open files` messages. Checking via `/proc/pid/fd` indeed revealed that the number of file descriptors had reached the limit. At first I could not reproduce this locally on my machine, but now I can and I think I know why it happens:

image

The problematic part is in [LiquibaseEntitiyResolve](https://github.com/liquibase/liquibase/blob/256675bca43a089e32c940e10ed8ed7a5f9d66f6/liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java#L38), which is called when Liquibase parses the database changelogs (we've got 11 XML changelog files) after we call `Liquibase#listUnrunChangeSets´.

When the `LiquibaseEntityResolver` is constructed, it [also creates a `fallbackResourceAccessor`](https://github.com/liquibase/liquibase/blob/256675bca43a089e32c940e10ed8ed7a5f9d66f6/liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java#L19) of type `ClassLoaderResourceAccessor`. The `ClassLoaderResourceAccessor`  loads all JARs of the application, but [does so only lazily](https://github.com/liquibase/liquibase/blob/256675bca43a089e32c940e10ed8ed7a5f9d66f6/liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java#L51) only when its `#openStreams` method is called. 

Next the `LiquibaseEntityResolver` [creates a `CompositeResourceAccessor`](https://github.com/liquibase/liquibase/blob/256675bca43a089e32c940e10ed8ed7a5f9d66f6/liquibase-core/src/main/java/liquibase/parser/core/xml/LiquibaseEntityResolver.java#L38) with the resource loader from the current scope and the fallback resource loader.  Now, and that's where the error starts happening, the composite resource accessor [always calls `openStreams`](https://github.com/liquibase/liquibase/blob/256675bca43a089e32c940e10ed8ed7a5f9d66f6/liquibase-core/src/main/java/liquibase/resource/CompositeResourceAccessor.java#L34) on _all_ accessors, regardless of whether an earlier found something or not.

This means that `init` method of the fallback `ClassLoaderResourceAccessor` is always called, loading all JARs.

In our case the `LiquibaseEntityResolver` is created about ~20 times, and each time it loads ~300 JARs. The fiel descriptor limit on the server is 4000, so it crashes before liquibase is done.

What I had been wondering is why I cannot observe this behavior locally, but now I've got an explanation for that. The same process I described above _actually does happen_  on my machine, but: the file descriptors are closed implicitly by the `finalize`  of the `ZipFileSystem`. When I debug into the application, I can observe the file descriptors growing on my machine as well. It's just that I seem to get lucky that the garbage collector kicks in early enough before even more file descriptors are opened. When 
I increased the file descriptor limit on the test server, it finish running liquibase, but it only ran the finalizer and closed the file descriptor several minutes later (peak was ~6500 open file descriptors)

image

- - -
Is that enough information to reproduce? Not sure what the best solution here might be, but I guess some things that could be done are (i) closing the created file systems explicitly, (ii) not creating a new fallback accessor each time, (iii) not using the fallback accessor when the resource accessor from the current scope already returns a result.

### LINKED ISSUE #1913: Classpath scan time lapse for every included changelog file
## Environment
**Liquibase Version**: 4.3.5

**Liquibase Integration & Version**: Maven 3.2.5

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: PostgreSql 10.8.1

**Operating System Type & Version**: Windows 7

## Description
Hello,

While ugrading an app from SpringBoot 2.4.6 to 2.5.1, Liquibase dependency was updated from 3.10.3 to 4.3.5, the database management startup time increased from 4 seconds to 33 seconds.

For my changlog, I use an inclusion for each applicative version (32 times).

`<include file="major/minor/version-number.xml" relativeToChangelogFile="true" />`

With a profiling (see joined capture), it appears that with Liquibase 4.3.5, the classpath is scanned for each of the 32 resource files, which leads to an increase of the whole process duration. This behaviour did not occur in previous versions (Liquibase 3.10.3).

Regards,

## Before upgrade Liquibase 3.10.3 (SpringBoot 2.4)
<pre>
15/06/2021 10:51:21.234 INFO  [main] xx - Starting xx<br>
15/06/2021 10:51:21.294 INFO  [main] xx - No active profile set, falling back to default profiles: default<br>
15/06/2021 10:51:21.894 INFO  [main] hikari.HikariDataSource - HikariPool-1 - Starting...<br>
15/06/2021 10:51:22.034 INFO  [main] hikari.HikariDataSource - HikariPool-1 - Start completed.<br>
15/06/2021 10:51:24.328 INFO  [main] lockservice.StandardLockService - Successfully acquired change log lock<br>
15/06/2021 10:51:24.931 INFO  [main] changelog.StandardChangeLogHistoryService - Reading from xxx<br>
15/06/2021 10:51:24.971 INFO  [main] lockservice.StandardLockService - Successfully released change log lock<br>
15/06/2021 10:51:25.131 INFO  [main] xx - Started xx in 4.534 seconds (JVM running for 5.289)<br>
15/06/2021 10:51:25.141 INFO  [SpringContextShutdownHook] hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...<br>
15/06/2021 10:51:25.161 INFO  [SpringContextShutdownHook] hikari.HikariDataSource - HikariPool-1 - Shutdown completed.<br>
</pre>

## After upgrade Liquibase 4.3.5 (SpringBoot 2.5)
<pre>
15/06/2021 10:37:18.615 INFO  [main] xx - Starting xx<br>
15/06/2021 10:37:18.695 INFO  [main] xx - No active profile set, falling back to default profiles: default<br>
15/06/2021 10:37:19.316 INFO  [main] hikari.HikariDataSource - HikariPool-1 - Starting...<br>
15/06/2021 10:37:19.487 INFO  [main] hikari.HikariDataSource - HikariPool-1 - Start completed.<br>
15/06/2021 10:37:19.979 INFO  [main] liquibase.lockservice - Successfully acquired change log lock<br>
15/06/2021 10:37:51.364 INFO  [main] liquibase.changelog - Reading from xxx<br>
15/06/2021 10:37:51.455 INFO  [main] liquibase.lockservice - Successfully released change log lock<br>
15/06/2021 10:37:51.455 INFO  [main] liquibase.lockservice - Successfully acquired change log lock<br>
Skipping auto-registration<br>
15/06/2021 10:37:51.455 WARN  [main] liquibase.hub - Skipping auto-registration<br>
15/06/2021 10:37:51.465 INFO  [main] liquibase.lockservice - Successfully released change log lock<br>
15/06/2021 10:37:51.637 INFO  [main] xx - Started xx in 33.61 seconds (JVM running for 34.551)<br>
15/06/2021 10:37:51.647 INFO  [SpringApplicationShutdownHook] hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...<br>
15/06/2021 10:37:51.657 INFO  [SpringApplicationShutdownHook] hikari.HikariDataSource - HikariPool-1 - Shutdown completed.<br>
</pre>

The following profiling capture shows execution times for the ClassLoaderResourceAccessor.loadRootPaths method.

Liquibase-4 3 5-times

### PR DESCRIPTION
**Pull request by nvoxland**
LiquibaseEntityResolver was created too often, which caused Liquibase to open too many file descriptors.

* Updated code calling LiquibaseEntityResolver so they use a single instance instead of making many
* Updated LiquibaseEntityResolver to no use fallbackResourceAccessor unless it really had to
* Updated LiquibaseEntityResolver to use a singleton fallbackResourceAccessor

Fixes #1815
Fixes #1913

## Dev Handoff Notes (Internal Use)
Links

Fixed Issue:
        #1815
        #1913
    Local Branch: [https://github.com/liquibase/liquibase/tree/LB-1547](https://github.com/liquibase/liquibase/tree/LB-1547)
    Unit Tests: [https://github.com/liquibase/liquibase/pull/1860/checks](https://github.com/liquibase/liquibase/pull/1860/checks)
    Integration Tests: (shown in Unit Tests link above)
    Functional Tests: [https://jenkins.datical.net/job/liquibase-pro/job/LB-1547/](https://jenkins.datical.net/job/liquibase-pro/job/LB-1547/)

Testing

Steps to Reproduce: #1815
    Guidance:
        Does not change behavior, just improves performance

Dev Verification

Saw problem code go away via the profiler data.
(Did not save output at the time)

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1741) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by suryaaki2 — APPROVED** [review]

**Comment by vesin** [comment]
When this will be merged? I'm really depending on this fix...

**Comment by molivasdat** [comment]
Hi @vesin We are looking to put this into a release as soon as we can.  In the interim, there is a build with the update and you can see if it works for you in the meantime.
https://github.com/liquibase/liquibase/pull/1860/checks?check_run_id=3078620424
Check the artifacts for the liquibase.zip file.

**Comment by molivasdat** [comment]
Hi @vesin In talking internally the outlook for getting this change into a released version if the interim version does not work for you is early September.  Hope this works for you and team.

**Comment by vesin** [comment]
Thanks @molivasdat , that would be great!

**Pull request merged**
