### PR TITLE
CORE-3558 Unique constraint name is ignored when using the addColumn change

### PR DESCRIPTION
**Pull request by InfiniteLoop90**
┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-29) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.1

### CODE REVIEW

**Comment by InfiniteLoop90** [comment]
Sure thing. I'll switch this to the 3.8.x branch.

Out of curiosity, would this eventually get merged into the master branch?

**Comment by InfiniteLoop90** [comment]
Rebased this change onto the `3.8.x` branch.

**Comment by SteveDonie** [comment]
The 3.8.x branch will get merged to master in the near future. We should have a clearer picture of that in the next few weeks.

**Comment by InfiniteLoop90** [comment]
Hi @SteveDonie 
Let me know if there's anything else I need to do on this merge request.
Thanks!

**Comment by ro-rah** [comment]
Hi @InfiniteLoop90 ,

Sorry for the delay, as @SteveDonie hinted we are working on streamlining some of our processes including PR submission and acceptance.  Still working on when the merge to master will happen but that is the plan.

I will Condition this PR for upcoming sprints, thanks a bunch for the PR. 

-Ronak

**Comment by ro-rah** [comment]
Added RiskLow label as it includes [unit tests](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests).

**Pull request merged**
