### PR TITLE
Fixed the error of SQL generation when changed MySQL column remarks.

### PR DESCRIPTION
**Pull request by qq253498229**

### CODE REVIEW

**Comment by qq253498229** [comment]
https://liquibase.jira.com/browse/CORE-3516

**Comment by SteveDonie** [comment]
Thanks for the pull request. I tried cloning your repo and branch and I was unable to get the code to compile because of the changes to the ModifyDataTypeStatement constructor. Please ensure you can run `mvn clean package` with no errors.

**Comment by qq253498229** [comment]
I've fixed it , but I haven't used hsql before, so do not know how to complete the hsqlintegration.

**Comment by qq253498229** [comment]
wait wait ,I foud another bug .....

**Comment by molivasdat** [comment]
Hi @qq253498229 
Thank you for this Pull Request.

I’m putting together a core team of developers to help us with community requests. We’ll make Liquibase improvements faster together!

If you are willing to help, please reply to this comment and I’ll let you know the next steps.

Your friendly neighborhood developer advocate,
@molivasdat

**Pull request closed without merging**
