### PR TITLE
Fix #CORE-3493 Inconsistent resolution of ChangeLogParameters in liqu…

### PR DESCRIPTION
**Pull request by Holly-Marie**
Solution to the bug report CORE-3493.

I tested it with my changesets and it works as expected.
If required I could look into writing a few unit tests for this change as well.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-44) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2

### CODE REVIEW

**Comment by SteveDonie** [comment]
Thanks for submitting this! We are currently working on the final changes for the 3.8.1 release, and will plan on incorporating this change in the next release after that.

**Comment by ro-rah** [comment]
Hi @Holly-Marie !

Again thanks for submitting this PR, and thanks for include tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)). 

I'll move this into conditioning.

**Comment by ro-rah** [comment]
Risk Low label applied due to unit tests included and change seems reasonable :)

**Comment by Holly-Marie** [comment]
Hi @ro-rah!
Glad I could help.

**Comment by ro-rah** [comment]
Hey @Holly-Marie, as Developer Evangelist for Liquibase, I wanted to highlight some PR submitter and interview them for the community, would you be interested in sharing what made you interested in Liquibase and your journey to submitting a PR?  If so, please email me at rrahman@datical.com.  No matter how you decide, we still wish to thank you for participating in the Liquibase Community and making our product better!

**Comment by ro-rah** [comment]
Hey @mariochampion , making sure this goes to 3.10.2, it was originally slated for 3.10.1, but don't see it in JIRA.  If it needs to be bumped please let me know!  Thanks!

**Comment by nvoxland** [comment]
This will get merged into 4.0.x and then cherry picked back to 3.10.x

**Comment by nvoxland** [comment]
I cherry picked the changes in to 3.10.x

**Pull request merged**
