### PR TITLE
New Refactoring "dropAllIndexes"

### PR DESCRIPTION
**Pull request by Wallaby1999**
New Refactoring "dropAllIndexes" should be available to drop all indices of a table

## Pull Request Type

* [ ] Bug fix (non-breaking change which fixes an issue.)
* [x] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
When working with legacy databases it is sometimes unknown how indices are named, because they might have been named with a non-deterministic auto-generated name. To be able to refactor these tables, a refactoring "dropAllIndexes" should be available to drop all indices of a table.

## Expected/Desired Behavior
We are able to drop all indices of a table, just like we are able to drop all foreign keys.

### CODE REVIEW

**Comment by Wallaby1999** [comment]
Hi @ro-rah,
here is my new pull request for the dropAllIndexes refactoring. Unfortunately I get some test errors in liquibase.integration.ant.DropAllTaskTest, which I am not able to narrow down to a specific problem. Maybe someone can help me with this

**Comment by ro-rah** [comment]
@Wallaby1999 I see the test errors.  I will bring this one up with internally.

**Comment by Wallaby1999** [comment]
@ro-rah Are there any suggestions where the test error are originating from?

**Comment by ro-rah** [comment]
@Wallaby1999 , sorry for the delay, I just got my dev system up and running, I will take a look and respond by tomorrow.

**Comment by ro-rah** [comment]
Hey @Wallaby1999 ,

I am able to reproduce the errors.  I see:
`Caused by: liquibase.exception.ChangeLogParseException: Error parsing line 1135 column 52 of changelogs/common/common.tests.changelog.xml: cvc-complex-type.2.4.a: Invalid content was found starting with element 'dropAllIndexes'. One of '{"http://www.liquibase.org/xml/ns/dbchangelog":comment, "http://www.liquibase.org/xml/ns/dbchangelog":createTable, "http://www.liquibase.org/xml/ns/dbchangelog":dropTable, "http://www.liquibase.org/xml/ns/dbchangelog":createView, "http://www.liquibase.org/xml/ns/dbchangelog":renameView, "http://www.liquibase.org/xml/ns/dbchangelog":dropView, "http://www.liquibase.org/xml/ns/dbchangelog":insert, "http://www.liquibase.org/xml/ns/dbchangelog":addColumn, "http://www.liquibase.org/xml/ns/dbchangelog":sql, "http://www.liquibase.org/xml/ns/dbchangelog":createProcedure, "http://www.liquibase.org/xml/ns/dbchangelog":dropProcedure, "http://www.liquibase.org/xml/ns/dbchangelog":sqlFile, "http://www.liquibase.org/xml/ns/dbchangelog":renameTable, "http://www.liquibase.org/xml/ns/dbchangelog":renameColumn, "http://www.liquibase.org/xml/ns/dbchangelog":dropColumn, "http://www.liquibase.org/xml/ns/dbchangelog":mergeColumns, "http://www.liquibase.org/xml/ns/dbchangelog":modifyDataType, "http://www.liquibase.org/xml/ns/dbchangelog":createSequence, "http://www.liquibase.org/xml/ns/dbchangelog":alterSequence, "http://www.liquibase.org/xml/ns/dbchangelog":dropSequence, "http://www.liquibase.org/xml/ns/dbchangelog":renameSequence, "http://www.liquibase.org/xml/ns/dbchangelog":createIndex, "http://www.liquibase.org/xml/ns/dbchangelog":dropIndex, "http://www.liquibase.org/xml/ns/dbchangelog":addNotNullConstraint, "http://www.liquibase.org/xml/ns/dbchangelog":dropNotNullConstraint, "http://www.liquibase.org/xml/ns/dbchangelog":addForeignKeyConstraint, "http://www.liquibase.org/xml/ns/dbchangelog":dropForeignKeyConstraint, "http://www.liquibase.org/xml/ns/dbchangelog":dropAllForeignKeyConstraints, "http://www.liquibase.org/xml/ns/dbchangelog":addPrimaryKey, "http://www.liquibase.org/xml/ns/dbchangelog":dropPrimaryKey, "http://www.liquibase.org/xml/ns/dbchangelog":addLookupTable, "http://www.liquibase.org/xml/ns/dbchangelog":addAutoIncrement, "http://www.liquibase.org/xml/ns/dbchangelog":addDefaultValue, "http://www.liquibase.org/xml/ns/dbchangelog":dropDefaultValue, "http://www.liquibase.org/xml/ns/dbchangelog":addUniqueConstraint, "http://www.liquibase.org/xml/ns/dbchangelog":dropUniqueConstraint, "http://www.liquibase.org/xml/ns/dbchangelog":setTableRemarks, "http://www.liquibase.org/xml/ns/dbchangelog":setColumnRemarks, "http://www.liquibase.org/xml/ns/dbchangelog":customChange, "http://www.liquibase.org/xml/ns/dbchangelog":update, "http://www.liquibase.org/xml/ns/dbchangelog":delete, "http://www.liquibase.org/xml/ns/dbchangelog":loadData, "http://www.liquibase.org/xml/ns/dbchangelog":loadUpdateData, "http://www.liquibase.org/xml/ns/dbchangelog":executeCommand, "http://www.liquibase.org/xml/ns/dbchangelog":stop, "http://www.liquibase.org/xml/ns/dbchangelog":output, "http://www.liquibase.org/xml/ns/dbchangelog":empty, "http://www.liquibase.org/xml/ns/dbchangelog":rollback, WC[##other:"http://www.liquibase.org/xml/ns/dbchangelog"], "http://www.liquibase.org/xml/ns/dbchangelog":modifySql}' is expected.
	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:96)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:572)
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:351)`

I think we are missing a definition in:
dbchangelog-4.0.xsd
` <xsd:element ref="dropAllIndexes" maxOccurs="unbounded"/>`

Once I did that, I was able to get failed tests down from 28 to 10.

**Comment by Wallaby1999** [comment]
Ah, yes, I missed that. Just added the corresponding commit

**Comment by ro-rah** [comment]
Hey @Wallaby1999 ,

I still see 10 test cases failing, and was able to narrow it down to dropAllIndexes are thought of differently by others and sometimes even between different database platforms.

So, the H2 tests caught the following:
`Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: SYS_IDX_PK_DROPINDEXTEST_11069`

this is due to (quoting @nvoxland ):

> "all indexes" includes indexes that back primary keys, unique constraints, and sometimes foreign keys which maybe people don't want to actually drop and/or databases (including h2) don't let you drop directly without dropping the "owning" object first.

So where does that leave us?  I think 2 options, we can continue to iterate on this PR, which we will need:
**Option 1**
- it work for other platforms (ex. H2 expects you to own the index)
- changes to snapshot infra will make this easier post 4.0 release (we don't like to make calls to the DB in changeset as that breaks updateSQL functionality but there is precedent of dropAllForeignKeys)
- need to get the flags right so that folks changesets will be forwards compatible hopefully forever (maybe we can pass flags for types of indexes to delete)

**Option 2**
However, if that is too much, you can make the dropAllIndexes work by contributing an [extension](https://liquibase.jira.com/wiki/spaces/CONTRIB/pages/2424883/Contributing), advantages are:
- the functionality can be just how you want it (but the more inclusive the better to pull it in later)
- you can publish it anywhere
- less time to solve the issue
- we will add it to our [list](https://liquibase.jira.com/wiki/spaces/CONTRIB/pages/1998865/Available+Extensions)

Let me know what help you need!

Thanks,

Ronak

**Comment by Wallaby1999** [comment]
Hi @ro-rah,
thanks for your efforts here. Option 2 is not, what I would like to do, I would prefer to get it into core, when possible.
So for option 1 I just had a look into the code and I do not see any information on the index itself, if it is originating from a Primary Key, a Unique Constraints, a Foreign Key or is a self-created index. I would be fine to narrow down the "dropAllIndexes" command to just drop the self-created ones, because the other ones should get dropped when the corresponding constraint gets dropped. But I actually do not know, if or how it is possible to get this information out of the meta data somewhere.

Can you suggest, how to proceed on that?

**Comment by ro-rah** [comment]
Hey @Wallaby1999 , I will check on this.  My gut tells me that this has a bit of work on our end if we want to make it into core due to the different ways the supported DBs present constraints in the snapshot.

**Comment by ro-rah** [comment]
Thanks @Wallaby1999 for the work, I think there are some work for us to investigate on how to get type of constrains, so I will put it at impact high, risk high

**Comment by filipelautert** [comment]
Hi - that's an interesting feature. As it quite old and lacks answers I'll close it, but if you still willing to get this work included  please reopen the PR and fix the conflicts . Thanks!

**Pull request closed without merging**
