### PR TITLE
Write changelog only if changes exist

### PR DESCRIPTION
**Pull request by brachi-wernick**
## Impact

- [ `x`] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description
Write changelog only if changes exist.

When running `diffChangeLog` and there are no changes at all, it still generates an empty changelog file. 
It makes a lot of garbage file that needed to be removed manually.

### CODE REVIEW

**Comment by MalloD12** [comment]
@rberezen could you please let me know when [DAT-16261](https://datical.atlassian.net/browse/DAT-16261) is done, so I can approve this PR when all checks are green? 

Thanks,
Daniel.

**Comment by obovsunivskyii** [comment]
hi @brachi-wernick Thanks for adding this. Even when we generate a new diff changelog with no differences, we're still receiving this message.

```BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed. Some database objects and their dependencies cannot be represented automatically, and they may need to be manually updated before being deployed.
Liquibase command 'diffChangelog' was executed successfully.``` 

I think it would be nice to trigger a warning message in such scenarios, as `WARNING: No differences have been detected. The changelog [name of the changelog] was not generated.`
CC: @MalloD12

**Comment by brachipa** [comment]
@obovsunivskyii @MalloD12
This message is part of generic logging of Liquibase command and not speifically to diffChange log.

`Liquibase command 'diffChangelog' was executed successfully.` 

If you check the logs you will see some information about empty changes:

```
changeSets count: 0
No changesets to add.
Diff changelog command succeeded
Command execution complete
Liquibase command 'diff-changelog' was executed successfully.
```

I Think better to change  the log 

`No changesets to add.`

to be as the warning you suggested 

`WARNING: No differences have been detected. The changelog [name of the changelog] was not generated.`
 
And this will be in the scope of class `DiffToChangeLog`. and no need to start passing information between the change log class and the generic Liquibase classes.

Let me know if it sounds good and if so I'll commit it.

**Comment by brachipa** [comment]
I'm same person as [brachi-wernick](https://github.com/brachi-wernick) just work git user (by mistake forgot to switch)

**Comment by MalloD12** [comment]
> @obovsunivskyii @MalloD12 This message is part of generic logging of Liquibase command and not speifically to diffChange log.
> 
> `Liquibase command 'diffChangelog' was executed successfully.`
> 
> If you check the logs you will see some information about empty changes:
> 
> ```
> changeSets count: 0
> No changesets to add.
> Diff changelog command succeeded
> Command execution complete
> Liquibase command 'diff-changelog' was executed successfully.
> ```
> 
> I Think better to change the log
> 
> `No changesets to add.`
> 
> to be as the warning you suggested
> 
> `WARNING: No differences have been detected. The changelog [name of the changelog] was not generated.`
> 
> And this will be in the scope of class `DiffToChangeLog`. and no need to start passing information between the change log class and the generic Liquibase classes.
> 
> Let me know if it sounds good and if so I'll commit it.

Hi @brachipa,

I'm fine with it, but what do you guys think if we lightly change that message to something like:

`No changesets to add to the changelog output.`  

How does it sound to you? cc: @obovsunivskyii 

Thanks,
Daniel.

**Comment by obovsunivskyii** [comment]
> > @obovsunivskyii @MalloD12 This message is part of generic logging of Liquibase command and not speifically to diffChange log.
> > `Liquibase command 'diffChangelog' was executed successfully.`
> > If you check the logs you will see some information about empty changes:
> > ```
> > changeSets count: 0
> > No changesets to add.
> > Diff changelog command succeeded
> > Command execution complete
> > Liquibase command 'diff-changelog' was executed successfully.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I Think better to change the log
> > `No changesets to add.`
> > to be as the warning you suggested
> > `WARNING: No differences have been detected. The changelog [name of the changelog] was not generated.`
> > And this will be in the scope of class `DiffToChangeLog`. and no need to start passing information between the change log class and the generic Liquibase classes.
> > Let me know if it sounds good and if so I'll commit it.
> 
> Hi @brachipa,
> 
> I'm fine with it, but what do you guys think if we lightly change that message to something like:
> 
> `No changesets to add to the changelog output.`
> 
> How does it sound to you? cc: @obovsunivskyii
> 
> Thanks, Daniel.

I'm okay with these changes @MalloD12 @brachi-wernick thank you

**Comment by rberezen** [comment]
Looks good to me. Functional tests have been fixed in https://github.com/liquibase/liquibase-pro-tests/pull/1176. Thanks, @brachi-wernick, for your contribution!

**Comment by suryaaki2** [comment]
@filipelautert This shouldn't cause any breaking change for the customers, right?

**Comment by filipelautert** [comment]
> @filipelautert This shouldn't cause any breaking change for the customers, right?

@suryaaki2 Right! This PR skips the creation of a file that would just have xml headers on it.

**Review by filipelautert — APPROVED** [review]

**Review by MalloD12 — APPROVED** [review]
**Approved**.

Code changes looks good to me, and failing tests have been fixed in this [PR](https://github.com/liquibase/liquibase-pro-tests/pull/1176). Thank you, guys (@brachi-wernick - @rberezen)!!

**Comment by MalloD12** [comment]
@filipelautert I think we can already merge this one since @rberezen has already created the PR to fix the failing functional tests, and also merge Ruslan's PR.

Thanks,
Daniel.

**Pull request merged**
