### PR TITLE
#1081 using DBMS_UTILITY.DB_VERSION

### LINKED ISSUE #1081: Don't use v$session in Oracle as the SELECT grant on this view is not usually available to any user
**Description**
In Oracle multiuser and multitenant environments the `SELECT` grant on ```v$session``` is usually not available for any user. To do a SELECT from this view is usually enabled by granting `SELECT_CATALOG_ROLE` to the user. However, in more restricted environments this is not done due to security and privacy concerns.

There is a solution, to call `DBMS_UTILITY.DB_VERSION` stored procedure. The `DBMS_UTILITY` package, by default, can be executed by `PUBLIC`.

**To Reproduce**

* Create an Oracle user _without_ `SELECT_CATALOG_ROLE`
* Execute a Liquibase migration for this user and its schema
* Observe in the logs that 

```
2020-04-05 21:26:00 [main] [INFO ] [l.database.core.OracleDatabase] Could not set check compatibility mode on OracleDatabase, assuming not running in any sort of compatibility mode: Cannot read from v$parameter: ORA-00942: table or view does not exist
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-192) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.2.x

### PR DESCRIPTION
**Pull request by RockyMM**
Getting Oracle version using DBMS_UTILITY.DB_VERSION instead of querying v$parameter

- - -
name: Pull Request
about: Create a report to help us improve
title: ''
labels: Status:Discovery
assignees: ''

- - -

## Environment
**Liquibase Version**:
3.8.8
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
maven
**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
Oracle, all versions
**Operating System Type & Version**:
any

## Pull Request Type

Closes #1081 

* [ ] Bug fix (non-breaking change which fixes an issue.)
* [x] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Described in #1081 

## Steps To Reproduce
Described in #1081 

## Actual Behavior
Described in #1081 

## Expected/Desired Behavior
Described in #1081 

## Fast Track PR Acceptance Checklist:

* [ ] Build is successful and all new and existing tests pass
* [ ] Added Unit Test(s)
* [ ] Added Integration Test(s)
* [ ] Documentation Updated

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-253) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.2.2

### CODE REVIEW

**Comment by ro-rah** [comment]
@RockyMM 

Thanks for taking the time to open a PR.
Initial thought is sizing at risklow tag:
- includes tests
- closes #1081 
- includes reproducible step and expected behavior (yay, thanks!)

**Comment by molivasdat** [comment]
Hi @RockyMM 
Thank you for this Pull Request.

I’m putting together a core team of developers to help us with community requests. We’ll make Liquibase improvements faster together!

If you are willing to help, please reply to this comment and I’ll let you know the next steps.

Your friendly neighborhood developer advocate,
@molivasdat

**Comment by RockyMM** [comment]
Hey @molivasdat 

I am more than willing to help. Please explain next steps :)

**Comment by molivasdat** [comment]
Hi @RockyMM .  Please email me (molivas@liquibase.com) your email address and I'll let you know next steps.

**Review by nvoxland — APPROVED** [review]

**Comment by nvoxland** [comment]
This has been merged in already.

**Comment by RockyMM** [comment]
Nice!

**Pull request closed without merging**
