### PR TITLE
Fixed the issue that was preventing dropAll from working in Postgres (#1212)

### PR DESCRIPTION
**Pull request by stevesaliman**
This fix is being pushed to both the 4.2.x and 4.3.x branches because the master branch wasn't passing its tests, and I wanted to make sure that this fix goes out in the next release of Liquibase.

## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: N/A

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: Postgres

**Operating System Type & Version**: All

## Pull Request Type

* [x] Bug fix (non-breaking change which fixes an issue.)
* [ ] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
A clear and concise description of the issue being addressed.  Additional guidance [here](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core).
Running `dropAll` in a Postgres database doesn't drop partitioned tables because the Postgres JDBC driver doesn't return partitioned tables by default when asking for tables, and you can't drop inherited foreign constraints.

## Steps To Reproduce
To replicate the bug, the following driver and platform versions are required:

* JDBC Driver 42.1.1
* Postgres version greater than 10.

List the steps to reproduce the behavior.
This pull request includes some changeSets in liquibase-integration-tests/src/test/resources/changelogs/pgsql/complete/root.changelog.xml that create a partitioned table with a foreign key constraint to a parent table.  This will introduce two problems in the pre-patched code.

1. running `dropAll` will fail because Postgres can't drop the inherited constraint.  This has something to do with the way Postgres does partitions.
1. Without the change set that makes the foreign key constraint, `dropAll` will succeed, it won't drop the partitioned table, causing future `update` commands to fail because the object will still exist.

## Expected/Desired Behavior
Running `dropAll` should result in all objects being dropped from the database.  This behavior now happens as a result of the pull request, as verified by the integration tests that now include a partitioned table.  I verified that the tests were failing with the new changeSets before the code fix, and succeeding after the code fix.

##### Error Output to Console
{NOFORMAT}
Unexpected error running Liquibase: ERROR: cannot drop inherited constraint "fk_child_parent" of relation "partitioned_childp" [Failed SQL: (0) ALTER TABLE "proschema"."partitioned_childp" DROP CONSTRAINT "fk_child_parent"]
{NOFORMAT}

## Fast Track PR Acceptance Checklist:

* [x] Build is successful and all new and existing tests pass
* [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [x] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
* [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

## Internal Liquibase QA Requirements
* Use the changesets included in the integration tests to setup a Postgres instance with partitioned tables and a foreign key.
* Verify the bug reproduces with Liquibase 4.3.1
* Manually verify the fix using JDBC driver 42.1.1
* Manually verify the fix does not break the same test using JDBC driver 42.2.19 (latest as of 23II21)
* Add an automated functional test to the Postgres regressions  
##### Liquibase automated functional tests run on an internal build server and are not visible to the wider Community.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1146) by [Unito](https://www.unito.io/learn-more)
┆Attachments: <a href="https://share.unito.io/qYld3ZSZCvkPWovWpKVXXloXS_uJ4t9mkZhCkPRxkaPF">lb1146_afterDropAll.png</a> | <a href="https://share.unito.io/sEDUmH_KshhlZ3W8f7PY8NEe7a6g4tBI5URTK8zkuVl7">lb1146_beforeDropAll.png</a> | <a href="https://share.unito.io/6epMLJkPxvV-zQ-Xh-2inlqW2uSrOhjYNK6AuTzor9Gn">LB1146.xml</a>
┆Fix Versions: Community 4.3.2,Liquibase 4.3.2

### CODE REVIEW

**Comment by molivasdat** [comment]
Hi @stevesaliman Thanks for making this PR.
As I stated in 1649
4.3 is in the final testing phase so it will not make the cut for that one.  I will add it to the list for review for 4.4.x though.

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or [Test Harness Tests](https://github.com/liquibase/liquibase-test-harness/pulls)
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by stevesaliman** [comment]
Does this mean there will be no more 4.2.x or 4.3.x releases?  This issue is a bit of a show stopper for us since we need to be able to create partitioned tables, and we need `dropAll` to work.

Also, I'm not sure why the Travis build is failing.  The SQL that causes the failure in Travis works fine in my copy of Postgres.  I wonder if the syntax for creating partitioned tables changed with a particular version of Postgres?

**Comment by molivasdat** [comment]
Hi @stevesaliman 4.3.0 is in final testing before going out and released.  The current plan is to start merging fixes into 4.4 for the next release.  I'm not sure why the build is failing and will need to take a longer look too.

**Comment by stevesaliman** [comment]
Is there a release date in mind for 4.4?  Or any planned 4.3.x patches before 4.4?  I can always manually upload a build to our local maven repository, but I'd much rather use an officuail release of Liquibase if I can.

When I looked at the Travis log, it appeared that Postgres was rejecting the SQL that Liquibase is generated for the createTable change I added to `root.changelog.xml` in order to test this issue.  What I don't understand is why Postgres would reject it.  I pasted the SQL from the Travis log into my Postgres client, and it worked fine.  I don't know what version of Postgres Travis is using; I'm running Postgres 12.  I wouldn't expect them to change the syntax of the command to partition a table, but you never know...

**Review by nvoxland — APPROVED** [review]

**Comment by molivasdat** [comment]
Hi @stevesaliman The travis build is using postgres 9 so I'm not sure either if partitioned tables changed between 9 and 12 to break the build.  We do additional testing before releasing against multiple versions of postgres.  We are currently looking at how we can address this earlier than 4.4.x.

**Comment by stevesaliman** [comment]
It would appear that Postgres changed the way Partitioned tables work with Version 10.  Let's hear it for breaking changes :smiley: 

I'm not sure what the right answer is with regards to testing.  According to Postgres' [versioning](https://www.postgresql.org/support/versioning/) page, Version 10 has been out for a little more than 3 years, and I'd guess that most people have upgraded to version 10+.  But version 9 is still supported until November of this year, so Liquibase should probably not drop support for it.

Is there a simple way to limit the change set to just Postgres 10+ so that it runs on newer Postgres instances, but not on Travis while it is using version 9?

**Comment by molivasdat** [comment]
@stevesaliman We are slowly moving our tests out into our [testharness](https://github.com/liquibase/liquibase-test-harness) but have not had a chance to do so yet.  The test harness will allow us to test on multiple different versions of databases for cases like this when we get those tests moved over.

**Comment by nvoxland** [comment]
I've learned that github people with push access to the main repo to push commits to branches on forked repos. 

This PR originally had a problem where the automated tests were failing because the partition support is only in postgresql 10+ but we test with 9. 

So, experimenting with making a change locally (added "must be 10+" precondition) and pushing it to your fork vs. making a new branch on the main repo.

Let me know what you think of that approach, @stevesaliman. Feel like I'm overstepping too much by pushing commits to your repo? Or OK with the idea?

**Comment by stevesaliman** [comment]
If it helps get this fix to production, I'm all for it :smiley: 

My fork only exists to facilitate Pull Requests into the official repo, so I'm fine with your push.  I think adding the precondition is an elegant way to get the tests to pass now, while leaving them in place to run when the test harness starts using the newer version of Postgres

**Comment by molivasdat** [comment]
Hi @stevesaliman Now that we are in the midst of pulling this into the next release, we are having a hard time recreating this issue with current releases.  We tried 4.0.0, 4.2.2 and 4.3.1 to recreate this and could not.
Maybe it only happens with a certain postgresql jdbc driver.
We used postgresql-42.2.5.jar to test.
What driver are you using for the failing case?
We also tried with PostgreSQL Server 11.5 and 12.6

**Comment by stevesaliman** [comment]
I'm using Postgres 12.4.  I don't know where the Postgres driver comes from - maven brings it in somehow when I run a test - but it appears to be 42.1.1

It is strange that the behavior is not being replicated - Is it actually creating the partitioned table?

I looked at the release notes for the Postgres JDBC drivers, and I didn't see anything obvious that would change the behavior.

**Comment by stevesaliman** [comment]
Strange that Postgres is leaving behind a table - that was one of the things this PR is supposed to fix.  Was it leaving behind the partitioned table?

Some background about the fix: 

When I was working on the PR, I found that the Postgres driver's implementation of DatabaseMetaData.getTables considers a partitioned table to be a different type than the rest.  This was around line 1333 in the version of the driver I have.  The fix was to have Liquibase pass "PARTITIONED TABLE" as one of the types when we ask postgres to get tables in JdbcDatabaseSnapshot line 1083

**Comment by molivasdat** [comment]
Hi @stevesaliman Since the code is not dropping the table, would it be possible to upgrade the driver in your POM to a later version that works deleting the partitioned tables?  This driver works as far as our testing goes without any code changes on 4.3.  Possibly also with 4.2.2
PostgreSQL Driver v42.2.19.  
This will also help with future updates to the driver code and utilizing those driver's updates.

**Comment by stevesaliman** [comment]
I'm completely baffled as to why it works on your end...

On my system, I get the same failures with the new PostgreSQL Driver as I had with the old one, which makes sense when I look at the source code for the JDBC driver.  When PgDatabaseMetaData.getTables is called with an array of types, as Liquibase does JdbcDatabaseSnapshot, it only returns that type.  Liquibase passes in "TABLE", causing the Postgres driver to ignore objects of the "PARTITIONED_TABLE" type.  This is easily solved by simply adding PARTITIONED_TABLE to the types passed in if we're in a Postgres database.

The other issue with partitioned tables is related to constraints.  Liquibase tries to drop constraints in AbstractJdbcDatabase.dropDatabaseObjects if the database supports simply disabling foreign key constraints, which Postgres doesn't.  But Postgress can't drop what it considers an "inherited constraint".  This is easily solved by simply checking to see if we're dealing with Postgres when we check to see if we can disable constraints.

I can't test any of this in 4.3.0, because I get a NullPointerException in liquibase.hub.HubUpdater.register(HubUpdater.java:306).  My guess is that there is some kind of change in 4.3 that isn't compatible with the Liquibase Gradle plugin.  I'll look into fixing that over the weekend.

I'll be on Discord if you want to chat about this further.  I'm genuinely interested in figuring out why we're getting different behavior on our systems.

**Comment by molivasdat** [comment]
Hi @stevesaliman Happy to meetup on Discord.  Let me know your id through this channel or you can poke me on discord on the Liquibase server, molivas.  And we can pull in others to join.

**Comment by molivasdat** [comment]
ok @stevesaliman I was able to recreate the problem with PG 11.7 server PG 42.2.11 driver and 4.3.1.
Unexpected error running Liquibase: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: The database returned ROLLBACK, so the transaction cannot be committed. Transaction failure cause is <<ERROR: cannot drop inherited constraint "fk_child_parent" of relation "partitioned_childp">>
And then with the code fix merged in, I run 
liquibase dropAll
and I get 
All objects dropped from postgres@jdbc:postgresql://localhost:5432/gh1650
Liquibase command 'dropAll' was executed successfully.

**Comment by molivasdat** [comment]
I am getting 2 out of 26 integration test failures though.
testRerunDiffChangeLogAltSchema

```
liquibase.exception.DatabaseException: ERROR: schema "lbcat2" does not exist
  Position: 14 [Failed SQL: (0) CREATE TABLE lbcat2.databasechangeloglock (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP WITHOUT TIME ZONE, LOCKEDBY VARCHAR(255), CONSTRAINT DATABASECHANGELOGLOCK_PKEY PRIMARY KEY (ID)) TABLESPACE LIQUIBASE2]

	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:134)
	at liquibase.lockservice.StandardLockService.init(StandardLockService.java:101)
	at liquibase.lockservice.StandardLockService.forceReleaseLock(StandardLockService.java:410)
	at liquibase.dbtest.AbstractIntegrationTest.testRerunDiffChangeLogAltSchema(AbstractIntegrationTest.java:794)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: org.postgresql.util.PSQLException: ERROR: schema "lbcat2" does not exist
  Position: 14
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
	... 32 more
```
And 
testDiffExternalForeignKeys
```
Mar 03, 2021 8:02:07 PM liquibase.database
INFO: Successfully deleted all supported object types in schema DEFAULT.DEFAULT.
Mar 03, 2021 8:02:07 PM liquibase.snapshot
WARNING: Did not find catalog 'liquibasec' to snapshot
Mar 03, 2021 8:02:07 PM liquibase.database
INFO: Successfully deleted all supported object types in schema liquibasec.DEFAULT.
Mar 03, 2021 8:02:07 PM liquibase.snapshot
WARNING: Did not find catalog 'lbcat2' to snapshot
Mar 03, 2021 8:02:07 PM liquibase.database
INFO: Successfully deleted all supported object types in schema lbcat2.DEFAULT.
Mar 03, 2021 8:02:07 PM liquibase.lockservice
INFO: Successfully acquired change log lock
Mar 03, 2021 8:02:07 PM liquibase.changelog
INFO: Creating database history table with name: public.databasechangelog
Mar 03, 2021 8:02:07 PM liquibase.changelog
INFO: Reading from public.databasechangelog
Mar 03, 2021 8:02:07 PM liquibase.lockservice
INFO: Successfully released change log lock
Mar 03, 2021 8:02:07 PM liquibase.lockservice
INFO: Successfully acquired change log lock
Skipping auto-registration
Mar 03, 2021 8:02:07 PM liquibase.hub
WARNING: Skipping auto-registration
Mar 03, 2021 8:02:07 PM liquibase.lockservice
INFO: Successfully released change log lock

liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set changelogs/common/externalfk.init.changelog.xml::1::lujop:
     Reason: liquibase.exception.DatabaseException: ERROR: schema "lbcat2" does not exist
  Position: 14 [Failed SQL: (0) CREATE TABLE lbcat2.countries (id INTEGER NOT NULL, name VARCHAR(50), CONSTRAINT COUNTRIES_PKEY PRIMARY KEY (id))]

	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:273)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:272)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Liquibase.runInScope(Liquibase.java:2322)
	at liquibase.Liquibase.update(Liquibase.java:216)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:198)
	at liquibase.Liquibase.update(Liquibase.java:190)
	at liquibase.dbtest.AbstractIntegrationTest.testDiffExternalForeignKeys(AbstractIntegrationTest.java:1026)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set changelogs/common/externalfk.init.changelog.xml::1::lujop:
     Reason: liquibase.exception.DatabaseException: ERROR: schema "lbcat2" does not exist
  Position: 14 [Failed SQL: (0) CREATE TABLE lbcat2.countries (id INTEGER NOT NULL, name VARCHAR(50), CONSTRAINT COUNTRIES_PKEY PRIMARY KEY (id))]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:672)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.Scope.child(Scope.java:226)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66)
	... 43 more
Caused by: liquibase.exception.DatabaseException: ERROR: schema "lbcat2" does not exist
  Position: 14 [Failed SQL: (0) CREATE TABLE lbcat2.countries (id INTEGER NOT NULL, name VARCHAR(50), CONSTRAINT COUNTRIES_PKEY PRIMARY KEY (id))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1278)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1260)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	... 63 more
Caused by: org.postgresql.util.PSQLException: ERROR: schema "lbcat2" does not exist
  Position: 14
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:310)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:296)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:273)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:268)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
	... 68 more

```
Looks like both because lbcat2 no longer exists when they are run

**Comment by molivasdat** [comment]
scratch that, it was a setup issue.  All 28 tests passed!

**Comment by mariochampion** [comment]
nice work @molivasdat and @stevesaliman! thanks yall!

**Comment by stevesaliman** [comment]
I'm not worried about side effects to non-Postgres databases because the changes specifically target Postgres only.  I wasn't able to test that there were no side effects to Postgres 9, but I think the standard test suite took care of that.

That just leaves the version of the Postgres driver itself.  I'm not sure what happens when users try to pass "PARTITIONED TABLE" as a type to a version of the driver that doesn't know about that type.  Does it just ignore it, or does it cause problems?

If you have an easy to try running tests against an earlier version of the Postgres driver, that would be worth while.

If that runs fine, or if we're ok saying that postgres users need a certain minimum version of the JDBC drivers if they want to use Liquibase, then I feel pretty good about merging this fix.

**Comment by molivasdat** [comment]
As @XDelphiGrl said.  Thanks for the feedback!

**Pull request merged**
