### PR TITLE
 - [CORE-2858] Add ability to read included files. Also added ability…

### PR DESCRIPTION
**Pull request by bilak**
… to add/read includeAll, and property elements of changelog

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-103) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by bilak** [comment]
sorry for the code format, but I can't find proper formatter configuration for liquibase project.

**Comment by ro-rah** [comment]
Hi @bilak 

Would you resolve the branch conflicts and consider adding some tests?  Here's some info below to help:

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by bilak** [comment]
@ro-rah you can probably close this PR... I don't recall what I was trying to solve here.

**Comment by ro-rah** [comment]
@bilak , I am so sorry it took so long to get back to you.  We have revamped our PR process and I hope you will give PR submission a try again if you need it and find more responsive.

**Pull request closed without merging**
