### PR TITLE
Fix LabelExpression constructors when using array or collection

### LINKED ISSUE #4763: `LabelExpression` constructed with a collection of strings is not usable for `Liquibase.*(...)`
### Search first

- [X] I searched and no similar issues were found

### Description

The [`LabelExpression(Collection<String>)` constructor](https://github.com/liquibase/liquibase/blob/v4.23.1/liquibase-standard/src/main/java/liquibase/LabelExpression.java#L45-L51) is not setting the `originalString` member.
This member is crucial though, as the `liquibase.Liquibase` facade is using `labelExpression.getOriginalString()` everywhere.

So when you create an expression like that it's basically useless.

### Steps To Reproduce

- create a changelog with label `foo`
- instantiate a `LabelExpression` with a collection that contains only the label string `bar`
- run `Liquibase.update(...)` with that expression object
- witness the execution of the changelog, although it shouldn't

### Expected/Desired Behavior

Label strings from a collection are evaluated properly.

### Liquibase Version

4.23.1

### Database Vendor & Version

MariaDB

### Liquibase Integration

Quarkus

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

I ran into this issue while updating Liquibase in Quarkus from 4.20.0 to 4.23.1.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by MalloD12**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Fixes #4763 

Having a changeset like the one below:

```
<changeSet author="Liquibase" id="labelExpressionIssue" labels="foo">
        <!-- GOOD CHANGE -->
        <createTable tableName="TABLE_1">
            <column name="COL1" type="INT"/>
        </createTable>
    </changeSet>
```

When a LabelExpression is defined as:

```
new LabelExpression(new String[]{"bar", "test"})
```

or:
```
new ArrayList<>(List.of("bar, test"))
```

What was happening was that labels were ignored and changesets were deployed anyway.

### CODE REVIEW

**Comment by wwillard7800** [comment]
This change looks good to me.  I think this issue escaped us because that constructor is only used in tests internally.

**Review by StevenMassaro — APPROVED** [review]
This change is fine, but each constructor essentially does the same thing with slight differences. It might be a better long-term solution to have one constructor with all the logic, and the other constructors call the other constructor. This change is not necessary for this PR however.

**Comment by MalloD12** [comment]
Done, I have applied the same logic to `ContextExpression`. I'm going to create a DAT ticket to apply the constructor refactoring Steve mentioned. 

cc: @suryaaki2 

Thanks,
Daniel.

**Review by StevenMassaro — APPROVED** [review]

**Review by suryaaki2 — APPROVED** [review]

**Review by rberezen — APPROVED** [review]
test failures are not related to the fix

**Pull request merged**
