### PR TITLE
[CORE-3185] New Refactoring "dropAllIndexes" should be available to drop all indices of a table

### PR DESCRIPTION
**Pull request by Wallaby1999**
Proposal for implementation of [CORE-3185]

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-116) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by Wallaby1999** [comment]
As this request is now 1,5 years old, I would like to know if it is worth to spent time and effort to get it into the current master branch or if it is unwanted to implement this additional refactoring.

**Comment by SteveDonie** [comment]
Many apologies for not dealing with this sooner. We will definitely look at incorporating this into Liquibase. We've just shipped Liquibase 3.8.1, and will look into adding this for 3.9 

This would need to go into a 3.9 rather than 3.8.x because it introduces a new change type.

**Comment by Wallaby1999** [comment]
Thanks Steve, for the quick reply.
Please let me know, when I should rework my proposal to be able to merge it in the 3.9-branch and if there are any suggestion on the implementation.

**Comment by ro-rah** [comment]
Hi @Wallaby1999 , would mind resolving the conflicts on this PR?  I believe you mentioned this fix is important, would love to help get this merged in.

Thanks!

Ronak

**Comment by Wallaby1999** [comment]
Hi @ro-rah ,
unfortunately I am not familiar with working with GIT so I accidentially added commit 9acafc8 to this request. How can I remove it?

**Comment by Wallaby1999** [comment]
> Hi @ro-rah ,
> unfortunately I am not familiar with working with GIT so I accidentially added commit [9acafc8](https://github.com/liquibase/liquibase/commit/9acafc86f2717035898e46650cef9bafea56aa0a) to this request. How can I remove it?

Oh, it is even worse I added a lot of commits. I will close this request and create a new one to start fresh

**Comment by ro-rah** [comment]
Oh no @Wallaby1999 !  Sorry to hear, I was going to suggest since it was pushed to do a:
```
git revert <sha>
git push
```

But opening a new PR is fine too :)

**Pull request closed without merging**
