### PR TITLE
Fix 1039 sequence statement generation for PostgreSQL <= 9.4

### PR DESCRIPTION
**Pull request by nfalco79**
## Environment

**Liquibase Version**: 3.8.9

**Liquibase Integration & Version**: CLI, maven

**Database Vendor & Version**: PostgreSQL 9.4

**Operating System Type & Version**: Windows 10

## Pull Request Type

- [x] Bug fix (non-breaking change which fixes an issue.)
- [ ] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This fix the issue #1039 New liquibase version introduce a IF NOT EXIST in the sequence statement that is not supported for db version <= 9.4 as documented [here](https://www.postgresql.org/docs/9.5/sql-createsequence.html)

## Fast Track PR Acceptance Checklist:
- [ ] Build is successful and all new and existing tests pass
- [ ] Added Unit Test(s)
- [ ] Added Integration Test(s)
- [ ] Documentation Updated

This was tested against my local db and newer version using docker image of postgresql 10.16 and 12

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-207) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.1

### CODE REVIEW

**Comment by nfalco79** [comment]
I add a test cases for these changes

**Comment by ro-rah** [comment]
@nfalco79,

Thanks so much for adding the unit test, love to see a complete PR.  Will be reviewing, will update shortly.

-Ronak

**Comment by ro-rah** [comment]
Added RiskLow tag, as user @nfalco79 added unit tests to the PR (awesome!)

**Comment by ro-rah** [comment]
@nfalco79 , I added to the next sprint for now, its reasonable to expect this out in Q2.  Thanks so much for your submission! -Ronak

**Comment by nvoxland** [comment]
While it can be nice to auto-add an "IF EXISTS" to object creation to avoid errors, I also worry about magically adding that when the person writing the changeSet did not explicitly ask for it. 

We are looking hard at usability, and one of the factors in that is how much we try to guess at what a user really wants to do, and how much we do specifically what they told us to do. 

Using this as an example, the user did not tell us to continue without an error if the objects exist. Do we guess that is what they actually wanted? Or do we just do what they said? 

I'm not sure the correct answer yet, but also want to make sure that whatever the answer is we apply it consistently across all the databases and change types. 

Anyone have thoughts on that?

**Comment by nvoxland** [comment]
Nevermind, I see that the IF EXISTS is currently in the code, and this fix is just making sure that is not used for pre-9.5 postgreql.

We'll bring this fix in, but will continue to have the discussion on how we should handle smart logic like "if exists" .

**Pull request merged**
