### PR TITLE
Allow whitespace within a foreign key statement

### PR DESCRIPTION
**Pull request by sideeffffect**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Before, only `references: tablename(columnname)` worked. Now both `tablename(columnname)` and `tablename ( columnname )` work.

### CODE REVIEW

**Comment by sideeffffect** [comment]
Somebody please mark as `SafeToBuild` :pray: 
/cc @filipelautert @StevenMassaro

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

The change makes sense to me, thanks @sideeffffect!

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Comment by sideeffffect** [comment]
Thanks @nvoxland . Is it thinkable that my change (expanding what the regex matches) could cause the integration tests failures in MySQL and PostgreSQL?
Can you perhaps run the failed tests again?

**Comment by StevenMassaro** [comment]
> Thanks @nvoxland . Is it thinkable that my change (expanding what the regex matches) could cause the integration tests failures in MySQL and PostgreSQL? Can you perhaps run the failed tests again?

These tests were fixed on master, so I merged master into your branch. I'd expect them to pass now.

**Comment by sideeffffect** [comment]
Thank you Steven :bow: What do we do now?

**Comment by sideeffffect** [comment]
Oh, no worries. Thanks for letting me know. Fingers crossed everything goes well with the release :wink:

**Review by filipelautert — APPROVED** [review]
Thanks for the fix @sideeffffect ! In order to simulate it I added a test and it's all fine.

**Comment by sideeffffect** [comment]
Can you please re-run the tests? The error in `test (hsqldb-2.4)` https://github.com/liquibase/liquibase-test-harness/actions/runs/5203686934/jobs/9386921019 seems like a glitch.

**Comment by rberezen** [comment]
This pull request enhances REFERENCE_REGEX regular expression in the AddColumnGenerator class. It now enables the inclusion of white spaces within, for example, a foreign key statement (so both `tablename(columnname)` and` tablename ( columnname )` will work now).

- Functional and test harness executions passing.
- New unit test added.
- No additional testing required.

APPROVED

**Review by rberezen — APPROVED** [review]

**Review by rberezen — APPROVED** [review]

**Pull request merged**
