### PR TITLE
fix reading properties files from jar resources

### PR DESCRIPTION
**Pull request by ilyhabayda**
- - -
name: Pull Request
about: Create a report to help us improve
title: ''
labels: Status:Discovery
assignees: ''

- - -

## Environment
**Liquibase Version**: 4.2.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: -

**Operating System Type & Version**: windows 10

## Pull Request Type

* [x] Bug fix (non-breaking change which fixes an issue.)
* [ ] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
cli cannot find liquibase.properties inside jar file with resources

## Steps To Reproduce
* put liquibase.properties inside jar file with database changelog and chagesets. in my case it is DatabaseUpdateResources.jar
* replace path to liquibase.jar, database driver jar and jar with resouurces in command below and run it
* java -cp "${path_to_jar}\liquibase.jar;${path_to_jar}\DatabaseUpdateResources.jar;${path_to_database_driver_jar}\{database_driver.jar}" liquibase.integration.commandline.Main --logLevel=info update

## Actual Behavior
Errors:
  The option --url is required.
  The option --changeLogFile is required.

## Expected/Desired Behavior
liquibase used options from liquibase.properties inside jar in classpath.

## Additional Context
in version 3.5.3 cli update with properties file in jar  worked correctly, this problem happened after updating to 4.2.0. 

## Fast Track PR Acceptance Checklist:

* [x] Build is successful and all new and existing tests pass
* [x] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Documentation Updated

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-949) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by molivasdat** [comment]
Hi @ilyhabayda 
Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ilyhabayda** [comment]
my first build failed, but that was not the problem with my changes. I added a fix for this test based on changes in the source code that failed the test.
I did this for fix the build with my changes. it's ok? if not, i can remove this changes

**Comment by nvoxland** [comment]
We made some significant changes to the CLI implementation in 4.4.0 which renders this PR out of date.

I created #1892 as the issue you found and will adapt your code to the new codebase in a separate PR.

**Comment by nvoxland** [comment]
Duplicate of #1893

**Pull request closed without merging**
