### PR TITLE
Wrote a manpage

### PR DESCRIPTION
**Pull request by bceverly**
Hi,

I added a manpage for liquibase.  I'm in the process of submitting liquibase to the OpenBSD ports/packages system to be included in the list of available binary packages.

Thanks!

### CODE REVIEW

**Comment by adriens** [comment]
That's great @bceverly . Do yo intend to port it in the deb and rpm packages or shall we have to do it by ourselves ?

**Comment by bceverly** [comment]
Sorry, I'm not understanding the question.  Do I need to overwrite the liquibase.1 files in the rpm and core subdirectories and include that in the commit?

**Comment by ro-rah** [comment]
Sizing Med to allow time for Eng, Docs and QA to review.

**Comment by nvoxland** [comment]
This PR is just bringing in an older version of the help docs into a file which isn't being included in the artifacts.

I'm also not sure how different the openbsd man format is from what we will be shipping with rpm/deb. We really want to just be managing that man page content one time, and have it used across all the packaging formats.

Since this particular PR is out of date and would not be used anywhere, rather than bringing it in directly we should use it as a basis for the man page portion of the deb/rpm/openbsd package creation logic.

**Comment by kataggart** [comment]
closing this due to aging; we can revisit the idea of a MAN page in the future as needed. Thanks.

**Pull request closed without merging**
