### PR TITLE
NULL date value in prepared statement requires type in MSSQL

### PR DESCRIPTION
**Pull request by mobreza**
I urgently needed support for NULL date values in loadData for MSSQL. I didn't experience problems with NULL values for other data types.

## Test Requirements
* Do a code walk-through with internal Developer.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-24) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.1

### CODE REVIEW

**Comment by SteveDonie** [comment]
Looks pretty good - is there any way you can think of to have some unit or integration tests for this?

**Comment by mobreza** [comment]
The problem is best explained in https://liquibase.jira.com/browse/CORE-3246:

> The Problem is that the applyColumnParameter in ExecutablePreparedStatementBase passes wrong Parameters to stmt.setNull: `stmt.setNull(i, java.sql.Types.NULL);`
> The correct type of the column needs to be passed ( https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setNull-int-int- )

Would it be enough to test that `applyColumnParameter` declares the proper parameter type for `null` values? Setting other params in that method seems to work.

https://liquibase.jira.com/browse/CORE-1928 looks similar to https://liquibase.jira.com/browse/CORE-3399.

**Comment by ro-rah** [comment]
Hi @mobreza !

Yes if you add that test it would be much appreciated.  Here is some guidance on writing [unit tests](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests) and [integration tests](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests).

Thanks,

Ronak

**Comment by mobreza** [comment]
@ro-rah Is there a better way to test the parameter SQL types assigned in `ExecutablePreparedStatementBase`?

**Comment by ro-rah** [comment]
Hey @mobreza !  Thanks for giving the test a try. 

I feel some test is better than what we have now :-) I'll bring this up with @nvoxland and share feedback if any.

**Comment by ro-rah** [comment]
Risk Low assessed due to unit tests included, all checks pass.  This is a blocking issue for the user for MSSQL.

**Comment by nvoxland** [comment]
It is just a draft PR at this point, we need to add checks for additional data types before it can be merged in. But, I agree that it is a low risk

**Comment by ro-rah** [comment]
Sorry Erz, I fixed the labels, it is a RiskLow, I forgot to update it after @nvoxland 's comments.

**Comment by nvoxland** [comment]
This PR is being finished up in #1209

**Comment by ro-rah** [comment]
@nvoxland may I close this PR since it will be finished in #1209?

**Comment by nvoxland** [comment]
No, I'd like to see if this PR gets closed automatically when #1209 is merged. That will provide better history to this PR if it is.

**Pull request merged**
