### PR TITLE
[CORE-3526] TABLE is a reserved keyword in H2database since 1.4.197

### PR DESCRIPTION
**Pull request by tholu**
- Added test case to root.changelog.xml, added all current keywords in H2 Database, updated H2 to latest version 1.4.200
- Improved isSafeToRunUpdate() for H2

Based on #948.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-33) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.1

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @tholu 

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest 
changes, additional tests, or provide other feedback. The PR will be prioritized 
according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

Thanks!

Ronak

**Comment by ro-rah** [comment]
closes #948

**Comment by ro-rah** [comment]
Risk Low, contains unit tests and it is a bug fix.

**Comment by ro-rah** [comment]
Slated for Q2

**Comment by camsaul** [comment]
This change actually broke Liquibase + H2 for us, since it now quotes the newly-reserved keywords as lowercase strings.

In older versions of Liquibase 3.6.3 + H2 1.4.197 we had a table with a `values` column; using the `LEGACY` quoting strategy, the column that got created was `VALUES` (uppercased). When upgrading to Liquibase 4.4.3 the column is now created as `values` (lowercased) meaning all of our custom SQL that uses the quoted identifier `"VALUES"` no longer works

**Comment by nvoxland** [comment]
Yeah, it's hard to manage the combination of exactly when reserved words become invalid across database versions and within liquibase. 

Since I'd guess there isn't a lot of cases where you're hitting this, I'd suggest adding a `<modifySql>` section to the problem chagneSets that replace `"table"` with either `table` or `"TABLE"` depending on what direction you are going.

**Pull request merged**
