### PR TITLE
Record current Liquibase version on a RERUN changeset (#5529)

### LINKED ISSUE #5529: Update the Liquibase version info in the DatabaseChangeLog table upon RERUNning a changeset
### Search first

- [X] I searched and no similar issues were found

### Description

When a changeset is RERUN, most of the attributes in the DatabaseChangeLog table are updated to reflect the latest run: the DateExecuted, OrderExecuted, Comments, Contexts, Labels and some others. Not the Liquibase version used for running the changeset (column Liquibase) though.

### Steps To Reproduce

1. Run any changeset that has runAlways="true"
2. Upgrade Liquibase
3. Run that changeset again

### Expected/Desired Behavior

I suggest Liquibase start updating the Liquibase column too.

### Liquibase Version

4.23.2

### Database Vendor & Version

any (observed on Oracle)

### Liquibase Integration

any (observed on CLI)

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

any (observed on macOS)

### Additional Context

We've developed a sequence of finalization steps to run at the end of every Liquibase script. These steps include:

- compiling all procedures, functions, packages, views and materialized views that need compilation;
- failing if there are any remaining errors;
- ensuring views are visible to the users who have the permission to see them.

Over my team's 5+ years with Liquibase, we have used quite a bunch of versions. Recently we noticed the Liquibase versions recorded on these rerunning steps and were puzzled.
I'm finding the current behaviour inconsistent.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by jdvorak001**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description

When recording a RERUN changeset we also update the info in the DatabaseChangeLog.Liquibase column with the current Liquibase version.

Fixes #5529

## Things to be aware of
This modification would change the semantics of the DatabaseChangeLog.Liquibase column slightly: while previously it was the _version of Liquibase used for the the first run of the changeset_, it now becomes _version of Liquibase used for the last run of the changeset_. Has the former ever been intended?

### CODE REVIEW

**Comment by MalloD12** [comment]
Hi @jdvorak001,

Code changes look good to me, I just fixed some tests that were failing and it seems to be ok now. One thing we were discussing with the team that we would like to ask you is if you don't mind making some more code changes to make this case also applicable for [mark-next-changeset-ran](https://docs.liquibase.com/commands/utility/mark-next-changeset-ran.html) command. 

Thanks,
Daniel.

**Comment by jdvorak001** [comment]
Thanks @MalloD12 for the feedback.

Re: the mark-next-changeset-ran command, I'd be willing to. However, at this stage I can't see how a change could be written down to the DatabaseChangeLog table other than through MarkChangeSetRanGenerator, which I've modified. Would you please have a hint?

And, taking a fresh look at that class: there is yet another column that is INSERTed, but not UPDATEd: it's DESCRIPTION. I'd suggest to give it the same handling as all the other columns have, so that the changelog record fully reflects the last run of the changeset. Shall I ensure it gets UPDATEd?

**Comment by MalloD12** [comment]
> Thanks @MalloD12 for the feedback.
> 
> Re: the mark-next-changeset-ran command, I'd be willing to. However, at this stage I can't see how a change could be written down to the DatabaseChangeLog table other than through MarkChangeSetRanGenerator, which I've modified. Would you please have a hint?
> 
> And, taking a fresh look at that class: there is yet another column that is INSERTed, but not UPDATEd: it's DESCRIPTION. I'd suggest to give it the same handling as all the other columns have, so that the changelog record fully reflects the last run of the changeset. Shall I ensure it gets UPDATEd?

Hi @jdvorak001,

I've been talking with the team and there is no need to make any changes for `mark-next-changeset-ran` command. Regarding your last comment, what do you think should be updated in `DESCRIPTION` column? It sounds to me like it just reflects what change/s included in a given changeset are deployed (i.e. `createTable tableName=book`).

Thanks,
Daniel.

**Comment by jdvorak001** [comment]
> > And, taking a fresh look at that class: there is yet another column that is INSERTed, but not UPDATEd: it's DESCRIPTION. I'd suggest to give it the same handling as all the other columns have, so that the changelog record fully reflects the last run of the changeset. Shall I ensure it gets UPDATEd?
> 
> [...] what do you think should be updated in `DESCRIPTION` column? It sounds to me like it just reflects what change/s included in a given changeset are deployed (i.e. `createTable tableName=book`).

I'd think a line like
```
.addNewColumnValue("DESCRIPTION", limitSize(changeSet.getDescription()))
```
somewhere in https://github.com/liquibase/liquibase/blob/6b97a35b3d237f69964b6ca6771ab449269fefa6/liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java#L70-L83
would ensure also the DESCRIPTION gets updated on a changeset being RERUN.

For one-off changes this would most likely be the same value; however, for repeated changesets their structure might evolve over time, too. If the rest of the DatabaseChangeLog record documents the last run of the changeset, so should its DESCRIPTION.

So my point is, all columns except for the ( ID, AUTHOR, FILE ) key should get updated.

**Comment by MalloD12** [comment]
> > > And, taking a fresh look at that class: there is yet another column that is INSERTed, but not UPDATEd: it's DESCRIPTION. I'd suggest to give it the same handling as all the other columns have, so that the changelog record fully reflects the last run of the changeset. Shall I ensure it gets UPDATEd?
> > 
> > 
> > [...] what do you think should be updated in `DESCRIPTION` column? It sounds to me like it just reflects what change/s included in a given changeset are deployed (i.e. `createTable tableName=book`).
> 
> I'd think a line like
> 
> ```
> .addNewColumnValue("DESCRIPTION", limitSize(changeSet.getDescription()))
> ```
> 
> somewhere in
> 
> https://github.com/liquibase/liquibase/blob/6b97a35b3d237f69964b6ca6771ab449269fefa6/liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java#L70-L83
> 
> 
> would ensure also the DESCRIPTION gets updated on a changeset being RERUN.
> For one-off changes this would most likely be the same value; however, for repeated changesets their structure might evolve over time, too. If the rest of the DatabaseChangeLog record documents the last run of the changeset, so should its DESCRIPTION.
> 
> So my point is, all columns except for the ( ID, AUTHOR, FILE ) key should get updated.

Thank you for your clarification, @jdvorak001! Yeah, makes total sense. Feel free to make the discussed changes. Please, also have in mind adding description field to the update statement will require us to fix `generateSql_update` test from `MarkChangeSetRanExecuteTest` class.

Thanks,
Daniel.

**Comment by jdvorak001** [comment]
Ok, done.
Jan

**Review by MalloD12 — APPROVED** [review]
**Approved**.

LGTM. Thank you, @jdvorak001 for this PR!

Build and tests have been successfully executed. 

Thanks,
Daniel.

**Review by filipelautert — APPROVED** [review]

**Comment by rberezen** [comment]
@jdvorak001 could you please resolve conflcits when you get a chance?

**Comment by rberezen** [comment]
@jdvorak001 there is some compilation error after merging master. Could you take a look?
```
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/liquibase/liquibase/liquibase-standard/src/main/java/liquibase/sqlgenerator/core/MarkChangeSetRanGenerator.java:[73,63] cannot find symbol
```

**Comment by jdvorak001** [comment]
Yes, I can see commit 547e54a affected the same sections of MarkChangeSetRanGenerator.java. 
It should be resolved now.

**Review by rberezen — APPROVED** [review]

**Pull request merged**
