### PR TITLE
Improve deferrable validation for AddForeignKey constraints generator

### PR DESCRIPTION
**Pull request by alero**
This is an effort to minimize the clutter in the config and the support hsqldb in junit developer testing with the same changesets that are using in Postgre in production/integration testing

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @alero ,

Would you resolve branch conflict and  consider adding tests for this PR?  Here's some guidance on that below:

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
@alero thanks for getting rid of the merge conflict!  I'll size it as a medium, but happy to size it low if we get tests added.

**Comment by filipelautert** [comment]
Hello @alero ! A lot changed in the last years on Liquibase. Is this change still required?

**Comment by alero** [comment]
HI @filipelautert we still use this adaption and have actually forked it last month again to be up to date with latest releases

**Comment by filipelautert** [comment]
@alero ! Thanks for the quick answer. Do you think you can fix the conflicts (as we renamed liquibase-core to liquibase-standard and so on) so I can keep on moving this one along?

**Comment by filipelautert** [comment]
Hello @alero ! I fixed the conflicts and tried to push the fix to your master branch but I don't have permission to do so. Would you be able to grant permission or fix the conflicts ?

**Comment by alero** [comment]
Hello @filipelautert I have added you to the repo, so should be able to push now and thank you for the support.

**Comment by filipelautert** [comment]
> Hello @filipelautert I have added you to the repo, so should be able to push now and thank you for the support.

Thanks , almost there! But seems the branch is protected and I can't push to your master anyway, so I created PR https://github.com/alero/liquibase/pull/1 in your repo to your master 🤣  could you approve and merge it?

**Comment by alero** [comment]
approved and merged it to master

**Review by filipelautert — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]
7 years later it's still alive!

**Review by rberezen — APPROVED** [review]

**Pull request merged**
