### PR TITLE
CORE-3299 ShouldRunChangeSetFilter initialization behavior update fro…

### PR DESCRIPTION
**Pull request by dnacra**
…m 3.5.0 breaks custom task

Revert ShouldRunChangeSetFilter initialization to use actual Database instead of a static copy of Database.getRanChangeSetList().
Update ShouldRunChangeSetFilter.accept() logic to filter the list for the latest executed ChangeSet.
Added unit test.

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @dnacra ,

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
Hello again @dnacra , thanks for adding tests.  I will be moving this to the latest 3.x branch, which happens to be 3.10.x seeing how there were conflicts to resolve anyways.  Please let me know if this was truly intended to be 3.5.x fix.

**Comment by dnacra** [comment]
Hi @ro-rah. This was truly intended for the 3.5.x branch indeed. Last time I checked there were no conflicts with the 3.5.x branch but that was about 8 months ago. I can take a look at those if needed.

Thanks!

**Comment by ro-rah** [comment]
Hi @dnacra , oh, sorry!  I changed the branch target back.  There is a conflict, would appreciate you taking a look.  Also, thanks for the quick response!

**Comment by dnacra** [comment]
@ro-rah All conflicts are now fixed.
I also fixed an issue with the fragile test ShouldRunChangeSetFilterTest.should_decline_not_changed_changeset_when_has_run_on_change to run with proper checksum and execution date for the RanChangeset

**Comment by kataggart** [comment]
closing due to age

can re-open as needed

**Pull request closed without merging**
