### PR TITLE
Fixed CommandLineUtilsTest for german locale

### LINKED ISSUE #4216: Test fails on non-English locales
### Search first

- [X] I searched and no similar issues were found

### Description
```
[ERROR] Failures:
[ERROR]   CommandLineUtilsTest.getBanner:17 Condition not satisfied:

banner.contains("Starting Liquibase at")
|      |
|      false
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##                                                ##
####################################################
Starte Liquibase am 11:04:41 (Version [local build] #0, kompiliert am 2023-05-05 08:56+0000)

[ERROR]   CommandLineUtilsTest.getBanner with banner disabled:29 Condition not satisfied:

banner.contains("Starting Liquibase at")
|      |
|      false
Starte Liquibase am 11:04:41 (Version [local build] #0, kompiliert am 2023-05-05 08:56+0000)
```
### Steps To Reproduce

On a non-English (e. g. German) locale execute `mvn package`.

### Expected/Desired Behavior

Test succeeds.

### Liquibase Version

latest

### Database Vendor & Version

none

### Liquibase Integration

none

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

Windows 11

### Additional Context

Locale: DE_de

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by nvoxland**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] Test Fix
 
## Description

CommandLineUtil was failing for german locales because we translate text we're asserting on into german.

Fixes #4216

## Things to be aware of

Just fixes the test

## Things to worry about

Nothing

### CODE REVIEW

**Comment by mkarg** [comment]
I don't think it is a good idea to simply turn "Version" into "version". It might work with German locale, but what about language having a completely different word for "Version" (like Polish "wersja")?

**Comment by mkarg** [comment]
I don't think it is a good idea to let the test use the code that is to be tested. What shall be the use of this? If there is a typo in the bundle file, the test shall guarantee that the typo still exists?!

**Review by mkarg — COMMENTED** [review]
Give me some days. I will check on German laptop next week. Thanks!

**Comment by mkarg** [comment]
Unfortunately I'm busy with our own software currently, but stay tuned, a full test on German locale will follow ASAP. Good that Paul triggered me today, so I had a reminder. :-)

**Comment by mkarg** [comment]
Sorry for the delay. Here is the test result on a German Windows 10 Pro:

```
[ERROR] Failures:
[ERROR]   CSVReaderTest.invalid csv:41 Condition not satisfied:

e.message.startsWith("Unterminated quoted field at end of CSV line")
| |       |
| |       false
| Unterminiertes Anf├╝hrungszeichen am Ende einer CSV-Zeile. Anfang des verlorenen Textes: ['' , '' ,
| ]
com.opencsv.exceptions.CsvMalformedLineException: Unterminiertes Anf├╝hrungszeichen am Ende einer CSV-Zeile. Anfang des verlorenen Textes: ['' , '' ,
]
        at com.opencsv.CSVReader.primeNextRecord(CSVReader.java:245)
        at com.opencsv.CSVReader.flexibleRead(CSVReader.java:610)
        at com.opencsv.CSVReader.readNext(CSVReader.java:204)
        at liquibase.util.csv.CSVReader.readNext(CSVReader.java:36)
        at liquibase.util.csv.CSVReaderTest.$spock_feature_0_1(CSVReaderTest.groovy:37)

[ERROR]   CSVReaderTest.invalid csv:41 Condition not satisfied:

e.message.startsWith("Unterminated quoted field at end of CSV line")
| |       |
| |       false
| Unterminiertes Anf├╝hrungszeichen am Ende einer CSV-Zeile. Anfang des verlorenen Textes: ['g' , 'h' ,
| ]
com.opencsv.exceptions.CsvMalformedLineException: Unterminiertes Anf├╝hrungszeichen am Ende einer CSV-Zeile. Anfang des verlorenen Textes: ['g' , 'h' ,
]
        at com.opencsv.CSVReader.primeNextRecord(CSVReader.java:245)
        at com.opencsv.CSVReader.flexibleRead(CSVReader.java:610)
        at com.opencsv.CSVReader.readNext(CSVReader.java:204)
        at liquibase.util.csv.CSVReader.readNext(CSVReader.java:36)
        at liquibase.util.csv.CSVReaderTest.$spock_feature_0_1(CSVReaderTest.groovy:37)

[ERROR]   CSVReaderTest.invalid csv:41 Condition not satisfied:

e.message.startsWith("Unterminated quoted field at end of CSV line")
| |       |
| |       false
| Unterminiertes Anf├╝hrungszeichen am Ende einer CSV-Zeile. Anfang des verlorenen Textes: ["def
| ]
com.opencsv.exceptions.CsvMalformedLineException: Unterminiertes Anf├╝hrungszeichen am Ende einer CSV-Zeile. Anfang des verlorenen Textes: ["def
]
        at com.opencsv.CSVReader.primeNextRecord(CSVReader.java:245)
        at com.opencsv.CSVReader.flexibleRead(CSVReader.java:610)
        at com.opencsv.CSVReader.readNext(CSVReader.java:204)
        at liquibase.util.csv.CSVReader.readNext(CSVReader.java:36)
        at liquibase.util.csv.CSVReaderTest.$spock_feature_0_1(CSVReaderTest.groovy:37)

[INFO]
[ERROR] Tests run: 3825, Failures: 3, Errors: 0, Skipped: 7
```

Unfortunately there seems to be more code that relies on particular behavior. Do you want to add that fix, or do you want me to provide one? This issue is a showstopper for me, as I cannot test my contribution regarding [SQL Anywhere TIMESTAMP](https://github.com/liquibase/liquibase/issues/3971).

NB: I think it is not a good idea that any test is dependend of the locale in any way and would highly recommend removing any such dependencies instead of fixing them.

**Comment by filipelautert** [comment]
Hello @mkarg - I faced the same problem on Windows pt-br:

```
Condition not satisfied:

e.message.startsWith("Unterminated quoted field at end of CSV line")
| |       |
| |       false
| Delimitador de fim de campo texto não encontrado ao final da linha CSV. Começo do texto perdido: ('' , '' ,
| ).
```

I believe that `CSVReaderTest `is the last one that needs to be fixed.  I changed the test to use the line number instead of verifying the message. 

Could you check if the build works for you now?

**Review by mkarg — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]
This PR Enables liquibase tests to run regardless of the machine locale.

**Review by rberezen — APPROVED** [review]

**Pull request merged**
