### PR TITLE
CORE-3464 Add Oracle Foreign Key defs. to dependency graph

### PR DESCRIPTION
**Pull request by danielthegray**
Since a dependency graph already exists, I simply added mappings for the
foreign key relationships on the DB. I also renamed an Oracle-specific
method for more clarity.

The goal of this PR is to ensure that the generated changelog for an Oracle database has the table definitions in the right order (sometimes it would create a table with a foreign key pointing to a table that hadn't been created/defined yet).

### CODE REVIEW

**Comment by danielthegray** [comment]
I might also add that the FOREIGN KEY dependencies are already added to the dependency graph for MS SQL Server (so I think it makes perfect sense to add it for Oracle as well!)

**Comment by danielthegray** [comment]
@SteveDonie is there a chance for this to make it into the upcoming 3.8.x release? I saw in a comment on another PR that you guys would be releasing 3.8.1 soon?

If it doesn't fit into you're schedule, should I just point the PR at the master branch instead?

**Comment by danielthegray** [comment]
I can see that the new changes on branch 3.8.x make this PR obsolete (since the re-ordering of the Oracle database objects has been re-written). Therefore, I will now close this PR.

**Comment by SteveDonie** [comment]
Thanks Daniel - I appreciate the effort!

**Pull request closed without merging**
