### PR TITLE
Fixed issue with h2 loadUpdateData not correctly handling values with the string " values " in the inserted data 

### LINKED ISSUE #1767: Liquibase loadUpdateData doesn't properly insert H2 column text 'scale values mean'
## Environment
**Liquibase Version**: 4.3

**Liquibase Integration & Version**: maven (but reproduces on CLI too)

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: H2

**Operating System Type & Version**:

## Description
Here is the description with a workaround:
https://forum.liquibase.org/t/cant-insert-the-string-scale-values-mean-without-it-being-changed/5121

## Steps To Reproduce
* Have Liquibase installed in the commandline (latest is fine, 4.3 as of this issue)
* git clone: https://github.com/MAYarbrough/LiquibaseH2Issue
* do a liquibase update SQL 

## Actual Behavior
Changeset rendered:
-- Changeset db.changelog-master.yaml::1595012255439-41::myarbrou
-- WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
MERGE INTO PUBLIC.usage_agreement_terms (version, text, start_date) VALUES ('v1.0', **'scale KEY(version) values mean',** '2021-02-12');

## Expected/Desired Behavior
Changeset should be:
-- Changeset db.changelog-master.yaml::1595012255439-41::myarbrou
-- WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
MERGE INTO PUBLIC.usage_agreement_terms (version, text, start_date) VALUES ('v1.0', **'scale values mean'**, '2021-02-12');

### PR DESCRIPTION
**Pull request by tomyy**
## Environment
**Liquibase Version**: all

**Liquibase Integration & Version**: all

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: H2

**Operating System Type & Version**: all

## Pull Request Type

* [x] Bug fix (non-breaking change which fixes an issue.) closes #1767 
* [ ] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
(Copied from https://github.com/liquibase/liquibase/issues/1767)

Here is the description with a workaround:
https://forum.liquibase.org/t/cant-insert-the-string-scale-values-mean-without-it-being-changed/5121

## Steps To Reproduce
* Have Liquibase installed in the commandline (latest is fine, 4.3 as of this issue)
* git clone: https://github.com/MAYarbrough/LiquibaseH2Issue
* do a liquibase update SQL

## Actual Behavior
Changeset rendered:
-- Changeset db.changelog-master.yaml::1595012255439-41::myarbrou
-- WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
MERGE INTO PUBLIC.usage_agreement_terms (version, text, start_date) VALUES ('v1.0', 'scale KEY(version) values mean', '2021-02-12');

## Expected/Desired Behavior
Changeset should be:
-- Changeset db.changelog-master.yaml::1595012255439-41::myarbrou
-- WARNING The following SQL may change each run and therefore is possibly incorrect and/or invalid:
MERGE INTO PUBLIC.usage_agreement_terms (version, text, start_date) KEY(version) VALUES ('v1.0', 'scale values mean', '2021-02-12');

## Fast Track PR Acceptance Checklist:

* [x] Build is successful and all new and existing tests pass
* [x] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
* [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

### CODE REVIEW

**Comment by molivasdat** [comment]
Hi @tomyy 
Thanks for this PR.
There should be a snapshot build in github actions associated with this PR if the tests succeed.
Here's what happens next:
A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or [Test Harness Tests](https://github.com/liquibase/liquibase-test-harness/pulls)
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by tomyy** [comment]
How can I trigger a rebuild? The "Build and Test / Java 11" failed because some dependencies could not be resolved, but my code change doesn't change any dependencies...

**Review by nvoxland — APPROVED** [review]
Code review and test results:

Things to be aware of:
- Change fixes regular expression to use the first " values " it finds in a statement as the "values" part of the SQL vs. the last " values " it finds which might be in some of the inserted data.
- Adds a unit test for a problem "values" statement
- Only impacts H2

Things to worry about:
- Nothing

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
PR fixes and H2 bug caused by having the key word "values" in the data of a loadData changetype. 
* New unit test added to validate the fix.

APPROVED

Note: There were test harness failures for EDB Postgres; these are unrelated to this fix and were due to the EDB environment not loading correctly.

**Comment by tabbyf00** [comment]
Thanks for your PR submission! We just finished reviewing and merging it into the [4.17.0 release](https://github.com/liquibase/liquibase/releases/tag/v4.17.0) on October 10, 2022. When you get a chance, could you please Star the [Liquibase project](https://github.com/liquibase/liquibase)? The star button is in the upper right corner of the screen.

**Comment by tabbyf00** [comment]
Thanks for your PR submission! We just finished reviewing and merging it into the [4.17.0 release](https://github.com/liquibase/liquibase/releases/tag/v4.17.0) on October 10, 2022. When you get a chance, could you please Star the [Liquibase project](https://github.com/liquibase/liquibase)? The star button is in the upper right corner of the screen.

**Pull request merged**
