### PR TITLE
Made ChangeWithColumns extend Change so that an extension would have …

### PR DESCRIPTION
**Pull request by pmendelson**
…access to both sets of methods. 

An example of a usage is to create a set of helper methods that are used by both an extension of CreateTableChange and AddColumnChange.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-105) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.0 beta 2

### CODE REVIEW

**Comment by pmendelson** [comment]
Pull request as stated is not as useful as I thought.  I'm planning to propose an interface hierarchy like: Change >> **TableChange** >> ChangeWithColumns but I need to do more research to see if that would break uses of ChangeWithColumns

**Comment by ro-rah** [comment]
Hi @pmendelson ,

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
Hi @pmendelson , if you still are interested in this PR being merged as is, would you mind adding some tests?  I will size at a Med for now.

**Comment by nvoxland** [comment]
Since the original poster didn't end up seeing as much value in the change as he was hoping, and we're already planning on a overall analysis of the Change hierarchy which may or may not include something similar to this change and/or his other proposed change, I'll just close this one for now.

**Pull request closed without merging**
