### PR TITLE
Fix OSGi import for `org.apache.commons.io`

### PR DESCRIPTION
**Pull request by vkolomeyko**
Fixes: https://github.com/liquibase/liquibase/issues/6020

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
 

## Description

Since LB has a compile dependency on `org.apache.commons.io` package, it is incorrect to list it as an optional dependency.

After the change the section will have:
```
Import-Package: ...,org.apache.commons.io;version="[2.16.1,3)"
 ```

## Additional Context

Since `commons-io` library perform a multi-version export, this change is also putting some version constrains to pick the latest version.

### CODE REVIEW

**Comment by filipelautert** [comment]
Hey @vkolomeyko - based on https://github.com/liquibase/liquibase/pull/6021, do you think we will need to add the other apache commons in this list too?

**Comment by vkolomeyko** [comment]
> Hey @vkolomeyko - based on #6021, do you think we will need to add the other apache commons in this list too?

@filipelautert - it might be a good idea. Let me do that, as part of this PR.
Outside of `org.apache.commons.io` I can only see in the code `import org.apache.commons.lang3`.

**Comment by vkolomeyko** [comment]
@filipelautert - I think this PR is ready for review. Could you (re-)start CI pipelines?

**Comment by a1flecke** [comment]
Looking forward to this fix. Some of our projects are broken because of this

**Review by MalloD12 — APPROVED** [review]
**Approved**.

Changes seems to be good. Build and test checks have been successfully executed. @rberezen I think there is no need for this change to trigger functional tests or test harness. What do you think?

Thanks,
Daniel.

**Comment by rberezen** [comment]
> **Approved**.
> 
> Changes seems to be good. Build and test checks have been successfully executed. @rberezen I think there is no need for this change to trigger functional tests or test harness. What do you think?
> 
> Thanks, Daniel.

Agree

**Comment by vkolomeyko** [comment]
@filipelautert @MalloD12 @rberezen @jandroav - would you be comfortable merging this PR into the main branch?

**Review by filipelautert — APPROVED** [review]

**Comment by MalloD12** [comment]
Cool, thank you @vkolomeyko for your quick confirmation!

Daniel.

**Pull request merged**
