### PR TITLE
Fixes #1411 by adding a separate query fr DB2 on AS400

### LINKED ISSUE #1411: DropAll doesn't work anymore on DB2 for i
## Environment
**Liquibase Version**: 4.0.0

**Database Vendor & Version**: DB2 for i (AS400 iSeries)

## Description
When dropping all tables, Liquibase tries to lookup foreign key constraints. It executes a database specific query to do this.
It has a specific query for DB2, but this only works for DB2 UDB, and not for DB2 for i.

## Steps To Reproduce
List the steps to reproduce the behavior.
Execute a dropAll against a DB2 for i database. 

## Actual Behavior
An exception occurs:
`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in com.essers.legplanning.domain.support.internal.DomainSupportConfiguration: Invocation of init method failed; nested exception is liquibase.excep
tion.DatabaseException: liquibase.command.CommandExecutionException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: com.ibm.as400.access.AS400JDBCSQLSyntaxErrorException: [SQL0204] REFERENCES in SYSCAT type *FILE not found.
`

## Expected/Desired Behavior
No exception occurs and tables are dropped.

## Additional Context
This worked on 3.6.3, but not anymore on 4.0.0. The reason for this is some internal Liquibase refactoring, where dropping the tables is now done differently. See StandardLockService.destroy [https://github.com/liquibase/liquibase/commit/7fa3d5305ef3a9b2cd7d7e79bde48a8cae82755c](https://github.com/liquibase/liquibase/commit/7fa3d5305ef3a9b2cd7d7e79bde48a8cae82755c)

A similar check has already built in to retrieve unique constraints. See [https://liquibase.jira.com/browse/CORE-1915](https://liquibase.jira.com/browse/CORE-1915)
An extra db2 check was built in (see [https://github.com/liquibase/liquibase/commit/b54ee3faee00c7d9a99036dc711094556b50298e)](https://github.com/liquibase/liquibase/commit/b54ee3faee00c7d9a99036dc711094556b50298e))
{{ if (database.getDatabaseProductName().startsWith("DB2 UDB for AS/400"))}}

## Test Requirements (Internal Liquibase QA)
This issue is a special case where we do not have access to the database platform in order to perform testing. Our validations will be to ensure the changes have not impacted other platforms.

#### Manual Test Requirements
Setup: Populate the database with tables with a foreign key. 

_Verify successful drop-all of tables associated by a foreign key._

* Oracle
* MSSQL
* MySQL
* Postgres
* Maria DB

#### Automated Test Requirements
* Verify all existing functional tests pass on the build server.
* Implement hasForeignKey and doesNothaveForeignKey methods for the DataBaseInstance class.
  * MySQLInstance.java
  * MariaDbInstance.java
  * MsSqlInstance.java
  * OracleInstance.java
  * NOTE: PostgresInstance.java is already implemented.
* Add a new test to DropAllTests.java that validates drop-all when a foreign key exists.
  * Test without a Pro license
  * Test CLI only (no Maven)
  * Test all supported platforms (multidb test)
  * Use the new format of CLI commands (LiquibaseNewCli) to construct Liquibase command line.
  * Make sure to add labels to new foreign key changesets added to the update changelog.
    * labels=”lb-683, community, addFk”

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-683) by [Unito](https://www.unito.io)
┆Fix Versions: Community 4.x

### PR DESCRIPTION
**Pull request by wardvijf**
## Environment
**Liquibase Version**: 4.0.0

**Database Vendor & Version**: DB2 for AS400

## Pull Request Type

* [x] Bug fix (non-breaking change which fixes an issue.)
* [ ] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
See https://github.com/liquibase/liquibase/issues/1411 

## Fast Track PR Acceptance Checklist:

* [x] Build is successful and all new and existing tests pass
* [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Documentation Updated

- - -
#### Links
* Fixed Issue: https://github.com/liquibase/liquibase/issues/1411 
* Local Branch: https://github.com/liquibase/liquibase/tree/wardvijf-1411-foreign-keys-db2-as400
* Unit Tests: https://github.com/liquibase/liquibase/pull/1412/checks
* Integration Tests: (shown in Unit Tests link above)
* Functional Tests: https://jenkins.datical.net/job/liquibase-pro/job/wardvijf-1411-foreign-keys-db2-as400/

#### Testing
* Steps to Reproduce: https://github.com/liquibase/liquibase/issues/1411 
* Guidance: 
  * Only impacts DB2 on as400

#### Dev Verification
Just code reviewed

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-684) by [Unito](https://www.unito.io)
┆Fix Versions: Community 4.x

### CODE REVIEW

**Comment by wardvijf** [comment]
@molivasdat is there anything else needed to get this PR merged?

**Comment by molivasdat** [comment]
Hi @wardvijf Thanks for reaching out again.  If you have a unit test to add that would be great. I don't have a DB2 on i to test out this fix with for integration testing either.  I'll get with the team to see where this can be integrated.

**Comment by wardvijf** [comment]
@molivasdat can you point me to an example test? As far as I can see, none of the existing as400/db code has unit tests?

**Comment by wardvijf** [comment]
@molivasdat just a friendly reminder, as we're waiting for this one ;-)

**Comment by molivasdat** [comment]
Hi @wardvijf As far as unit tests, if there are none for db2 on i, then it would be great to be the first.
https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests
or a functional test for those with access to a db2 on i system
https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Integration+Tests

Thanks for the reminder too.  We are working on releasing 4.3.0 in the final testing phase.  It won't make that one but looking at what fits in the next release.

**Comment by wardvijf** [comment]
Hi @molivasdat, I have been looking into the Liquibase code to write some tests for this. I did not find a way to write a standard unit test for it because the changes are made deep down in an private nested class (JdbcDatabaseSnapshot.CachingDatabaseMetaData.ForeignKeysResultSetCache).

Writing an integration test is also not possible, because by default Liquibase does not support db2i as a database, only the standard db2 (although there is some db2i specific code in the core). An extension is available for db2i (see https://github.com/liquibase/liquibase-db2i). I have also been thinking if we can do the change over there, but since the change is needed deep down in the Liquibase core (ForeignKeysResultSetCache), I don't think that's possible? Maybe @r2liquibase knows?

Side note: the existing db2i specific code that is already present in ForeignKeysResultSetCache is also not tested (see https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/snapshot/JdbcDatabaseSnapshot.java#L1533 )

How can we proceed with this one? We really want to upgrade to Liquibase 4.x, but this is blocking us right now.

**Comment by molivasdat** [comment]
Hi @wardvijf Thanks for the detailed feedback.  I'll bring this issue up in our development meeting and get back to you with options.

**Comment by wardvijf** [comment]
@molivasdat ok thanks. Do you have an idea of timing?

**Comment by wardvijf** [comment]
@molivasdat any updates?

**Comment by molivasdat** [comment]
Apologies, it has not made it into the branch for 4.4.0.  We are starting our focus on issues/PRs that are preventing folks from moving to 4.x.

**Review by nvoxland — APPROVED** [review]
The query is isolated to AS400 db2, so I assume it works and if not it won't break anything else

**Review by suryaaki2 — APPROVED** [review]

**Comment by wardvijf** [comment]
@molivasdat do you expect anything from my side for this to be merged?

**Pull request merged**
