### PR TITLE
Fixing #3708 - AddColumn fix for H2 version 1.4.200

### LINKED ISSUE #3708: AddColumn is no longer working with H2 version 1.4.200 in 4.19
## Environment

**Liquibase Version**: 4.19.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: H2 1.4.200

**Operating System Type & Version**: Windows 10

**Infrastructure Type/Provider**: VM

## Description

In Liquibase version 4.19.0 with H2 version 1.4.200, during the changelog execution the following error is thrown, when a new column is added: `Cannot add a primary key column`, even when the column is not defined to be a primary key

## Steps To Reproduce

List the steps to reproduce the behavior.
- Update temporarily the H2 version in the liquibase's root pom.xml to 1.4.200
- Execute the runYamlChangelog test of the H2IntegrationTest class

## Actual Behavior
The test fails with the error message:
```
liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation failures
          Cannot add a primary key column, changelogs/yaml/common.tests.changelog.yaml::add-column-test1::alan

```
## Expected/Desired Behavior
- The test is executed successfully even with H2 version 1.4.200
- In general: new columns could be added in case of this H2 version, as it was supported in version 4.18.0

### PR DESCRIPTION
**Pull request by KarolyNevelos**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description
Fixes the AddColumn functionality with H2 version 1.4.200 which no longer works in version 4.19.0.

The current code is always throwing "Cannot add a primary key column" error for the H2 Version 1, however this should only happen when the isPrimaryKey constraint is given.

Fixes #3708

### CODE REVIEW

**Comment by filipelautert** [comment]
Introduced by PR https://github.com/liquibase/liquibase/pull/3372

**Comment by alexmuntean** [comment]
we need this. please approve this.

**Review by filipelautert — APPROVED** [review]
Fixes the AddColumn functionality with H2 version 1.4.200 that was broken by PR #3372 merged on 4.19.0 . Thanks @KarolyNevelos for the fix and the tests!

**Review by XDelphiGrl — APPROVED** [review]
This fixes a regression impacting H2 v1.4.x that caused primary key validation errors during add column generation for columns not defined as primary keys.
* Functional and test harness executions passing.
* New `AddColumnGeneratorTest` to ensure that if H2 is v1 AND a non-primary key column is added that there are no validation errors. Thanks for the fix and for the test, @KarolyNevelos!
* No additional testing required.

APPROVED

**Pull request merged**
