### PR TITLE
[CORE-2008] Add support for creating and altering H2 sequences with max ...

### PR DESCRIPTION
**Pull request by fm8**
...and min values.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-82) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by nvoxland** [comment]
I think the 1.3.175 (2014-01-18) version is still new enough that we need a version check of H2 to determine if minValue or maxValue is supported. Could you add that in?

**Comment by javexpress** [comment]
Hi Nathan,

I think H2 (1.4.190) is now ready for minValue and maxValue support in liquibase.

Here is the error raised:
INFO 12/27/15 12:39 AM: liquibase: Successfully released change log lock
00:39:54.056 [main] WARN  - SQL Error: 0, SQLState: null  o.h.e.jdbc.spi.SqlExceptionHelper
00:39:54.056 [main] ERROR - liquibase.exception.ValidationFailedException: Validation Failed:
     2 changes have validation failures
          minValue is not allowed on h2, com/javexpress/gwt/fw/server/sistem/update/sistem.update.000.xml::DT_GUNCE_seq::hakanc
          maxValue is not allowed on h2, com/javexpress/gwt/fw/server/sistem/update/sistem.update.000.xml::DT_GUNCE_seq::hakanc
  o.h.e.jdbc.spi.SqlExceptionHelper

Thank you for this great work again.

**Comment by kailt** [comment]
Any progress on this? What's blocking the merge?

**Comment by fm8** [comment]
Apologies, this is with me - looking back on the history, Nathan asked for a check of the H2 version being used as the feature is quite new. I'll have a look into it this week.

**Comment by barclay-reg** [comment]
hey @fm8 any news about this?
do you need help?

**Comment by fm8** [comment]
Hi @barclay-reg , I've just pushed some changes to this branch that should solve the immediate problem. But I'm having some serious git merge issues trying to merge latest changes from master in. If you can help with that I would be most appreciative! Also, do you have a use-case that you can use to test this with -- I've only tested with unit tests at this stage...

**Comment by barclay-reg** [comment]
Hi @fm8, I will check that soon (the testing). About merging ... I'd suggest rebasing your branch CORE-2008_3.3.x to liquibase:master (instead of merging). Even if this may make your working copy not compiling in the first moment or causes conflicts, this seems the better and cleaner way ... I will try this also tomorrow

**Comment by barclay-reg** [comment]
hey @fm8, Ive completed by tests, looks good so far, but here are some comments
* why is there no version check at CreateSequenceGenerator
** incrementBy should also be valid for H2 ( see alterSequence)
* methodName databaseIsUnsupportedH2Database is missleading
* no check, if no version is given at all (like with --url=offline:h2)
** result seems TRUE in this case, other cases like this would force the user, to give a version (like --url=offline:h2?version=1.4.190)

I couldn't do anything about the merging stuff.
Maybe best is, to create complete new feature-branch and redo the changes - this would also make this pull-request obsolete

**Comment by fm8** [comment]
Thanks for your comments @barclay-reg , most appreciated!

I also tried rebasing with no success, so I'll try again with a new branch after synching my fork with the latest changes from master. I'll close this pull request once I've opened a new one, and I'll drop you a line.

The new pull request should have solutions to the comments raised.

**Comment by barclay-reg** [comment]
Hi @fm8, any progress with the new pull request?
If it's ok for you, I can do this.

**Comment by fm8** [comment]
Hi @barclay-reg , if you would be happy to do that I would really appreciate your help...!!

**Comment by barclay-reg** [comment]
Hi @fm8 and @nvoxland 

new PR with this changes is arrived see 
https://github.com/liquibase/liquibase/pull/603

**Comment by ro-rah** [comment]
Closing this as it is superceded by #603

**Pull request closed without merging**
