### PR TITLE
Allow primary key on addColumn for H2

### PR DESCRIPTION
**Pull request by nick318**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Allow adding primary key column for H2. 
Remove it from validation, so that liquibase could generate an SQL.

### CODE REVIEW

**Comment by nick318** [comment]
@tabbyf00 @nvoxland should I ping or just sit back and wait? 🙂

**Comment by nvoxland** [comment]
**Pre-Review Notes**

Thanks for the PR!

Changes overall make sense. Adds a unit test, but could use a test changeset added to `changelogs/h2/complete/root.changelog.xml` to see it actually running.

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Review by MalloD12 — APPROVED** [review]
Approved.

# Review and testing results:

This change looks good to me. I have only made few small changes which are detailed below:
- Added validation to do not allow adding a column for H2 below version 
- updated “testAddPrimaryKeyColumnH2” test to validate add column validation error is added for H2 version lower from 2.X
- Update “auto increment on varchar column” test from DiffChangelogTest to disable auto-commit mode.

### Things to be aware of:
- Change is only applicable for H2, so it doesn't not have an impact on any other DB.
- Manually and unit tested.

### Things to worry about:
- Nothing

**Review by suryaaki2 — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]
Change applies only for H2 version > 2 .

**Review by XDelphiGrl — APPROVED** [review]
H2 v2 supports adding primary keys in an `ALTER TABLE` statement. This PR extends Liquibase to generate SQL for the addition of primary keys in `ALTER TABLE` statements, and will no longer throw a validation error for H2 v2 and later. H2 v1 does not support adding primary keys in `ALTER TABLE` statements; Liquibase checks the database major version and throws a validation error for H2 v1. 

*Example of Liquibase Generated SQL for ALTER TABLE in H2 v2*
```
ALTER TABLE table_name ADD ID BIGINT NOT NULL PRIMARY KEY";
```

* Automated functional and test harness executions are passing.
* Lovely new unit tests added for v1 and v2 cases.
* No additional testing required.

APPROVED

**Pull request merged**
