### PR TITLE
Add '@Deprecated' annotation to update() methods

### PR DESCRIPTION
**Pull request by tati-qalified**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [ X ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description
Some update() methods were missing the '@Deprecated' annotation, which made the javadocs outdated. I added the annotation to these methods: 
- update(String contexts, Writer output)
- update(Contexts contexts, Writer output)
- update(Contexts contexts, LabelExpression labelExpression, Writer output)
- update(Contexts contexts, LabelExpression labelExpression, Writer output, boolean checkLiquibaseTables)

## Things to be aware of
This will change the javadocs documentation

## Things to worry about
It's my understanding that all liquibase.update() methods are deprecated. If not, ignore this PR.

### CODE REVIEW

**Review by filipelautert — APPROVED** [review]

**Comment by MalloD12** [comment]
I think it would be nice if we also add some javadoc recommending users to use CommandScope. Something like:
```
 /**
 * @deprecated use {@link CommandScope}
 */**
```

What do you guys think about it? cc: @tati-qalified @filipelautert

**Review by MalloD12 — APPROVED** [review]

**Comment by tati-qalified** [comment]
@MalloD12 sounds good, I see that you've already merged to master, should I push the changes here or create another PR?

**Comment by tati-qalified** [comment]
Woops, I saw "merged master into master" and thought it was the other way around. I'll update the code.

**Comment by tati-qalified** [comment]
Updated. Are we good to go? Any other suggestions?

**Comment by MalloD12** [comment]
> Updated. Are we good to go? Any other suggestions?

Nothing else from my side, thank you @tati-qalified!

**Pull request merged**
