### PR TITLE
trying to improve situation for oracle generated sql

### PR DESCRIPTION
**Pull request by mrmarkyb**
for use with sql-maven-plugin not sure how best to use property injection

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @mrmarkyb ,

Thanks for your PR submission and sorry for the long delay.  We are jump starting our process.  I see that there is a conflict that must be resolved, would you mind making that update?

**Comment by ro-rah** [comment]
One more note @mrmarkyb:

Tests can move this to the next state (Conditioning) easier if you include tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)).  Would you be willing to add tests as well?

Thanks in advance :)

**Comment by ro-rah** [comment]
Hi @mrmarkyb , I have not seen a response so, I am moving to 4.0 beta 3 bucket, risk high/impact med to make room for resolving conflicts and testing.

**Comment by molivasdat** [comment]
Hi @mrmarkyb 
Thank you for this Pull Request.

I’m putting together a core team of developers to help us with community requests. We’ll make Liquibase improvements faster together!

If you are willing to help, please reply to this comment and I’ll let you know the next steps.

Your friendly neighborhood developer advocate,
@molivasdat

**Comment by filipelautert** [comment]
Hi - please reopen the PR and fix the conflicts if you still willing to get this work included. Thanks!

**Pull request closed without merging**
