### PR TITLE
Add support for multiline rollback

### PR DESCRIPTION
**Pull request by Saravanan21**
Allow support multiline rollback without having to put lots of comment, using the format:

```
--liquibase formatted sql

--changeset saravanan:1
create table person (
    id serial primary key,
    first_name varchar(50),
    last_name varchar(50),
    dob date,
    signup timestamp
);

insert into foo (table_name)
values (
    'person'
);

--changesetrollback
delete from foo where table_name = 'person';
drop table person;
```

### CODE REVIEW

**Comment by olegshtch** [comment]
@Saravanan21 It's a nice feature. Are there any news about it?

**Comment by SteveDonie** [comment]
Datical, the company that is currently maintaining Liquibase, has recently committed more resources to the project. We are currently reviewing all open pull requests and will be making decisions on them in the near future. Thanks for your patience.

**Comment by onurozardic** [comment]
> 
> 
> Datical, the company that is currently maintaining Liquibase, has recently committed more resources to the project. We are currently reviewing all open pull requests and will be making decisions on them in the near future. Thanks for your patience.

Hi Steve, is there any deadline defined for the process? Thanks and best regards.

**Comment by ro-rah** [comment]
Hi @Saravanan21 

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
Hi @Saravanan21 ,

Thanks for adding tests!  Would you please resolve the branch conflicts?  Thanks,  Ronak

**Comment by pronoyroy** [comment]
related issue #334 https://github.com/liquibase/liquibase/pull/334

**Comment by kataggart** [comment]
@pronoyroy thanks for calling my attention to this after I closed it; we are working through issues/PRs, prioritizing things related to security and bugs that interfere with primary use cases. We will be able to put more attention on requested enhancements soon. Thanks again for re-viving this. Exactly what I was hoping as I try to clean out the backlog a bit to help us better focus.

**Comment by filipelautert** [comment]
Hello @Saravanan21  et al , thanks for the contribution Currently we have 3 PR's to handle the same problem using slightly different approaches: #334, #695 and #1399 . After reviewing the PRs, the comments and the way Liquibase works we want to go ahead with PR #1399 . So we will close this one and will centralize the discussion there. The reason we are not advancing with this one is that formatted sql file should be executable outside of liquibase through normal database tools without doing liquibase-specific things. Basically you could still copy/paste the contents into any sql editor and run it and it will still make your changes correctly, even though it wouldn't track them in the databasechangelog table.

That's why the --changeSet delimiter etc. are sql comments, and PR #1399 follows this approach.

**Pull request closed without merging**
