### PR TITLE
Fix snowflake dbdoc and snapshot execution.

### PR DESCRIPTION
**Pull request by costin-moraru**
https://forum.liquibase.org/t/snowflake-support-for-snapshots/4639

- - -
name: Pull Request
about: Create a report to help us improve
title: ''
labels: Status:Discovery
assignees: ''

- - -

## Environment
**Liquibase Version**: 3.x and 4.x

**Liquibase Integration & Version**:  CLI

**Liquibase Extension(s) & Version**: liquibase-snowflake-4.0.0

**Database Vendor & Version**: Snowflake

**Operating System Type & Version**: CLOUD

## Pull Request Type

* [x ] Bug fix (non-breaking change which fixes an issue.)
* [x ] Enhancement/New feature (non-breaking change which adds functionality)
* [x ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
When running the liquibase dbDoc or snapshot command, the following error happen:
**liquibase.exception.UnexpectedLiquibaseException: Don't know how to query for sequences on DEV_APP @ jdbc:snowflake://dev.us-east-1.snowflakecomputing.com:443/ (Default Schema: MY_DATABASE)**
The error is caused by some differences in the sequnce query and in the constraint table name.

## Steps To Reproduce
* Start a new project for Snowflake db
* Add a changeset
* Run liquibase update
* Run liquiabse dbdoc doc_folder or liquibase snapshot ...

## Actual Behavior
liquibase.exception.UnexpectedLiquibaseException: Don't know how to query for sequences on costinmoraru @ jdbc:snowflake://gi78848.eu-central-1.snowflakecomputing.com:443/ (Default Schema: DEMO)
[log.log](https://github.com/liquibase/liquibase/files/5262097/log.log)

## Expected/Desired Behavior
Execute liquiabse dbdoc doc_folder or liquibase snapshot successful.

## Screenshots (if appropriate)
NO

## Additional Context
NO

## Fast Track PR Acceptance Checklist:

* [x ] Build is successful and all new and existing tests pass
* [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-696) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.x,Liquibase 4.3.1

### CODE REVIEW

**Comment by molivasdat** [comment]
HI @costin-moraru Thanks for creating this PR and the help with @ro-rah .  We may need to split this PR up into mysql changes and move the snowflake changes over to the [snowflake extension](https://github.com/liquibase/liquibase-snowflake)
Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest
changes, additional tests, or provide other feedback. The PR will be prioritized
according to our development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
I am so glad y'all are working together! (@costin-moraru  and @molivasdat ).  I am happy to help.  Pretty sure we have some docs on extension dev.

**Comment by nvoxland** [comment]
It looks like the snowflake changes already exist in the liquibase/liqubase-snowflake extension. As the snowflake support improves in that extension, we'll eventually move it into the main repository but are not ready to yet.

Can you @costin-moraru can you double check that you don't get any errors if you are using the snowflake extension? And if you still are, open a PR there?

**Comment by nvoxland** [comment]
It looks like your mysql changes are in #1441 , so I will close this PR as "should already be in the snowflake extension" and handle the mysql portion with the other PR.

**Comment by costin-moraru** [comment]
Hi, i'll do. Maybe snowflake extension is not loaded properly. I'll check.

Il Mer 10 Feb 2021, 22:26 Nathan Voxland <notifications@github.com> ha
scritto:

**Pull request closed without merging**
