### PR TITLE
Make Liquibase AutoCloseable

### PR DESCRIPTION
**Pull request by andrejpetras**
Hi,

I am working on the Liquibase extension for the [QuarkusIO](https://quarkus.io/) framework. 
Liquibase extension PR: https://github.com/quarkusio/quarkus/pull/6334
For better integration and handling of the database connection it would be much better if the liquibase.Liquibase implements AutoClosable interface.

```
public class Liquibase implements AutoCloseable {
    @Override
    public void close() throws Exception {
        if (database != null) {
            database.close();
        }
    }
}
```

Would it suit you?

Regards,
Andrej

### CODE REVIEW

**Comment by andrejpetras** [comment]
@nvoxland any update on this? How can I help?

**Comment by gsmet** [comment]
For the record, it would simplify a lot the integration of Liquibase in Quarkus as we wouldn't have to wrap `Liquibase`.

**Comment by SteveDonie** [comment]
After review, we have decided that this is a good and safe change, and we would like to accept it. I will also be cherry-picking the change into the 3.8.x branch so that it is included in the 3.8.7 release, which should be in the next few weeks. We will be releasing either 3.9.0 or 4.0.0 (based off master plus the changes that have been made in the 3.8.x branch) in the next month or two.

**Comment by SteveDonie** [comment]
Pull request for the 3.8.x branch is PR #987

**Comment by gsmet** [comment]
Thanks @SteveDonie !

**Comment by andrejpetras** [comment]
@SteveDonie thank you. 
I updated the Quarkus PR, now we just need to wait for the Liquibase release (3.8.7), after that we can merge it to the Quarkus version (@gsmet) and also to public blog about `Quarkus meets Liquibase`

**Comment by SteveDonie** [comment]
I just merged #987 into the 3.8.x branch, and we expect that 3.8.7 release with that in it will be on or about February 20.

**Comment by andrejpetras** [comment]
@SteveDonie https://capgemini.github.io/development/Quarkus-meets-Liquibase/

**Pull request merged**
