### PR TITLE
Added table name to unique constraints cache key for PostgreSQL

### LINKED ISSUE #2069: diffChangelog generates ADD CONSTRAINT changesets for existing unique constraints
## Environment
**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: Gradle

**Liquibase Extension(s) & Version**: Liquibase-Hibernate5 4.4.3

**Database Vendor & Version**: PostgreSQL 13

**Operating System Type & Version**: Windows 10, DB is running in Docker container

## Description
I have a Spring Boot application with Spring Data JPA connecting to a PostgreSQL 13 and I'm using Liquibase for migrations using the Gradle plugin.

When I run the `diffChangelog` Gradle task, the generated changelog contains statements like

```
-- changeset krakhman:1630671193066-3
ALTER TABLE public.surgery_free_friday ADD CONSTRAINT surgery_free_friday_date UNIQUE (date);
```

even though the `surgery_free_friday_date` is present in the database.

I've debugged the code and I've landed on the following line in `liquibase.snapshot.jvm.UniqueConstraintSnapshotGenerator#listColumns`:

grafik

As you can see on the screenshot, there is a mismatch in the cache keys, supposedly caused by the "null" which in turn is caused by this line

grafik

as `row.get("TABLE_NAME")` always seems to return `null`.

## Steps To Reproduce
It seems the bug is triggered, when `bulkQuery` is set to `true` in this line

grafik

## Actual Behavior
`ADD CONSTRAINT` changesets are generated in the changelog.

## Expected/Desired Behavior
NO `ADD CONSTRAINT` changesets are generated in the changelog.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-2130) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by cypressious**
Fixes #2069

### CODE REVIEW

**Comment by nvoxland** [comment]
I pushed the current version of master to your fork to fix the build issue.

**Comment by molivasdat** [comment]
Hi @cypressious Thanks for creating this PR.
@nvoxland Looks like this build is still broken.  Not where the build issue lies.


A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or [Test Harness Tests](https://github.com/liquibase/liquibase-test-harness/pulls)
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by cypressious** [comment]
Is there anything I can do to help?

**Comment by molivasdat** [comment]
@cypressious I think this may be a build break to get you a temp fix.

**Comment by nvoxland** [comment]
The problem is that your branch name has a / in it which throws off what we currently have for the "make a version from the branch" logic.

I'm in the midst of a redo of the build logic which will probably take a week or so more to work though. Probably easiest to just wait for that vs. trying to handle it in this PR or even renaming your branch.

**Comment by cypressious** [comment]
I can create a new PR, that would be absolutely no problem :)

**Comment by molivasdat** [comment]
@cypressious That would probably be the most expedient way to fix the build issue to get you a temp fix.

**Pull request closed without merging**
