### PR TITLE
Fix Postgresql autoIncrement Information in snapshot

### LINKED ISSUE #2867: Postgres autoIncrementInformation in snapshot is not correct
## Environment

**Liquibase Version**: 4.10

**Database Vendor & Version**: [all tested by test-harness](https://github.com/liquibase/liquibase-test-harness#test-harness-support-matrix)

**Operating System Type & Version**: windows 10

## Description
Regardless of what is actually configured for auto increment values for column, snapshot always shows 
```
...
            "autoIncrementInformation": {
              "incrementBy": "1!{java.math.BigInteger}",
              "startWith": "1!{java.math.BigInteger}"
            },
...
```

## Steps To Reproduce
PostgreSQL example:
run SQL similar to what Liquibase generates for [addAutoIncrement test](https://github.com/liquibase/liquibase-test-harness/blob/cc8a0007bb2410f0292113a1def112cae43a289e/src/main/resources/liquibase/harness/change/changelogs/addAutoIncrement.xml#L22-L23) in test harness
```
CREATE TABLE public.autoincrement_test ("intColumn" INTEGER NOT NULL, "dateColumn" date, CONSTRAINT autoincrement_test_pkey PRIMARY KEY ("intColumn"));
CREATE SEQUENCE  IF NOT EXISTS public."autoincrement_test_intColumn_seq" START WITH 100 INCREMENT BY 2;
ALTER TABLE public.autoincrement_test ALTER COLUMN  "intColumn" SET NOT NULL;
ALTER TABLE public.autoincrement_test ALTER COLUMN  "intColumn" SET DEFAULT nextval('public."autoincrement_test_intColumn_seq"');
ALTER SEQUENCE public."autoincrement_test_intColumn_seq" OWNED BY public.autoincrement_test."intColumn";
```
insert few values into the table
```
insert into PUBLIC.autoincrement_test ("dateColumn") values ('2010-07-28');
insert into PUBLIC.autoincrement_test ("dateColumn") values ('2010-07-28');
insert into PUBLIC.autoincrement_test ("dateColumn") values ('2010-07-28');
```
run `select * from PUBLIC.autoincrement_test` and observe values for `intcolumn` are 100, 102, 104. This shows that autoincrement works.
run `liquibase --output-file=mySnapshot.json snapshot --snapshotFormat=json` command against this DB

## Actual Behavior
mySnapshot.json contains 
```
            "autoIncrementInformation": {
              "incrementBy": "1!{java.math.BigInteger}",
              "startWith": "1!{java.math.BigInteger}"
            },
```
for intColumn 

## Expected/Desired Behavior
mySnapshot.json contains incrementBy=2 startWith=100 (106 in case insert queries were ran)

## Additional Context
Discovered in test-harness where [expected json](https://github.com/liquibase/liquibase-test-harness/blob/main/src/main/resources/liquibase/harness/change/expectedSnapshot/addAutoIncrement.json) across all platforms contains   `incrementBy`=1 and `startsWith`=1 even if values in input changelog were different.  Observed for all platforms from [Test-Harness Support Matrix](https://github.com/liquibase/liquibase-test-harness#test-harness-support-matrix) that support `incrementBy` and `startWith` attributes for addAutoIncrement changeType

### PR DESCRIPTION
**Pull request by filipelautert**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Fix Postgresql auto increment details. Extracted code from ColumnSnapshotGenerator into new class AutoIncrementSequencesCache, and by doing this get rid of a deprecated method usage and creates a standard way to implement new sequence queries.

The AutoIncrementSequencesCache will run a query once against the database and store a cache of all sequences that are related to auto increment fields. To add support to anotehr database , a new query needs to be created returing the same 5 fields that are provided by the existing queries.

## Things to be aware of

- Fixes #2867  .
- This change breaks Postgresql addAutoIncrement tests on test-harness, so PR https://github.com/liquibase/liquibase-test-harness/pull/377 needs to be merged together with this one to ensure it passes.

## Things to worry about

- None

## Additional Context

- None

### CODE REVIEW

**Review by XDelphiGrl — APPROVED** [review]
PR fixes a bug where Liquibase did not capture the start value and increment by parameters for Postgres autoincrement columns. The bug fixes the underlying issue in `snapshot` as well as snapshot-based commands like `generate-changelog` and `diff-changelog`. 
* Code refactored to be more readable.
* Associated liquibase-test-harness PR to add automated test case [PR](https://github.com/liquibase/liquibase-test-harness/pull/377)
* No additional testing required.

APPROVED

**Comment by XDelphiGrl** [comment]
I am leaving this ticket in code review until the test-harness PR passes. Please take a look at the test failures when you have a moment, @filipelautert. Thanks!

[https://github.com/liquibase/liquibase-test-harness/pull/377](https://github.com/liquibase/liquibase-test-harness/pull/377)

**Comment by filipelautert** [comment]
@XDelphiGrl finally tests are fixed, sorry for the delay.

**Comment by suryaaki2** [comment]
@filipelautert Do you want to add javadoc comments?

**Review by suryaaki2 — APPROVED** [review]

**Comment by filipelautert** [comment]
> @filipelautert Do you want to add javadoc comments?

@suryaaki2 just did it, thanks for point out.

**Pull request merged**
