### PR TITLE
H2 unknown reserved word

### PR DESCRIPTION
**Pull request by davidwatkins73**
`UNKNOWN` is a [reserved word](http://www.h2database.com/html/advanced.html#keywords) in H2

- - -
name: Pull Request
about: Liquibase fails to execute change referring to a column named `UNKNOWN` as it is a reserved word.  This is a newly added reserved word as it works on older (1.3.x) versions of H2.
title: 'Adding 'UNKNOWN' to H2 reserved word list
labels: Status:Discovery
assignees: '?'

- - -

## Environment
**Liquibase Version**:  tried 3.5.1, 3.9.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: None

**Database Vendor & Version**: H2 1.4.200

**Operating System Type & Version**: Windows 10

## Pull Request Type

* [x] Bug fix (non-breaking change which fixes an issue.)
* [ ] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Liquibase fails to execute changes for H2 if a column is named 'UNKNOWN'.

Example error:

```
  Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "ALTER TABLE data_type ADD unknown[*] BOOLEAN DEFAULT FALSE NOT NULL"; expected "identifier"; SQL statement:
```

## Steps To Reproduce
Execute liquibase with a changeset referencing a column named 'UNKNOWN'.

Here is a live example from the [Waltz](https://github.com/finos/waltz/blob/master/waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml#L274) project.

## Actual Behavior
Errors as described above

## Expected/Desired Behavior
Executes database change on H2 Correctly

## Screenshots (if appropriate)
n/a

## Additional Context
n/a

## Fast Track PR Acceptance Checklist:

* [ ] Build is successful and all new and existing tests pass
* [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-312) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2

### CODE REVIEW

**Comment by davidwatkins73** [comment]
Reason for not running build before submission:
 
I tried to build the `liquibase-core` and `liquibase-base` modules in maven.  The first gave this error:

```
[INFO] 4 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/dev/repos/liquibase/liquibase-core/src/main/java/liquibase/resource/FileSystemResourceAccessor.java:[211,49] reference to newFileSystem is ambiguous
  both method newFileSystem(java.nio.file.Path,java.lang.ClassLoader) in java.nio.file.FileSystems and method newFileSystem(java.nio.file.Path,java.util.Map<java.lang.String,?>) in java.nio.file.FileSystems match
[INFO] 1 error
[INFO] -------------------------------------------------------------
```

the second didn't seem to do a full compile.

**Comment by ro-rah** [comment]
Hi @davidwatkins73 

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
@damienbiggs , would you be interested in expanding the unit test for this file?
https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/test/java/liquibase/database/core/H2DatabaseTest.java

Thanks!

Ronak

**Comment by ro-rah** [comment]
Set Risk to Low since it looks like a defect fix.

**Comment by damienbiggs** [comment]
Hi Ronak

I haven't used liquibase in a long time so wouldn't feel confident making
changes for it at the moment.

**Comment by ro-rah** [comment]
@damienbiggs , sorry I called out the wrong user earlier.  No prob, it I sized it with some time to look at it on our side.  Thanks for the quick reply!

**Comment by nvoxland** [comment]
The change is against master, so has to be cherry picked back into 3.10.x

**Comment by nvoxland** [comment]
This change has already been made in 3.10.x, so closing this PR

**Pull request closed without merging**
