### PR TITLE
Improved handling of endDelimiter="/"

### LINKED ISSUE #2688: Liquibase 4.9.0 and "endDelimiter:/" recognizes "/" used in PL/SQL code for calculation as changeset end delimiter
## Environment

**Liquibase Version**:
4.9.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI in Image from https://hub.docker.com/r/liquibase/liquibase

**Liquibase Extension(s) & Version**: 
n.a.

**Database Vendor & Version**:
Oracle Database 21 XE (21.3.0.0) provided by [gvenzl/oracle-xe
](https://hub.docker.com/layers/oracle-xe/gvenzl/oracle-xe/21.3.0-slim/images/sha256-d496c24007fe6c828826f7a74702733275140097758500f986a8531fb4ec754b?context=explore)

**Operating System Type & Version**:
Podman 4.0.1 on Linux

## Description

With Liquibase **4.8.0** the installation of an PL/SQL function in an Oracle 21 XE database including **/** for calculation purposes in the source code is working without any problems.

After upgrade of the Liquibase image to version **4.9.0**, the installed source code of the function in the database ends before **/** in the return statement and the function in the dabase is invalid because of missing code.

### Environment

- [Oracle Database 21 XE Image](https://hub.docker.com/layers/oracle-xe/gvenzl/oracle-xe/21.3.0-slim/images/sha256-d496c24007fe6c828826f7a74702733275140097758500f986a8531fb4ec754b?context=explore)
- JDBC driver from Oracle Instant Client 21.5.0.0.0 64bit on Linux
- [Liquibase 4.8.0 Image](https://hub.docker.com/layers/liquibase/liquibase/liquibase/4.8.0/images/sha256-ee265e6b60249a831a512bdcd068857c8bef70a6490016676c931e9462b66a99?context=explore)
- [Liquibase 4.9.0 Image](https://hub.docker.com/layers/liquibase/liquibase/liquibase/latest/images/sha256-6405a2f22d815351785adeb32e23b24918e86e483e27e4b936678c2ddf3c244a?context=explore)
- Podman 4.0.1

### Changelog install_functions.yaml
```
#
# install_functions.yaml
#
databaseChangeLog:
    - include:
        file: create_fnc_get_elapsed_time.sql
        relativeToChangelogFile: true
```

### Changeset create_fnc_get_elapsed_time.sql
```
--liquibase formatted sql
--changeset data_public:create_fnc_get_elapsed_time.sql dbms:oracle endDelimiter:/ failOnError:true runAlways:true runOnChange:true stripComments:false splitStatements:true

CREATE OR REPLACE FUNCTION fnc_get_elapsed_time
  (i_start_time                    IN NUMBER
   ,i_end_time                     IN NUMBER
  )
      RETURN NUMBER
      PARALLEL_ENABLE
  IS
  BEGIN

      RETURN ((i_end_time - i_start_time) / 100);

  EXCEPTION
      WHEN OTHERS
      THEN
          BEGIN
              RAISE;
          END;
  END fnc_get_elapsed_time;
/
```
### Execution of Liquibase 4.8.0
```
time podman run \
        --name lb-ora \
        --rm \
        --volume /database:/liquibase/changelog:Z \
        --volume /opt/oracle/instantclient:/liquibase/instantclient:ro \
        docker.io/liquibase/liquibase:4.8 \
        --changeLogFile=install_functions.yaml \
        --defaultsFile=/liquibase-development.properties \
        --password="pwd" \
        update
```
### Execution of Liquibase 4.9.0
```
time podman run \
        --name lb-ora \
        --rm \
        --volume /database:/liquibase/changelog:Z \
        --volume /opt/oracle/instantclient:/liquibase/instantclient:ro \
        docker.io/liquibase/liquibase:latest \
        --changeLogFile=install_functions.yaml \
        --defaultsFile=/liquibase-development.properties \
        --password="pwd" \
        update
```

### Liquibase properties
```
#
# properties for installation of database objects using Liquibase
#
classpath: /liquibase/changelog:/liquibase/instantclient
driver: oracle.jdbc.OracleDriver
liquibase.hub.mode: off
logLevel: warning
url: jdbc:oracle:thin:@<hostname>:1521/xepdb1
username: <username>
strict: true
```

## Actual Behavior
Partly output when Liquibase **4.9.0** is executed with **logLevel: debug**:

```
[2022-03-27 15:52:48] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2022-03-27 15:52:48] FINE [liquibase.util] Computed checksum for inputStream as 31c679bed1defccaefd71f030edcc363
[2022-03-27 15:52:48] FINE [liquibase.util] Computed checksum for 8:31c679bed1defccaefd71f030edcc363: as 94140ee341f64935c5e26926f93ff590
[2022-03-27 15:52:48] FINE [liquibase.servicelocator] Loaded liquibase.hub.HubService instance liquibase.hub.core.MockHubService
[2022-03-27 15:52:48] FINE [liquibase.servicelocator] Loaded liquibase.hub.HubService instance liquibase.hub.core.StandardHubService
Running Changeset: 012-DATA_PUBLIC/create_fnc_get_elapsed_time.sql::create_fnc_get_elapsed_time.sql::data_public
[2022-03-27 15:52:48] FINE [liquibase.changelog] Running Changeset: 012-DATA_PUBLIC/create_fnc_get_elapsed_time.sql::create_fnc_get_elapsed_time.sql::data_public
[2022-03-27 15:52:48] FINE [liquibase.executor] Changeset 012-DATA_PUBLIC/create_fnc_get_elapsed_time.sql::create_fnc_get_elapsed_time.sql::data_public
[2022-03-27 15:52:48] FINE [liquibase.changelog] Reading ChangeSet: 012-DATA_PUBLIC/create_fnc_get_elapsed_time.sql::create_fnc_get_elapsed_time.sql::data_public
[2022-03-27 15:52:48] FINE [liquibase.database] Executing Statement: CREATE OR REPLACE FUNCTION fnc_get_elapsed_time
  /**
   * Calculates the current elapsed time in seconds since the given start time.
   *
   *
   */
  (i_start_time                    IN NUMBER
   ,i_end_time                     IN NUMBER
  )
      RETURN NUMBER
      PARALLEL_ENABLE
  IS
  BEGIN

      RETURN ((i_end_time - i_start_time)
[2022-03-27 15:52:48] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2022-03-27 15:52:48] FINE [liquibase.configuration] No configuration value for liquibase.sql.logLevel found
[2022-03-27 15:52:48] FINE [liquibase.configuration] Configuration liquibase.sql.logLevel is using the default value of FINE
[2022-03-27 15:52:48] FINE [liquibase.executor] CREATE OR REPLACE FUNCTION fnc_get_elapsed_time
  /**
   * Calculates the current elapsed time in seconds since the given start time.
   *
   *
   */
  (i_start_time                    IN NUMBER
   ,i_end_time                     IN NUMBER
  )
      RETURN NUMBER
      PARALLEL_ENABLE
  IS
  BEGIN

      RETURN ((i_end_time - i_start_time)
[2022-03-27 15:52:48] FINE [liquibase.executor] 0 row(s) affected
[2022-03-27 15:52:48] FINE [liquibase.database] Executing Statement: 100);

  EXCEPTION
      WHEN OTHERS
      THEN
          BEGIN
              RAISE;
          END;
  END fnc_get_elapsed_time;
[2022-03-27 15:52:48] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2022-03-27 15:52:48] FINE [liquibase.executor] 100);

  EXCEPTION
      WHEN OTHERS
      THEN
          BEGIN
              RAISE;
          END;
  END fnc_get_elapsed_time;
[2022-03-27 15:52:48] FINE [liquibase.executor] Release Database Lock
[2022-03-27 15:52:48] FINE [liquibase.executor] Executing with the 'jdbc' executor
[2022-03-27 15:52:48] INFO [liquibase.lockservice] Successfully released change log lock
[2022-03-27 15:52:48] SEVERE [liquibase.integration] ORA-00900: invalid SQL statement

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Migration failed for change set 012-DATA_PUBLIC/create_fnc_get_elapsed_time.sql::create_fnc_get_elapsed_time.sql::data_public:
     Reason: liquibase.exception.DatabaseException: ORA-00900: invalid SQL statement
 [Failed SQL: (900) 100);

  EXCEPTION
      WHEN OTHERS
      THEN
          BEGIN
              RAISE;
          END;
  END fnc_get_elapsed_time;]
        at liquibase.command.CommandScope.execute(CommandScope.java:163)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:51)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Migration failed for change set 012-DATA_PUBLIC/create_fnc_get_elapsed_time.sql::create_fnc_get_elapsed_time.sql::data_public:
     Reason: liquibase.exception.DatabaseException: ORA-00900: invalid SQL statement
 [Failed SQL: (900) 100);

  EXCEPTION
      WHEN OTHERS
      THEN
          BEGIN
              RAISE;
          END;
  END fnc_get_elapsed_time;]
        at liquibase.integration.commandline.Main$1.run(Main.java:443)
        at liquibase.integration.commandline.Main$1.run(Main.java:221)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:165)
        at liquibase.integration.commandline.Main.run(Main.java:221)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:157)
        ... 14 more
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set 012-DATA_PUBLIC/create_fnc_get_elapsed_time.sql::create_fnc_get_elapsed_time.sql::data_public:
     Reason: liquibase.exception.DatabaseException: ORA-00900: invalid SQL statement
```

## Expected/Desired Behavior
PL/SQL source code using **/** for calculations is valid installed in an Oracle database and is not recognized as "endDelimiter" character of a Liquibase changeset.

## Screenshots (if appropriate)
PL/SQL source code in Oracle SQL Developer after installation with Liquibase **4.8.0**:
grafik

PL/SQL source code in Oracle SQL Developer after installation with Liquibase **4.9.0**:
grafik

## Additional Context
There seems to be a change in [liquibase-core/src/main/java/liquibase/util/StringUtil.java](https://github.com/liquibase/liquibase/commit/b949f0af7c8aa5478ab14b1659e04da1c35e844d), which could be relevant for the changed behaviour in Liquibase **4.9.0**.

### PR DESCRIPTION
**Pull request by nvoxland**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

If people put endDelimiter="/", they really mean the oracle-style syntax of:

```
statement 1
/
statement2
/
```

and we should treat that as such and not actually use "/" as a simple delimiter. Otherwise, something like:

```
create table x id int default 2/4
/
```
splits in the wrong spot.

Fixes #2688

## Things to be aware of

- Only impacts split logic when endDelimiter is /
- The default end delimiter already handles `/` like this, this change just extends that to explicitly specifying endDelimiter="/"

## Things to worry about

- Nothing

### CODE REVIEW

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
* Fix improves handling of the Oracle end delimiter `/` by checking to see if the `/` is at the beginning of a line and not within a statement.
* New unit tests added.
* No additional testing required.

APPROVED 

[Passing Functional Tests](https://github.com/liquibase/liquibase-pro-tests/actions/runs/2749188664)
[Passing Test Harness Execution](https://github.com/liquibase/liquibase-test-harness/actions/runs/2749191477)

**Comment by db-geek** [comment]
Thank you for the fix.

I tested Liquibase 4.15 with my Oracle database setup and the problem has been resolved.

**Comment by Sumitkrchaudhary** [comment]
This issue is seen again in 4.24 and 4.25. Is there something that broke this ?

**Comment by adrian-velonis1** [comment]
Follow-up (4.29.0): https://github.com/liquibase/liquibase/pull/5704: "Fix SQL execution issue with endDelimiter '/' and splitStatements"

**Pull request merged**
