### PR TITLE
Improved SpringResourceAccessor

### LINKED ISSUE #1436: includeAll not working with Liquibase 4.0.0
Starting with Liquibase 4.0.0, the includeAll definition in a change log file doesn´t work anymore if the referenced files are placed in a JAR file.
It´s working fine, if the files can be referenced from a target folder during development but not when the changesets should be accessed from JAR.

For details, see also https://forum.liquibase.org/t/includeall-with-v4-0-0/4655
Text from forum update
With the Quarkus version 1.7.1 which uses Liquibase 3.9.x everything works fine.

But Quarkus 1.8.x upgrades to Liquibase 4.0.0 and this causes issues with change sets using the includeAll tag.

Our changeLog.xml contains following:
<includeAll path="db/1.0.0/" errorIfMissingOrEmpty="true"/>

When we start the application in the Quarkus dev mode (mvn quarkus:dev) everything works fine; the changeLog is read and every file under the given path (db/1.0.0/) is executed/checked from Liquibase.

But if we run the application directly (with java -jar) we are getting following error:

```
Caused by: liquibase.exception.SetupException: Could not find directory or directory was empty for includeAll 'db/1.0.0/'
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:528)
```

The resources under this given folder are just not found.

If I define the includes per file, it´s working fine:

How can we define the includeAll tags with the new Liquibase 4.0.0 version?

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-714) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.3.2,Liquibase 4.3.2

### LINKED ISSUE #1595: since refacoring of ClassLoaderResourceAccessor in 4..0.0-beta2, searchPath "classpath*:" is not handled anymore correctly
## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: spring-boot 2.3.7.RELEASE

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: Postgres (but doesn't matter)

**Operating System Type & Version**: Linux mint (but doesn't matter)

## Description
includeAll in a spring-boot project with a searchPath containing a "classpath*:" doesn't find anything.

## Steps To Reproduce
Define an "includeAll" task in a spring boot project with a searchPath set to "classpath*:db/changelog" and changelog files available on the searchPath failed because not found
`

* includeAll:
        path: classpath*:db/changelog
`

## Actual Behavior
Doesn't find changelogs

## Expected/Desired Behavior
Should find changelog to include

## Screenshots (if appropriate)
* 

## Additional Context
Problem comes from SpringResourceAccessor.finalizeSearchPath method which expect to always have "classpath:classpath:" and in that case, path is "classpath:classpath*:" so not replaced.

https://github.com/liquibase/liquibase/blob/aae1f015540f2a814b7a9e3d7b4db2fa465e9a23/liquibase-core/src/main/java/liquibase/integration/spring/SpringResourceAccessor.java#L157

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1060) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.3.2

### LINKED ISSUE #1657: Relative Path error when using the includeAll tag and Springboot
## Environment
**Liquibase Version**: v4.1.1 and v4.2.2 (it was working in 4.0.0 and 4.1.0)

**Liquibase Integration & Version**: SpringBoot 2.3.1

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**:  MariaDB

**Operating System Type & Version**:  Windows

## Description
Use of the includeAll tag results in "error parsing classpath".  The same configuration works with LB v4.0.0 and v4.1.0.

## Steps To Reproduce
Use these changelogs:

[db.changelog-1.0.0.yaml.txt](https://github.com/liquibase/liquibase/files/5881979/db.changelog-1.0.0.yaml.txt)
[db.changelog-master.yaml.txt](https://github.com/liquibase/liquibase/files/5881980/db.changelog-master.yaml.txt)
[db.changelog-0.0.0.yaml.txt](https://github.com/liquibase/liquibase/files/5881981/db.changelog-0.0.0.yaml.txt)

## Actual Behavior
The "liquibase update" command errors.

`Caused by: liquibase.exception.ChangeLogParseException: Error parsing classpath:/db/changelog/db.changelog-master.yaml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:88) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:337) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:229) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:160) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Scope.child(Scope.java:169) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Scope.child(Scope.java:159) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Scope.child(Scope.java:138) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2277) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:215) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:201) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:321) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:269) ~[liquibase-core-4.2.2.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	... 24 common frames omitted
Caused by: liquibase.exception.SetupException: Error parsing /db/changelog/db.changelog-0.0.0.yaml
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:373) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:320) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:82) ~[liquibase-core-4.2.2.jar:na]
	... 37 common frames omitted
Caused by: liquibase.exception.ChangeLogParseException: Error parsing /db/changelog/db.changelog-0.0.0.yaml
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:88) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:586) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:365) ~[liquibase-core-4.2.2.jar:na]
	... 39 common frames omitted
Caused by: liquibase.exception.SetupException: The file file:/C:/dev/repos/pas-audit-groups/target/classes/db/changelog/changes/v0/0300-createTable-Appointment.xml was not found in
...
Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.
	at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:547) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:414) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:320) ~[liquibase-core-4.2.2.jar:na]
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:82) ~[liquibase-core-4.2.2.jar:na]
`

## Expected/Desired Behavior
The "liquibase update" command should be successful when using includeAll in the changelogs.

## Additional Context

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1157) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.3.1,Liquibase 4.3.1

### PR DESCRIPTION
**Pull request by nvoxland**
* Support classpath*:
* Correctly find classes in directories and jar files

Fixes #1657 
Fixes #1595

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1173) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by famod** [comment]
I don't think this change will fix #1436 (for Quarkus) since that problem seems to be located somewhere else: https://github.com/liquibase/liquibase/blob/v4.2.2/liquibase-core/src/main/java/liquibase/resource/ClassLoaderResourceAccessor.java#L236

**Review by wwillard7800 — APPROVED** [review]
Looks good

**Comment by famod** [comment]
@wwillard7800 have you seen my comment? WDYT? Thanks!

**Comment by nvoxland** [comment]
@famod you are right. This doesn't address your issue. I hadn't looked closely enough at the error messages when I marked this as fixing yours. I'll comment more on your ticket.

**Pull request merged**
