### PR TITLE
Informix data type generation with Default Value cause

### PR DESCRIPTION
**Pull request by iboyko**
Commit 1d6e13a144940dd233b5852698720dcf465c3d47 ported to branch 3.5.x

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-112) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @iboyko 

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
@iboyko , thanks for adding the test!  I am changing the base to 3.10.x as that is the latest release we are working on, please let me know if this was truly intended for 3.5.x only.

**Comment by ro-rah** [comment]
riskMed, although it has tests, the description is not clear to me, so allowing time to determine.

**Comment by molivasdat** [comment]
Hi @iboyko 
Thank you for this Pull Request.

I’m putting together a core team of developers to help us with community requests. We’ll make Liquibase improvements faster together!

If you are willing to help, please reply to this comment and I’ll let you know the next steps.

Your friendly neighborhood developer advocate,
@molivasdat

**Comment by iboyko** [comment]
Hello @molivasdat,
Thank you for the invitation. Can you tell me more about this opportunity?
Best regards,
@iboyko

**Comment by molivasdat** [comment]
Hi @iboyko .  Please me an email with your email address and I can give you more details.
Mine is molivas@liquibase.com

**Pull request merged**
