### PR TITLE
remove useless check

### PR DESCRIPTION
**Pull request by filipelautert**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by sayaliM0412 — APPROVED** [review]
LGTM !!

**Comment by StevenMassaro** [comment]
This was originally added as a security measure, I think. Why was it removed?

**Comment by filipelautert** [comment]
@sayaliM0412 and I were trying to understand why it would be a security feature and could not find a case where it would prevent a insecure build, as the next check (for safeToBuild label) is the one preventing community pr's from being built. I believe it was ther just to make sure that we never execute any github-action from community?

Or maybe we could revert it but adding another check for the source repo like
```
 if: github.event.pull_request && contains(github.head_ref, 'github-action') && && github.event.pull_request.head.repo.full_name != 'liquibase/liquibase'
```

**Comment by StevenMassaro** [comment]
> @sayaliM0412 and I were trying to understand why it would be a security feature and could not find a case where it would prevent a insecure build, as the next check (for safeToBuild label) is the one preventing community pr's from being built. I believe it was ther just to make sure that we never execute any github-action from community?
> 
> Or maybe we could revert it but adding another check for the source repo like
> 
> ```
>  if: github.event.pull_request && contains(github.head_ref, 'github-action') && && github.event.pull_request.head.repo.full_name != 'liquibase/liquibase'
> ```

I can't find anything in Jira that explains why it was added either. Looks like Andre added it, who no longer works here.

**Pull request merged**
