### PR TITLE
Firebird: fix createIndex missing space around "computed"

### PR DESCRIPTION
**Pull request by Markus-Patt**
This change fixes the case in invalid sql is generated, when an index with an computed value is created.

- - -
name: CreateIndexGeneratorFirebird generates invalid SQL on computed field

about:  #1490 
title: ''
labels: Status:Discovery
assignees: ''

- - -

## Environment
**Liquibase Version:**
4.1.1

**Database Vendor & Version**:
Firebird 2.5
Firebird 3.0

## Pull Request Type

* [x] Bug fix (non-breaking change which fixes an issue.)
* [ ] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
A clear and concise description of the issue being addressed.

* Adding an index on a "computed by" value generates invalid sql

## Steps To Reproduce
```xml
    <changeSet id="1" author="1">
        <createTable tableName="foo">
            <column name="id" type="INT">
                <constraints nullable="false" primaryKey="true" primaryKeyName="PK_foo" />
            </column>
            <column name="bar" type="INT" />
        </createTable>
    </changeSet>

    <changeSet id="2" author="2">
        <createIndex tableName="foo" indexName="idx_bar">
            <column name="bar + 1" computed="true" />
        </createIndex>
    </changeSet>
```

This creates the following sql:

```sql
CREATE INDEX idx_baz ON fooCOMPUTED BY (baz + 1)
```

which misses a space between the table name an the the keyword "computed"

## Fast Track PR Acceptance Checklist:

* [x] Build is successful and all new and existing tests pass
* [x] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

### CODE REVIEW

**Comment by molivasdat** [comment]
Thanks @Markus-Patt for finding the issue and creating a fix for it.

**Comment by Markus-Patt** [comment]
Shame on me, I missed a test.
Fixed now.

**Review by nvoxland — APPROVED** [review]
Code review and test results:

Things to be aware of:
- Changes make sense to me
- Only impacts firebird

Things to worry about:
- Nothing

**Comment by tabbyf00** [comment]
Thanks for your PR submission! We just finished reviewing and merging it into the [4.17.0 release](https://github.com/liquibase/liquibase/releases/tag/v4.17.0) on October 10, 2022. When you get a chance, could you please Star the [Liquibase project](https://github.com/liquibase/liquibase)? The star button is in the upper right corner of the screen.

**Pull request merged**
