### PR TITLE
fix #1106 #CORE-3269 degree sign accepted as text

### LINKED ISSUE #1106: Exception in thread "main" liquibase.util.grammar.TokenMgrError: Lexical error at line 146302, column 163. Encountered: "\u00b0" (176), after : ""
## Environment
**Liquibase Version**:  3.8.6

## Description
As reported in CORE-3269 the ° sign inside sql liquibase formatted file throws the error liquibase.util.grammar.TokenMgrError 

## Steps To Reproduce
Create a changeset with an insert statement like
`insert into table (column) values ('warm temp. 32°')`

## Actual Behavior
Error: TokenMgrError 

## Expected/Desired Behavior
No Errors.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-218) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by matteoturra**
- - -
name: Pull Request
about: Create a report to help us improve
title: ''
labels: Status:Discovery
assignees: ''

- - -

## Environment
**Liquibase Version**: 3.8.6 

**Database Vendor & Version**: Oracle 12

**Operating System Type & Version**: Windows 10

## Pull Request Type

* [ x] Bug fix (non-breaking change which fixes an issue.)
* [ ] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
The sqlformat parser does not accepts certain character from Latin1 Iso extension (like £°) throwing TokenMgrError 
See: https://liquibase.jira.com/browse/CORE-3269

## Steps To Reproduce
Create a changeset with an insert statement like
insert into table (column) values ('warm temp. 32°')

See #1106 

## Fast Track PR Acceptance Checklist:

* [ x] Build is successful and all new and existing tests pass
* [ x] Added Unit Test(s)
* [ ] Added Integration Test(s)
* [ ] Documentation Updated

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @matteoturra ,

Many thanks for your PR submission!

Would you mind filling out the description template for this PR?  We use this to assess the PRs before they enter into internal Engineering.  It looks like these items like description of the issue being fixed, why you updated the files, version of Liquibase, and steps to reproduce would be helpful to.  This is what step 9 details in [our community guide to submitting PRs](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core).

Thanks for creating [unit test](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)!

Again, thanks for all the work you have put in so far.

-Ronak

**Comment by ro-rah** [comment]
Hi @matteoturra ,

Thanks for writing the Unit tests, and I see this should close #1106 as well as closes CORE-3269.  The unit test speaks for itself and the test can be the following insert should not cause a parse error:
`insert into table (column) values ('warm temp. 32°')`

I'll get this into conditioning.

**Comment by ro-rah** [comment]
Reasoned on the Risk low b/c it contains unit tests, and it is currently broken.

**Comment by Aeolun** [comment]
@ro-rah It's been months and it appears this is still an issue. I'm currently unable to deal with fullwidth tilde ～. Is there any chance to get this merged?

**Comment by Aeolun** [comment]
There are actually a lot more ranges that break raw SQL when you are working with the Japanese language.

image

**Comment by ro-rah** [comment]
Hi @Aeolun and @matteoturra, escalating to my colleague @molivasdat for update.

**Comment by nvoxland** [comment]
This change was already made at some point, but I created #2329 for the additional unicode points @Aeolun mentioned

**Comment by kataggart** [comment]
Thank you @nvoxland !

**Pull request closed without merging**
