### PR TITLE
Fix CORE-3455 + CORE-3555 load[Update]Data/column@defaultValue[XXX] was not used

### PR DESCRIPTION
**Pull request by b-gyula**
This ticket addresses several issues related to loadData and loadUpdateData. The Liquibase CORE issues are:

* Fix [CORE-3455](https://liquibase.jira.com/browse/CORE-3455) load[Update]Data Get all column's missing type information from the DB even if columns are declared in the change
* Fix [CORE-3555](https://liquibase.jira.com/browse/CORE-3555) _load[Update]Data/column@defaultValue[XXX]_ was not used. It works for EMPTY cells (Ones with "NULL" are still inserted as NULL)
* Fix: NullPointerException in LoadDataChange if "header" was used for not existing column
* Fix: load[Update]Data@file, load[Update]Data@tableName, column@name not only required, it mustn't be empty to avoid cryptic SQL errors
* XSD changes: column.name, loadData.tableName, loadData.file made required, nonEmptyString
* Fix [CORE-3554](https://liquibase.jira.com/browse/CORE-3554) load[Update]Data treated values differently depending if column type is defined

- - -
##### Based on the linked issues/prs, it does not appear that database platform is a factor in reproing this bug.
1. Create a table named MY_TABLE that has the following columns:

* ID - integer
* NAME - varchar
* CREATION_DATE - timestamp
2. Create a CSV file named mydata.csv containing a few rows of data:
```java
ID,NAME,CREATION_DATE
,,2020-04-20T16:36:27.267747
,,2020-04-21T16:37:27.267747
,,2020-04-22T16:37:27.267747
```

3. Create a changelog with a loadData change:
```java
<changeSet author="Me" id="1::dataForTable" labels="data">
<loadData file="data/mydata.csv" primaryKey="id" tableName="MY_TABLE">
     <column name="created_date" type="timestamp"/>
</loadData>
</changeSet>
```

4. Execute a liquibase update to deploy the data to the table:
```java
liquibase --changeLogFile=myChangelog.xml update
```

## Expected Results
The update is successful.
The table has values for all the columns listed in the CSV, not just the one listed in created_date.

## Actual Results
The update fails.
There is a datatype mismatch trying to insert the timestamp data into the integer id column.

## Steps to Reproduce: "NullPointerException in LoadDataChange if "header" was used for not existing column"

With the existing setup above, change loadData to be:

```
    <changeSet id="2" author="nvoxland">
        <loadData tableName="table1" file="data.csv" relativeToChangelogFile="true">
            <column header="created_date" name="invalid" type="timestamp"/>
        </loadData>
    </changeSet>
```

### Expected results:
update fails with a "column invalid does not exist" type error

### Actual results:
Null pointer exception

**Manual Test Criteria**

* Verify the bug can be reproduced on an older build.
* Do a desk check with the Developer
* Verify the bug cannot be reproduced with the fix build.

**Automated Test Criteria**

* Write a regression test to verify correct mapping of data to columns in a table.
  * Name : Verify loadData writes data to the expected table column
  * Description : Ticket ID

- - -
## Repro Steps to Validate XSD Changes
* Unzip the liquibase.jar
* Navigate to www.liquibase.org\xml\ns\dbchangelog\
* Open the XSD dbchangelog-4-4.xsd and search for loadDataAttributes attributeGroup.
* Search XSD for the tableNameAttribute attributeGroup
* Search XSD for the string <xsd:attributeGroup name="column">.
* Search XSD for xsd:element name "loadData".
* Search XSD for  xsd:element name "loadUpdateData".

**Expected Results**
The loadDataAttribute attribute "file" is required. (use="required")
The loadDataAttribute attribute "file" type is "nonEmptyString."
The tableNameAttribute attribute "tableName" type is required.
The tableNameAttribute attribute "tableName" type is "nonEmptyString."
The column attributeGroup attribute "name" is required. 

No automated tests for XSD validations.

## Repo Steps for CORE-3555

Using the above table, create a changeset like:
```
        <loadData tableName="table1" file="data.csv" relativeToChangelogFile="true">
            <column name="name" type="string" defaultValue="my default"/>
        </loadData>
```

in your data.csv file, have a row with an empty name field
```
id,Name,created_date
1,a,2020-01-03T3:15:00
2,,2022-02-04T3:18:33
```

### Expected results:
Running update will insert "my default" for row 2

### Actual results:
Running update inserts null for row 2

## Repo: load[Update]Data treats values differently depending column type is defined

Using the above table, create a changeset like:
```
        <loadData tableName="table1" file="data.csv" relativeToChangelogFile="true">
            <column name="name" type="string"/>
        </loadData>
```

in your data.csv file, have a row with an empty name field and spaces around a name field.
```
id,Name,created_date
1, a ,2020-01-03T3:15:00
2,,2022-02-04T3:18:33
```

Expected:
Running `liquibase update` will insert ' a ' WITH spaces for row 1 and null for row 2 if you have type="string" OR if you have type="varchar(50)" OR if you remove the type attribute completely.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-30) by [Unito](https://www.unito.io)
┆Fix Versions: Community 4.4.0,Liquibase 4.4.0

### CODE REVIEW

**Comment by ro-rah** [comment]
Hey @b-gyula ,

Thanks for this PR, working on getting it into conditioning.  As always, thanks for adding [tests](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests).

-Ronak

**Comment by ro-rah** [comment]
Assessed Risk Low for including unit test and this is one of a few PRs by @b-gyula (thanks again!).  -Ronak

**Comment by ro-rah** [comment]
Moved to Conditioning, expect this to be merged before end of Q2.

**Comment by nvoxland** [comment]
This PR is using some "default" methods which is not available in the Java 8 we need to support, so will need some changes around that. 

It also makes XSD changes, so they will need to be made as part of a new-release XSD rather than changing the existing xsd

**Comment by molivasdat** [comment]
Hi @b-gyula Since this has xsd changes we will need to move it out to 4.x.  If you want to make the changes, you can do them against 4.1.x branch.

**Comment by nvoxland** [comment]
Updated code to be based off master and made a few minor style tweaks.

**Review by nvoxland — APPROVED** [review]

**Review by suryaaki2 — APPROVED** [review]

**Pull request merged**
