### PR TITLE
CORE-3471 Fixed NPE in LiquibaseUtil when MANIFEST.MF doesn't contain…

### PR DESCRIPTION
**Pull request by maksymgendin**
… Bundle-Version or Build-Time

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-57) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2

### CODE REVIEW

**Comment by DanielFran** [comment]
Should fix also https://liquibase.jira.com/browse/CORE-3468?

**Comment by maksymgendin** [comment]
@DanielFran Yes, it should! Sorry, haven't seen your ticket.

**Comment by DanielFran** [comment]
@maksymgendin It is not mine!

When validating if exists any issue related with this problem https://liquibase.jira.com/projects/CORE/issues/CORE-3472 befoe I open the issue, I found that your PR might fix this https://liquibase.jira.com/browse/CORE-3468...

**Comment by DanielFran** [comment]
@maksymgendin @nvoxland @SteveDonie Maybe you might want to take a look at https://liquibase.jira.com/projects/CORE/issues/CORE-3472 it seems a blocking issue for version 3.8?

**Comment by maksymgendin** [comment]
@nvoxland Please don't forget this one for 3.9.0

**Comment by isaki** [comment]
I also patched this with #919 (I hadn't seen this PR) if they are looking for a quick fix without any dependency changes. Either will do the job.

**Comment by Hronom** [comment]
This bug is a pretty big blocker you know?

**Comment by SteveDonie** [comment]
This will definitely be addressed in 3.8.1

**Comment by ro-rah** [comment]
Hi @maksymgendin ,

Sorry this did not make the cut for the release.  I am going to recommend this goes to Conditioning but would you mind resolving the conflict on this PR?

Thanks,

Ronak

**Comment by ro-rah** [comment]
RiskMedium to give us time to resolve conflicts and target to 3.10.1

**Comment by maksymgendin** [comment]
@ro-rah Thanks for your input. I think this pull request became already obsolete since the bug should have been fixed already on master branch.

**Comment by ro-rah** [comment]
Thanks for the response @maksymgendin !

**Pull request closed without merging**
