### PR TITLE
CORE-2024

### PR DESCRIPTION
**Pull request by ssuehs-shango**
Remove embedded Jetty from Liquibase core.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-81) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @ssuehs-shango ,

Sorry for the very long wait.  And...

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
Hi @ssuehs-shango , I am moving the target to 3.10.x since that is the latest release we are working on. Please let me know if this was intended only for 3.3.x releases.

**Comment by ro-rah** [comment]
Thought it would be a risklow since I can't find any mention of jetty in the master branch, but now have a merge conflict.  Will leave it at a riskMed unless @ssuehs-shango would you care to resolve the conflict?

**Comment by nvoxland** [comment]
Jetty was removed in a previous liquibase release. Maybe 3.8ish?

**Pull request closed without merging**
