### PR TITLE
Include "path" in databasechangelog's description column for all change types with "path" attributes

### LINKED ISSUE #3236: Extension of the description in the databasechangelog for sqlFile
## Environment

**Liquibase Version**: 4.15.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: DB2z

**Operating System Type & Version**: Windows 10 Pro

**Infrastructure Type/Provider**: 

## Description

If you include a file containing SQL commands with `<sqlFile path="IUNT500.sql"/>`, then after execution you will find a row with the DESCRIPTION `sqlFile `in the DATABASECHANGELOG table.

This is unfavorable if you use sqlFile frequently, because you do not recognize at once which file was executed.

It would be helpful if the DESCRIPTION would be extended by `path=IUNT500.sql`.

### PR DESCRIPTION
**Pull request by MichaelKern-IVV**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description
Extends the DESCRIPTION column of the DATABASECHANGELOG for sqlFile by the path specification, for example `sqlFile path=IUNT200.sql`

## Additional Context
Fixes #3236

### CODE REVIEW

**Review by nvoxland — APPROVED** [review]
Code review and test results:

Things to be aware of:
- Applies to any changes with "path" at an attribute
- No automated tests, but I don't know an easy way to add one with the current code setup
- Just impacts text-based descriptions of the change (like in databasechangelog table)

Things to worry about:
- Nothing

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
This PR enhances the traceability of changeset deployments in the DATABASEDCHANGELOG table. The filename specified in the `path` attribute of changesets is now written to  DATABASECHANGELOG.DESCRIPTION. 

* Code looks good. Approving and moving to ready to test.

**Comment by XDelphiGrl** [comment]
@filipelautert and @MalloD12, hello -

Can you please add a functional test to validate this change? Let me know when you have a PR in the liquibase-pro-tests repo and I will review it. Thanks!

-erzsebet

**Comment by filipelautert** [comment]
Hi @MalloD12 - can you help with the functional tests here?

**Review by suryaaki2 — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]
A lot of tests added, thanks @MalloD12  !

**Comment by MalloD12** [comment]
@filipelautert @XDelphiGrl:

Guys, I have added few tests to validate this change:

- Validate path is set as part of the description column for "Create Procedure" and "SQLFile" (Unit Test)
- Validate if path is too long it should be truncated to not exceed 255 characters which is the limit of description column (databasechangelog table)
- Validate path is contained in the description column (Integration Test)

To avoid having to make Unit Test a bit more complex I've removed the scenario for "Create View" as somehow this was making some other unit test not related to this change fail on Windows. @FBurguer could you please make sure this is also working on Windows, just in case?

Thanks,
Daniel.

**Review by suryaaki2 — APPROVED** [review]

**Comment by FBurguer** [comment]
For this PR I tested if the if the path was added for `createView` `createProcedure` and `sqlFile` changetypes on windows. All three worked as expected.

**Pull request merged**
