### PR TITLE
Change the case of sys.extended_properties.

### LINKED ISSUE #4096: liquibase 4.20.0 ms sql server case sensitive issue with sys.extended_properties
### Search first

- [X] I searched and no similar issues were found

### Description

Hi there!

Looking at 

liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetTableRemarksGenerator.java

I can see in line 47 that SYS.EXTENDED_PROPERTIES is coded in upper case. MS SQL Server defines its internal schemas and tables in lower case

https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/extended-properties-catalog-views-sys-extended-properties

So when I create a table in liquibase with given remarks on a ms sql server database with case sensitive collation like Latin1_General_CS_AS I get the following error:

liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset my_changelog.xml::1::myuser:
     Reason: liquibase.exception.DatabaseException: Invalid object name 'SYS.EXTENDED_PROPERTIES'. [Failed SQL: (208) IF EXISTS(  SELECT extended_properties.value FROM SYS.EXTENDED_PROPERTIES WHERE major_id = OBJECT_ID('MYSCHEMA.MYTABLE') AND name = N'MS_DESCRIPTION' AND minor_id = 0 ) BEGIN  EXEC sys.sp_updateextendedproperty @name = N'MS_Description' , @value = N'My description' , @level0type = N'SCHEMA' , @level0name = N'MYSCHEMA' , @level1type = N'TABLE' , @level1name = N'MYTABLE' END  ELSE  BEGIN  EXEC sys.sp_addextendedproperty @name = N'MS_Description' , @value = N'My description' , @level0type = N'SCHEMA' , @level0name = N'MYSCHEMA' , @level1type = N'TABLE' , @level1name = N'MYTABLE' END]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:136)

Maybe someone could fix this.

Thank you for providing this library and greetings

steffb74

### Steps To Reproduce

Just create a changeset with createTable and a remarks in it and run it against a ms sql server case sensitive database.

### Expected/Desired Behavior

SYS.EXTENDED_PROPERTIES in liquibase-core/src/main/java/liquibase/sqlgenerator/core/SetTableRemarksGenerator.java should be lower case

### Liquibase Version

4.20.0

### Database Vendor & Version

MS SQL Server

### Liquibase Integration

plain java

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

Windows 10

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by jccampanero**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Change the case of `sys.extended_properties` according to [its actual definition](https://learn.microsoft.com/en-us/sql/relational-databases/system-catalog-views/extended-properties-catalog-views-sys-extended-properties).

It avoids errors when dealing with SQL Server databases with case sensitive collation such as `Latin1_General_CS_AS`.

The case of `sys.columns` had been changed as well and for the same reason.

Fixes #4096.

## Additional Context

Due to the nature of the problem, the PR does not provide any unit tests.

### CODE REVIEW

**Comment by nvoxland** [comment]
Initial review:

Change is what I'd expect. Thanks!

Things to be aware of:
- Nothing

Things to worry about:
- Nothing

**Comment by jccampanero** [comment]
Thank you very much @nvoxland , I am happy to hear that.

**Comment by filipelautert** [comment]
Hello @jccampanero ! We changed the project structure , so could you please help to resolve the merge conflicts? It must be straight forward in you IDE.

**Review by filipelautert — APPROVED** [review]
Fixes case sensitive name of mssql internal tables. Thanks @jccampanero !

**Comment by jccampanero** [comment]
You are welcome @filipelautert.

Yes, of course, I integrated the latest changes from `master` into the PR source branch.

Please, don't hesitate to contact me again if necessary.

**Comment by filipelautert** [comment]
Thanks @jccampanero !

**Review by suryaaki2 — APPROVED** [review]

**Comment by XDelphiGrl** [comment]
SQL Server functional tests started here: [https://github.com/liquibase/liquibase-pro-tests/actions/runs/4853058824](https://github.com/liquibase/liquibase-pro-tests/actions/runs/4853058824)

**Review by XDelphiGrl — APPROVED** [review]
SQL Server is case insensitive by default but collation can be configured to enforce case sensitivity. Prior to this PR, Liquibase was incorrectly using UPPERCASE literal `SYS.EXTENDED_PROPERTIES` and `SYS.COLUMNS` in queries to set table and column remarks. This resulted in failures on SQL Server instances with case sensitive collation because `SYS` != `sys`. PR uses the SQL Server lowercase convention to query for table and column remarks.
* SQL Server full functional regressions passing [https://github.com/liquibase/liquibase-pro-tests/actions/runs/4853058824](https://github.com/liquibase/liquibase-pro-tests/actions/runs/4853058824)
* A PR is opened on test harness to fix the expected results for querying for table and column remarks to expect lowercase instead of uppercase names. [https://github.com/liquibase/liquibase-test-harness/pull/541](https://github.com/liquibase/liquibase-test-harness/pull/541)
* Test harness execution using PR is passing. [https://github.com/liquibase/liquibase-test-harness/actions/runs/4854100607](https://github.com/liquibase/liquibase-test-harness/actions/runs/4854100607)
* No additional testing required.

APPROVED

**Comment by jccampanero** [comment]
Thank you very much for merging this work.

**Comment by XDelphiGrl** [comment]
Thank you very much, @jccampanero for providing a PR!

**Comment by jccampanero** [comment]
> Thank you very much, @jccampanero for providing a PR!

You are welcome @XDelphiGrl. Thank you for integrating my work.

**Comment by nvoxland** [comment]
@jccampanero I'd be interested in hearing a bit more on what got you interested in helping with Liquibase, and what was easy and what was hard with your first contributions. If you'd be interested in talking a bit, email me at `nathan@liquibase.org`

**Comment by jccampanero** [comment]
Yes, of course, thank you very much for giving me the opportunity to email you @nvoxland: I sent you an email.

**Pull request merged**
