### PR TITLE
Added identification of charset to read sql file

### PR DESCRIPTION
**Pull request by tharsissantana**

### CODE REVIEW

**Comment by tharsissantana** [comment]
Sorry for my English.

In my project it was necessary to set the endDelimiter for the rollback and can read sql file with ANSI encoding.

So it was added a jar to identify charset of the file at the time of reading and so treat properly.

**Comment by nvoxland** [comment]
I'd rather not add the dependency on any23 and tika, I'll have to look at how difficult it would be to implement on it's own.

**Comment by ro-rah** [comment]
Hi @tharsissantana ,

Would you consider resolving branch conflicts and adding tests for this PR?  Here's some guidance on that below:

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by filipelautert** [comment]
Hello! It has been a long time since this has been proposed and Liquibase tried different ways of handling file encodings in the meantime. So the way to specify a file encoding is using "--file-encoding" parameter, and changing that could cause issues with checksums . 
Anyway thanks for the PR @tharsissantana ! If you have any concerns or other ideas please feel free to reopen it.

**Pull request closed without merging**
