### PR TITLE
Update MySQL boolean behaviour from TinyInt(1) to TinyInt

### LINKED ISSUE #5069: MYSQL - Update TinyInt(1) boolean behavior to TinyInt
### Search first

- [X] I searched and no similar issues were found

### Description

We have recently merged #4090 which changed boolean behavior from `BIT` to `TINYINT(1)`, but someone from the community just shared with us there is a chance on this, and now boolean in MySQL should be just `TINYINT` (without any parameter), see this [comment](https://github.com/liquibase/liquibase/pull/4090#issuecomment-1764858220).

### Steps To Reproduce

N/A

### Expected/Desired Behavior

Update BooleanType and tests (including test-harness)

### Liquibase Version

_No response_

### Database Vendor & Version

_No response_

### Liquibase Integration

_No response_

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by MalloD12**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description
Starting from 8.0.17, MySQL shows a warning (`"Integer display width is deprecated and will be removed in a future release"`) when directly using tinyint(1), instead of tinyint. So, here we are updating **BooleanType** class to address this change.

Fixes #5069 

## Things to be aware of
- None

## Things to worry about
- None

### CODE REVIEW

**Review by filipelautert — APPROVED** [review]

**Comment by rberezen** [comment]
Possibly there could be some test harness failures (I searched through code, I guess should be fine), but we can't check until we merge, since test-harness execution is broken currently.

**Review by rberezen — APPROVED** [review]

**Comment by MalloD12** [comment]
> Possibly there could be some test harness failures (I searched through code, I guess should be fine), but we can't check until we merge, since test-harness execution is broken currently.

Yeap, test harness will fail but I have created this [PR](https://github.com/liquibase/liquibase-test-harness/pull/641) for that which I'll ask interop team to merge it when have this one merged.

**Comment by rberezen** [comment]
> > Possibly there could be some test harness failures (I searched through code, I guess should be fine), but we can't check until we merge, since test-harness execution is broken currently.
> 
> Yeap, test harness will fail but I have created this [PR](https://github.com/liquibase/liquibase-test-harness/pull/641) for that which I'll ask interop team to merge it when have this one merged.

oh,nice! I have not found anything related to TinyInt(1) cause I have an old repo state...Thanks Daniel!

**Comment by PetterIsberg** [comment]
I know this is already merged so I should probably create a proper issue for it, but the mysql jdbc driver can convert between TINYINT(1) and BOOLEAN automatically. This is because boolean is an alias for tinyint(1) in mysql.
Creating a column with type boolean in mysql server will create it as tinyint(1) without any warnings.
This PR will probably break the auto-conversion functionality, as columns created in Liquibase as booleans will no longer be tinyint(1) and thus not identified as booleans by the jdbc connector.
Hope my explanation makes sense.
"BOOL, BOOLEAN These types are synonyms for TINYINT(1)" [ https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html ]
if tinyInt1isBit=true return boolean : [ https://dev.mysql.com/doc/connector-j/en/connector-j-reference-type-conversions.html ]

**Pull request merged**
