### PR TITLE
Refactored DatabaseChangeLog table creation, update, query

### PR DESCRIPTION
**Pull request by Moszee**
In order to create extension that needs to modify changelog table structure we decided to refactor logic that creates this table. It should easier to modify the table. We are open to suggestions how to make this code better.

Base behaviour shouldn't be changed.

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @Moszee 

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
@Moszee would you be willing to resolve the conflicts?

**Comment by ro-rah** [comment]
added RiskHigh tag really to denote additional effort for conflict resolution and possible test time.

**Comment by Moszee** [comment]
I'll try to merge these conflicts, as soon as i'll get spare time. Hopefully this month :)

Best regards

**Comment by ro-rah** [comment]
@Moszee , thanks for the quick reply!  Good luck!

**Comment by filipelautert** [comment]
Hi - please reopen the PR and fix the conflicts if you still willing to get this refactoring included. Thanks!

**Pull request closed without merging**
