### PR TITLE
Fix addAutoIncrement startValue and incrementBy support on postgresql

### PR DESCRIPTION
**Pull request by nvoxland**
## Description

This handles two issues related to the addAutoIncrement tag

#### Postgresql not respecting startValue and incrementBy

1. The startValue and incrementBy 

A changelog like:

```
    <changeSet id="1" author="example">
        <createTable tableName="test_table">
            <column name="id" type="int"/>
        </createTable>
    </changeSet>

    <changeSet id="2" author="example">
        <addAutoIncrement  tableName="test_table" columnName="id" incrementBy="2" startWith="10"/>
    </changeSet>
```

doesn't include the incrementBy or startWith attributes when creating the sequence in postgresql. 

#### 4.0+ XSDs doesn't allow defaultOnNull or generationType on addAutoIncrement

These attributes were added in 3.6 for oracle, but not really added to the XSD. They happened to work because there was a problem in the XSD that allowed any attribute in addAutoIncrement, and when we fixed that in 4.0 these attributes stopped working.

This PR adds the two attributes back so they can be used again. 

NOTE: It does NOT change the behavior where they are **ignored** for databases other than oracle, rather than throwing a validation exception. We ignore the behavior since it's oracle-specific functionality and so to preserve cross-database compatibility we don't fail the changelog validation.

Test Harness test: liquibase/liquibase-test-harness#213

### CODE REVIEW

**Comment by nvoxland** [comment]
Code review and test results:

Things to be aware of
- The incrementBy/startWith change just passes the values along to the existing code which uses them
- The defaultOnNull/generationType change just allows the XSD to not fail validation, there was no change to the logic in how they are used

Things to worry about
- Without our test patterns in place yet for "does Change X work against database Y" and "how to test XML->Change" parsing, I couldn't add automated tests for it. The changes are straightforward so fairly safe, so not worth blocking this PR until we can get the larger testing effort further along.

**Comment by kataggart** [comment]
@nvoxland this is in ready to merge, but no reviewers requested. Can you please add whomever should review? Thanks!

**Review by suryaaki2 — APPROVED** [review]

**Comment by nvoxland** [comment]
Not sure why it was in ready to merge. It should be ready for test now, though.

**Comment by XDelphiGrl** [comment]
Note: This fix changes the XSD.

**Comment by XDelphiGrl** [comment]
@nvoxland, I'm moving this one back to development as the test-harness PR is not approved (changes requested). 

CC @KushnirykOleh

**Comment by nvoxland** [comment]
@KushnirykOleh fixed up the test harness tests

**Review by XDelphiGrl — APPROVED** [review]
* Fix adds support for two additional attributes on sequences.
  *  Impacts Postgres, EDB Postgres and CockroachDB.
* Test harness extended to validate START WITH and INCREMENT BY for Postgres and EDB.
* Net-new test CockroachDB harness cases added for all sequence-related Liquibase changeTypes.
* No further testing necessary.

APPROVED

[Test Harness Results](https://github.com/liquibase/liquibase-test-harness/pull/213/checks)
[Functional Test Results](https://github.com/liquibase/liquibase-pro-tests/actions/runs/2350113481)

**Pull request merged**
