### PR TITLE
Support MaxDB for sequences

### PR DESCRIPTION
**Pull request by wuttke**
MaxDB Liquibase Diff does not work for sequences as this database (liquibase-maxdb repo) is not included in the SequenceSnapshotGenerator.
(Query should be moved to the Database successor, anyways...)
(I also backported this to the 3.5.x branch.)

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-41) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by wuttke** [comment]
There is also problems here:
* JdbcDatabaseSnapshot
* UniqueConstraintSnapshotGenerator

**Comment by wuttke** [comment]
Could this PR be merged?

**Comment by nvoxland** [comment]
Thanks! We're catching up on a set of fixes already in master, then will get this merged in.

**Comment by ro-rah** [comment]
Placing Risk Low flag, I can see @nvoxland has approved these changes.

**Pull request merged**
