### PR TITLE
Fix missing catalog on add column rollback

### PR DESCRIPTION
**Pull request by jandurovec**
When rollback script for "add column" change is generated, catalog name is missing from generated SQL. As a result of that the rollback may not work if the affected table is not in the default catalog.

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @jandurovec 

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest 
changes, additional tests, or provide other feedback. The PR will be prioritized 
according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
Adding Risk low as it fixes a break and includes [unit tests](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)

**Review by nvoxland — APPROVED** [review]
Code review and test results:

Things to be aware of:
- Changes make sense to me
- Added unit test to ensure data is being copied correctly

Things to worry about:
- Nothing

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
This fix preserves the catalog name when generating drop column SQL. 
* A new unit test validates the catalog, schema and table name are all included in a drop column statement. 

APPROVED

**Comment by tabbyf00** [comment]
Thanks for your PR submission! We just finished reviewing and merging it into the [4.17.0 release](https://github.com/liquibase/liquibase/releases/tag/v4.17.0) on October 10, 2022. When you get a chance, could you please Star the [Liquibase project](https://github.com/liquibase/liquibase)? The star button is in the upper right corner of the screen.

**Pull request merged**
