### PR TITLE
DAT-12842

### PR DESCRIPTION
**Pull request by sayaliM0412**
## Impact
https://datical.atlassian.net/browse/DAT-12842 
Automate deployment of XSDs to new beta landing site

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## User Impact

No user impact

## Technical choices made
Removing the previous code changes as we do not need to split the version by `.` as `aws s3 sync syncs directories and S3 prefixes`

### CODE REVIEW

**Comment by jnewton03** [comment]
@sayaliM0412 do we no longer need the logic for `major.minor` ?  If we release a `4.19.2` is the deploy_xsd job going to fail because there is no XSD that ends in `4.19.2` ?

**Comment by sayaliM0412** [comment]
> @sayaliM0412 do we no longer need the logic for `major.minor` ? If we release a `4.19.2` is the deploy_xsd job going to fail because there is no XSD that ends in `4.19.2` ?

we are directly syncing the `xsd` from the `source` to a `destination` now. And as those source only have `xsd` , we are good.

**Review by jnewton03 — APPROVED** [review]

**Comment by sayaliM0412** [comment]
> > > @sayaliM0412 do we no longer need the logic for `major.minor` ? If we release a `4.19.2` is the deploy_xsd job going to fail because there is no XSD that ends in `4.19.2` ?
> > 
> > 
> > we are directly syncing the `xsd` from the `source` to a `destination` now. And as those source only have `xsd` , we are good. The `xsd` for eg: https://github.com/liquibase/liquibase-pro/tree/master/pro/src/main/resources/www.liquibase.org/xml/ns/pro does not include a new `4.19.2` xsd.
> 
> I didn't even catch that change. Nicely done! LGTM! Lets have QA test and then we can merge 🚀

The `release-published` will still go through all the steps ie `deploy_maven` `deploy_javadocs`,etc. I tested it with those commented out and both uploads were successful.

**Comment by sayaliM0412** [comment]
Closing this PR as duplicate PR : https://github.com/liquibase/liquibase/pull/3909/files.

**Pull request closed without merging**
