### PR TITLE
Included SQL to return unique constraints for Sybase.

### PR DESCRIPTION
**Pull request by crenan**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

- Adjusted return SQL for Sybase unique constraints used in snapshot.
- Formated [SybaseDatabaseTest.groovy](https://github.com/liquibase/liquibase/compare/master...crenan:liquibase:patch-1?expand=1#diff-a80ad968c122d9182db50ea7a646bb0e7634bc9ad44f864a7564c3abd8e1eb5d)
- Included [SybaseDatabaseTest.java](https://github.com/liquibase/liquibase/compare/master...crenan:liquibase:patch-1?expand=1#diff-b4402f783a4fb313f21915780a3df6b693ca0beedad22257b61b009ac079c3cb) for basic tests over SybaseDatabase class.

## Things to be aware of

- Followed the documentation on [SAP Infocenter](https://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc36274.1570/html/tables/tables6.htm) (version 16.0 but works for all versions of SAP Sybase ASE).

## Things to worry about

- I didn't found tests nor did I created new ones to cover this change.

## Additional Context

- I found the TODO when I tried to use db-doc command in CLI Liquibase.
- The new URL prefix is for use with jconn4.jar (JDBC driver provided by SAP for Sybase ASE).

### CODE REVIEW

**Review by MalloD12 — APPROVED** [review]
Approved.

# Review and testing results:

Overall this changes looks ok to me:

- Made a bit of refactoring by moving JUnit tests to groovy format 
- Removed JUnit tests class
- Build and test run successfully

### Things to be aware of:
- Nothing else more than what has been described in this PR.

### Things to worry about:
- Nothing else more than what has been described in this PR.

**Comment by MalloD12** [comment]
Hi @crenan, 

First, I would like to thank you for the changes you have added, as I mentioned in my previous comment they look good. There is a minor thing I would like to ask you if you can also do for us which is renaming the branch name. Some of the checks in our repo trigger some tests from some other projects, and due to the way, our logic looks for a branch name (which does not include the fork name) it can lead to ambiguity if the branch name already exists. Here are useful [guidelines](https://deepsource.io/blog/git-branch-naming-conventions/) that could be useful for this. 

Thanks in advance,
Daniel.

**Comment by crenan** [comment]
> Hi @crenan,
> 
> First, I would like to thank you for the changes you have added, as I mentioned in my previous comment they look good. There is a minor thing I would like to ask you if you can also do for us which is renaming the branch name. Some of the checks in our repo trigger some tests from some other projects, and due to the way, our logic looks for a branch name (which does not include the fork name) it can lead to ambiguity if the branch name already exists. Here are useful [guidelines](https://deepsource.io/blog/git-branch-naming-conventions/) that could be useful for this.
> 
> Thanks in advance, Daniel.

Done.
New PR @ https://github.com/liquibase/liquibase/pull/3517

**Comment by MalloD12** [comment]
> > Hi @crenan,
> > First, I would like to thank you for the changes you have added, as I mentioned in my previous comment they look good. There is a minor thing I would like to ask you if you can also do for us which is renaming the branch name. Some of the checks in our repo trigger some tests from some other projects, and due to the way, our logic looks for a branch name (which does not include the fork name) it can lead to ambiguity if the branch name already exists. Here are useful [guidelines](https://deepsource.io/blog/git-branch-naming-conventions/) that could be useful for this.
> > Thanks in advance, Daniel.
> 
> Done. New PR @ #3517

Thank you!

**Pull request closed without merging**
