### PR TITLE
Add ConfiguredValueModifier extension point for plugins

### PR DESCRIPTION
**Pull request by mcred**
## Environment: All OS

**Liquibase Version**: 4.6.1 + 

**Liquibase Integration & Version**: CLI

## Pull Request Type

- [ ] Bug fix (non-breaking change which fixes an issue.)
- [X] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Extensions should be able to modify the value of a property directly based on a loaded priority. Example: the value for a url in the properties file could be a placeholder and the extension should replace that value during runtime. 

## Testing
I was not able to get all of the unit tests to pass prior to developing this plugin, but the additional tests for ConfiguredValueTest pass and the existing tests for that class continue to pass. 

Screen Shot 2021-12-03 at 2 08 52 PM

## Fast Track PR Acceptance Checklist:

- [ ] Build is successful and all new and existing tests pass
- [X] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
- [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
- [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
- [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

### CODE REVIEW

**Comment by andre15silva** [comment]
Hi, we are researchers in software engineering, working on a novel GitHub bot for helping understand build failures.

We have run our prototype bot [flacocobot](https://github.com/SpoonLabs/flacoco) on this failing PR and below are the results.

What do you think?

Thanks a lot! --Davide (@dginelli), André (@andre15silva), Matias (@martinezmatias), Benjamin (@danglotb), Martin (@monperrus)

**********************************

The line (92) of the file liquibase-core/src/test/groovy/liquibase/configuration/ConfiguredValueTest.groovy has been identified with a suspiciousness value of 14.66%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.integration.commandline.MainTest#testLocalProperties`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.parser.core.xml.XMLChangeLogSAXParserTest#testIgnoreDuplicateChangeSets`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>

**********************************

The line (20) of the file liquibase-core/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java has been identified with a suspiciousness value of 14.43%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.integration.commandline.MainTest#testLocalProperties`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.parser.core.xml.XMLChangeLogSAXParserTest#testIgnoreDuplicateChangeSets`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>

**********************************

The line (21) of the file liquibase-core/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java has been identified with a suspiciousness value of 14.43%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.integration.commandline.MainTest#testLocalProperties`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.parser.core.xml.XMLChangeLogSAXParserTest#testIgnoreDuplicateChangeSets`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>

**********************************

The line (22) of the file liquibase-core/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java has been identified with a suspiciousness value of 14.43%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.integration.commandline.MainTest#testLocalProperties`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.parser.core.xml.XMLChangeLogSAXParserTest#testIgnoreDuplicateChangeSets`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>

**********************************

The line (23) of the file liquibase-core/src/main/java/liquibase/configuration/ConfiguredValueModifierFactory.java has been identified with a suspiciousness value of 14.43%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.integration.commandline.MainTest#testLocalProperties`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.parser.core.xml.XMLChangeLogSAXParserTest#testIgnoreDuplicateChangeSets`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>

**********************************

**Review by nvoxland — APPROVED** [review]
I made some changes to your original PR:
- I moved the logic of applying the modifier into LiquibiseConfiguration which is the more "root" spot. That should make it be applied everywhere better
- I renamed ConfiguredValueModifier's getPriority() method to getOrder() since it's not really the "replacing" logic we use for plugins but an "order" like in CommandStep. Related to that, I made the factory not implement PluginFactory since it's not using the normal plugin replacement logic.
- I made ConfiguredValueModifier's logic be based around being another "override" spot vs. replacing values. I think that will work better with the tracking and logic we have around "nested" values.

**Comment by nvoxland** [comment]
The failing functional tests are unrelated to this change

**Review by XDelphiGrl — APPROVED** [review]
PR allows Liquibase extensions to modify configuration values based on a ordering (or priority) set by the extension. 
* Code used by extension developers; no impact on Liquibase users beyond those using extensions that take advantage of this enhancement.
* New unit tests added.
* No additional testing required.

APPROVED

[Functional Tests](https://github.com/liquibase/liquibase-pro-tests/runs/6630224880)
[Passing Test Harness Execution](https://github.com/liquibase/liquibase-test-harness/actions/runs/2398167054)
NOTE: Test failures in the functional test suite are due to mismatch in expected console output and actual console output for the checks feature. These are unrelated to the changes in this PR and can be disregarded.

**Review by suryaaki2 — APPROVED** [review]

**Pull request merged**
