### PR TITLE
Load XSD files under OSGI

### PR DESCRIPTION
**Pull request by ponziani**
PR for https://github.com/liquibase/liquibase/issues/2817

### CODE REVIEW

**Review by nvoxland — CHANGES_REQUESTED** [review]
Thanks for the PR! Sorry for the delay looking at it. 

The main thing you're doing is searching in the getClass.getClassLoader() vs. Thread.currentContextLoader right?

It's probably better to have that expanded classpath in what's returned by getSearchClassloader() so it can be better controlled by subclasses, since that method is the "first check the classloader" part of the logic.

Could you update that method to return a ClassLoader that combines the two?

**Comment by ponziani** [comment]
Any suggestions on how to do that ? 

I was looking for a CompositeClassloader, but although it's mentioned in your changelog.txt https://github.com/liquibase/liquibase/pull/927, it's not there in the codebase. Any history on that ?

**Comment by nvoxland** [comment]
I was hoping there was something in the general java APIs to have a composite classloader, but didn't see one. I pushed a commit to your fork with what I was generally thinking. Does that make sense? Does that still work with OSGi better?

**Comment by ponziani** [comment]
Hi Nathan, I haven't tried it, but I assume it will work with OSGi.

Fyi, Drools has an implementation of this idea as well : https://github.com/kiegroup/drools/blob/c07f0d800ae7441fcb5b6fe7055088315569e2ae/kie-internal/src/main/java/org/kie/internal/utils/CompositeClassLoader.java

**Comment by ponziani** [comment]
Hi @nvoxland, @filipelautert,

I believe an even better solution might be to make OSGiResourceAccessor a CompositeResourceAccessor

as suggested in https://github.com/liquibase/liquibase/pull/3597#issuecomment-1364647460

Please have a look at that other ticket, which is about the same issue.

**Comment by filipelautert** [comment]
> Hi @nvoxland, @filipelautert,
> 
> I believe an even better solution might be to make OSGiResourceAccessor a CompositeResourceAccessor
> 
> as suggested in [#3597 (comment)](https://github.com/liquibase/liquibase/pull/3597#issuecomment-1364647460)
> 
> Please have a look at that other ticket, which is about the same issue.

Hello @ponziani  - I took a look at #3597 and it seems easy to implement. Can we close this PR and use 3597  as the fix?

**Comment by ponziani** [comment]
@filipelautert , I think you can close this one indeed. But https://github.com/liquibase/liquibase/pull/3597 does not implement the suggested solution. 

https://github.com/liquibase/liquibase/pull/3597 makes the XSD's available for other bundles, which is good, but I feel liquibase-core should be able to access them itself, which can be achieved by making OSGiResourceAccessor a CompositeResourceAccessor imho.

**Comment by filipelautert** [comment]
@ponziani oh , I see. So this one may be more related to PR #2608 ?

**Comment by ponziani** [comment]
Yep. To be able to load the liquibase-core XSD-files, the OSGiResourceAccessor should be a combination of the ClassLoaderResourceAccessor for the calling bundle it is now with a ClassLoaderResourceAccessor for the liquibase-core bundle.

For https://github.com/liquibase/liquibase/pull/2608 the first ClassLoaderResourceAccessor could be extended as suggested in that PR.

**Review by filipelautert — APPROVED** [review]
Changes are fine, it just adds a seond classloader to make sure that resources can be loaded in multiclassloader environments.

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
By default, Liquibase enables SECURE_PARSING to prevent loading potentially malicious remote XSD files. This logic breaks XSD loading in OSGI environments because Liquibase is not able to load its own XSDs from a jar file. This PR addresses that issue by implementing a composite classloader to get resources from multiple loaders.
* Test harness and functional test executions passing.
* No additional testing required.

APPROVED

**Comment by XDelphiGrl** [comment]
@nvoxland, have your concerns been addressed? If so, we can move this to ready to merge.

**Pull request merged**
