### PR TITLE
Improved concurrency support by using ConcurrentHashMaps

### LINKED ISSUE #3788: ConcurrentModificationException when updating multiple schema's in parallel
## Environment

**Liquibase Version**: 4.19.0

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: hibernate

**Database Vendor & Version**: postgresql

**Operating System Type & Version**: various

**Application runtime**: Wildfly 26.1.2

## Description

We're updating multiple schema's in parallel. As soon as two threads attempt to start updating their respective schema, a ConcurrentModificationExecption occurs.

	liquibase.exception.ChangeLogParseException: java.util.ConcurrentModificationException
		at deployment.iridium-util.ear//liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
		at deployment.iridium-util.ear//liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:408)
		at deployment.iridium-util.ear//liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:393)
		at deployment.iridium-util.ear//liquibase.Liquibase.lambda$update$1(Liquibase.java:249)
		at deployment.iridium-util.ear//liquibase.Scope.lambda$child$0(Scope.java:180)
		at deployment.iridium-util.ear//liquibase.Scope.child(Scope.java:189)
		at deployment.iridium-util.ear//liquibase.Scope.child(Scope.java:179)
		at deployment.iridium-util.ear//liquibase.Scope.child(Scope.java:158)
		at deployment.iridium-util.ear//liquibase.Liquibase.runInScope(Liquibase.java:2431)
		at deployment.iridium-util.ear//liquibase.Liquibase.update(Liquibase.java:237)
		at deployment.iridium-util.ear//liquibase.Liquibase.update(Liquibase.java:222)
		at deployment.iridium-util.ear//liquibase.Liquibase.update(Liquibase.java:208)
		at deployment.iridium-util.ear.iridium-data-update.jar//nl.topicus.iridium.update.updater.steps.LiquibaseSchemaUpdateBatchlet.process(LiquibaseSchemaUpdateBatchlet.java:75)
		at org.jberet.jberet-core@1.3.13.Final//org.jberet.runtime.runner.BatchletRunner.run(BatchletRunner.java:76)
		at org.wildfly.extension.batch.jberet@26.1.2.Final//org.wildfly.extension.batch.jberet.deployment.BatchEnvironmentService$WildFlyBatchEnvironment$1.run(BatchEnvironmentService.java:189)
		at org.wildfly.extension.request-controller@18.1.2.Final//org.wildfly.extension.requestcontroller.ControlPointTask.run(ControlPointTask.java:46)
		at org.wildfly.extension.batch.jberet@26.1.2.Final//org.wildfly.extension.batch.jberet.thread.pool.WildFlyJobExecutor$1.run(WildFlyJobExecutor.java:72)
		at org.jberet.jberet-core@1.3.13.Final//org.jberet.spi.JobExecutor$1.run(JobExecutor.java:99)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
		at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
	Caused by: java.util.ConcurrentModificationException
		at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
		at deployment.iridium-util.ear//liquibase.util.ObjectUtil.getMethods(ObjectUtil.java:245)
		at deployment.iridium-util.ear//liquibase.util.ObjectUtil.getReadMethod(ObjectUtil.java:208)
		at deployment.iridium-util.ear//liquibase.util.ObjectUtil.hasReadProperty(ObjectUtil.java:96)
		at deployment.iridium-util.ear//liquibase.util.ObjectUtil.hasProperty(ObjectUtil.java:85)
		at deployment.iridium-util.ear//liquibase.change.ColumnConfig.load(ColumnConfig.java:783)
		at deployment.iridium-util.ear//liquibase.change.AddColumnConfig.load(AddColumnConfig.java:48)
		at deployment.iridium-util.ear//liquibase.change.AbstractChange.load(AbstractChange.java:639)
		at deployment.iridium-util.ear//liquibase.changelog.ChangeSet.toChange(ChangeSet.java:541)
		at deployment.iridium-util.ear//liquibase.changelog.ChangeSet.handleChildNode(ChangeSet.java:464)
		at deployment.iridium-util.ear//liquibase.changelog.ChangeSet.load(ChangeSet.java:388)
		at deployment.iridium-util.ear//liquibase.changelog.DatabaseChangeLog.createChangeSet(DatabaseChangeLog.java:822)
		at deployment.iridium-util.ear//liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:413)
		at deployment.iridium-util.ear//liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:376)
		at deployment.iridium-util.ear//liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
		... 21 more

### PR DESCRIPTION
**Pull request by jurgenkleverwal**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

Fixes #3788

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

The changes make sense to me. I appreciate you fixing more than just the ObjectUtil spot where you were seeing the problem.

Questions I have:
- None

Potential risks:
- None: the objects behave the same in single-threaded apps and just work better in multi-threaded ones. Technically more overhead, but database interactions always greatly overshadow any any java-system level performance differences so I'm not worried about it.

What could make the full review difficult:
- Nothing

**Comment by thomaspkd** [comment]
We ran in the same issue. If I used the "liquibase-core" with this fix integrated from @jurgenkleverwal, the update runs fine in parallel. When will this fix integrated in an official liquibase Version?

**Comment by filipelautert** [comment]
@thomaspkd  we will potentially have it on the next release that may be done still on February.

**Review by XDelphiGrl — APPROVED** [review]
Java `HashMap` prohibits concurrent operations on the same object. By replacing `HashMap` with `ConcurrentHashMaps`, Liquibase correctly handles updating multiple schemas simultaneously. 
* Functional and test harness executions passing.
* No additional testing required.

APPROVED

**Review by filipelautert — APPROVED** [review]

**Comment by Aigul9** [comment]
@jurgenkleverwal @thomaspkd hi, guys! could you please share the approach to run multiple schemas in parallel? I'm searching for the similar solution

**Comment by jurgenkleverwal** [comment]
> @jurgenkleverwal @thomaspkd hi, guys! could you please share the approach to run multiple schemas in parallel? I'm searching for the similar solution

@Aigul9 I use a batching system to run multiple jobs in parallel. Each job creates a Liquibase object for one schema, using the LiquibaseFactory, and calls update on this object. Hope this helps!

**Pull request merged**
