### PR TITLE
update docs URL (DAT-8947)

### PR DESCRIPTION
**Pull request by StevenMassaro**

### CODE REVIEW

**Comment by suryaaki2** [comment]
@StevenMassaro I vaguely remember I found multiple occurrences of www.liquibase.org instead of just one place

**Comment by StevenMassaro** [comment]
> @StevenMassaro I vaguely remember I found multiple occurrences of [www.liquibase.org](http://www.liquibase.org) instead of just one place

I can't find any other places @suryaaki2

**Comment by suryaaki2** [comment]
> > @StevenMassaro I vaguely remember I found multiple occurrences of [www.liquibase.org](http://www.liquibase.org) instead of just one place
> 
> I can't find any other places @suryaaki2

@StevenMassaro  Should we also change the message here? "The command 'rollbackOneUpdateSQL' requires a Liquibase Pro License, available at http://www.liquibase.org/download or sales@liquibase.com"

**Comment by StevenMassaro** [comment]
> > > @StevenMassaro I vaguely remember I found multiple occurrences of [www.liquibase.org](http://www.liquibase.org) instead of just one place
> > 
> > 
> > I can't find any other places @suryaaki2
> 
> @StevenMassaro Should we also change the message here? "The command 'rollbackOneUpdateSQL' requires a Liquibase Pro License, available at http://www.liquibase.org/download or [sales@liquibase.com](mailto:sales@liquibase.com)"

Checking, will get back to you.

**Review by suryaaki2 — APPROVED** [review]

**Pull request merged**
