### PR TITLE
Add support for valueSequenceNext in Snowflake

### LINKED ISSUE #4330: Liquibase ‘valueSequenceNext’ not working with Snowflake
### Search first

- [X] I searched and no similar issues were found

### Description

We are running into an issue with the Liquibase when trying to use the ‘update’ ([update](https://docs.liquibase.com/change-types/update.html)) change type. We need to update an existing database column to get the values from a sequence and the attribute ‘valueSequenceNext’ seems to be an appropriate choice to accomplish this

`changeSet:
id: 1
changes:
  - update:
      tableName: table_name
      columns:
       - column:
            name: column_name
            valueSequenceNext: SEQUENCE_NAME`

The above causes the exception below.

image
it seems like liquibase is looking for the string ‘sequenceNextValueFunction’ definition but it is missing for Snowflake.

`public class SnowflakeDatabase extends AbstractJdbcDatabase {
     
    public SnowflakeDatabase() {
        super.setCurrentDateTimeFunction("current_timestamp::timestamp_ntz");
        super.unmodifiableDataTypes.addAll(Arrays.asList("integer", "bool", "boolean", "int4", "int8", "float4", "float8", "numeric", "bigserial", "serial", "bytea", "timestamptz"));
        super.unquotedObjectsAreUppercased = true;
        super.addReservedWords(this.getDefaultReservedWords());
        super.defaultAutoIncrementStartWith = BigInteger.ONE;
        super.defaultAutoIncrementBy = BigInteger.ONE;
    }`

But other database has it.

`public H2Database() {
    
     super.unquotedObjectsAreUppercased = true;
     super.sequenceNextValueFunction = "NEXTVAL('%s')";   <---
 }`

Any workaround or suggestions to resolve this issue ?

Thanks

-Isao

### Steps To Reproduce

see the description above.

### Expected/Desired Behavior

no exception

### Liquibase Version

latest

### Database Vendor & Version

_No response_

### Liquibase Integration

_No response_

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by jccampanero**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

This small change adds support for obtaining next sequence values in Snowflake.

The use case is relevant for instance when using `valueSequenceNext` when updating a column value as described in #4330.

Fixes #4330

**Test Harness** test coverage for this change has been added as part of this [PR](https://github.com/liquibase/liquibase-test-harness/pull/580). 

## Things to be aware of

Nothing.

## Things to worry about

Nothing.

## Additional Context

N/A.

### CODE REVIEW

**Review by MalloD12 — COMMENTED** [review]
Thank you @jccampanero for submitting another PR. Code changes looks good to me.

Even though test harness tests have been successfully executed, I have requested the Test Harness team to add an extra scenario on their suite to cover this change, I'll wait for that ticket to be done to finally approve this PR.

On the other hand, functional tests are failing but these failures don't seem to be related with this PR.

**Review by MalloD12 — APPROVED** [review]
Test Harness [PR](https://github.com/liquibase/liquibase-test-harness/pull/580) created for adding `valueSequenceNext` test coverage.

**Review by filipelautert — APPROVED** [review]

**Comment by jccampanero** [comment]
> Thank you @jccampanero for submitting another PR. Code changes looks good to me.
> 
> Even though test harness tests have been successfully executed, I have requested the Test Harness team to add an extra scenario on their suite to cover this change, I'll wait for that ticket to be done to finally approve this PR.
> 
> On the other hand, functional tests are failing but these failures don't seem to be related with this PR.

Sorry for the late reply @MalloD12 Daniel. 

You are welcome, and thank you very much.

Yes, of course, I think it makes perfect sense to provide the tests you consider necessary.

**Comment by rberezen** [comment]
This pull adds support for valueSequenceNext in Snowflake.

- Functional and test harness executions passing (there is one harness failure but it's random and not related to this PR)
- New unit test added.
- No additional testing required.

APPROVED

**Review by rberezen — APPROVED** [review]

**Pull request merged**
