### PR TITLE
runAlways should run regardless of checksum validation

### LINKED ISSUE #4125: RunAlways="true" still fails checksum errors
### Search first

- [X] I searched and no similar issues were found

### Description

Currently, if you have just `runAlways="true"` on a changeSet it will always run, **_unless_** you change your changeset. When that happens, it throws a validation error. This is surprising to people, as they think saying `runAlways="true"` means to always run it regardless, and the reason they are often wanting it to always run it always is because they change it frequently.

See https://forum.liquibase.org/t/changelog-parameters-and-checksum-errors/639/6 as an example thread.

Currently it can be worked around by setting both `runAlways="true"` and `runOnChange="true"` but that should not be necessary.

### Steps To Reproduce

Create a changeset:

```   
 <changeSet id="1" author="example" runAlways="true">
        <outputMessage message="Hello World"/>
    </changeSet>
```
and `update` with it twice. It should output the message each time.

Change it to 
```   
 <changeSet id="1" author="example" runAlways="true">
        <outputMessage message="Hello To You"/>
    </changeSet>
```
and run `update` again. It fails with a validation error.

### Expected/Desired Behavior

The updated changeset should still run without validation error

### Liquibase Version

_No response_

### Database Vendor & Version

_No response_

### Liquibase Integration

_No response_

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by jccampanero**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Currently, `runAlways` still fails with checksum related errors when the changeset definition changes.

This can sometimes lead to confusion (please, consider read [this thread](https://forum.liquibase.org/t/changelog-parameters-and-checksum-errors/639/8) in the Liquibase forum, for instance).

The change allows `runAlways` to be executed in any situation, regardless of whether the changeset has been modified or not.

Fixes #4125.

## Things to be aware of

Nothing.

## Things to worry about

Change existing functionallity.

## Additional Context

N/A

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

The "breaking change" checkbox is technically right since it changes behavior, but I'd see it more as a bugfix in general. The people broke by it are people with `runAlways="true"` and are for some reason relying on the fact that it shouldn't re-run if they change the content of the changeset. That seems like something nobody would do? But, it would be good to make sure we call it out a bit in the release notes, so I'm OK with leaving it as that.

Code change looks good, but probably good to add a test case to ValidatingVisitorTest?

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Comment by jccampanero** [comment]
Yes, of course, I will try to create the test case to `ValidatingVisitorTest` @nvoxland.

**Review by filipelautert — COMMENTED** [review]
Hello @jccampanero ! are you working on the test case to ValidatingVisitorTest as you mentioned ? I triggered the build so we can validate if everything else is fine.
Thanks!

**Comment by jccampanero** [comment]
Sorry @filipelautert, no, honestly I forgot it!! I will try implementing it as soon as possible.

Please, sorry again.

**Comment by jccampanero** [comment]
@filipelautert I provided a possible test case for describing the implemented functionality.

Please, don't hesitate to contact me again if necessary.

And again, sorry...

**Review by filipelautert — APPROVED** [review]
Thanks for this fix @jccampanero and for adding tests to it, much appreciated.

**Comment by jccampanero** [comment]
> Thanks for this fix @jccampanero and for adding tests to it, much appreciated.

You are welcome @filipelautert, thank you for your support.

**Comment by XDelphiGrl** [comment]
You're an outstanding collaborator, @jccampanero! Thank you for everything you've done for the Liquibase Community. Please don't worry about apologizing for taking a little time to get back to us or add tests because everything you do is helpful & truly appreciated!

**Review by XDelphiGrl — APPROVED** [review]
Fix addresses a long-standing and confusing behavior that required `runOnChange=true` in order to fully utilize the `runAlways=true` feature. In particular, a changeset with `runAlways=true` would throw checksum validation errors if the changeset was modified; this is unexpected because we've said, "Hey, Liquibase! Always run this guy, no matter if there are changes or not." The workaround was to include `runOnChange=true` to get `runAlways` to behave the way the property name indicates. This fix makes `runAlways=true` independent from the `runOnChange=true` property.
* Excellent new unit test added.
* Functional and test harness executions passing. There were SQL Server test harness failures in earlier builds. They passed on rerun [here](https://github.com/liquibase/liquibase-test-harness/actions/runs/4996296241).
* No additional testing required.

APPROVED

**Comment by jccampanero** [comment]
> You're an outstanding collaborator, @jccampanero! Thank you for everything you've done for the Liquibase Community. Please don't worry about apologizing for taking a little time to get back to us or add tests because everything you do is helpful & truly appreciated!

Thank you very much for your kindness and your words @XDelphiGrl, I appreciate them very much; on the contrary, thank you very much for all your support and for this excellent library, it is a pleasure to be able to contribute to this excellent project.

**Pull request merged**
