### PR TITLE
Move ChangeLogParameters helper methods to ChangeLogParameters class (DAT-17883)

### PR DESCRIPTION
**Pull request by abrackx**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description
Moves both `addJavaProperties` and `addDefaultFileProperties` from the `DatabaseChangelogCommandStep` class to the `ChangeLogParameters` class. These method are useful and should be the standard way to fetch these properties even if our command pipeline isn't explicitly using DatabaseChangelogCommandStep.

### CODE REVIEW

**Comment by MalloD12** [comment]
This looks ok to me. Just one question, would it not be useful to have this two methods in a `CommandStepUtil` class? These two methods seem to be just used in `DatabaseChangelogCommandStep` class, but there is one similar implementation for `addJavaPropertiesToChangelogParameters()` in `LiquibaseCommandLine` (maybe we can use the same implementation there as well).

**Comment by abrackx** [comment]
> This looks ok to me. Just one question, would it not be useful to have this two methods in a `CommandStepUtil` class? 
What about sticking it on the `ChangeLogParameters` class itself? That makes sense to me. I'll have to leave the java props one inside this class since it's public, but can change it to call the new one. 
> there is one similar implementation for `addJavaPropertiesToChangelogParameters()` in `LiquibaseCommandLine` (maybe we can use the same implementation there as well).
That's true! But that one looks slightly different and deals with calling out to the `Main` class. That makes me nervous, idk if I want to mess with that one too. 🤣

**Review by StevenMassaro — APPROVED** [review]

**Comment by StevenMassaro** [comment]
Are there places where this is currently done manually and should be changed to instead use these newly public methods?

**Comment by abrackx** [comment]
@MalloD12 @StevenMassaro I moved these into the `ChangeLogParameters` class because that seemed even better for discoverability.

**Review by MalloD12 — APPROVED** [review]
LGTM

**Review by filipelautert — APPROVED** [review]

**Review by StevenMassaro — APPROVED** [review]

**Pull request merged**
