### PR TITLE
CORE-1127: Filter by context when doing a rollback.

### PR DESCRIPTION
**Pull request by berryh**
[X] BUG

When a changelog file contains two changesets with same author and id but with different contexts, only the first changeset has its rollback block applied when rolling back. Liquibase will always choose the first changeset without taking the context into account. See the issue for an example of this behaviour. This pull request is an option to fix this, by filtering on context before actually doing the rollback.

It adds unit tests to make sure it run correctly.

JIRA Issue: [CORE-1127](https://liquibase.jira.com/browse/CORE-1127)

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @berryh ,  Sorry for the wait.  There appears to be conflicts that need to be resolved, would you mind doing that.

After which I can pull this into Conditioning targeting a 4.0 Beta 2 release.

**Comment by ro-rah** [comment]
@berryh while you are working on the conflict, we could use your help in writing tests, which in turn would help get this PR merged in faster.

Here is the canned response I have been sending out now that our PR process has been jump started, it contains some good guidance on tests:Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by berryh** [comment]
Hi all, sorry for the long silence! Nice to see this PR progressing, if there's still anything you need from me, please let me know!

**Comment by filipelautert** [comment]
Hi @berryh , after ro-rah comment  in 2020 I thought you went MIA.  I merged master to your branch and added some integration tests, if you want to take a look and see if it's all fine for you let me know.

**Review by filipelautert — APPROVED** [review]

**Comment by berryh** [comment]
Fair enough, nice work! I remember seeing the comment and saying that I'd have to take a look at it later, but never got around to it. Nice to see this being picked up!

**Pull request merged**
