### PR TITLE
Adds flow file examples (DAT-11287)

### PR DESCRIPTION
**Pull request by abrackx**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Adds example flow files.

### CODE REVIEW

**Comment by StevenMassaro** [comment]
Why is the flowvariables file only in the xml folder? Shouldn't it be in all of the folders?

**Comment by suryaaki2** [comment]
> Why is the flowvariables file only in the xml folder? Shouldn't it be in all of the folders?

If it is the same file then why it should be in all the folders?

**Comment by abrackx** [comment]
Good question! I was just following the [ticket](https://datical.atlassian.net/browse/DAT-11287), I'll confirm with mario this was intentional.

**Comment by abrackx** [comment]
This was _not_ intentional, all directories should be the same. Good catch yall!

- [ ] Add flowvariables to all directories

**Review by StevenMassaro — APPROVED** [review]

**Pull request merged**
