### PR TITLE
Feature/proxy schema

### PR DESCRIPTION
**Pull request by matej-liptak**
Let's add new feature for OracleDatabase--to let users define target schema to which changes from the changeSet should be applied by adding new attribute "targetSchema" to the changeSet element.

Because of security reasons, DBA admins do not want to grant too much privileges to LQB schema defined in the property file that is used for connecting to database. However, CONNECT THROUGH privilege is acceptable and with this privilege, LQB schema could be used to deploy anything needed to selected business schemas that would have CONNECT THROUGH privilege granted. In such case, LQB schema defined in the property file (the username field) would be used as a proxy schema.

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @matej-liptak!

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest 
changes, additional tests, or provide other feedback. The PR will be prioritized 
according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
Hi @matej-liptak ,

Would you be willing to write [unit test](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests) and/or[ integration tests](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests) for this PR?

That would help us take in this enhancement faster.

Thanks in advance!

Ronak

**Comment by ro-rah** [comment]
Labeled as riskhigh to allow time to fill in tests, analyze and have this go to 3.10.1

**Comment by ro-rah** [comment]
Hi @matej-liptak , we discussed this in the Conditioning meeting internally and have decided that there is more design work needed, will rebase to master so it can eventually make it out into 4.x.

Will update you if we need help on the additional design work.

**Comment by molivasdat** [comment]
Hi @matej-liptak 
Thank you for this Pull Request.

I’m putting together a core team of developers to help us with community requests. We’ll make Liquibase improvements faster together!

If you are willing to help, please reply to this comment and I’ll let you know the next steps.

Your friendly neighborhood developer advocate,
@molivasdat

**Comment by filipelautert** [comment]
Hi - that's an interesting feature. As it quite old and lacks answers I'll close it, but if you still willing to get this work included  please reopen the PR and fix the conflicts . Thanks!

**Pull request closed without merging**
