### PR TITLE
Java 8 improvements

### PR DESCRIPTION
**Pull request by arturobernalg**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [X ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Java 8 improvements:

-  Replace Lambda with method reference
-  Anonymous type can be replaced with method reference
-  Collections.sort() can be replaced with 'List.sort()'
-  Replace Loop with 'Collection.removeIf()'
-  Replace Loop 'List.replaceAll()'

**Please keep in mind that this field is just a matter of taste. Oriented to java 8 functional.**

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Appreciate the switches to lambdas. It's cleaner/shorter code.

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- A lot of changes to double check don't have unexpected differences.

**Review by MalloD12 — APPROVED** [review]
**Approved**

## Review and testing results:

This PR LGTM. Thank you @arturobernalg code looks much more clear with all these java 8 replacements you have performed here. Build and tests successfully executed.

### Things to be aware of:
- None

### Things to worry about:
- None

**Review by XDelphiGrl — APPROVED** [review]
PR continues code modernization to use Java 8 best practices, specifically replacing lambda expressions with method references. For example:

**Lambda as Anonymous Method**
```
            return jvmLocked(id, new Callable<CDILiquibaseConfig>() {
            return jvmLocked(id, () -> createCDILiquibaseConfig(id, is));
                @Override
                public CDILiquibaseConfig call() throws Exception {
                    return createCDILiquibaseConfig(id, is);
                }
            });
```

**Same Code, Using a Method Reference**
```
return jvmLocked(id, () -> createCDILiquibaseConfig(id, is));
```
This results in cleaner, modernized code.

* Functional and test harness executions passing.
* No additional testing required.

APPROVED

**Comment by filipelautert** [comment]
Hello @arturobernalg - I was going to merge it but it has some conflicts now. Could you help to fix it?

**Comment by arturobernalg** [comment]
> Hello @arturobernalg - I was going to merge it but it has some conflicts now. Could you help to fix it?

@filipelautert Done.

**Comment by filipelautert** [comment]
Hey @MalloD12 or @arturobernalg  - can you fix the conflicts here so we can merge this PR? thanks!

**Comment by arturobernalg** [comment]
> Hey @MalloD12 or @arturobernalg - can you fix the conflicts here so we can merge this PR? thanks!

Yep, 
i'll look into today.
TY

**Comment by filipelautert** [comment]
Sorry @arturobernalg - I missed you comment and did the merge myself - Liquibase was a mess because of a lot of refactoring that we implemented lately.

**Pull request merged**
