### PR TITLE
Fixed issue that unique constraint precondition does not honor schemaName attribute on MySQL

### LINKED ISSUE #3977: mssql liquibase 4.20.0 - precondition uniqueConstraintExists fails when the unique constraint exists
- [X] I searched and no similar issues were found

Hello! thank you for this api and for your time.
i have a changeset that creates a unique constraint

        <addUniqueConstraint columnNames="NAME" constraintName="UN_TABLENAME_NAME" deferrable="false"
                             disabled="false" initiallyDeferred="false" tableName="TABLENAME"/>
i have a changeset with a precondition on unique constraint exists that fails even though the unique constraint index was created previously

    <changeSet id="CHANGESETID" author="CHANGESETAUTHOR">
        <preConditions>
            <uniqueConstraintExists tableName="TABLENAME" constraintName="UN_TABLENAME_NAME"/>
        </preConditions>
        <dropUniqueConstraint tableName="TABLENAME" constraintName="UN_TABLENAME_NAME"/>
    </changeSet>

- the application does not start because the precondition uniqueConstraintExists is not met

### Steps To Reproduce

the previous changesets will prevent the application from starting with the following stacktrace

```

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'baseLiquibase' defined in class path resource [...]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset changesetfile::CHANGESETID::CHANGESETAUTHOR:
     Reason: 
          changesetfile : UN_TABLENAME_NAME on TABLENAME() does not exist

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1607)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1571)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1460)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1347)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 101 common frames omitted
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset changesetfile::CHANGESETID::CHANGESETAUTHOR:
     Reason: 
          changesetfile : UN_TABLENAME_NAME on TABLENAME() does not exist

	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:136)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:297)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:295)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Liquibase.runInScope(Liquibase.java:2639)
	at liquibase.Liquibase.update(Liquibase.java:236)
	at liquibase.Liquibase.update(Liquibase.java:221)
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:329)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:284)
	at ....afterPropertiesSet(....java:82)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 115 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset changesetfile::CHANGESETID::CHANGESETAUTHOR:
     Reason: 
          changesetfile : UN_TABLENAME_NAME on TABLENAME() does not exist

	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:631)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:59)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:124)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:124)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:105)
	at liquibase.Scope.lambda$child$0(Scope.java:187)
	at liquibase.Scope.child(Scope.java:196)
	at liquibase.Scope.child(Scope.java:186)
	at liquibase.Scope.child(Scope.java:165)
	at liquibase.Scope.child(Scope.java:256)
	at liquibase.Scope.child(Scope.java:260)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:75)
	... 134 common frames omitted
Caused by: liquibase.exception.PreconditionFailedException: Preconditions Failed
	at liquibase.precondition.core.AndPrecondition.check(AndPrecondition.java:47)
	at liquibase.precondition.core.PreconditionContainer.check(PreconditionContainer.java:213)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:617)
	... 154 common frames omitted


Process finished with exit code 255


```

### Expected/Desired Behavior

we expect that the precondition uniqueConstraintExists is met and the application starts.

### Liquibase Version

4.20.0

### Database Vendor & Version

mssql 19

### Liquibase Integration

spring boot

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

mac m1, mssql 19 docker image

### Additional Context

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by mpvvliet**
Fixes #3977

## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Things to be aware of

Only for MySQL.

### CODE REVIEW

**Comment by mpvvliet** [comment]
Figured out how to use the default schema in a precondition. This fixes all problems in #3977 as far as I can see.

**Comment by MalloD12** [comment]
Hi @mpvvliet,

Thank you for taking the time to create this PR. Code changes look good to me. I have only added a comment to ask you for a little improvement. One other thing I would like to ask you is about tests. I think it would be good if we can an integration test for `mssql`. It would be simply adding a new changeset in this file `src/test/resources/changelogs/mssql/complete/root.changelog.xml`. Something like this:

```
<changeSet id="CHANGESETID" author="CHANGESETAUTHOR">
    <preConditions>
        <uniqueConstraintExists tableName="address" constraintName="uq_address_line1line2"/>
    </preConditions>
    <dropUniqueConstraint tableName="address" constraintName="address"/>
</changeSet>
```

Thanks in advance,
Daniel.

**Comment by mpvvliet** [comment]
@MalloD12 happy to add the test. Any reason it's for `mssql` specifically? 

Also, I see changeset 32 adds the constraint and changeset 33 removes it. Given the changes, it seems to me that we would want to execute the test with the constraint present in the DB and the changeset having a `<not/>` around the precondition. That way, without the code changes, the constraint would not be found, passing the precondition and failing on dropping the constraint, failing the test. With the change, the changeset would not be executed, passing the test.

I'm not too familiar with how these tests work so could be off. :-)

**Comment by MalloD12** [comment]
Hi @mpvvliet,

I said `mssql` just because I saw that was the database specified in #3977, but this is a good point. I think it would be better to be more generic and specify this case in the changelog that will be deployed in any DB. This could be `src/test/resources/changelogs/mssql/complete/root.changelog.xml`. Some integration tests basically deploy a changelog and do specific checks afterward, but in some other cases, we are good enough just knowing a given changelog has been successfully deployed, which means that the given scenarios (changesets) didn't have any issue when they were deployed.

I hope it helps you to have a better (high-level) idea of how these tests work, if not please ask and I'll do my best to give you a better picture of them.

Thanks,
Daniel.

**Comment by mpvvliet** [comment]
@MalloD12 I refactored the code as per your suggestion and added an integration test. The entire test suite passes in my local setup.

**Review by filipelautert — APPROVED** [review]

**Review by rberezen — APPROVED** [review]

**Pull request merged**
