### PR TITLE
Add rollback changeset reference for SQL changelogs

### LINKED ISSUE #1335: changeSetId & changeSetAuthor tags are not getting recognized by liquibase in rollback while using liquibase formatted sql.
## Environment
**Liquibase Version**: 4.0.0

**Liquibase Integration & Version**: 4.0.0

**Liquibase Extension(s) & Version**:  4.0.0

**Database Vendor & Version**: MSSQL 2016

**Operating System Type & Version**: Windows

## Description
changeSetId & changeSetAuthor tags are not getting recognized by liquibase in rollback while using liquibase formatted sql.
But it is working properly if using xml based change set as mentioned in https://docs.liquibase.com/workflows/liquibase-community/using-rollback.html

Following is my **ChangeLog.xml**:- 
`<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
  xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd">
<changeSet author="appuser" id="release_tag_3.20.09">
    <tagDatabase tag="release_tag_3.20.09" />
   </changeSet>
<include relativeToChangelogFile="true" file="1.sql" />
<changeSet author="appuser" id="release_tag_3.20.10">
        <tagDatabase tag="release_tag_3.20.10" />
</changeSet>
<include relativeToChangelogFile="true" file="2.sql" />
</databaseChangeLog>`

**1.sql** :-

--liquibase formatted sql
--changeset dhansal:1_sql
drop table if exists changeRollback
GO
create table changeRollback(id int)
GO
--rollback drop table changeRollback

**2.sql** :-

--liquibase formatted sql
--changeset dhansal:2_sql
alter table changeRollback add id2 int
GO
--rollback changeSetId:1_sql changeSetAuthor:dhansal

And I'm running rollback till tag version "release_tag_3.20.10" then it is giving me syntax error as it is considering "changeSetId:1_sql changeSetAuthor:dhansal" as a sql rather than referencing to previous changeSet.
.

### PR DESCRIPTION
**Pull request by atzawada**
- - -
name: Add rollback changeset reference for SQL changelogs
about: Add rollback changeset reference for SQL changelogs
title: ''
labels: Status:Discovery
assignees: ''

- - -
## Environment
**Liquibase Version**: 

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Pull Request Type
Closes #1335.

* [ ] Bug fix (non-breaking change which fixes an issue.)
* [x] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
Code to introduce referencing another changeset in a rollback statement in a SQL changelog file.

## Current Behavior
Liquibase currently doesn't have any behavior to allow for referencing another changeset in a SQL rollback statement.

## Desired Behavior
The new code would allow for this functionality, using either;

```sql
--rollback changeSetId:create-table-demo changeSetAuthor:atzawada changeSetPath:src/main/resources/testCreate.sql
```

if the changeset being referenced is in a different changelog file, or:

```sql
--rollback changeSetId:create-table-demo changeSetAuthor:atzawada
```

if the changeset is in the same changelog file.

## Fast Track PR Acceptance Checklist:

* [x] Build is successful and all new and existing tests pass
* [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Documentation Updated

### CODE REVIEW

**Comment by molivasdat** [comment]
Thanks @atzawada for creating this enhancement request.
Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest
changes, additional tests, or provide other feedback. The PR will be prioritized
according to our development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

If you have any unit tests or integration tests to add that would be great.

**Comment by awhitford-cip** [comment]
What is the hold up on this PR?  Can I help?  Because [I am interested in this functionality](https://forum.liquibase.org/t/how-to-rollback-changesetid-using-sql-dialect/7081).

**Comment by kataggart** [comment]
@awhitford-cip The hold up is that we are fortunate to have a high volume of community requests and are continually working on how best to address them. Some folks are also right now on much needed vacation, but we will review.

**Comment by atzawada** [comment]
Hi @kataggart, @awhitford-cip, completely understand the difficulty getting to this with the high volume of PRs coming in. Still willing to help get this in if there are changes that need to be made.

**Review by nvoxland — APPROVED** [review]
Code review and test results:

Things to be aware of:
- Change only impacts formatted sql (other formats already had this feature)
- Pattern match is case insensitive like it should be
- I added a unit test and some additional error handling

Things to worry about:
- Nothing

The changes look good, thanks @atzawada !

**Review by suryaaki2 — APPROVED** [review]

**Comment by FBurguer** [comment]
For this PR, I tested if rollback reference works with a changeset on the same changelog and with one in another changeset. Both work just fine. Theres a couple behaviors that called my atention and think is good to share and be aware about: 
-You cant reference  a changeset from a changelog that isnt in the same root changelog as the call.
-Liquibase reads the changelogs in order, so if you have a changeset with a rollback changeset reference on `changelog1.sql` and have the reference changeset on `changelog2.sql`, liquibase will fail with "changeset doesnt exists"

Test Environment:
Java 8
Windows 10
Postgres 13 conatiner

**Comment by kataggart** [comment]
@awhitford-cip @atzawada This is now available in 4.16 that released on Friday.

**Pull request merged**
