### PR TITLE
Updated documentation

### PR DESCRIPTION
**Pull request by b-gyula**
* Added description for 
  * addAutoIncrement / generationType, defaultOnNull, startWith, incrementBy
  * addForeignKeyConstraint / referencedTableCatalogName, referencedTableSchemaName, baseTableSchemaName, baseTableCatalogName
  * addUniqueConstraint, createIndex / clustered
  * alterSequence / sequenceName, cycle
  * createProcedure / procedureName, replaceIfExists, procedureText
  * createTable / remarks + tablespace
  * createView / remarks
  * dropAllForeignKeyConstraints / baseTableSchemaName, baseTableName
  * dropTable / cascadeConstraints
  * load[Update]Date / usePreparedStatements, commentLineStartsWith, separator, quotchar
  * setTableRemarks / remarks
  * setColumnRemarks / remarks
  * sql / sql
  * update + insert / where
* Fields marked required for ALL
  * insert, update / tableName, columns 
  * dropTabe / tableName
  * output / message
  * tagDatabase / tag made
* Minor typo fixes
* Changed examples for `dbms` to be consistent with the samples on the website

_Findings_

* createProcedure / comments defined as `comment` in te XSD so it's never populated -> Removed from documentation (changeSet can have `comment` child)
* sql / comment read, but never used -> Should be removed also (changeSet can have `comment` child)

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-12) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.1.0

### CODE REVIEW

**Comment by mariochampion** [comment]
hey @SteveDonie, i want to add this to the next sprint. Can you do the review @nvoxland?

**Comment by mariochampion** [comment]
hey @SteveDonie -- as we are about to do end-to-end for 3.8.9, i would say we should merge this AFTER that. so that it goes into 3.8.10. 

I think QA and @nvoxland will need to weigh in for final approval.

**Comment by ro-rah** [comment]
Hey @b-gyula !

Looking to move this into conditioning now, as a reminder here's the canned response stuff below:

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest 
changes, additional tests, or provide other feedback. The PR will be prioritized 
according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

Thanks,

Ronak

**Comment by mariochampion** [comment]
hey @ro-rah -- the assessment is that these changes are good, but both because of the changes to the XSD in 4.0 and the overall docs site CMS update, we need to wait for that, or do the changes twice. it is still Active, just waiting for other things to line up.

**Comment by ro-rah** [comment]
Thanks for the transparency @mariochampion !

**Comment by nvoxland** [comment]
All the content changes you had in this should be incorporated into our new docs.liquibase.com site.

We are not going to be relying as much on generated documentation for the time being, so I'm going to go through the code to pull in the general cleanup changes you did but not things that make the doc generation easier/better but doesn't impact anything else. 

I'll also clean out the old content that is now an unused duplicate of what is managed elsewhere.

**Comment by molivasdat** [comment]
Hi @mariochampion @nvoxland @mccormickc.  Did this PR make it over to the new docs site?

**Comment by molivasdat** [comment]
Hi @b-gyula .  Your changes made it over into the new documentation site.
https://docs.liquibase.com/change-types/community/custom-change.html 
and any new updates to the documentation are described here ->
https://github.com/Datical/liquibase-docs

**Pull request closed without merging**
