### PR TITLE
CORE-3222: Added missing slf4j-api dependency to assembly tar/zip

### PR DESCRIPTION
**Pull request by andham**
Signed-off-by: Anders Hammar <anders@hammar.net>

### CODE REVIEW

**Comment by SteveDonie** [comment]
:+1:

**Comment by lucasmorano** [comment]
👍

**Comment by RobertDeRose** [comment]
Why is this just hanging out not being merged? I was about to submit the same thing.  Been broken for two releases now

**Comment by feoktant** [comment]
@RobertDeRose same for my PR :( seems so, Liquibase authors are not interested in open source

**Comment by adriens** [comment]
👏 👍

**Pull request merged**
