### PR TITLE
Support prepared statements for query

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by fbiville** [comment]
As I feared, that change is unfortunately not enough:
```
     Reason: java.lang.IllegalStateException: Cannot find generators for database class liquibase.ext.neo4j.database.Neo4jDatabase, statement: liquibase.ext.neo4j.statement.ParameterizedCypherStatement@38fb50f8
```

**Comment by fbiville** [comment]
This change has been tested end-to-end in https://github.com/liquibase/liquibase-neo4j/pull/195 and it works perfectly!
This would be a SUPER USEFUL addition for the Neo4j plugin.

**Review by nvoxland — APPROVED** [review]

**Comment by nvoxland** [comment]
Code Review and test results:

Things to be aware of
- I worked with @fbiville on the changes. He tested that it works with his use case
- Until I get the liquibase-sdk module split out, the change is in a module that I can't write an integration test for
- It's not code that is used by anything in liquibase-core, but adds a capability usable by extensions (and future liquibase funtionality)

Things to worry about
- Nothing

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
* Change improves handling of parameterized SQL statements.
* Code impacts only extension writers.
* @fbiville and @nvoxland co-ordinated manual testing of the fix in Florent's environment.
  * Thank you for being an amazing Liquibase contributor, @fbiville!

APPROVED

**Pull request merged**
