### PR TITLE
Rawsqlstatement refactoring fixes

### PR DESCRIPTION
**Pull request by MalloD12**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

After [PR](https://github.com/liquibase/liquibase/pull/5812) was merge there were some test failures (on Functional Tests) reported by QA. That is being fixed by this PR, for one of the failures it seems there could be an error on how PRINT statement is executed using PreparedStatement, so for now we have decided to revert these changes and leave the `AbstractSQLChange` class as it was before, that's good enough to fix one the failing tests.

### CODE REVIEW

**Comment by MalloD12** [comment]
Hey @rberezen,

If it's all good with this PR I think we can enable back the two failing tests we are currently ignoring:

- ShowSqlWarningStructuredLoggingTests.ShowSqlWarningMessagesStructuredLogging()
- And if I'm not wrong the other one failing was SnapshotWithSchemasRegressionTests.snapshotWithSchemasSnowflake

Thanks,
Daniel.

**Review by StevenMassaro — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]

**Comment by rberezen** [comment]
> Hey @rberezen,
> 
> If it's all good with this PR I think we can enable back the two failing tests we are currently ignoring:
> 
> * ShowSqlWarningStructuredLoggingTests.ShowSqlWarningMessagesStructuredLogging()
> * And if I'm not wrong the other one failing was SnapshotWithSchemasRegressionTests.snapshotWithSchemasSnowflake
> 
> Thanks, Daniel.

https://github.com/liquibase/liquibase-pro-tests/actions/runs/9685941075
https://github.com/liquibase/liquibase-pro-tests/actions/runs/9685937952
let's see the test results

**Comment by MalloD12** [comment]
I think with the latest changes we are ready to go with this PR:

- Snowflake tests are running successfully: see execution details [here](https://github.com/liquibase/liquibase-pro-tests/actions/runs/9702456012)
- MSSQL tests need to be updated: @rberezen mentioned he will update those in the test branch where we are restoring some failing tests.

@obovsunivskyii: I think we can coordinate on Monday to merge this one and also the pro-tests one.

 Thanks,
Daniel.

**Comment by rberezen** [comment]
> I think with the latest changes we are ready to go with this PR:
> 
> * Snowflake tests are running successfully: see execution details [here](https://github.com/liquibase/liquibase-pro-tests/actions/runs/9702456012)
> * MSSQL tests need to be updated: @rberezen mentioned he will update those in the test branch where we are restoring some failing tests.
> 
> @obovsunivskyii: I think we can coordinate on Monday to merge this one and also the pro-tests one.
> 
> Thanks, Daniel.

https://github.com/liquibase/liquibase-pro-tests/pull/1482
https://github.com/liquibase/liquibase-pro-tests/actions/runs/9718956389
if green - we can merge
ty

**Pull request merged**
