### PR TITLE
expire analytics cache after 60 minutes (DAT-19278)

### PR DESCRIPTION
**Pull request by StevenMassaro**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Long running applications do not ever refresh the cached analytics configuration data. This PR adds a 60 minute expiration policy to the cached data.

### CODE REVIEW

**Comment by ben-manes** [comment]
fwiw, a single element cache might view a caching library as too heavy-weight. If you needed a thread-safe, expiring `Supplier`, then you might consider mirroring the double-checked locking approach used in Guava's [Suppliers.memoizeWithExpiration(supplier)](https://github.com/google/guava/blob/cc2c5d3d6623fe66a969c29fcb422bf02fb57a1f/guava/src/com/google/common/base/Suppliers.java#L286-L346).

**Comment by StevenMassaro** [comment]
> fwiw, a single element cache might view a caching library as too heavy-weight. If you needed a thread-safe, expiring `Supplier`, then you might consider mirroring the double-checked locking approach used in Guava's [Suppliers.memoizeWithExpiration(supplier)](https://github.com/google/guava/blob/cc2c5d3d6623fe66a969c29fcb422bf02fb57a1f/guava/src/com/google/common/base/Suppliers.java#L286-L346).

Thanks @ben-manes ! We had some plans of what we might do with caffeine going forward, which was part of the reason for bringing it in now. Unfortunately we still need to support Java 8, so it looks like that won't be an option. In any case, thanks for pointing out the Guava code, I'll review it.

**Review by filipelautert — APPROVED** [review]

**Comment by ben-manes** [comment]
> Unfortunately we still need to support Java 8, so it looks like that won't be an option. 

Caffeine 2.x is Java 8 based if you’d like to use that. In v3 we switched from Unsafe to VarHandles, removed deprecations, etc but it’s mostly equivalent between those major versions thanks to a n exhaustive test suite.

**Review by abrackx — APPROVED** [review]
Nice! Can you remove the mention of caffeine in the pr?

**Pull request merged**
