### PR TITLE
[4.24 Regression] Checksum error while performing update and then rollback with a changelog parameter - Fix for issue #5278

### PR DESCRIPTION
**Pull request by ebussieres**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This PR fixes a bug introduced in 4.24.0. This PR fixes issue #5278

### CODE REVIEW

**Comment by EvaristeGalois11** [comment]
Just wanted to add: would it be possible to backport this fix to 4.24.X? Spring boot 3.2.X is using that version and they have a policy of updating only to patch releases, so it could permit them to fix it without having to wait for 3.3.0

**Comment by ebussieres** [comment]
> Just wanted to add: would it be possible to backport this fix to 4.24.X? Spring boot 3.2.X is using that version and they have a policy of updating only to patch releases, so it could permit them to fix it without having to wait for 3.3.0

Sure, what is the branch for the 4.24.x release ?

**Comment by EvaristeGalois11** [comment]
Sorry my bad, it was a message for the liquibase devs for when they will process this PR.

**Comment by filipelautert** [comment]
> Just wanted to add: would it be possible to backport this fix to 4.24.X? Spring boot 3.2.X is using that version and they have a policy of updating only to patch releases, so it could permit them to fix it without having to wait for 3.3.0

Hello @EvaristeGalois11 - this fix will probably be included with 4.26.0 . Sorry but liquibase don't have a policy to release minor versions with fixes for previous versions yet.

**Comment by filipelautert** [comment]
@ebussieres thanks for the fix! so seems we forgot to add the parameter to some commands... thanks for spotting that!

**Review by filipelautert — APPROVED** [review]
This PR adds missing arguments to Liquibase class that were missing during a fix for issue #4491 + it adds tests!

**Review by rberezen — APPROVED** [review]

**Pull request merged**
