### PR TITLE
fix support for custom DB2Database implementations

### LINKED ISSUE #2058: Exception during dropAll on a custom DB2 Database implementation
**Liquibase Version**:
4.4.3

**Database Vendor & Version**:
DB2i

## Description
We extended DB2Database to do some tweaks to make it work on DB2i (similar to what they do in https://github.com/liquibase/liquibase-db2i). 

An exception occurs when executing the dropAll command.
I attached a PR to fix this. 

## Steps To Reproduce
- Register your own custom DB2iDatabase (which extends DB2Database and overrides supportsBooleanDataType)
- execute a dropAll against a DB2i database

## Actual Behavior
An exception occurs with the stacktrace mentioned below.

## Expected/Desired Behavior
No exception occurs and the dropAll executes normally

## Additional information
During a dropAll we get the following exception while liquibase tries to create the databasechangeloglock table:

`Caused by: liquibase.exception.LockException: liquibase.exception.DatabaseException: [SQL0204] BOOLEAN in *LIBL type *SQLUDT not found. [Failed SQL: (-204) CREATE TABLE "RICUSTOMER".DATABASECHANGELOGLOCK (ID INTEGER NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DBCHGLOGLOCK PRIMARY KEY (ID))]
        at liquibase.core@4.5.0-local-SNAPSHOT/liquibase.lockservice.StandardLockService.acquireLock(StandardLockService.java:293)
        at liquibase.core@4.5.0-local-SNAPSHOT/liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:211)`

DB2i does not support boolean types, and thus we specified this in our custom DB2iDatabase by overriding the existing DB2Database.supportsBooleanDataType.

The implementation in liquibase.datatype.core.BooleanType however is not correct, it does not take this into consideration because of a bug. It uses an incorrect isAssignableFrom:
`if (database.getClass().isAssignableFrom(DB2Database.class)) {
			if (((DB2Database) database).supportsBooleanDataType())
				return new DatabaseDataType("BOOLEAN");
			else
				return new DatabaseDataType("SMALLINT");
        }`

### PR DESCRIPTION
**Pull request by wardvijf**
Fixes #2058

- - -
#### Links
* Fixed Issues: 
  * [https://github.com/liquibase/liquibase/issues/2058](https://github.com/liquibase/liquibase/issues/2058)
  * [https://github.com/liquibase/liquibase/issues/2067](https://github.com/liquibase/liquibase/issues/2067)
* Test Results: [https://github.com/liquibase/liquibase/pull/](https://github.com/liquibase/liquibase/pull/){PR ID}/checks

#### Testing
* Steps to Reproduce:
  * Requires a db2i datatabase and the corresponding extension
  * [https://github.com/liquibase/liquibase/issues/2058](https://github.com/liquibase/liquibase/issues/2058)
  * [https://github.com/liquibase/liquibase/issues/2067](https://github.com/liquibase/liquibase/issues/2067)
* Guidance:
  * Impact: fixes a how we are checking the type of database so we correctly use the db2i extension, does not impact the other database support

#### Dev Verification
Reviewed code only, since I don't have a db2i database to test with. But, I see how the fix would address the problem with the extension.

#### Github Users
* wardvijf

## Test Requirements (Liquibase Internal QA)
**Manual Tests**

* Verify the functional tests are passing in the GitHub actions build.
* None required.
* This fix is targeted to a database platform that QA does not have access to at this time.

**Automated Tests**

* No new functional tests required.
* No new test-harness tests required.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-2168) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by ducatier** [comment]
Fixes #2067

**Comment by wardvijf** [comment]
@molivasdat is there anything I can do to help getting this merged?

**Comment by molivasdat** [comment]
Hi @wardvijf Yes, we need to fix the build so that at least you can have a test fix for this issue.

**Comment by wardvijf** [comment]
@molivasdat the build is fixed

**Comment by molivasdat** [comment]
Hi @wardvijf Thanks for the feedback.
We are little behind in pulling in PRs at the moment.
Hopefully the new interim fix can hold you until we can pull into an official build.

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or [Test Harness Tests](https://github.com/liquibase/liquibase-test-harness/pulls)
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by wardvijf** [comment]
@molivasdat Is this one still on the radar? Just checking, since we are really waiting for this fix

**Comment by wardvijf** [comment]
@molivasdat we have no interim fix, we are waiting for this to be released.

**Review by nvoxland — APPROVED** [review]

**Review by suryaaki2 — APPROVED** [review]

**Comment by wardvijf** [comment]
Okay, we have 2 approvals, which is great. Who can merge this one? /cc @suryaaki2 @nvoxland

**Comment by nvoxland** [comment]
I pushed a merge of origin/master to the fork so it should build successfully now

**Pull request merged**
