### PR TITLE
Recognize jdbc:edb urls as a distinct EnterpriseDB dialect

### PR DESCRIPTION
**Pull request by szandany**
## Description
Adds EnterpriseDBDatabase dialect class so that liquibase will correctly recognize "jdbc:edb:..." urls as being like postgresql but potentially different.

There was some stub code around that used a postgersql.getDbType() call to differentiate between COMMUNITY and EDB enum values which I switched to the more standard "instanceof EnterpriseDBDatabase" checks. 

With this change, liquibase should correctly recognize the url value `jdbc:edb://host:5444/dbname` and default to using the edb jdbc driver.

|----|----|----|----|----|
|liquibase lib directory|properties/cli|properties/cli|dialect|changetype|
|EDB driver installed|Driver|url|updateSQL|createPackage|
|no|none|jbdc:edb|FAIL|FAIL|
|no|postgres|jbdc:edb|FAIL|FAIL|
|no|edb|jbdc:edb|edb|pass|
|no|none|jbdc:postgres|postgres|FAIL|
|no|postgres|jbdc:postgres|postgres|FAIL|
|no|edb|jbdc:postgres|postgres|FAIL|
|yes|none|jbdc:edb|edb|pass|
|yes|postgres|jbdc:edb|FAIL|FAIL|
|yes|edb|jbdc:edb|edb|pass|
|yes|none|jbdc:postgres|postgres|FAIL|
|yes|postgres|jbdc:postgres|postgres|FAIL|
|yes|edb|jbdc:postgres|postgres|FAIL|

## Testing
Start an enterprisedb container like:

```java
docker run --rm -e POSTGRES_PASSWORD=LiquibasePass1 -p5444:5432 enterprisedb/postgresql
```

and then connect to it on localhost:5444 with standard postgresql tools to create a test user/database:

```java
create user lbuser;
alter user lbuser password 'LiquibasePass1';

create database lbcat owner lbuser;
```

With the fix, you can run liquibase operations against `--url jdbc:edb://localhost:5444/lbcat --username lbuser --password LiquibasePass1` and it will default to the `com.edb.Driver` driver. You can see this by not having the edb driver in your lib dir and getting a `Cannot find database driver: com.edb.Driver` error.

By adding the driver from [https://www.enterprisedb.com/software-downloads-postgres](https://www.enterprisedb.com/software-downloads-postgres) to your lib dir, the "cannot find database driver" error goes away and liquibase runs like normal.

## Level of EDB Support
This change ONLY makes it so a jdbc:edb url works as users expect. We are not adding official support for edb yet or testing anything beyond that we can connect and do a very simple update operation. Any additional EDB testing or features will be done in future work. This just sets us up for that work and makes basic use easy for end users.

- - -
#### Links
* Stand alone PR
* Test Results: [https://github.com/liquibase/liquibase/pull/2244/checks](https://github.com/liquibase/liquibase/pull/2244/checks)

#### Testing
* Steps to Reproduce: See above
* Guidance:
  * Impact: only impacts enterprisedb support.

#### Dev Verification
Started enterprisedb container and ran operations against it using standard postgresql URL. Saw that jdbc:edb failed with the missing driver as expected.

## **Test Requirements (Liquibase Internal QA)**
Examples of liquibase.properties and changelog files are attached.

Configure liquibase.properties file to connect to your database instance.

**Manual Tests.**

_1 Verify Liquibase behavior when EDB Driver is_ **_not_** _in lib diectory and_ **_jdbc:edb_** _url is specified._

* make sure jdbc:postgres url is commented out in liquibase.properties file
* make sure jdbc:edb url is uncommented in liquibase.properties file
* _1.1 Verify that Liquibase throws an error if_ **_no_** _driver is specified_
  * make sure both edb and postgres drivers are commented out in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `Unexpected error running Liquibase: java.lang.RuntimeException: Cannot find database driver: com.edb.Driver`
* _1.2 Verify that Liquibase throws an error if_ **_postgres_** _driver is specified_
  * uncomment postgres driver in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * ```
Unexpected error running Liquibase: Connection could not be created to jdbc:edb://localhost:### with driver org.postgresql.Driver. 
Possibly the wrong driver for the given database URL
```


* _1.3 Verify that Liquibase throws an error if_ **_edb_** _driver is specified_
  * comment out postgres driver in liquibase.properties file
  * uncomment edb driver in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `Unexpected error running Liquibase: java.lang.RuntimeException: Cannot find database driver: com.edb.Driver`

_2 Verify Liquibase behavior when EDB Driver is_ **_not_** _in lib diectory and j_**_dbc:postgres_** _url is specified._

* make sure jdbc:edb url is commented out in liquibase.properties file
* make sure jdbc:postgres url is uncommented in liquibase.properties file
* _2.1 Verify that Liquibase works succesfully if_ **_no_** _driver is specified_
  * make sure both edb and postgres drivers are commented out in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `udate-sql` is successful
    * ```
-- Changeset lb2185-changelog.xml::1::Liquibase
CREATE TABLE public.test_table (test_id INTEGER NOT NULL, test_column VARCHAR, CONSTRAINT test_table_pkey PRIMARY KEY (test_id));
-- Changeset lb2185-changelog.xml::2::your.name
CREATE OR REPLACE FUNCTION TestFunction()  
RETURNS test_table  
LANGUAGE SQL   
AS   
$$  
    SELECT * FROM test_table;  
$$/
```

  * run `liquibase update -changelog-file lb2185-changelog.xml --labels table,function` 
    * `update` is successful
    * `test_table` is present in database
    * `TestFunction` is present in database
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels package`
    * `udate-sql` is successful
    * ```
-- Changeset lb2185-changelog.xml::3::Liquibase
CREATE OR REPLACE PACKAGE empinfo
			IS
    				emp_name VARCHAR2(10);
    				PROCEDURE get_name (
        				p_empno NUMBER
    				);
    				FUNCTION display_counter
    				RETURN INTEGER;
			END/
```


  * run `liquibase update -changelog-file lb2185-changelog.xml --labels package`
    * `syntax error` is thrown
* _2.2 Verify that Liquibase works succesfully if_ **_postgres_** _driver is specified_
  * uncomment postgres driver in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `udate-sql` is successful
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels table,function` 
    * `update` is successful
    * `test_table` is present in database
    * `TestFunction` is present in database
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels package`
    * `syntax error` is thrown
* _2.3 Verify that Liquibase throws an error if_ **_edb_** _driver is specified_
  * comment out postgres driver in liquibase.properties file
  * uncomment edb driver in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `Unexpected error running Liquibase: Connection could not be created to jdbc:postgresql://localhost:5506/lbcat with driver com.edb.Driver.  Possibly the wrong driver for the given database URL`

_3_ _Verify Liquibase behavior when EDB Driver_ **_is_** _in lib diectory and j_**_dbc:postgres_** _url is specified._

* make sure jdbc:edb url is commented out in liquibase.properties file
* make sure jdbc:postgres url is uncommented in liquibase.properties file
* _3.1 Verify that Liquibase works succesfully if_ **_no_** _driver is specified_
  * make sure both edb and postgres drivers are commented out in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `udate-sql` is successful
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels table,function` 
    * `update` is successful
    * `test_table` is present in database
    * `TestFunction` is present in database
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels package`
    * `udate-sql` is successful
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels package`
    * `syntax error` is thrown
* _3.2 Verify that Liquibase works succesfully if postgres driver is specified_
  * uncomment postgres driver in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `udate-sql` is successful
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels table,function` 
    * `update` is successful
    * `test_table` is present in database
    * `TestFunction` is present in database
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels package`
    * `udate-sql` is successful
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels package`
    * `syntax error` is thrown
* _3.3 Verify that Liquibase throws an error if_ **_edb_** _driver is specified_
  * comment out postgres driver in liquibase.properties file
  * uncomment edb driver in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `Unexpected error running Liquibase: Connection could not be created to jdbc:postgresql://localhost:5506/lbcat with driver com.edb.Driver.  Possibly the wrong driver for the given database URL`

_4_ _Verify Liquibase behavior when EDB Driver_ **_is_** _in lib diectory and j_**_dbc:edb_** _url is specified._

* make sure jdbc:postgres url is commented out in liquibase.properties file
* make sure jdbc:edb url is uncommented in liquibase.properties file
* _4.1 Verify that Liquibase works succesfully if_ **_no_** _driver is specified_
  * make sure both edb and postgres drivers are commented out in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `udate-sql` is successful
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels table,function` 
    * `update` is successful
    * `test_table` is present in database
    * `TestFunction` is present in database
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels package`
    * `udate-sql` is successful
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels package`
    * `update` is successful
    * `empinfo` package is present in database (SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE') 
* _4.2 Verify that Liquibase throws an error if postgres driver is specified_
  * uncomment postgres driver in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `Unexpected error running Liquibase: Connection could not be created to jdbc:edb://localhost:5506/lbcat with driver org.postgresql.Driver.  Possibly the wrong driver for the given database URL`
* _4.3 Verify that Liquibase throws an error if_ **_edb_** _driver is specified_
  * comment out postgres driver in liquibase.properties file
  * uncomment edb driver in liquibase.properties file
  * make sure both edb and postgres drivers are commented out in liquibase.properties file
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels table,function`
    * `udate-sql` is successful
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels table,function` 
    * `update` is successful
    * `test_table` is present in database
    * `TestFunction` is present in database
  * run `liquibase update-slq -changelog-file lb2185-changelog.xml --labels package`
    * `udate-sql` is successful
  * run `liquibase update -changelog-file lb2185-changelog.xml --labels package`
    * `update` is successful
    * `empinfo` package is present in database (SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE = 'PACKAGE') 

_5 Verify Liquibase behavior when EDB Driver_ **_is_** _specified in classpath and j_**_dbc:edb_** _url is specified._

* repeat TestCases 4.1 - 4.3
* expected results stay the same as in TestCases 4.1 - 4.3



┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-2185) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by r2liquibase** [comment]
What do you think about creating a new EDB extension? @nvoxland created a template that should make that easier: https://github.com/liquibase/liquibase-extension-example.

**Comment by szandany** [comment]
Hi @r2liquibase

**Comment by wwillard7800** [comment]
We should make sure we don't re-invent the wheel wrt to the EDB work done in DaticalDB.

**Comment by andre15silva** [comment]
Hi, we are researchers in software engineering, working on a novel GitHub bot for helping understand build failures.

We have run our prototype bot [flacocobot](https://github.com/SpoonLabs/flacoco) on this failing PR and below are the results.

What do you think?

Thanks a lot! --Davide (@dginelli), André (@andre15silva), Matias (@martinezmatias), Benjamin (@danglotb), Martin (@monperrus)

**********************************

The line (16) of the file liquibase/util/csv/CSVWriter has been identified with a suspiciousness value of 65.47%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>
liquibase/util/csv/CSVWriter

**********************************

The line (70) of the file liquibase/changelog/OfflineChangeLogHistoryService has been identified with a suspiciousness value of 65.47%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>
liquibase/changelog/OfflineChangeLogHistoryService

**********************************

The line (83) of the file liquibase/changelog/ChangeLogHistoryServiceFactory has been identified with a suspiciousness value of 65.47%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>
liquibase/changelog/ChangeLogHistoryServiceFactory

**********************************

The line (85) of the file liquibase/changelog/ChangeLogHistoryServiceFactory has been identified with a suspiciousness value of 65.47%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>
liquibase/changelog/ChangeLogHistoryServiceFactory

**********************************

The line (93) of the file liquibase/database/OfflineConnection has been identified with a suspiciousness value of 65.47%.

<details>
     <summary>Failing tests that cover this line</summary>

- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testNewCsvFileDeletion`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSqlAndNoDdl`
- `liquibase.changelog.OfflineChangeLogHistoryServiceTest#testInitOfflineWithOutputLiquibaseSql`
</details>
liquibase/database/OfflineConnection

**********************************

**Review by nvoxland — APPROVED** [review]

**Comment by nvoxland** [comment]
I talked with @wwillard7800 about these changes and they are good. It's just some simple support at this point and not re-inventing anything. As we look at future features we can bring in other existing code as needed.

**Review by suryaaki2 — APPROVED** [review]

**Comment by szandany** [comment]
You have the right link to download the edb JDBC driver in your comment, @kataggart.

**Pull request merged**
