### PR TITLE
Output a delimiter command for MySQL client.

### PR DESCRIPTION
**Pull request by adangel**
This behavior can be triggered with `outputDelimiter="true"` for SQL changes.
This allows for generating SQL via outputSQL that can be used
directly with the MySQL command line tool.

The following example changeset:

```
<changeSet id="1" author="a">
    <sql endDelimiter="//" splitStatements="false" outputDelimiter="true">
        CREATE PROCEDURE x (a int)
        BEGIN
          DECLARE b int;
        END//
    </sql>
</changeSet>
```

Will produce the following SQL:

```
--  Changeset test-changelog.xml::1::a
delimiter //
CREATE PROCEDURE x (a int)
        BEGIN
          DECLARE b int;
        END//
delimiter ;
```

I've chosen now the name `outputDelimiter`. Let me know, if this is ok or whether I should change it.

Thanks!

### CODE REVIEW

**Comment by nvoxland** [comment]
I'm waiting with this pull request because I think it will fit better in with the 4.0 refactoring because it is fairly mysql-specific.

**Comment by ro-rah** [comment]
Hi @adangel,

Would you resolve branch conflict for this PR (thanks for adding tests)?  Here's some guidance on that below:

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by adangel** [comment]
@ro-rah I've rebase this PR against master. It compiles and unit tests are working. I didn't do any integration tests nor did I use this feature at all.... so I can't tell whether it really works and whether it breaks other things....

**Comment by ro-rah** [comment]
@adangel , thanks!  Sorry for the wait, will send this to the 4.0 release

**Pull request closed without merging**
