### PR TITLE
Postgresql - Fallback to default schema name in SequenceSnapshotGenerator when this is null

### LINKED ISSUE #3542: NullPointerException in SequenceSnapshotGenerator
## Environment

**Liquibase Version**: 4.18.0

**Database Vendor & Version**: PostgresDatabase

**Operating System Type & Version**: Windows 10

## Description

In case the `SequenceSnapshotGenerator` is used by e.g. a `sequenceExists` precondition having no schema name set, the `SequenceSnapshotGenerator` fails at line 235 with a NullPointerException: "Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null"

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "replacement" is null
	at java.base/java.lang.String.replace(String.java:2959)
	at deployment.gemini-web.war//liquibase.snapshot.jvm.SequenceSnapshotGenerator.getSelectSequenceSql(SequenceSnapshotGenerator.java:235)
	at deployment.gemini-web.war//liquibase.snapshot.jvm.SequenceSnapshotGeneratorSnowflake.getSelectSequenceSql(SequenceSnapshotGeneratorSnowflake.java:35)
	at deployment.gemini-web.war//liquibase.snapshot.jvm.SequenceSnapshotGenerator.snapshotObject(SequenceSnapshotGenerator.java:89)
	at deployment.gemini-web.war//liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:66)
	at deployment.gemini-web.war//liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
	at deployment.gemini-web.war//liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:312)
	at deployment.gemini-web.war//liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:105)
	at deployment.gemini-web.war//liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:58)
	at deployment.gemini-web.war//liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:34)
	at deployment.gemini-web.war//liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
	at deployment.gemini-web.war//liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:244)
	at deployment.gemini-web.war//liquibase.snapshot.SnapshotGeneratorFactory.has(SnapshotGeneratorFactory.java:133)
	at deployment.gemini-web.war//liquibase.precondition.core.SequenceExistsPrecondition.check(SequenceExistsPrecondition.java:59)
	at deployment.gemini-web.war//liquibase.precondition.core.NotPrecondition.check(NotPrecondition.java:35)
	at deployment.gemini-web.war//liquibase.precondition.core.AndPrecondition.check(AndPrecondition.java:40)
	at deployment.gemini-web.war//liquibase.precondition.core.PreconditionContainer.check(PreconditionContainer.java:213)
	at deployment.gemini-web.war//liquibase.changelog.ChangeSet.execute(ChangeSet.java:601)
```

Please check SequenceSnapshotGenerator#getSelectSequenceSql(Schema schema, Database database):

`
String pgSequenceQuery = COMMON_PG_SEQUENCE_QUERY.replace("SCHEMA_NAME", schema.getName());
`

This happens because of the implementation in SnapshotGeneratorFactory#has(DatabaseObject example, Database database) which triggers searching the sequences without applying any default values on the first try.

It would also perform a seconds try with a default value applied, but the NullPointerException occurred already before.

## Steps To Reproduce

Use a sequence exists precondition without a schema:

```
<changeSet author="me" id="someId">
    <preConditions onFail="MARK_RAN">
        <sequenceExists sequenceName="mySequence" />
    </preConditions>
</changeSet>
```

## Actual Behavior

A NullpointerException occurs while checking if a sequence exists.

## Expected/Desired Behavior

Checking if sequences are existing is done correctly.

### PR DESCRIPTION
**Pull request by djochim**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

In liquibase 4.18.0, the SequenceExistsPrecondition fails, with a null schema name during snapshot creation.
[Table snapshot](https://github.com/liquibase/liquibase/blob/0804df2bd989c3318d9994b8546d3b55a45ef7f3/liquibase-core/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java#L113) creation fallbacks to the default schema in this case. 

This code change adds a fallback to the default schema if schema name = null.

Fixes #3542 NullPointerException in SequenceSnapshotGenerator

## Things to be aware of

- Alternative solution: The whole snapshot creation [fallbacks to the default schema](https://github.com/liquibase/liquibase/blob/0804df2bd989c3318d9994b8546d3b55a45ef7f3/liquibase-core/src/main/java/liquibase/snapshot/SnapshotGeneratorFactory.java#L136) if null is returned. SequenceSnapshotGenerator can also return null if the schema name is null. 

## Things to worry about

- Is this the expected behavior in all cases or are there further cases where the fallback is not correct?

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Change make sense off hand. Thanks!

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Comment by djochim** [comment]
Would it be possible to get a snapshot version for testing the fix?

**Comment by filipelautert** [comment]
> Would it be possible to get a snapshot version for testing the fix?

Hello @djochim ! Sure, I trigerred the build you can download them from the section here -> https://github.com/liquibase/liquibase/actions/runs/3829437295

**Review by filipelautert — APPROVED** [review]
* Postgresql specific fix
* Tests added

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
This PR is a Postgres-specific fix to snapshot of sequences. It prevents a null pointer if sequences do not have a schema defined. In that case, Liquibase uses the default schema (public).
* Functional and test harness executions passing.
* New unit test added to validate cases where a schema is defined, is set to default or is undefined. 
* No additional testing required.

APPROVED

**Pull request merged**
