### PR TITLE
Run tests using Java 21

### PR DESCRIPTION
**Pull request by filipelautert**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [X] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Profile non-jdk8 was used to upgrade mockito libraries as we still need to compile and test using Java 8.

### CODE REVIEW

**Comment by filipelautert** [comment]
Caused by: java.lang.IllegalArgumentException: Java 21 (65) is not supported by the current version of Byte Buddy which officially supports Java 20 (64) - update Byte Buddy or set net.bytebuddy.experimental as a VM property

**Comment by filipelautert** [comment]
Our bytebuddy version is old (1.12.19) because our Mockito version is old (4.10) .  We can try to upgrade bytebuddy by itself and see if it works.
We can't upgrade mockito to 5.x series that uses the new bytebuddy as it requires java 11  - this would break our java 8 build.

**Comment by StevenMassaro** [comment]
> Our bytebuddy version is old (1.12.19) because our Mockito version is old (4.10) . We can try to upgrade bytebuddy by itself and see if it works. We can't upgrade mockito to 5.x series that uses the new bytebuddy as it requires java 11 - this would break our java 8 build.

Why are we still building against Java 8 if it's end of life?

**Review by StevenMassaro — APPROVED** [review]

**Comment by filipelautert** [comment]
> Why are we still building against Java 8 if it's end of life?

@StevenMassaro seems people still using Java 8 (even pro customers?) so we want to make sure that we are compatible with that. But I agree that we should drop support for it soon (Liquibase 5?) .

**Pull request merged**
