### PR TITLE
Delegate change set equality tests

### PR DESCRIPTION
**Pull request by droy-sandbox**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Moving the responsibility of determining ChangeSet/RanChangeSet equality from the change log filters to the to the RanChangeSet.isSameAs() method.  The change is logically equivalent to what existed before but centralizes the equality logic to the RanChangeSet class.

This was done so that extension developers can override the ChangeSet and RanChangeSet classes to provide a different behavior by overriding the isSameAs() and toString() methods.  My particular use case is identifying change sets only by id to support refactoring of database change logs.  This allows me to move change sets around without having them mis-identified as "new" change sets.

## Things to be aware of

N/A

## Things to worry about

N/A

## Additional Context

N/A

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Code cleanup is always appreciated, thanks!

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Review by MalloD12 — APPROVED** [review]
**Approved**.

This is looking good to me and all checks are green. Thanks @droy-sandbox for this clean up, very appreciate it.

**Review by filipelautert — APPROVED** [review]
Seems fine, removes redundant methods.

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
PR removes redundant logic from several changeset classes, relying instead upon the logic in the `isSameAs` method in [https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/changelog/RanChangeSet.java](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/changelog/RanChangeSet.java).
* Functional and test harness executions passing.
* No additional testing necessary.

APPROVED

**Pull request merged**
