### PR TITLE
Fix liquibase.skip in maven plugin when activated in multithreaded build

### PR DESCRIPTION
**Pull request by piotrwielgolaski-tomtom**
it is critical to not make this check under Scope as it will fail in multithreaded builds

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

This change move decision about skipping maven plugin execution outside of "scope".
When user wants to skip plugin he can enable multithreaded build (-T 1C) which in current implementation fails.

## Additional Context

it is very small step into fixing issue https://github.com/liquibase/liquibase/issues/3446

### CODE REVIEW

**Comment by nvoxland** [comment]
Initial review:
Thanks for the step along the way.

Things to be aware of:
- I didn't figure out why the change is needed, that can be part of the main review

Things to worry about:
- Nothing

**Comment by piotrwielgolaski-tomtom** [comment]
> * I didn't figure out why the change is needed, that can be part of the main review

@nvoxland this change is to make sure liquidbase will skip its execution as fast as possible. 
today because of problem with scope manager that does not work in multithreaded setup user can't even skip plugin. Also there is no reason to open scope and then make decision to skip.

**Review by filipelautert — APPROVED** [review]
Simple change - exit before creating scope and doing other validations. Thanks @piotrwielgolaski-tomtom

**Comment by XDelphiGrl** [comment]
Functional Tests Running Here: [https://github.com/liquibase/liquibase-pro-tests/actions/runs/4960363854](https://github.com/liquibase/liquibase-pro-tests/actions/runs/4960363854)

Test Harness Running Here: [https://github.com/liquibase/liquibase-test-harness/actions/runs/4960375512](https://github.com/liquibase/liquibase-test-harness/actions/runs/4960375512)

**Review by XDelphiGrl — APPROVED** [review]
The Maven `skip` property was being ignored by Liquibase in multithreaded environments; this PR adjusts the code to address that bug.
* Functional and test harness executions passing.
* No additional testing required.

APPROVED

**Comment by piotrwielgolaski-tomtom** [comment]
@suryaaki2 any chance you will find time to review it?

**Pull request merged**
