### PR TITLE
Core 3463 fix for validateX attributes of constraintsConfig

### PR DESCRIPTION
**Pull request by stevesaliman**
This is the same as my previous pull request for this issue, but done against the 3.8.x branch.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-53) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.1

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @stevesaliman ,

I just looked at another one of our PRs.  Thanks again for submitting and sorry it took us so long to respond.  Looks like there is a conflict, would you mind resolving?  Thanks for adding to the tests!

Ronak

**Comment by stevesaliman** [comment]
I rebased this pull request to the latest 3.8.x branch, and it looks like the conflicts are resolved.

**Comment by ro-rah** [comment]
I sized this at a RiskMedium, maybe a low.
- includes tests
- closes CORE-3463
- user did follow @nvoxland guidance on https://liquibase.jira.com/browse/CORE-3463

**Comment by ro-rah** [comment]
Hi @stevesaliman ,

May we have reproducible steps to test this PR?  

Erz brings up a good point, we need a way to test it.  It looked like we followed all recommended steps from Nathan but I should have checked for clear repro steps.  
I looked in https://liquibase.jira.com/browse/CORE-3463 and was unable to find reproducible steps.

Thanks, 

Ronak

**Comment by stevesaliman** [comment]
If you still want to reproduce this, perhaps the easiest way is to run the unit tests of the Liquibase Groovy DSL, which fails without the patch because of the method names, but succeeds with it.

**Pull request merged**
