### PR TITLE
Make liquibase.snapshot.ResultSetCache an extensible class.

### PR DESCRIPTION
**Pull request by breglerj**
This is useful in case an extension has to override
liquibase.snapshot.jvm.UniqueConstraintSnapshotGenerator#listConstraints.

## Environment

**Liquibase Version**:
4.5.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI

**Liquibase Extension(s) & Version**: 
liquibase-hanadb

**Database Vendor & Version**:
SAP HANA

**Operating System Type & Version**:

## Pull Request Type

- [x] Bug fix (non-breaking change which fixes an issue.)
- [ ] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

A clear and concise description of the issue being addressed.  Additional guidance [here](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core).
- Describe the actual problematic behavior.
- Ensure private information is redacted.

see https://github.com/liquibase/liquibase-hanadb/issues/69

## Steps To Reproduce

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

see https://github.com/liquibase/liquibase-hanadb/issues/69

## Actual Behavior
A clear and concise description of what happens in the software **before** this pull request.
- Include console output if relevant
- Include log files if available.

see https://github.com/liquibase/liquibase-hanadb/issues/69

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** this pull request.

## Fast Track PR Acceptance Checklist:

- [x] Build is successful and all new and existing tests pass
- [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
- [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
- [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
- [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

### CODE REVIEW

**Comment by breglerj** [comment]
@r2liquibase can you please take a look at this? It will help fixing https://github.com/liquibase/liquibase-hanadb/issues/69.

**Comment by molivasdat** [comment]
HI @breglerj Thanks for creating this issue.

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or [Test Harness Tests](https://github.com/liquibase/liquibase-test-harness/pulls)
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by molivasdat** [comment]
Part of this fix may belong in the hanadb extension.

**Review by nvoxland — APPROVED** [review]
Code review and test results:

I've been hoping to make some significant changes to this API for a while, and so the methods were not extensible because I wasn't sure how compatible we'll continue to be long-term as we do things like support nosql databases etc.

But, that is likely a while from now still that we'll get to that and we will already have to deal with compatibility issues at this point, so no use blocking people from extending things as they need now. 

Things to be aware of:
- Doesn't change behavior, just makes methods extendable

Things to worry about:
- Nothing

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
* Fix changes several snapshot classes to `protected` to allow extensibility.
* Fix does not impact functionality of current implementations leveraging these classes.
* No additional testing required.

APPROVED

**Pull request merged**
