### PR TITLE
Add Class-Path entry to the manifest file to simplify command line execution

### PR DESCRIPTION
**Pull request by b-gyula**
* CORE-3566 Class-Path entry in the jar could simplify execution
* Fix: `Build-Time, Build-Number, Liquibase-Version` attributes were not set in the manifest file

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-25) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.1

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @b-gyula,

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest 
changes, additional tests, or provide other feedback. The PR will be prioritized 
according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

Thanks!

Ronak

**Comment by ro-rah** [comment]
Hah, sorry accidentally hit the Close button instead of comment.  Please disregard the close.

**Comment by ro-rah** [comment]
Labeled it as Low risk as it is minor changes to poms.

**Comment by ro-rah** [comment]
closes CORE-3566

**Comment by ro-rah** [comment]
Discussed internally, want to point out the removal of `<manifestFile>src/main/assembly/MANIFEST.MF</manifestFile>` from the pom, and don't know enough yet to say weather all that is covered in <manifestEntries>

**Comment by nvoxland** [comment]
As part of the testing, we'll want to look at the final result of what is in the MANIFEST.MF file.

**Comment by b-gyula** [comment]
The [MANIFEST.MF](https://github.com/liquibase/liquibase/files/4825730/MANIFEST.MF.txt)

**Comment by ro-rah** [comment]
Yay, thanks for providing the file @b-gyula!

**Comment by nvoxland** [comment]
I'll merge this in after #1108 gets merged in

**Comment by nvoxland** [comment]
I double checked to make sure that having the class-path header didn't make liquibase fail if the listed jars were not there. 

It was fine.

**Comment by nvoxland** [comment]
The changes in this PR came along in #1237 and will be in 3.10.1

**Pull request closed without merging**
