### PR TITLE
Fixed #3745 error generation intType when using autoIncrement=true with H2 V2

### LINKED ISSUE #3745: Table creation fails with H2 v2 when a change set specifies `autoIncrement="true"`
# Environment

Liquibase Version: 4.19.0

Liquibase Integration & Version: SpringBoot v3.0.2

Database Vendor & Version: H2 v2.1.214

Operating System Type & Version: MacOS v13.1

# Description

Since upgrading to H2 v2 my change set no longer applies.

# Steps To Reproduce

Create a change set such as this:

```xml
 <changeSet author="mark" id="createPersonsTable">
     <createTable tableName="persons">
         <column autoIncrement="true" name="personId" type="INT(10)"/>
         <column name="lastName" type="VARCHAR(255)"/>
         <column name="firstName" type="VARCHAR(255)"/>
         <column name="address" type="VARCHAR(255)"/>
         <column name="city" type="VARCHAR(255)"/>
     </createTable>
 </changeSet>
```

The magic part is the `autoIncrement="true"`.

Recreation is [here](https://github.com/CynanX/LiquibaseH2Issue).

# Actual Behavior

An exception is throw: -

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [uk/co/mark/LiquibaseConfiguration.class]: liquibase.exception.MigrationFailedException: Migration failed for changeset changelog/0.3.0/tables/example.xml::1::test-user:
     Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "CREATE TABLE PUBLIC.EXAMPLE (ID INT[*](10) GENERATED BY DEFAULT AS IDENTITY NOT NULL, NAME VARCHAR(45) NOT NULL, CONSTRAINT PK_EXAMPLE PRIMARY KEY (ID))"; expected "ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE PUBLIC.EXAMPLE (ID INT(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL, NAME VARCHAR(45) NOT NULL, CONSTRAINT PK_EXAMPLE PRIMARY KEY (ID)) [42001-214] [Failed SQL: (42001) CREATE TABLE PUBLIC.EXAMPLE (ID INT(10) GENERATED BY DEFAULT AS IDENTITY NOT NULL, NAME VARCHAR(45) NOT NULL, CONSTRAINT PK_EXAMPLE PRIMARY KEY (ID))]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:313) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1130) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:905) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137) ~[spring-boot-test-3.0.2.jar:3.0.2]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[spring-core-6.0.4.jar:6.0.4]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[spring-core-6.0.4.jar:6.0.4]
	at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1386) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:543) ~[spring-boot-test-3.0.2.jar:3.0.2]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137) ~[spring-boot-test-3.0.2.jar:3.0.2]
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108) ~[spring-boot-test-3.0.2.jar:3.0.2]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:184) ~[spring-test-6.0.4.jar:6.0.4]
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:118) ~[spring-test-6.0.4.jar:6.0.4]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:127) ~[spring-test-6.0.4.jar:6.0.4]
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:191) ~[spring-test-6.0.4.jar:6.0.4]
```

# Expected/Desired Behavior

The table should be created.

# Additional Context

The above change set works fine when using H2 v1.x.

### PR DESCRIPTION
**Pull request by quonas**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description
Fixed #3745 when a column use both intType and autoincrement  with h2 v2 ，the generated data type syntax is incorrect.

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

The fix seems isolated to what the reported problem is. I wonder if a better solution may be to not be using the raw definition in the first place but looking at the object more directly? But I've not stepped through the code closely enough to know one way or the other.

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Comment by filipelautert** [comment]
Hello @quonas , thanks for the fix.
I reviewed the code based on Nathan's suggestion and replaced the regular expression for a simpler call. What do you, does it work for you too?

**Comment by quonas** [comment]
> Hello @quonas , thanks for the fix. I reviewed the code based on Nathan's suggestion and replaced the regular expression for a simpler call. What do you, does it work for you too?

I agree with this modification. Thank you for your code review.

**Review by filipelautert — APPROVED** [review]
Fixes an error where autoincrement columns would cause an exception.
Adds tests, thanks @quonas !

**Review by XDelphiGrl — APPROVED** [review]
PR addresses a regression in Liquibase SQL generation for H2 integers when `autoIncrement` is true. 
* New unit tests added for combinations of int with various precisions and `autoIncrement` values (true or default (false)).
* Test harness executions passing.
* There were some failures in the functional test suite; these were in SQLServer and Postgres and can be disregarded for the purposes of this PR.
* No additional testing required.

APPROVED

**Review by suryaaki2 — APPROVED** [review]

**Pull request merged**
