### PR TITLE
Implement "author" command argument for diffChangelog command

### LINKED ISSUE #1610: diffChangelog command is not respecting the changeSetAuthor option
## Environment
**Liquibase Version**:
3.10.3

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
Any

**Liquibase Extension(s) & Version**: 
Any

**Database Vendor & Version**:
Any

**Operating System Type & Version**:
Any

## Description
since the `diffChangelog` command has the potential to write to an external changelog file,
I think we should also respect the `changeSetAuthor` option as what `generateChangelog` command did.

## Steps To Reproduce
execute `diffChangelog` command with `--changeSetAuthor` option

### PR DESCRIPTION
**Pull request by vitaliyg2**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Currently there is no way to specify changesets author for changesets generated by the diffChangelog command.
This implements support of the author command argument for the diffChangelog command, same way as it's implemented for the generateChangelog command.

This allows to specify author for diffChangelog in properties file or from the command line, also implemented changeSetAuthor property for Maven plugin (same way as it is implemented for generateChangelog command).

Fixes #1610

## Things to be aware of

Implementation is based on the generateChangelog command.

### CODE REVIEW

**Comment by filipelautert** [comment]
Hello @vitaliyg2 , thanks for the improvement!
I fixed the current tests, but do you think you could add a new test for this change at diffChangelog.test.groovy ?

**Comment by VitaliyCP** [comment]
Hi @filipelautert,
I'm not sure if it worth creating  new test for this (it will be practically identical copy of the existing test) , for now I just updated one of the existing tests to also check for if author argument is working correctly.

**Comment by vitaliyg2** [comment]
Hi @filipelautert,
I'm not sure if it worth creating new test for this (it will be practically identical copy of the existing test) , for now I just updated one of the existing tests to also check for if author argument is working correctly.

**Review by filipelautert — APPROVED** [review]
Thanks @vitaliyg2 , Adding the parameter to a test seems enough.

**Review by suryaaki2 — APPROVED** [review]

**Comment by filipelautert** [comment]
Thanks @vitaliyg2 for unhiding author field for generate-changelog!

**Comment by XDelphiGrl** [comment]
Functional tests started here: [https://github.com/liquibase/liquibase-pro-tests/actions/runs/4993639743](https://github.com/liquibase/liquibase-pro-tests/actions/runs/4993639743)

**Review by XDelphiGrl — APPROVED** [review]
Did you ever wish you could generate a changelog or diff-changelog and specify an author name, instead of relying on the autogenerated author name? Now you can! This PR introduces a new `diff-changelog` command property `author` that Liquibase uses to popluate the author attribute on generated changesets. `Generate-changelog` already implemented the `author` command property, but it was hidden from the help. The property is now correctly documented in the CLI help for both `diff-changelog` and `generate-changelog`. 
* Integration tests expanded to validate the new functionality.
* Light manual testing of `diff-changelog --author customAuth` for all changelog formats passing.
* Test harness failures are unrelated to this PR and can be disregarded.
* Functional tests passing.

APPROVED

**Comment by unlimitedsola** [comment]
Hi All, big thanks for adding this feature ❤️. In my original feature request, I only mentioned that the `author` was missing as an argument for the generated changelogs, but I could see supporting the `context` option could also be a useful addition too. Would you mind if I follow the steps of this PR and also add the support for `context`?

**Comment by filipelautert** [comment]
Hello @unlimitedsola ! Sure, please feel free to create a new pr. The more features the merrier :)

**Pull request merged**
