### PR TITLE
On SQL Server use 'datetime2' instead of 'datetime' for type 'timestamp'

### PR DESCRIPTION
**Pull request by thomseno**
## Environment
**Liquibase Version**: 3.8.9, applicable to all newer versions

**Liquibase Integration & Version**: maven 3.6.3, spring boot 2.2.13.RELEASE

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: SQL Server 2019 (5.0.4043.16),  SQL Server 2016 (13.0.4604.0)

**Operating System Type & Version**:

## Pull Request Type

* \[ ] Bug fix (non-breaking change which fixes an issue.)
* \[x] Enhancement/New feature (non-breaking change which adds functionality)
* \[ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
According to Microsoft it is recommended to use `datetime2` instead of `datetime` for all new projects, because of portability and precision (see [datetime (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql)).

## Actual Behavior
Currently a liquibase change set including a `type="timestamp"` will create a column of type `datetime` on SQL Server.

## Expected/Desired Behavior
Whenever one uses `type="timestamp"` in liquibase change sets a column of type `datetime2`  will be created on SQL Server.

## Additional Context
Columns of type `datetime` were causing problems in combination with Hibernate and `@Version`.

## Fast Track PR Acceptance Checklist:

<

!--- If you're unsure about any of these, just ask us in a comment. We're here to help|width=200,height=183!

-->

* \[x] Build is successful and all new and existing tests pass
* \[ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* \[ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* \[ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
* \[ ] Documentation Updated

- - -
#### Links
* Fixed Issue: Stand alone PR
* Local Branch: [https://github.com/liquibase/liquibase/tree/LB-1191](https://github.com/liquibase/liquibase/tree/LB-1191)
* Unit Tests: [https://github.com/liquibase/liquibase/pull/1679/checks](https://github.com/liquibase/liquibase/pull/1679/checks)
* Integration Tests: (shown in Unit Tests link above)
* Functional Tests: [https://jenkins.datical.net/job/liquibase-pro/job/LB-1191/](https://jenkins.datical.net/job/liquibase-pro/job/LB-1191/)

#### Testing
* Steps to Reproduce: See above
* Guidance: 
  * Impacts only mssql

#### Dev Verification
Ran changelog with type=datetime to ensure it was created as datetime2
(no output was saved at the time)

## Test Requirements (Liquibase QA Engineers)
* No new functional automated tests required.
* Add a changetype test to the [liquibase/liquibase-test-harness](https://github.com/liquibase/liquibase-test-harness) to validate timestamp handling for MSSQL

Here is an example of SQL to generate a table with columns of type datetime2, one with default and another with precision specified, and a third column of type timestamp.

```java
CREATE TABLE testdatetime2 (
    id INT PRIMARY KEY IDENTITY,
    name VARCHAR (50) NOT NULL,
    created_at DATETIME2,
    created_at_precision DATETIME2(3),
    created_timestamp TIMESTAMP
);
```

_Verify generate-changelog returns datetime2 for a SQL Server column with default precision._
_Verify generate~~changelog returns datetime2 for a SQL Server column with a non~~default precision._ 
_Verify generate-changelog returns datetime2 for a SQL Server column created as TIMESTAMP._
_Verify update-sql produces valid SQL for all three columns._
_Verify an update operation creates a table with all three columns as datetime2._

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-1191) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by molivasdat** [comment]
Hi @thomseno Thanks for creating this PR.

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Review by nvoxland — APPROVED** [review]
The changes seem good. Datetime2 is the recommended version for sqlserver, and datetime2 works on all supported sqlserver versions.

It will cause a change in behavior for existing users who had "timestamp" converted to "datetime" before, though. Their existing scripts will switch to datetime2 going forward.

**Comment by nvoxland** [comment]
Because this will change the behavior of existing changelogs, we will have to release it as part of a major release like 4.5.0 vs. a patch release like 4.4.1.

**Review by suryaaki2 — APPROVED** [review]

**Comment by nvoxland** [comment]
I set this as "ReleaseMajor" because it will be changing the behavior of existing changelogs and so needs to out in a non-patch release like 4.5.0

**Pull request merged**
