### PR TITLE
DAT-12597 include commercial sources and javadoc in reversion

### PR DESCRIPTION
**Pull request by ap-liquibase**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

**Goal**: To make sure that LB Comercial javadoc and sources are included in the `liquibase-additional-<version>.zip` artifact that gets attached to draft releases.

As it turns out in liquibase/liquibase  build.yml we already create javadoc and sources for LB Commercial. That means that I don’t need to do it via workflows in the LB Pro repo (as was my first try, but is not as simple). 
The re-version.sh script in liquibase/liquibase controls what is included in the `liquibase-additional-<version>.zip` so listing the sources and javadoc for commercial there marks these for inclusion. That is the essence of my change.

No additional user action is required.
For more context see [here](https://datical.atlassian.net/browse/DAT-12597)

### CODE REVIEW

**Comment by StevenMassaro** [comment]
@ap-liquibase Can you fill out the description for the PR?

**Review by abrackx — APPROVED** [review]
Overall looks good to me, I checked the output of the manual run and it produced valid commericial-sources and commercial-javadocs jars.

**Comment by ap-liquibase** [comment]
Added details to description. if you agree then I'll merge in the change and close ticket @StevenMassaro @abrackx

**Review by StevenMassaro — APPROVED** [review]
@filipelautert can you review?

**Review by filipelautert — APPROVED** [review]
All good!

**Pull request merged**
