### PR TITLE
Separate Firebird v3 from earlier Firebird versions

### PR DESCRIPTION
**Pull request by Wallaby1999**
Proposal for implementing 'firebird3' together with tests

### CODE REVIEW

**Comment by ro-rah** [comment]
Thanks @Wallaby1999 for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest 
changes, additional tests, or provide other feedback. The PR will be prioritized 
according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.
-Ronak

**Comment by ro-rah** [comment]
closes #1077

**Comment by ro-rah** [comment]
This has been targeted for release in Q2, updates as work progresses. :)

**Comment by ro-rah** [comment]
Hey @Wallaby1999,

I was looking at https://github.com/liquibase/liquibase/issues/1093, were you latest changes differentiating the shortname for Firebird vs Firebird3?

Thanks,

Ronak

**Comment by Wallaby1999** [comment]
> were you latest changes differentiating the shortname for Firebird vs Firebird3?

Yes, it does. If you take a look into commit [2a651ce6ba26a7dab9d9cd14872c203c3023fa5d](https://github.com/liquibase/liquibase/pull/1079/commits/2a651ce6ba26a7dab9d9cd14872c203c3023fa5d) it is introducing firebird3 as shortname for Firebird Databases >= 3.

**Comment by ro-rah** [comment]
Brilliant @Wallaby1999!  

I thought those commits covered that case but since I'm still a liquibase newb, I thought it better to ask than to hold up this PR for a lack of my understanding.  Thanks for the response!

-Ronak

**Comment by nvoxland** [comment]
I think we'd want to keep the shortname the same between 3 vs. not. 

As a user, it would be surprising they'd need to use a "firebirdv3" vs. just "firebird" in dbms attributes, and it would require updating old changeSets when a database is upgraded from 2 to 3.

I see splitting the V3Database class off vs. adding "if version > 3" blocks in the code as an implementation detail of how we want to manage the differences vs. something that should be exposed to the users.

**Comment by Wallaby1999** [comment]
@nvoxland Just for clarification: it would be enough to use the same shortname for both Database classes and adjust the tests accordingly?

**Comment by Wallaby1999** [comment]
So I just added a commit to remove the "firebird3" shortname again, but now I am not able to differentiate the Firebird versions in the tests, when the generated SQL is different:

- ./liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addLookupTable/firebird.sql
- ./liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/addNotNullConstraint/firebird.sql
- ./liquibase-core/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/dropNotNullConstraint/firebird.sql

@nvoxland: How could I solve that issue and test both cases Firebird >= 3 and < 3?

**Comment by nvoxland** [comment]
Different SQL with different versions is a general problem with the current test setup for many databases, not just firebird 2 vs. 3. 

We're working on improving that in a separate effort, but don't have anything to give you with it right now besides just have the tests at least consistent between 2 or 3. I'm guessing v3 is most common, so that is probably the best version to commit.

**Comment by nvoxland** [comment]
Prior to merging this in, I will add firebird support to the build server

**Comment by grauds** [comment]
Hi, could we please bump it up? Is this planned to be resolved? Or there is a well known workaround?

**Comment by MalloD12** [comment]
Hi @Wallaby1999,

Are you still keen to get this PR merged? Would you mind resolving the existing merge conflicts we have at the moment? In the same line as what Nathan mentioned, I think we should align this PR to use the existing `FirebirdDatabase` class and not have a new one just to differentiate the database version number. I think if in some specific test, we need to run some Firebird tests with a specific version number we can create an instance of it by overriding its `getDatabaseMajorVersion()` method. Something like this:

```
 FirebirdDatabase h2DatabaseV1 = new FirebirdDatabase() {
            @Override
            public int getDatabaseMajorVersion() {
                return 3;
            }
 };
```
If you have any questions/concerns please do not hesitate to reach out to us. I apologize for the time this PR has been waiting, but it's now on our radar and we will try to provide an answer as soon as possible.

Thanks,
Daniel.

**Comment by Wallaby1999** [comment]
It is more than three years since I started this. Unfortunately it is totally out of interest now. Do whatever you want with this, I do not care any more about it.

**Pull request closed without merging**
