### PR TITLE
Include Maven wrapper to use the same Maven version

### PR DESCRIPTION
**Pull request by asomov**
[Maven wrapper](https://github.com/takari/maven-wrapper) does not depend on the local Maven and it allows to use defined Maven version
The usage:
`.\mvnw clean test`

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-124) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 4.0 beta 2

### CODE REVIEW

**Comment by ro-rah** [comment]
@asomov 
Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
Sizing RiskMed due to no included test.  However seems easy enough to test.

**Comment by asomov** [comment]
The pull request is 2 years old.

**Comment by ro-rah** [comment]
Yes, the PR is 2 years old, and before my time with Liquibase.  

My first project I wanted to accomplish is to respond to all the PRs submitted.  I apologize for the wait and understand not wanting to invest anymore in this old issue.  

If you choose to [contribute code](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core) or time again, I believe that you would have a better experience.  I hope under our new direction of community first for Liquibase and the return to our open source roots proves that through future interactions.

Anyways, thanks for the contribution and your time, you deserved a faster response.

-Ronak

**Pull request closed without merging**
