### PR TITLE
Tidy ExecutorService code, remove superfluous map access (Issue 1841)

### PR DESCRIPTION
**Pull request by jamey-clari**
## Description

Tidy ExecutorService code, remove superfluous imports and map access.

### CODE REVIEW

**Comment by molivasdat** [comment]
Hi @jamey-clari 
If the build succeeds in GitHub Actions there will be a snapshot build of this PR.

Here's what happens next:
A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or [Test Harness Tests](https://github.com/liquibase/liquibase-test-harness/pulls)
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by jamey-clari** [comment]
> Hi @jamey-clari
> If the build succeeds in GitHub Actions there will be a snapshot build of this PR.
> 
> Here's what happens next:
> A member of the Liquibase team will take a look at your contribution and may suggest:
> 
> * Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
> * Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or [Test Harness Tests](https://github.com/liquibase/liquibase-test-harness/pulls)
> * Provide other feedback, like requesting changes.
> 
> The PR will be prioritized according to our internal development and testing capacity.
> 
> We’ll let you know when it’s ready to move to the next step or if any changes are needed.

NP @molivasdat - I'd expect things to wind their way through the pipeline for a bit.

**Comment by jamey-clari** [comment]
It looks like some sort of surefire test failed for only Java 11.  It's hard to imagine that any of my edits were JDK version sensitive let alone to version 11 but not 8 and 16.  Is it possible the build had some sort of transient issue and simply needs to be retried?

**Review by nvoxland — APPROVED** [review]
Code review and test results:

Things to be aware of:
- The changes make sense, mainly cleanup work
- No change in behavior, so existing tests should would anything changed

Things to worry about:
- Nothing

**Review by XDelphiGrl — APPROVED** [review]
* PR makes the code in ExecutorService and AbstractJdbcDatabase classes more readable.
* Fix prevents duplication of stack trace in log output.
* No additional testing required.

APPROVED

**Review by suryaaki2 — APPROVED** [review]

**Pull request merged**
