### PR TITLE
fix: Checksum for SQL changes containing dbms attributes can get different values if md5sum column is null

### LINKED ISSUE #5618: Generating incorrect md5sum
### Search first

- [X] I searched and no similar issues were found

### Description

We migrated from version 4.9.1 to version 4.25.0 without issues, but in a certain situation, it was necessary to perform the clear-checksums, and after recalculating the md5sum by 4.25.0, it started reporting inconsistencies in the generated md5

### Steps To Reproduce

Steps to reproduce:

1. Have this changeSet executed in your database by version 4.9.1 where the md5sum `8:3b06ccdb23f1b15752104130a7d5e3d6` was generated
2. Execute the `liquibase update` command in version 4.25.0, it will upgrade the md5sum generating the following value: `9:a4f08e5d093fb1cb5061048413e6f954`
3. Execute the `liquibase clear-checksums` command, which will set the md5sum to null
4. Execute the `liquibase update` command again in version 4.25.0. In this case, it will update the md5sum value incorrectly and execute normally. Value found in our tests: `9:d41d8cd98f00b204e9800998ecf8427e`
5. Execute the `liquibase update` command again in version 4.25.0, and from then on, it will always give an error indicating that the md5sum is incorrect

Additional details:

- We used Java OpenJDK version "1.8.0_312".
- To execute this and other files, we have another XML db-update file that includes it

Changelog where the problem occurred:
```
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.6.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.6.xsd">
	<changeSet author="automation" id="123"> 
		<preConditions onFail="MARK_RAN">
			<not>
				<sqlCheck expectedResult="0">
					<![CDATA[
						select count(*) from flex_registration_config
						where ds_content_persistence_layout not like '%<DataSource>%'
					]]>
				</sqlCheck>
			</not>
       	</preConditions> 
		<sql  dbms="oracle" splitStatements="false">
		<![CDATA[
			DECLARE
				p xmlparser.parser;
				doc xmldom.DOMDocument;
				v_replace CLOB;
				nl xmldom.DOMNodeList;
				len number;

				CURSOR c is 
					select id_flex_registration_config, ds_content_persistence_layout from flex_registration_config;
				
				procedure clob_replace( i_src CLOB, i_match VARCHAR2, i_rep VARCHAR2 , i_result IN OUT CLOB) IS
				  MAX_VARCHAR2 NUMBER DEFAULT 15000;  -- depending on your character set, 32767 may not be your actual number of available characters
				
				  l_ret_clob CLOB;                    -- temporary CLOB to be returned
				  l_next_idx NUMBER;                  -- used to traverse the source CLOB, captures the next instance of the match string
				  l_search_begin NUMBER DEFAULT 1;    -- used to traverse the source CLOB, indicates the starting point of the next search
				  l_parse_begin NUMBER DEFAULT 1;     -- used to copy date from the source CLOB, indicates the beginning of the copy window
				  l_parse_end NUMBER;                 -- used to copy date from the source CLOB, indicates the beginning of the end window
				
				BEGIN
				
				  -- Create a temporary CLOB to be returned
				  DBMS_LOB.CREATETEMPORARY( l_ret_clob, TRUE );
				
				  LOOP
				
					l_next_idx := DBMS_LOB.INSTR( i_src, i_match, l_search_begin, 1 );
				
					-- Exit once we do not find another occurance of the match string
					EXIT WHEN l_next_idx = 0;
				
					-- Special handling if we find a match at the first character of the source string
					IF l_next_idx = 1 THEN
				
					  l_parse_begin := LENGTH( i_match ) + 1;
				
					  IF LENGTH( i_rep ) > 0 THEN
						DBMS_LOB.APPEND( l_ret_clob, i_rep );
					  END IF;
				
					ELSE
				 
					  -- Copy source data up to the match
					  l_parse_end := l_next_idx - 1;
					  DBMS_LOB.COPY( l_ret_clob, i_src, ( l_parse_end - l_parse_begin + 1 ), DBMS_LOB.GETLENGTH( l_ret_clob ) + 1, l_parse_begin );
					  
					  -- Replace the match string
					  IF LENGTH( i_rep ) > 0 THEN
						DBMS_LOB.APPEND( l_ret_clob, i_rep );
					  END IF;
				
					  -- Move the beginning of the next parse window past our match string
					  l_parse_begin := l_parse_end + LENGTH( i_match ) + 1;
				
					END IF;
				
					-- Move the beginning of the search window past our match string
					l_search_begin := l_next_idx + LENGTH( i_match );
				
				  END LOOP;
				
				
				  -- Special handling for the trailing final characters of the source CLOB
				  IF DBMS_LOB.GETLENGTH( i_src ) > ( l_parse_end  + LENGTH( i_match ) ) THEN
				
					l_parse_begin := l_parse_end  + LENGTH( i_match ) + 1;
					l_parse_end := DBMS_LOB.GETLENGTH( i_src );
					DBMS_LOB.COPY( l_ret_clob, i_src, ( l_parse_end - l_parse_begin + 1 ), DBMS_LOB.GETLENGTH( l_ret_clob ) + 1, l_parse_begin );
				
				  END IF;
				
				  
				  IF DBMS_LOB.GETLENGTH(l_ret_clob) = 0 THEN
					i_result := i_src;
				  ELSE
					i_result := l_ret_clob;
				  END IF;

				END clob_replace;
				
			BEGIN
				--DBMS_OUTPUT.ENABLE(1000000);
				FOR r IN c 
				LOOP
					-- new parser
					p := xmlparser.newParser;

					-- set some characteristics
					xmlparser.setValidationMode(p, FALSE);

					-- parse input
					xmlparser.parseclob(p, r.ds_content_persistence_layout);
					-- get document
					doc := xmlparser.getDocument(p);
					-- get elements DataSource
					nl := xmldom.getElementsByTagName(doc, 'DataSource');
					len := xmldom.getLength(nl);
				   
					if len = 0 then 
					 DBMS_OUTPUT.PUT_LINE(' Incluindo a tag DataSource no  flex_registration_config id [' || r.id_flex_registration_config || ']');
					 clob_replace(r.ds_content_persistence_layout,'</LayoutPersistenciaCadastroFlexivel>', '<DataSource>java:/datasource/SAFCommons_DS</DataSource></LayoutPersistenciaCadastroFlexivel>',v_replace);
					
					 update flex_registration_config 
						 set ds_content_persistence_layout = v_replace
					 where id_flex_registration_config = r.id_flex_registration_config;
					
					 dbms_lob.freetemporary(v_replace);
					 v_replace := null;
					end if;
				   
					dbms_xmldom.freedocument(doc);
					xmlparser.freeparser(p);
					p := null;
					doc := null;
					
				END LOOP;
			   COMMIT;             
			END;
		]]>
		</sql>
		<rollback>
			<sql  dbms="oracle" splitStatements="false">
			<![CDATA[
				DECLARE
					p xmlparser.parser;
					doc xmldom.DOMDocument;
					v_replace CLOB;
					nl xmldom.DOMNodeList;
					len number;

					CURSOR c is 
						select id_flex_registration_config, ds_content_persistence_layout from flex_registration_config;
					
					procedure clob_replace( i_src CLOB, i_match VARCHAR2, i_rep VARCHAR2 , i_result IN OUT CLOB) IS
					  MAX_VARCHAR2 NUMBER DEFAULT 15000;  -- depending on your character set, 32767 may not be your actual number of available characters
					
					  l_ret_clob CLOB;                    -- temporary CLOB to be returned
					  l_next_idx NUMBER;                  -- used to traverse the source CLOB, captures the next instance of the match string
					  l_search_begin NUMBER DEFAULT 1;    -- used to traverse the source CLOB, indicates the starting point of the next search
					  l_parse_begin NUMBER DEFAULT 1;     -- used to copy date from the source CLOB, indicates the beginning of the copy window
					  l_parse_end NUMBER;                 -- used to copy date from the source CLOB, indicates the beginning of the end window
					
					BEGIN
					
					  -- Create a temporary CLOB to be returned
					  DBMS_LOB.CREATETEMPORARY( l_ret_clob, TRUE );
					
					  LOOP
					
						l_next_idx := DBMS_LOB.INSTR( i_src, i_match, l_search_begin, 1 );
					
						-- Exit once we do not find another occurance of the match string
						EXIT WHEN l_next_idx = 0;
					
						-- Special handling if we find a match at the first character of the source string
						IF l_next_idx = 1 THEN
					
						  l_parse_begin := LENGTH( i_match ) + 1;
					
						  IF LENGTH( i_rep ) > 0 THEN
							DBMS_LOB.APPEND( l_ret_clob, i_rep );
						  END IF;
					
						ELSE
					 
						  -- Copy source data up to the match
						  l_parse_end := l_next_idx - 1;
						  DBMS_LOB.COPY( l_ret_clob, i_src, ( l_parse_end - l_parse_begin + 1 ), DBMS_LOB.GETLENGTH( l_ret_clob ) + 1, l_parse_begin );
						  
						  -- Replace the match string
						  IF LENGTH( i_rep ) > 0 THEN
							DBMS_LOB.APPEND( l_ret_clob, i_rep );
						  END IF;
					
						  -- Move the beginning of the next parse window past our match string
						  l_parse_begin := l_parse_end + LENGTH( i_match ) + 1;
					
						END IF;
					
						-- Move the beginning of the search window past our match string
						l_search_begin := l_next_idx + LENGTH( i_match );
					
					  END LOOP;
					
					
					  -- Special handling for the trailing final characters of the source CLOB
					  IF DBMS_LOB.GETLENGTH( i_src ) > ( l_parse_end  + LENGTH( i_match ) ) THEN
					
						l_parse_begin := l_parse_end  + LENGTH( i_match ) + 1;
						l_parse_end := DBMS_LOB.GETLENGTH( i_src );
						DBMS_LOB.COPY( l_ret_clob, i_src, ( l_parse_end - l_parse_begin + 1 ), DBMS_LOB.GETLENGTH( l_ret_clob ) + 1, l_parse_begin );
					
					  END IF;
					
					  
					  IF DBMS_LOB.GETLENGTH(l_ret_clob) = 0 THEN
						i_result := i_src;
					  ELSE
						i_result := l_ret_clob;
					  END IF;

					END clob_replace;
					
				BEGIN
					--DBMS_OUTPUT.ENABLE(1000000);
					FOR r IN c 
					LOOP
						-- new parser
						p := xmlparser.newParser;

						-- set some characteristics
						xmlparser.setValidationMode(p, FALSE);

						-- parse input
						xmlparser.parseclob(p, r.ds_content_persistence_layout);
						-- get document
						doc := xmlparser.getDocument(p);
						-- get elements DataSource
						nl := xmldom.getElementsByTagName(doc, 'DataSource');
						len := xmldom.getLength(nl);
					   
						if len >= 1 then 
						 DBMS_OUTPUT.PUT_LINE(' Removendo a tag DataSource no  flex_registration_config id [' || r.id_flex_registration_config || ']');
						 clob_replace(r.ds_content_persistence_layout,'<DataSource>java:/datasource/SAFCommons_DS</DataSource>', '',v_replace);
						
						 update flex_registration_config 
							 set ds_content_persistence_layout = v_replace
						 where id_flex_registration_config = r.id_flex_registration_config;
						
						 dbms_lob.freetemporary(v_replace);
						 v_replace := null;
						end if;
					   
						dbms_xmldom.freedocument(doc);
						xmlparser.freeparser(p);
						p := null;
						doc := null;
						
					END LOOP;
				   COMMIT;             
				END;
			]]>
			</sql>
		</rollback>
	</changeSet>
</databaseChangeLog>
```

### Expected/Desired Behavior

When executing the `liquibase clear-checksums` followed by the `liquibase update` the md5sum should be generated correctly and in subsequent executions of `liquibase update` there should be no validation of the md5sum

### Liquibase Version

4.25.0

### Database Vendor & Version

Oracle 19.3.0.0.0

### Liquibase Integration

CLI

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

Debian GNU/Linux 11

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by filipelautert**
Database object needs to be present in scope when upgradingChecksums because of dbms tags in sql changes. This method is only triggered when md5sum column is null.

Fixes #5618 

## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by MalloD12 — APPROVED** [review]
**Approved**.

It looks ok, I think it would be nice to add a changeset to our commons changelog file that contains a SQL change with a `dbms` attribute on its body. I think with that one would be good enough, or maybe we can also add an integration test scenario with the same steps that were reported in #5618.

Let me know if you need any help with that, I could help you adding those tests.

**Comment by filipelautert** [comment]
> or maybe we can also add an integration test scenario with the same steps that were reported in #5618.

@MalloD12 I think the integration test would be good, could you handle it? In fact we require 4 steps:

Steps to Reproduce:
1. Run update
2. Clear the checksums using clearCheckSums
3. Perform an update 
4. Perform another update

Thanks!

**Comment by MalloD12** [comment]
> > or maybe we can also add an integration test scenario with the same steps that were reported in #5618.
> 
> @MalloD12 I think the integration test would be good, could you handle it? In fact we require 4 steps:
> 
> Steps to Reproduce:
> 
> 1. Run update
> 2. Clear the checksums using clearCheckSums
> 3. Perform an update
> 4. Perform another update
> 
> Thanks!

Sure, I'll work on it today.

**Review by tati-qalified — APPROVED** [review]
Manually tested with `<sql>`, `<sqlFile>` and `<modifySql>` tags, and with an included .sql changelog.
Verified that the bug used to manifest **only** for `<sql>` and `<sqlFile>`.
Verified that this PR fixes the bug.

**Review by rberezen — APPROVED** [review]

**Pull request merged**
