### PR TITLE
CORE-3326 Numero sign is a symbol in Russian

### PR DESCRIPTION
**Pull request by tolix**
Numero sign in Russian it's a regular symbol ([https://en.wikipedia.org/wiki/Numero_sign)](https://en.wikipedia.org/wiki/Numero_sign)). Problem was described here [https://liquibase.jira.com/browse/CORE-3326](https://liquibase.jira.com/browse/CORE-3326) and actual for lb 4.0 version

- - -
name: Pull Request
about: Create a report to help us improve
title: 'CORE-3326 Numero sign is a symbol in Russian'
labels: Status:Discovery
assignees: ''

- - -

## Environment
**Liquibase Version**: 4.0 and earlier

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: any

**Database Vendor & Version**: any

**Operating System Type & Version**: any

## Pull Request Type

* \[x] Bug fix (non-breaking change which fixes an issue.)
* \[ ] Enhancement/New feature (non-breaking change which adds functionality)
* \[ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
[https://liquibase.jira.com/browse/CORE-3326](https://liquibase.jira.com/browse/CORE-3326)

## Fast Track PR Acceptance Checklist:

<

!--- If you're unsure about any of these, just ask us in a comment. We're here to help|width=200,height=183!

-->

* \[ ] Build is successful and all new and existing tests pass
* \[ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* \[ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* \[ ] Documentation Updated

- - -
#### Links
* Fixed Issue: [https://liquibase.jira.com/browse/CORE-3326](https://liquibase.jira.com/browse/CORE-3326)
* Test Results: [https://github.com/liquibase/liquibase/pull/1320/checks](https://github.com/liquibase/liquibase/pull/1320/checks)

#### Testing
* Steps to Reproduce: [{LINK TO ISSUE OR "See above"}](https://liquibase.jira.com/browse/CORE-3326)
* Guidance:
  * Impact: Adds this one specific char as an understood char by our parser

#### Dev Verification
Code review and ensured existing automated tests pass. Did not add extra unit test since we don't test every character

### **Test Requirements (Liquibase Internal QA)**
**Manual Tests**

_Verify update-sql works correctly when Numero sign is in comment._

* `liquibase update-sql --changelog-file lb562-changelog.xml --labels comment`
* no error is thrown
* generated sql correctly displays Numero sign

_Verify update is successful  when Numero sign is in comment._

* `liquibase update --changelog-file lb562-changelog.xml --labels comment`
* no error is thrown
* comment in DATABASECHANGELOG table correctly displays Numero sign

_Verify update-sql works correctly when Numero sign is in insert tag._

* `liquibase update-sql --changelog-file lb562-changelog.xml --labels insert`
* no error is thrown
* generated sql correctly displays Numero sign

_Verify update is successful  when Numero sign is in insert tag._

* `liquibase update --changelog-file lb562-changelog.xml --labels insert`
* no error is thrown
* inserted value correctly displays Numero sign

_Verify update-sql works correctly when Numero sign is in sql tag._

* `liquibase update-sql --changelog-file lb562-changelog.xml --labels sql`
* no error is thrown
* generated sql correctly displays Numero sign

_Verify update is successful  when Numero sign is in sql tag._

* `liquibase update --changelog-file lb562-changelog.xml --labels sql`
* no error is thrown
* inserted value correctly displays Numero sign

_Verify update-sql works correctly when Numero sign is in sqlFile tag._

* `liquibase update-sql --changelog-file lb562-changelog.xml --labels sqlfile`
* no error is thrown
* generated sql correctly displays Numero sign

_Verify update is successful  when Numero sign is in sqlFile tag._

* `liquibase update --changelog-file lb562-changelog.xml --labels sqlfile`
* no error is thrown
* SquareBracketsTest procedure successfully created

_Verify update-sql works correctly when Numero sign is in formatted sql changelog_

* `liquibase update-sql --changelog-file lb562-changelog.sql`
* no error is thrown
* generated sql correctly displays Numero sign

_Verify update is successful  when Numero sign is in formatted sql changelog_

* `liquibase update --changelog-file lb562-changelog.sql`
* no error is thrown
* AnotherTest procedure successfully created

_Verify generate-changelog correctly handles Numero sign_

* `liquibase generate-changelog --changelog-file lb562-generated.xml --diff-types tables,columns,data`
* no error is thrown
* execute `drop-all command`
* run `update` with generated changelog
  * `liquibase update --changelog-file lb562-generated.xml`
* update is succsessful
* table TEST_TABLE1 is created and filled with data that correctly displays Numero sign

**Automated Tests**

No new functional tests required for this fix.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-562) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by molivasdat** [comment]
Thanks @tolix 
Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by netlink128** [comment]
Hello! When we can get this fix?
Thank you!

**Comment by netlink128** [comment]
Hello! When we can get this fix?
This is huge stop factor for us today. 
Do you have any forecasts?

**Comment by molivasdat** [comment]
I have add this to the list of issues to process.
Needs to merge with existing currency changes that were added to this file.

**Review by nvoxland — APPROVED** [review]
Changes look good. I resolved the conflict and pushed it to the fork

**Review by suryaaki2 — APPROVED** [review]

**Comment by netlink128** [comment]
Hello!
When we can get it in release?

**Pull request merged**
