### PR TITLE
Issue 3584: Add support for relativeToChangelogFile for ChangeLogProperty class/property attribute

### PR DESCRIPTION
**Pull request by jasonlyle88**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [X] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

A clear and concise description of the change being made.  

Add a new attribute to the `property` changeLog attribute for `relativeToChangelogFile`. Modified the `ChangeLogProperty` class to add the new property along with setter/getter function. Modified the `dbchangelog-latest.xsd` to know about the new attribute. Then modified the `DatabaseChangeLog` and `YamlChangeLogParser` classes to handle the `relativeToChangelogFile` property correctly in regards to the `property` `file` attribute.

## Things to be aware of

Used the code from the `include` attribute for the `relativeToChangelogFile`, so it should be solid.

I also defaulted the `relativeToChangelogFile` attribute to false so that it does not break current behavior.

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Being able to use relativeToChangelogFile logic for changelog properties files is a nice enhancement, thanks.

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Comment by jasonlyle88** [comment]
@nvoxland @filipelautert Anything I need to do to move this forward? I understand if you all have just been busy and haven't gotten too it, just wanted to double check I hadn't missed doing anything that is needed to move forward!

**Comment by filipelautert** [comment]
Hey @jasonlyle88 , I think that during this week or the next we may be able to finish reviewing it. We've been a bit slower because of  end of the year , but we are getting there :D

**Comment by jasonlyle88** [comment]
And that is absolutely understandable! Thanks for the quick response. As I said, just wanted to make sure I didn't need to provide anything else!

**Comment by MalloD12** [comment]
Hey @jasonlyle88, 

I've been reviewing this PR and overall it was ok, although I had to make some changes on the way file resource is getting, plus added some unit tests to validate this change. I would appreciate it if you have a look at them and share any feedback/concerns you might have. 

Thanks,
Daniel.

**Review by MalloD12 — APPROVED** [review]
**Approved**. Thanks @jasonlyle88 for putting these changes in place, it's very appreciate it. 

## Review and testing results:

From my side this looking good. Actions performed on this PR:
- Manually tested this PR and behave as expected.
- Made some changes on how resources are get and manually tested changes. 
- Updated condition to make sure whether file has been found or not.
- Unit tests added.

### Things to be aware of:
- None

### Things to worry about:
- None

**Review by XDelphiGrl — APPROVED** [review]
Liquibase changelog properties are a powerful way to parameterize your changelog for use in different environments. Changelog properties can be defined inline within the changelog or by referencing a file containing changelog properties. This PR introduces the ability to specify that a file containing changelog properties can be relative to the changelog file. 
* The `property` changelog type allows specification of `relativeToChangelogFile`
  * The default for `relativeToChangelogFile` remains FALSE for backwards compatibility.
* Automated functional and test harness executions passing.
* New unit tests added.
* No additional testing required.

APPROVED

**Review by filipelautert — APPROVED** [review]

**Comment by filipelautert** [comment]
This is fine @jasonlyle88 !
It's all good and it will make into next major version (aka 4.20), thanks for the code!. I'm just not merging it to master yet as we may release 4.19.x and we don't release xsd changes with minor versions.

**Comment by XDelphiGrl** [comment]
> Sorry about the review request/changes... Dropped my phone when the page was open and clicked something as I was trying to catch it 😳

I'm so glad that this doesn't only happen to me!! lol!

**Comment by jasonlyle88** [comment]
@filipelautert okay, great, sounds good!

I recently realized that `ChangeLogProperty` could benefit from a `errorIfMissingOrEmpty ` attribute (when the `file` attribute is used) like with `includeAll`. Since that work would touch all the same files as this change, I was gonna open a separate branch once this was merged in... But would like to get it included in 4.20 if possible along with this change. I was also thinking about implementing it for I clude since it's the same concept when referencing files like this. 

If you're waiting to merge this in, how would you like me to proceed to implement `errorIfMissingOrEmpty`. Should I make a branch off of this branch, just work off master and we will get the two merged appropriately, or would you propose another way of accomplishing that?

**Comment by filipelautert** [comment]
> @filipelautert okay, great, sounds good!
> 
> I recently realized that `ChangeLogProperty` could benefit from a `errorIfMissingOrEmpty` attribute (when the `file` attribute is used) like with `includeAll`. Since that work would touch all the same files as this change, I was gonna open a separate branch once this was merged in... But would like to get it included in 4.20 if possible along with this change. I was also thinking about implementing it for `include` since it's the same concept when referencing files like this.
> 
> If you're waiting to merge this in, how would you like me to proceed to implement `errorIfMissingOrEmpty`? Should I make a branch off of this branch, just work off master and we will get the two merged appropriately, or would you propose another way of accomplishing that?

Sorry @jasonlyle88 , I missed this last comment of you. could you create a new PR for this change and mark me in the comments? I'm going to merge this one today so it can be the base for you.

Thanks!

**Comment by jasonlyle88** [comment]
No worries @filipelautert . Thanks for getting this merged in! I will create the new PR sometime in the next week or so and make sure to tag you on it.

Thanks @MalloD12 @XDelphiGrl @filipelautert for getting this across the finish line!

**Pull request merged**
