### PR TITLE
LiquibaseServletListener.contextInitialized() should not shut Embedded Derby down

### PR DESCRIPTION
**Pull request by stanio**
---
name: Pull Request
about: Create a report to help us improve
title: 'LiquibaseServletListener.contextInitialized() should not shut Embedded Derby down'
labels: Status:Discovery
assignees: ''

---

## Environment

**Liquibase Version**: 3.8.x

**Liquibase Integration & Version**: servlet

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Apache Derby 10.14

**Operating System Type & Version**:

## Pull Request Type

- [x] Bug fix (non-breaking change which fixes an issue.)
- [x] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

In certain configurations using `LiquibaseServletListener` with Embedded Derby application may fail with `java.sql.SQLNonTransientConnectionException: No current connection.`.

Full details of *Steps To Reproduce*, *Actual Behavior*, *Expected/Desired Behavior* and *Additional Context* have been given to [CORE-3540][].  This is my suggestion of how it could be addressed.

## Fast Track PR Acceptance Checklist:

- [x] Build is successful and all new and existing tests pass
- [x] Added Unit Test(s)
- [ ] Added Integration Test(s)
- [ ] Documentation Updated

[CORE-3540]: https://liquibase.jira.com/browse/CORE-3540

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-232) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.1

### CODE REVIEW

**Comment by stanio** [comment]
I have added relevant unit tests but I had to add `derby` as `test` dependency – not sure if that's o.k.

**Comment by ro-rah** [comment]
@stanio thanks again for another PR.

Sizing as RiskLow:
- good discription
- includes tests

**Comment by stanio** [comment]
Added sample `LiquibaseServletListenerTest`, although I had to add `derby` as a test dependency again.  I'll rework the tests (possibly drop the last one) if given suggestions from the Liquibase maintainers.

**Comment by ro-rah** [comment]
@stanio , I will defer to Erzsebet on the inclusion of derby.  Thanks for the test add!

**Comment by nvoxland** [comment]
We decided we will not do any additional manual testing beyond what will be covered with the automated tests.

**Pull request merged**
