### PR TITLE
Fix double with precision type error for H2 

### LINKED ISSUE #3099: DOUBLE with precision doesn't work anymore with H2 database
## Environment

**Liquibase Version**: `4.9.1` and `4.13.0`

**Liquibase Integration & Version**: jar - application tests/integration tests

**Database Vendor & Version**: `H2` `2.1.214`

**Operating System Type & Version**: macos monterey 12.4

## Description

Liquibase doesn't translate `DOUBLE` field to correct value in H2 database. It's translated directly to DOUBLE but that type is [not supported](http://www.h2database.com/html/datatypes.html) by H2. 

## Steps To Reproduce

```
databaseChangeLog:
- changeSet:
    id: 1
    author: author
    comment: initial schema
    changes:
    - createTable:
        columns:
        - column:
            name: double_val
            type: DOUBLE(20)
        tableName: double_test
```

```
 Reason: liquibase.exception.DatabaseException: Syntax error in SQL statement "CREATE TABLE double_test (double_val DOUBLE[*](20))"; expected "PRECISION, ARRAY, INVISIBLE, VISIBLE, NOT NULL, NULL, AS, DEFAULT, GENERATED, ON UPDATE, NOT NULL, NULL, AUTO_INCREMENT, DEFAULT ON NULL, NULL_TO_DEFAULT, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, NULL, CHECK, REFERENCES, AUTO_INCREMENT, ,, )"; SQL statement:
CREATE TABLE double_test (double_val DOUBLE(20)) [42001-214] [Failed SQL: (42001) CREATE TABLE double_test (double_val DOUBLE(20))]

	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:126)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:262)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Scope.child(Scope.java:243)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:261)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2400)
	at liquibase.Liquibase.update(Liquibase.java:208)
	at liquibase.Liquibase.update(Liquibase.java:194)
	at liquibase.Liquibase.update(Liquibase.java:190)
	at liquibase.Liquibase.update(Liquibase.java:182)
```

## Actual Behavior
We've migrated from spring boot `2.4.5` to `2.7.2` where also liquibase (`3.10.3` - > `4.9.1`) and h2 (`1.4.200` -> `2.1.214`) versions changed and columns with `DOUBLE(xy)` were working previously.

## Expected/Desired Behavior
Column with `DOUBLE(xy)` is correctly translated.

### PR DESCRIPTION
**Pull request by MalloD12**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Fix double type column parsing when double type is specified with precision (i.e. double(25)). 

Fixes #3099 

## Things to be aware of

- Added logic to parse double(xy) as a "Double Precision" for H2 database.
- Only impact on H2 database.

## Things to worry about

- Nothing.

## Additional Context

- Nothing.

### CODE REVIEW

**Review by nvoxland — APPROVED** [review]
Looking at the docs, it looks like h2 1.x supported "double" and "double precision" as aliases for each other, but 2.x only supports "double precision. Neither version supports arguments, so I simplified the code down to just "always return double precision"

**Review by XDelphiGrl — APPROVED** [review]
Fix addresses a bug in Liquibase SQL generation for the DOUBLE PRECISION datatype. 
* New unit tests added to validate input of "double" and "double(20)"; both inputs are expect to return DOUBLE PRECISION.
  * H2 itself does not support providing precision, but Liquibase will handle such input as DOUBLE PRECISION.
* No additional testing required.

APPROVED

**Review by suryaaki2 — APPROVED** [review]

**Comment by TomBenjamins** [comment]
Could you please apply this fix also to the BIGINT, INTEGER, BOOLEAN types?

https://github.com/liquibase/liquibase/issues/3099#issuecomment-1192324131

this bug is blocking for us to upgrade to h2 v2.

**Comment by bhuism** [comment]
+1

**Comment by richardmLL** [comment]
+1

**Comment by hilkojacobse** [comment]
+1

**Comment by MalloD12** [comment]
@TomBenjamins We have already applied a similar fix for `INT(xt)`. I wasn't aware this was also an issue for `BOOLEAN` and `BIGINT`. I'll discuss it today with the team and get back to you guys. Thanks for the feedback.

**Comment by MalloD12** [comment]
Hey guys, I just want to let you know I'll be creating a separate issue to address `BIGINT` and `BOOLEAN` types. For `INTEGER`, we already have an open [issue](https://github.com/liquibase/liquibase/issues/3250) for that. But I would also like to ask you if you guys can share some example (changelog/changeset) on how you are using these types.

Thanks,
Daniel.

**Comment by TomBenjamins** [comment]
Hello Daniel,

for us the only blocking one is BIGINT, as that one is being used in nearly all our table creation scripts.
On mysql it still works fine, but on H2 v2 we get similar syntax exceptions as described in this issue and #3099  
If you can provide me the new issue link I can add a liquibase example for at least the BIGINT issue there.

greetings, 

Tom

**Comment by MalloD12** [comment]
Hey @TomBenjamins I have just created this [issue](https://github.com/liquibase/liquibase/issues/3300), please have a look to it and feel free to edit/anything you guys consider relevant for me when working on it. 

Thanks,
Daniel.

**Pull request merged**
