### PR TITLE
Improve ChangeFactory initialization time

### PR DESCRIPTION
**Pull request by stanio**
This is currently taking most of the Liquibase initialization time on my side, which is rather slow especially when included during the startup of an application.  I've identified the following time-gobbling areas:

-   Every `Change` type is loaded and initialized (can't change much about it currently), including very slow meta-data initialization;
-   Most time-consuming `analyzeSupportedDatabases()` and `analyzeRequiredDatabases()` during the construction of `ChangeParameterMetaData` – these can be lazily evaluated, which also avoids evaluating them for any `Change` types which don't end up used;
-   Multiple unnecessary bean introspections for the same type – lesser performance impact, still unnecessary adds up:
    -   `AbstractChange.createChangeMetaData()` obtains full property info, then for each property `createChangeParameterMetadata()` obtains full property info copy on its own; next
    -   `ChangeParameterMetaData.getCurrentValue()` / `setValue()` obtain full property info copy on every invocation.

Considering the following simple test:

```java
        long startTime = System.currentTimeMillis();
        ChangeFactory.getInstance();
        long elapsedTime = System.currentTimeMillis() - startTime;
        System.out.println("Time [sec]: " + elapsedTime / 1E3);
```

I get improvement from originally ~3.1 sec down to ~1.3 sec.  In my production case, I'm getting originally ~3.5 sec down to ~1.5 sec.  So I think this is a rather significant win – please consider merging it upstream.

__
<sup>This is my second take on this matter, after my previous premature attempt #958.</sup>

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-15) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.1

### CODE REVIEW

**Comment by SteveDonie** [comment]
Thanks for working on this! We will review this and get back to you.

**Comment by ro-rah** [comment]
Hi @stanio ,  again thanks for the submission.  These time improvements if accurate are significant and awesome!

My role currently at Liquibase is focusing on making it easier to accept the good work the community is doing, while maintaining quality.  One of things I am looking for to move PRs to the front of the line is unit tests, [here our guidance](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests).

Would you mind writing unit tests for the changes made in AbstractChange.java and ChangeParameterMetaData.java ?

Thanks,

Ronak

**Comment by stanio** [comment]
Hi @ro-rah.  Thanks for getting back.  I'll look into Liquibase guidance for writing unit tests.

In the meantime, given the non-functional nature of this change, I will likely need guidance on what type of test Liquibase maintainers would like to see – possibly measuring time, or maybe test the existing behavior?  The former may be tricky, and the later is not supposed to change.  I'll have a look at what existing tests for these classes there are.

**Comment by ro-rah** [comment]
Ah @stanio , you are totally right, seems since this is a performance tweak, we should just verify we didn't break functionality.  Performance testing would probably fall back on my side of the fence :)

I will check in with the team, till then I think you have done great, glad to hear you will read the unit test doc, that will come in handy for future submissions. 

We all at Liquibase appreciate the work you put in here, thanks for being a part of the team!

Ronak

**Comment by ro-rah** [comment]
Hey, we are looking to have this fix merged in by Q2.  Thanks so much for the help @stanio.

**Pull request merged**
