### PR TITLE
Add ChangeWithTablespace interface to ease batch processing

### PR DESCRIPTION
**Pull request by danielthegray**
Sometimes, when defining a ChangeExecListener, it would be useful to have a listener like this, to change the tablespace in bulk for a bunch of changes without having to maintain an exhaustive list of all the necessary changes yourself.

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @danielthegray !

It looks like this PR has some conflicts with Master than need to be resolved, would you please resolve.  

Tests can move this to the next state (Conditioning) easier if you include tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)).  Would you be willing to add tests as well?

Thanks,

Ronak

**Comment by danielthegray** [comment]
Hi! I've resolved the merge conflict.

I be happy to add tests but I'm not sure what tests could be added. The only intention is to have a common interface for all the database changes that have a tablespace parameter... As you can see it's a small change (just adding an interface) and the main thing would be that the project compiles, and that none of the existing tests are broken (once again, highly unlikely due to the nature of the change).

If you can think of any test cases that would be useful, I'd be happy to add them.
Cheers,
Daniel

**Comment by ro-rah** [comment]
@danielthegray , thanks for the response!  Actually your clarification was just what I was looking for.  During Conditioning these clarifications help confirm effort, including QA.  Stating that existing integration tests should cover it gives our internal QA a hand.  Thanks for the quick response!

**Comment by ro-rah** [comment]
I sized this as a RiskMedium.  Normally it would be RiskLow with minor improvement and clarification on how to test but sized it up for internal review time to vet how or if we would want the enhancement of batch processing.

**Comment by danielthegray** [comment]
You're welcome! The change should be completely transparent to all users of the class, it just enables more rich change processing in the future.

Either way, thanks for including it on your timeline!

**Comment by filipelautert** [comment]
Hi - this is a simple and nice change that I don't know why it got stuck. 
As it is quite old I'll close the PR, but please reopen it and fix the conflicts if you still willing to get this work included. Thanks!

**Pull request closed without merging**
