### PR TITLE
Upgrades installer JDK version for next release.

### PR DESCRIPTION
**Pull request by filipelautert**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [X] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

A clear and concise description of the change being made.  

Upgrades java minor version for installer.

## Things to be aware of

- none

## Things to worry about

- none

### CODE REVIEW

**Review by nvoxland — APPROVED** [review]

**Review by suryaaki2 — APPROVED** [review]

**Comment by XDelphiGrl** [comment]
@filipelautert , @FBurguer and @MalloD12 - hi! I removed the autocandidate tag from this ticket. As a new version of the JRE is shipping, we should do a smoke test using the updated Mac and Windows installers. My suggestions are:

**For both Mac and Windows Installers**
* Upgrade of an existing Liquibase installation.
  * Verify the correct JRE is installed.
  * Verify Liquibase uses the new JRE.
  * Verify the previous JRE is removed from the liquibase installation folder. If this is not the case, ask Dev why not and what a user should do in this situation. If there are manual steps involved, they should be documented.
* Fresh install of Liquibase to a new directory when JAVA_HOME is not configured.
  * Verify the correct JRE is installed
  * Verify Liquibase uses the installed JRE without complaining JAVA_HOME is not configured.

**Comment by MalloD12** [comment]
> @filipelautert , @FBurguer and @MalloD12 - hi! I removed the autocandidate tag from this ticket. As a new version of the JRE is shipping, we should do a smoke test using the updated Mac and Windows installers. My suggestions are:
> 
> **For both Mac and Windows Installers**
> 
> * Upgrade of an existing Liquibase installation.
>   
>   * Verify the correct JRE is installed.
>   * Verify Liquibase uses the new JRE.
>   * Verify the previous JRE is removed from the liquibase installation folder. If this is not the case, ask Dev why not and what a user should do in this situation. If there are manual steps involved, they should be documented.
> * Fresh install of Liquibase to a new directory when JAVA_HOME is not configured.
>   
>   * Verify the correct JRE is installed
>   * Verify Liquibase uses the installed JRE without complaining JAVA_HOME is not configured.

I can do Mac testing if you guys need some help with that.

**Review by XDelphiGrl — APPROVED** [review]
Adoptium, formerly AdoptOpenJDK, released a new long term support (LTS) version of the Java JDK v17. This PR updates the Liquibase installers to use the latest LTS OpenJdk17 version.
* Additional testing is required; see comments.

APPROVED

[Adoptium](https://adoptium.net)

**Comment by FBurguer** [comment]
@MalloD12 Please do! Im doing the windows one

**Comment by XDelphiGrl** [comment]
**Windows**

* Verify Install4J version is 10.0.4. **PASS**
  * The version is printed to the .install4j/installation.log
  * `[INFO] install4j version: 10.0.4 (build 10066)`

* Verify upgrade from 4.18.0 installer is successful. **PASS**

* Verify the PATH prompt is presented when previous Liquibase did not add liquibase to the PATH. **PASS**

* Verify liquibase --version shows correct version after upgrade. PASS
  * `Core: //master/6371/9f2ddf/2023-01-03 14:56+0000, Pro: master/2609/f578a8/2022-12-29T15:13:39Z]`

* Verify a fresh install is successful. **PASS**

* Verify liquibase --version shows correct version for fresh install. **PASS**
  * `Core: //master/6371/9f2ddf/2023-01-03 14:56+0000, Pro: master/2609/f578a8/2022-12-29T15:13:39Z]`

Verify an uninstall using the Install4J uninstaller is successful. **PASS**



**Mac**

* Verify Install4J version is 10.0.4. **PASS**
  * The version is printed to the .install4j/installation.log
  * `[INFO] install4j version: 10.0.4 (build 10066)`

* Verify upgrade from 4.18.0 installer is successful. **PASS**

* Verify liquibase --version shows correct version after upgrade. **PASS**
  *  `Core: //master/6371/9f2ddf/2023-01-03 14:56+0000, Pro: master/2609/f578a8/2022-12-29T15:13:39Z]`

* Verify the PATH prompt is presented when previous Liquibase did not add liquibase to the PATH. **PASS**
  * Path is located in /etc/paths.d; cat liquibase to see path value.
  * `/usr/local/opt/liquibase`

* Verify a fresh install is successful. **PASS**

* Verify liquibase --version shows correct version for fresh install. **PASS**
  * `Core: //master/6371/9f2ddf/2023-01-03 14:56+0000, Pro: master/2609/f578a8/2022-12-29T15:13:39Z]`

Verify an uninstall using the Install4J uninstaller is successful. **PASS**

Everything looks good! Ready to merge!

**Review by XDelphiGrl — APPROVED** [review]

**Pull request merged**
