### PR TITLE
refactor ValidatingVisitor to use factory pattern, error if strict is set and defaults file does not exist (DAT-15920)

### PR DESCRIPTION
**Pull request by StevenMassaro**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Refactor the `ValidatingVisitor` into the factory pattern to support pro usages.

### CODE REVIEW

**Comment by StevenMassaro** [comment]
@filipelautert @suryaaki @wwillard7800 @abrackx 

I would appreciate some opinions on the breaking changes introduced in this PR. Are they problematic? If so, should I see if I can reduce the number of breaking changes (at the cost of making the new interface have a not ideal class name).

**Comment by filipelautert** [comment]
> @filipelautert @suryaaki @wwillard7800 @abrackx
> 
> I would appreciate some opinions on the breaking changes introduced in this PR. Are they problematic? If so, should I see if I can reduce the number of breaking changes (at the cost of making the new interface have a not ideal class name).

@StevenMassaro I searched in our extensions and seems no one overrides or uses it. It makes sense as ValidatingVisitor is at the core of liquibase. Perhaps adding javadoc to the new interface ValidatingVisitor providing directions on how to use it would be enough?

**Comment by wwillard7800** [comment]
> > @filipelautert @suryaaki @wwillard7800 @abrackx
> > I would appreciate some opinions on the breaking changes introduced in this PR. Are they problematic? If so, should I see if I can reduce the number of breaking changes (at the cost of making the new interface have a not ideal class name).
> 
> @StevenMassaro I searched in our extensions and seems no one overrides or uses it. It makes sense as ValidatingVisitor is at the core of liquibase. Perhaps adding javadoc to the new interface ValidatingVisitor providing directions on how to use it would be enough?

I agree with @filipelautert .  I think if we provide instructions on how to get their customized `ValidatingVisitor` into play, then we are good.

**Review by filipelautert — APPROVED** [review]

**Comment by StevenMassaro** [comment]
This approach is not ideal. Closing in favor of a new approach.

**Comment by StevenMassaro** [comment]
@filipelautert Can you rereview this? I changed the implementation to not be a breaking change. This should improve things considerably.

**Review by abrackx — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]
Well, that's an even better approach!

**Pull request merged**
