### PR TITLE
Fixed issued with bundling in shaded jars

### PR DESCRIPTION
**Pull request by isaki**
The implementation in 3.8.0 that searches for build information in the MANIFEST is not compatible with shaded builds as not all shaded builds have the required information. Additionally, there is an unclosed input stream in the current implementation.

The issue manifests as an NPE when `buildInfoValue.equals("UNKNOWN")` after this value was assigned `null` after reading MANIFEST.MF.

This PR addresses these two issues in the following way:

- Wrapped manifest input read with a try-with-resources block.
- Changed default build info to be null and change all checks to be against null; these are null safe.
- Added final null check and returned a default value ("UNKNOWN", set now as a constant).

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-51) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2

### CODE REVIEW

**Comment by Hronom** [comment]
Devs please merge this and release

**Comment by mpe85** [comment]
@nvoxland Is it possible to have this in an upcoming 3.8.1 patch release?

**Comment by SteveDonie** [comment]
This will be fixed in 3.8.1

**Comment by ro-rah** [comment]
Hi @isaki ,

Looks like there is a merge conflict here, would you please resolve and push to PR?

Please also consider adding tests.

Tests can move this to the next state (Conditioning) easier if you include tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)).  Would you be willing to add tests as well?

Thanks,

Ronak

**Comment by isaki** [comment]
I thought this was fixed in 3.8.1 using a different approach. Has this problem resurfaced?

**Comment by ro-rah** [comment]
@isaki that definitely could be the case, I can check and close if that is the case.

**Comment by ro-rah** [comment]
Putting at risklow for the time it takes to confirm this is no longer an issue and close out.

**Comment by ro-rah** [comment]
Closing per @isaki's comments.

**Pull request closed without merging**
