### PR TITLE
Replace old stream creation with java.nio.

### PR DESCRIPTION
**Pull request by arturobernalg**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [X ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ X] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Use new java lib java.nio that  the streams created using Files methods are usually more efficient than those created by stream constructors.

Key differences

https://www.baeldung.com/java-nio-vs-nio-2
https://www.oracle.com/technical-resources/articles/javase/nio.html
https://docs.oracle.com/javase/tutorial/essential/io/fileio.html

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Always nice to modernize the old java code, and hopefully get a bit of a performance improvement. Thanks!

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Review by MalloD12 — APPROVED** [review]
**Approved**.

## Review and testing results:
Thanks @arturobernalg. This PR lgtm, I like these changes. Build and tests have been successfully executed.

### Things to be aware of:
- None

### Things to worry about:
- None

**Review by suryaaki2 — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]
Thanks!

**Review by XDelphiGrl — APPROVED** [review]
PR improves Java-native file manipulation by using the Nio.2 package instead of streams to read and write files.
* Functional and test harness executions passing.
* No additional testing required.

APPROVED

**Pull request merged**
