### PR TITLE
Fixed: generateChangelog creates invalid changelog

### LINKED ISSUE #4482: generateChangelog creates invalid changelog
### Search first

- [X] I searched and no similar issues were found

### Description

Using latest Liquibase compiled from `master` I am running `generateChangelog`, directly followed by `validate`. The result looks like this:
```
Unexpected error running Liquibase: Validierung war nicht erfolgreich:
     894 Changes erfüllten die Anforderungen während der Validierung nicht
          initiallyDeferred is not allowed on asany, dbchangelog.xml::1689061476606-280::Quipsy (generated)
          deferrable is not allowed on asany, dbchangelog.xml::1689061476606-280::Quipsy (generated)
…
```
Apparently `generateChangelog` has a bug here, because it knows that it reads from asany, so it should not create something that is unsupported on asany.

### Steps To Reproduce

```bash
liquibase generateChangelog
liquibase validate
```

### Expected/Desired Behavior

Validation should not find any problems.

### Liquibase Version

master

### Database Vendor & Version

SAP SQL Anywhere 17.0.11

### Liquibase Integration

N/A

### Liquibase Extensions

N/A

### OS and/or Infrastructure Type/Provider

Windows 10 Pro (German)

### Additional Context

N/A

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by mkarg**
## Impact

Fixes #4482 

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

This PR fixes two bugs that are causing #4485:
* SQL Anywhere's JDBC driver incorrectly reports deferrable=true for *missing* `CHECK ON COMMIT`. In fact, this prevents to defer the check to the end of the transaction, but the caller is unable to *override* this decision, hence the driver should report the fact that this is *not deferrable*.
* SQL Anywhere is able to defer foreign keys (not other constraints or checks) using an Asany-specific syntax (`CHECK ON COMMIT`), but the driver said it is unable to defer *at all*.

## Things to be aware of

N/A

## Things to worry about

While this PR is a straightforward solution, a much cleaner one would be to extend Liquibase's internal handling of deferrability: We could introduce more detailed flags, in which cases (PKs, FKs, CHECKs) deferrability is possible, and whether the deferrability is caller-overridable or not. As such a change is rather complex and risky, I have chosen to not go down that way.

## Additional Context

N/A

### CODE REVIEW

**Comment by mkarg** [comment]
@nvoxland Kindly requesting your review. :-)

**Comment by mkarg** [comment]
This is a showstopper at least for SQL Anywhere.

**Review by MalloD12 — APPROVED** [review]
**Approved**.

Thank you, @mkarg for this PR. Code changes looks good to me. Build and all test checks have been successfully executed:

- Integration test has been added to validate this change. 

No concerns from my side.

Thanks,
Daniel.

**Review by filipelautert — APPROVED** [review]

**Review by suryaaki2 — APPROVED** [review]

**Comment by sayaliM0412** [comment]
@mkarg : just FYI, we are making changes to the labels and updating your PR, to test some changes we recently made. Hope you don't mind. Thank you. 

cc: @filipelautert @rberezen

**Review by rberezen — APPROVED** [review]

**Comment by filipelautert** [comment]
Hm...... @mkarg seems this PR was already merged as part of the other ones I merged today 🍕

**Comment by mkarg** [comment]
> Hm...... @mkarg seems this PR was already merged as part of the other ones I merged today 🍕

I'm currently on PTO but I will look into this next week.

**Comment by filipelautert** [comment]
Everything is already merged in other PRs, I just confirmed that.

**Pull request merged**
