### PR TITLE
Fix "Running Changeset: " logs written directly to stdout instead of using the maven logger

### PR DESCRIPTION
**Pull request by mensinda**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

I am categorizing this as a bugfix and not an enhancement, since I don't think that using the default `ConsoleUIService` (which writes to stdout) was intended.
 
## Description

With this PR, the "Running Changeset: " logs are written with the maven logger and not directly to stdout.

## Things to be aware of

Impact on the codebase: minimal

## Things to worry about

Nothing

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**
Thanks for the fix, @mensinda!

The change looks right to me. The UIService is there to adapt to whatever "UI" a particular integration has, and for maven their UI is the logs. 

It may make for some duplicate log messages, but the fix for that is larger and should be handled in a separate PR at some point, likely thinking about UI vs. logs more in general.

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Comment by filipelautert** [comment]
Hello @mensinda - PR https://github.com/liquibase/liquibase/pull/4152 was merge last week and coincidentally it has a method with the same that you used. Could you merge your changes to it? I believe your code would be added around line 633 -: https://github.com/liquibase/liquibase/pull/4152/files#diff-bbe8f062b4c3acf56905d187f674c41575cc99e3b114267095848997859f5926R633 ?
Thanks!

**Comment by mensinda** [comment]
Hello @filipelautert, I have updated the PR.

**Review by filipelautert — APPROVED** [review]
Thanks for the fix @mensinda !

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
This PR improves Liquibase Maven Plugin logging by using the the Maven Log UI instead of stdout for writing some messages. 
* Functional and test harness executions passing. There were some failures in an earlier test harness run, but those are resoleved [here](https://github.com/liquibase/liquibase-test-harness/actions/runs/4996393693).
* No additional testing required.

APPROVED

**Pull request merged**
