### PR TITLE
Enable Custom Changes Directly on Connection

### PR DESCRIPTION
**Pull request by snovak7**
With Enhancement in JIRA CORE-860, this enables custom Driver changes like COPY in Postgres.

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-71) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Liquibase 3.10.2

### CODE REVIEW

**Comment by ro-rah** [comment]
Hi @snovak7 ,

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by ro-rah** [comment]
Updated target branch to the next upcoming 3.10.x

**Comment by ro-rah** [comment]
Risk Med label applied due to no tests included.

**Comment by nvoxland** [comment]
Rather than adding this parameter (and any other people may want) to the interface, we are introducing the Scope object in 4.x to allow extensions and custom changes to the connection and other objects even without API changes.

You can get the current Database via Scope.getCurrentScope().getDatabase() which will have the connection on it. Or, you can pass that into ExecutorService to get the current executor for that database.

**Pull request closed without merging**
