### PR TITLE
CORE-2190: Proposed fix for not applying "modifySql" to remarks statements.

### PR DESCRIPTION
**Pull request by dusiema**
I looked into https://liquibase.jira.com/browse/CORE-2190 and also [commented](https://liquibase.jira.com/browse/CORE-2190?focusedCommentId=23995&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23995) on the issue for what I think could be a solution. 
Here is the pull request with the changes of the description.

### CODE REVIEW

**Comment by devilgate** [comment]
Hi Jens, This fixes the problem for me as far as the `COMMENT ON TABLE...` statements go. But then I hit the same problem with `COMMENT ON COLUMN...` 

The solution, of course, is to add your `skipVisitors` method to `SetColumnRemarks` as well.

I've made that change in my own fork, but I'm pretty new to Git and GitHub, so I'm not quite sure how to get that change to you. And in any case it might be easiest for you to apply the change and include it in this pull request.

**Comment by dusiema** [comment]
Hey, good to hear it's working for you ! 
I'll add this to the `SetColumnRemaks` as well. Should go automatically into the pull request then.

**Comment by dusiema** [comment]
I've added `skipVisitors` to `SetColumnRemarks`as well.

**Comment by nvoxland** [comment]
The fix in this pull request definitely works fine, but I am concerned with how broad the change is. There can more more uses for sqlVisitor than just modifySql, and there are probably times people want the remarks modified as well.

I agree that the main problem is that the modifySql should be in the createTable etc. tags. It was mainly put in changeSet for simplicity of implementation and XSD, but then it does also mean it needs to apply to the whole changeset SQL string, not just some (as it does).

I think the best approach will be to look at a larger improvement to how modifySql works with 4.0 including adding more targetted support in all the change tags.

**Comment by ro-rah** [comment]
Hi @dusiema,

Would you resolve branch conflict for this PR (thanks for adding the tests)?  Here's some guidance on that below:

Thanks for your pull request!

Here’s what happens next:

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) 
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by AlexUmarov** [comment]
Wow,  i have same problem in 2021 O_o
Fix some one this bug

**Comment by nvoxland** [comment]
On further review, I decided this approach isn't going to work. 

I agree that modifySql/append is a bit of blunt instrument, but it's also doing what it says it does and in general we can't safely know what statements the user expects to be modify and which not. 

There is modifySql/replace and modifySql/regExReplace which gives you more control, and perhaps there are better modifySql logic statements we can create as well. But I don't think we can be building logic into some statements to simply not allow modification of them like this.

**Pull request closed without merging**
