### PR TITLE
DAT token issue

### PR DESCRIPTION
**Pull request by MalloD12**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Adding `GITHUB_TOKEN` to the build configuration to make it able to resolve the below build error:

```
Error:  Failed to execute goal on project liquibase-dist: Could not resolve dependencies for project org.liquibase:liquibase-dist:pom:show-summary-output-SNAPSHOT: The following artifacts could not be resolved: org.liquibase:liquibase-core:jar:show-summary-output-SNAPSHOT (absent): Could not find artifact org.liquibase:liquibase-core:jar:show-summary-output-SNAPSHOT in liquibase (https://maven.pkg.github.com/liquibase/liquibase) ->
```

### CODE REVIEW

**Comment by StevenMassaro** [comment]
What problem is this solving?

**Comment by sayaliM0412** [comment]
@MalloD12 : can you just rename your original branch to DAT-* and run it again

**Comment by sayaliM0412** [comment]
> What problem is this solving?

https://liquibase.slack.com/archives/CK9JJEENB/p1691006468171639?thread_ts=1691002232.742739&cid=CK9JJEENB

**Comment by StevenMassaro** [comment]
> > What problem is this solving?
> 
> https://liquibase.slack.com/archives/CK9JJEENB/p1691006468171639?thread_ts=1691002232.742739&cid=CK9JJEENB

This PR will not fix the build failure that you linked. The build failure that you linked occurred because the branch name did not have `DAT-` in it, so this workflow never ran: https://github.com/liquibase/liquibase/blob/master/.github/workflows/build-branch.yml

Because that workflow never ran, the artifacts were not deployed to GPM for his branch.

**Review by StevenMassaro — CHANGES_REQUESTED** [review]
This is not needed

**Comment by sayaliM0412** [comment]
> > 
> 
> Ohh I didn't know it was failing because the branch name was not containing DAT.
> 
> @sayaliM0412 would these changes help for contributors who don't add `DAT-` as the prefix of their branch names?

I added a fix to my existing ticket -> https://github.com/liquibase/liquibase/pull/4587/commits/97116bbb1084fdcb196b7b090619a6e1fc08ffb1

**Comment by sayaliM0412** [comment]
fix -> https://github.com/liquibase/liquibase/pull/4587/commits/97116bbb1084fdcb196b7b090619a6e1fc08ffb1

**Pull request closed without merging**
