### PR TITLE
Improve dropAllForeignKeyConstraints performance

### LINKED ISSUE #1571: dropAllForeignKeyConstraints performance/errors in liquibase 3.10.3, works perfect in liquibase 3.4.2
## Environment
**Liquibase Version**: works fine on 3.4.2, broken on 3.10.3

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: MySql 5.6

**Operating System Type & Version**: centos 7

## Description
In 3.10.3 a dropAllForeignKeyConstraints change is incredibly slow (168087ms vs 55ms) and produces errors:

`14:52:17.216 INFO  [liquibase.util.SqlUtil]: Unknown default value: value 'XXX4' type SET('XXX1', 'XXX2', 'XXX3', 'XXX4') (SET('XXX1', 'XXX2', 'XXX3', 'XXX4')). Calling it a function so it's not additionally quoted`

The same command takes milliseconds to run on 3.4.2

## Steps To Reproduce
```
<changeSet id="1" author="XXX" context="XXX">
        <comment>Remove constrains</comment>
        <dropAllForeignKeyConstraints baseTableName="XXX"/>
    </changeSet>
```

Additionally in the general log i can see that liquibase is evaluating the whole server for FKs, with thousands of queries like this one:

```
SELECT A.REFERENCED_TABLE_SCHEMA AS PKTABLE_CAT,NULL AS PKTABLE_SCHEM,A.REFERENCED_TABLE_NAME AS PKTABLE_NAME,A.REFERENCED_COLUMN_NAME AS PKCOLUMN_NAME,A.TABLE_SCHEMA AS FKTABLE_CAT,NULL AS FKTABLE_SCHEM,A.TABLE_NAME AS FKTABLE_NAME, A.COLUMN_NAME AS FKCOLUMN_NAME, A.ORDINAL_POSITION AS KEY_SEQ,CASE WHEN R.UPDATE_RULE='CASCADE' THEN 0 WHEN R.UPDATE_RULE='SET NULL' THEN 2 WHEN R.UPDATE_RULE='SET DEFAULT' THEN 4 WHEN R.UPDATE_RULE='RESTRICT' THEN 1 WHEN R.UPDATE_RULE='NO ACTION' THEN 3 ELSE 3 END  AS UPDATE_RULE,CASE WHEN R.DELETE_RULE='CASCADE' THEN 0 WHEN R.DELETE_RULE='SET NULL' THEN 2 WHEN R.DELETE_RULE='SET DEFAULT' THEN 4 WHEN R.DELETE_RULE='RESTRICT' THEN 1 WHEN R.DELETE_RULE='NO ACTION' THEN 3 ELSE 3 END  AS DELETE_RULE,A.CONSTRAINT_NAME AS FK_NAME,(SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = A.REFERENCED_TABLE_SCHEMA AND TABLE_NAME = A.REFERENCED_TABLE_NAME AND CONSTRAINT_TYPE IN ('UNIQUE','PRIMARY KEY') LIMIT 1) AS PK_NAME,7 AS DEFERRABILITY FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE A JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS B USING (CONSTRAINT_NAME, TABLE_NAME) JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS R ON (R.CONSTRAINT_NAME = B.CONSTRAINT_NAME AND R.TABLE_NAME = B.TABLE_NAME AND R.CONSTRAINT_SCHEMA = B.TABLE_SCHEMA) WHERE B.CONSTRAINT_TYPE = 'FOREIGN KEY' AND A.TABLE_SCHEMA LIKE 'XXX' AND A.TABLE_NAME='XXX' AND A.REFERENCED_TABLE_SCHEMA IS NOT NULL ORDER BY A.REFERENCED_TABLE_SCHEMA, A.REFERENCED_TABLE_NAME, A.ORDINAL_POSITION
```

### LINKED ISSUE #2154: dropAllForeignKeyConstraint performance problems
## Environment

**Liquibase Version**: 4.4.2

**Liquibase Integration & Version**: Java

**Liquibase Extension(s) & Version**: -

**Database Vendor & Version**: PostgreSQL 12.6

**Operating System Type & Version**: RHEL, but happens as well on Windows 10 and centos

## Description

The `dropAllForeignKeyConstraints` change performs poorly for bigger database schemas in PostgreSQL databases, because more or less the complete schema metadata is loaded for finding the names of the foreign key constraints of a single table.

## Steps To Reproduce

You can use this changelog file to see the execution time difference between the two variants of dropping foreign key constraints.  The actual performance impact depends on the size of the schema.

[db.foreignKeyDeletionTest.txt](https://github.com/liquibase/liquibase/files/7395631/db.foreignKeyDeletionTest.txt)
_(Note: The file should be an XML changelog, but Github won't let me upload XML files here)_

## Actual Behavior

Using the `dropAllForeignKeyConstraints` is significantly slower than using several explicit `dropForeignKeyConstraint` changes.

When querying the database for the names of all foreign key constraints of the specified table, the complete schema information is loaded (all tables, foreign keys, primary keys, sequences, views, indizes etc.). Therefore the performance severly deteriorates for bigger schemas.

> 2021-10-22 08:37:26,586 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) ChangeSet database/db.core-test-20.xml::dropTestForeignKeysFast-1634818033::rsp ran successfully in 16ms

vs

> 2021-10-22 08:37:27,684 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) ChangeSet database/db.core-test-20.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 1093ms

Here is the log output for a local execution of the provided reproducer changeset with a local database containing a relatively small schema (~ 30 tables).

> 2021-10-22 08:37:26,528 - FINE  [liquibase.changelog] (ServerService Thread Pool -- 58) Running Changeset:database/db.core-test-20.xml::setupTestResources-1634817987::rsp
2021-10-22 08:37:26,533 - FINE  [liquibase.changelog] (ServerService Thread Pool -- 58) Reading ChangeSet: database/db.core-test-20.xml::setupTestResources-1634817987::rsp
2021-10-22 08:37:26,539 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Table otherTable created
2021-10-22 08:37:26,549 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Table foreignKeyDeletionTest01 created
2021-10-22 08:37:26,557 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Table foreignKeyDeletionTest02 created
2021-10-22 08:37:26,561 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) ChangeSet database/db.core-test-20.xml::setupTestResources-1634817987::rsp ran successfully in 33ms
2021-10-22 08:37:26,569 - FINE  [liquibase.changelog] (ServerService Thread Pool -- 58) Running Changeset:database/db.core-test-20.xml::dropTestForeignKeysFast-1634818033::rsp
2021-10-22 08:37:26,571 - FINE  [liquibase.changelog] (ServerService Thread Pool -- 58) Reading ChangeSet: database/db.core-test-20.xml::dropTestForeignKeysFast-1634818033::rsp
2021-10-22 08:37:26,574 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Foreign key FK_foreignKeyDeletionTest01_01 dropped
2021-10-22 08:37:26,577 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Foreign key FK_foreignKeyDeletionTest01_02 dropped
2021-10-22 08:37:26,579 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Foreign key FK_foreignKeyDeletionTest01_03 dropped
2021-10-22 08:37:26,581 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Foreign key FK_foreignKeyDeletionTest01_04 dropped
2021-10-22 08:37:26,583 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Foreign key FK_foreignKeyDeletionTest01_05 dropped
**2021-10-22 08:37:26,586 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) ChangeSet database/db.core-test-20.xml::dropTestForeignKeysFast-1634818033::rsp ran successfully in 16ms**
2021-10-22 08:37:26,590 - FINE  [liquibase.changelog] (ServerService Thread Pool -- 58) Running Changeset:database/db.core-test-20.xml::dropTestForeignKeysSlow-1634818754::rsp
2021-10-22 08:37:26,592 - FINE  [liquibase.changelog] (ServerService Thread Pool -- 58) Reading ChangeSet: database/db.core-test-20.xml::dropTestForeignKeysSlow-1634818754::rsp
2021-10-22 08:37:27,673 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Foreign keys on base table foreignKeyDeletionTest02 dropped
**2021-10-22 08:37:27,684 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) ChangeSet database/db.core-test-20.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 1093ms**
2021-10-22 08:37:27,688 - FINE  [liquibase.changelog] (ServerService Thread Pool -- 58) Running Changeset:database/db.core-test-20.xml::cleanupTestResources-1634819123::rsp
2021-10-22 08:37:27,690 - FINE  [liquibase.changelog] (ServerService Thread Pool -- 58) Reading ChangeSet: database/db.core-test-20.xml::cleanupTestResources-1634819123::rsp
2021-10-22 08:37:27,692 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Table foreignKeyDeletionTest01 dropped
2021-10-22 08:37:27,693 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Table foreignKeyDeletionTest02 dropped
2021-10-22 08:37:27,696 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) Table otherTable dropped
2021-10-22 08:37:27,698 - INFO  [liquibase.changelog] (ServerService Thread Pool -- 58) ChangeSet database/db.core-test-20.xml::cleanupTestResources-1634819123::rsp ran successfully in 10ms

## Expected/Desired Behavior

The `dropAllForeignKeyConstraints` change should not load the complete schema metadata for finding the names of the foreign key constraints of a single table. 
In the same way, the execution time of the change should not significantly increase with the amount of objects in the DB schema.

## Additional Context
There is another bug which could be related to this one => #1571 
I commented on it, but decided to create a separete one since we are using a different database and Liquibase version.

Also, I think I know why the change misbehaves, and I might be able to provide a PR for fixing it

### PR DESCRIPTION
**Pull request by Spindl**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

The dropAllForeignKeyConstraints change performs poorly for bigger database schemas in PostgreSQL databases, because more or less the complete schema metadata is loaded for finding the names of the foreign key constraints of a single table. Control was create but wasn't used.

Fixes #2154 
Fixes #1571 

## Things to be aware of

- Test coverage on DropAllForeignKeyConstraintsChangeTest .

## Things to worry about

- none

### CODE REVIEW

**Comment by molivasdat** [comment]
Hi @Spindl Thanks for the issue and PR creation.  We will add this to the list of issues and PRs that we are processing.
A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or [Test Harness Tests](https://github.com/liquibase/liquibase-test-harness/pulls)
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by filipelautert** [comment]
Hi @Spindl - so from what I see this fall under the "bug fix" section right? Control was create but wasn't used.
Also about #1571, seems it is the same issue. So we can add mark it as fixing this one too.
I did some runs with your text data and it really speeds up things:

	Original:
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 489ms
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 523ms
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 451ms
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 467ms
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 470ms
	 
	 
	 Fix:
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 278ms
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 303ms
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 252ms
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 228ms
	 db.foreignKeyDeletionTest.xml::dropTestForeignKeysSlow-1634818754::rsp ran successfully in 241ms


Also there is test coverage on DropAllForeignKeyConstraintsChangeTest .

Thanks!

**Review by filipelautert — APPROVED** [review]
Simple fix that improves performance as shown in my previous comment. Also there are test covering it.

**Review by XDelphiGrl — APPROVED** [review]
This PR fixes a Postgres performance bug during foreign key drops. The fix sets a `snapshotControl` objects to ensure the entire schema metadata is not scanned to find matching foreign keys. 
* No additional testing required.

APPROVED

**Review by nvoxland — APPROVED** [review]

**Review by suryaaki2 — APPROVED** [review]

**Pull request merged**
