### PR TITLE
Fix DB-Doc generation of Unique Constraints for Sybase ASE database.

### PR DESCRIPTION
**Pull request by crenan**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description
Fix DB-Doc generation of Unique Constraints for Sybase ASE databases.
For Sybase ASE there wasn't a specific code to return unique constraints (constraint name + column name) in class _UniqueConstraintSnapshotGenerator_ and because of that the execute code was the default one, which generates the follow error:

```
Unexpected error running Liquibase: Error executing SQL select CONSTRAINT_NAME, COLUMN_LIST as COLUMN_NAME, constraint_schema as CONSTRAINT_CONTAINER from information_schema.constraints where constraint_type='UNIQUE' and constraint_catalog='XXXXX' and constraint_schema='dbo' and table_name='XXXXX' and constraint_name='XXXXX': information_schema.constraints not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output).
```

## Things to be aware of

Some unique constraints may not return a column name (the result data of SQL may return `<null>` for the _column name_ column). This is propably because of lack of constraints information (use of _sp_foreignkey_ or _sp_primarykey_) for a table.

## Things to worry about

There isn't an unit test for the class.

## Additional Context

This fix is for the DB-Doc command.

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Changes make sense, thanks!

Questions I have:
- None

Potential risks:
- None. Change is isolated to sybase ASE

What could make the full review difficult:
- Nothing

**Comment by MalloD12** [comment]
@crenan thank you for putting these changes in place. The code looks good to me. The only comment I have here is regarding testing. I think it would be nice to add some test/s to validate this change. I've been trying yesterday to manually test this change as well as looking for some automated test I can use to validate this PR, but sadly I couldn't find any existent infra to test against Sybase ASE. I think it would be nice if we can add some integration test for this, if you are keen to do it I can either share some example with you or I can create a test skeleton and you tweak it/finish it as needed, or if you feel more comfortable and think a manual test would be good enough I'm ok with that too. 

Thanks,
Daniel.

**Comment by crenan** [comment]
@MalloD12 I recently switch jobs and no longer have access to the Sybase ASE DB server that I used for test these changes, but if you can compile a build to test with these changes, I sure can send to my friends in the old job and they can do a manual test and report back.

Besides that, I'm unable to reproduce the environment that I had there with the Sybase ASE test version, but I can try to improve any kind of integration test that you make.

Kind regards

**Comment by MalloD12** [comment]
> Details

Hi @crenan!

Oh, I see.  I would appreciate it if you guys can get the `liquibase-artifacts` from [here](https://github.com/liquibase/liquibase/suites/11689053564/artifacts/607819315) and manually test with it. If I find some more time during this sprint, I can try creating that skeleton for you so you guys can then continue with it. 

Thanks,
Daniel.

**Review by MalloD12 — COMMENTED** [review]
Code changes looks good to me. But before approving it we will wait for @crenan feedback to see if these changes are working or not against a Sybase DB. Artifacts link provided to be forward to the team for manual check.

**Comment by MalloD12** [comment]
@filipelautert as the code looks ok and all checks have run successfully I think we can move forward with this one, and if @crenan can get some feedback later from his friends we can still add that testing output here. How does it sound to you?

**Review by filipelautert — APPROVED** [review]

**Pull request merged**
