### PR TITLE
Normalize path using static function for Strings rather than Path.nor…

### PR DESCRIPTION
**Pull request by ffffionn**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Use the `DatabaseChangeLog.normalizePath(string)` function instead of `Path.normalize` to normalize the string to avoid generating a different path to previous versions. Reverses https://github.com/liquibase/liquibase/commit/351cbbc41c1f69d311c41b4bd74761c6ef979c60

Fixes: https://github.com/liquibase/liquibase/issues/4412

### CODE REVIEW

**Comment by MalloD12** [comment]
Hi @ffffionn,

I think the changes include here are ok, but would you mind adding some unit tests to validate them?

Thanks,
Daniel.

**Comment by ffffionn** [comment]
@MalloD12  good point, added

**Review by MalloD12 — APPROVED** [review]
**Approved**.

Thank you, @ffffionn! This looks good to me, thanks for adding a new unit test to validate your change.

**Comment by ffffionn** [comment]
and thanks for the change for the deprecated method - must have overlooked that!

**Review by filipelautert — APPROVED** [review]
Good catch!

**Review by rberezen — APPROVED** [review]

**Review by tati-qalified — APPROVED** [review]

**Comment by ffffionn** [comment]
Just wondering what we are waiting on for the merge. I'm eager to see this in the next release to use the latest version.

**Comment by filipelautert** [comment]
@ffffionn our build process was being refactored so we were holding merges for a while. I'll give it a last spin and merge it .

**Pull request merged**
