### PR TITLE
Fix getSerializableFieldValue when dealing with rollback object

### LINKED ISSUE #2084: YamlChangelogSerializer produces wrongly formed changelog if changeset contains rollback changes (Yaml and JSON)
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: liquibase-core lib 4.4.3

**Database Vendor & Version**: MySQL 8.0

**Operating System Type & Version**: Ubuntu 20.04

## Description

The `YamlChangelogSerializer` produces  a wrongly formed changelog file if a changeset contains `RollbackChanges`. 

## Steps To Reproduce
Running the following Java Code:
```Java
        DatabaseChangeLog changeLog = new DatabaseChangeLog();
        ChangeSet changeSet = new ChangeSet(UUID.randomUUID().toString(), "author", false, false, "", "test", "mysql", changeLog);
        changeSet.addRollbackChange(new EmptyChange());
        changeLog.addChangeSet(changeSet);

        YamlChangeLogSerializer serializer = new YamlChangeLogSerializer();
        OutputStream outputStream = new FileOutputStream("changelog-with-rollback.yaml");
        serializer.write(changeLog.getChangeSets(), outputStream);
        outputStream.close();
```
## Actual Behavior
Produces a changelog file with the following content:
```yaml
databaseChangeLog:
- changeSet:
    id: 96ad97c9-7981-4011-9a41-a9bba86f9c27
    author: author
    context: test
    dbms: mysql
    objectQuotingStrategy: LEGACY
    rollback:
      rollback:
        changes:
        - empty: {}
```
## Expected/Desired Behavior
Looking closely to the rollback section I don't expect the `rollback` statement twice and neither the `changes` statement inside. So in my opinion a well formed changelog should look like this:
```yaml
databaseChangeLog:
- changeSet:
    id: 96ad97c9-7981-4011-9a41-a9bba86f9c27
    author: author
    context: test
    dbms: mysql
    objectQuotingStrategy: LEGACY
    rollback:
      - empty: {}
```
## Additional Context
in a more complex example I created multiple changelogs and include them together in one changelog file. One of the child changelogs looks like this:
```yaml
databaseChangeLog:
- changeSet:
    id: 5e70305c-17da-481b-b247-1aab3ec338ce
    author: author
    context: test
    dbms: mysql
    objectQuotingStrategy: LEGACY
    rollback:
      rollback:
        changes:
        - dropColumn:
            columnName: paymentMethod
            tableName: customers
    changes:
    - addColumn:
        columns:
        - column:
            name: paymentMethod
            type: varchar(50)
        tableName: customers
```
After parsing it and serializing it again I ended up with this changelog:
```yaml
databaseChangeLog:
- changeSet:
    id: 5e70305c-17da-481b-b247-1aab3ec338ce
    author: author
    context: test
    dbms: mysql
    objectQuotingStrategy: LEGACY
    rollback:
      rollback:
        changes:
        - empty: {}
    changes:
    - addColumn:
        columns:
        - column:
            name: paymentMethod
            type: varchar(50)
        tableName: customers
```
where you can see, that the rollback section is completely wrong, because it parsed the already wrongly serialized rollback section as an empty change.

### PR DESCRIPTION
**Pull request by MalloD12**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description
A fix to Rollback object serialization that was duplicating the rollback key has been implemented.

Fixes #2084

### CODE REVIEW

**Review by filipelautert — COMMENTED** [review]
Thanks for the fix @MalloD12 ! Could you also add a test to validate that the xml format still working fine too?

**Comment by MalloD12** [comment]
> Thanks for the fix @MalloD12 ! Could you also add a test to validate that the xml format still working fine too?

Sure, I'll do that @filipelautert.

Thanks,
Daniel.

**Review by filipelautert — APPROVED** [review]

**Comment by MalloD12** [comment]
It's fixed now. Thanks, @rberezen!

**Comment by rberezen** [comment]
> It's fixed now. Thanks, @rberezen!

Thank you!

**Review by rberezen — APPROVED** [review]

**Pull request merged**
