### PR TITLE
Decode encoded URLs from Spring resources

### LINKED ISSUE #5155: Spring resource URLs are not decoded
### Search first

- [X] I searched and no similar issues were found

### Description

Using liquibase as a standalone program works with spaces in the filenames ( for changelogs ). However it does not work for files with spaces in their filenames when using it integrated with Spring.

Liquibase internally uses the following class for the integration with Spring: [FileSystemResource](https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/io/FileSystemResource.java).

More specifically it uses the following method getURL on the resource.
This method did not encode spaces in old versions of Spring which is why the integration with liquibase was working.

This behaviour has been modified a long time ago after this issue: https://github.com/spring-projects/spring-framework/issues/8580

Liquibase did not adapt the code to decode this URL, hence this is blocking for legacy projects that have spaces in their filenames. Although I agree that spaces in file name should always be avoided, I do think that this should not be a blocking issue.

### Steps To Reproduce

Add one changelog with a space in the filename and try to run liquibase with Spring. 
The easiest way to reproduce this is to generate a Spring Boot project with the minimal required dependencies and one changelog with the space.

### Expected/Desired Behavior

I expect that after the fix it is possible to run liquibase with Spring Boot even for files with spaces in their filenames.

### Liquibase Version

_No response_

### Database Vendor & Version

All

### Liquibase Integration

Spring Boot

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

All

### Additional Context

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by Ayrossi**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Things to worry about

None.

Fixes #5155

### CODE REVIEW

**Comment by Ayrossi** [comment]
@filipelautert Sorry, I do not know how to add the label

**Comment by filipelautert** [comment]
no problems @Ayrossi , I think only someone from the project has permission to do it. Done!

**Comment by Ayrossi** [comment]
Added commit to fix sonar's detected code smell

**Comment by Ayrossi** [comment]
Hi @filipelautert 

I see that the check has failed for CodeQL, however I am not sure if that is something related to my changes or something that I can fix. Can you verify? Thanks!

**Comment by filipelautert** [comment]
hello @Ayrossi - no worries, codeql is currently failing for contributed PR's. We need to fix it someday...

**Review by filipelautert — APPROVED** [review]

**Review by tati-qalified — APPROVED** [review]

**Review by rberezen — APPROVED** [review]

**Pull request merged**
