### PR TITLE
Added quotes around ${JAVA_PATH} in liquibase shell script to avoid spaces in path issues

### PR DESCRIPTION
**Pull request by szandany**
**Branch: Liquibase/master**

Added quotes around ${JAVA_PATH} in line 77 to avoid issues when there are spaces in the JAVA_PATH when using Emulators like "Git bash for Windows".

This fix will prevent having issues with spaces in JAVA_PATH.  For example: when running Liquibase commands in Windows with Linux/Unix like Emulators such as: "Git bash for Windows" or "Minimalist GNU for Windows" with preexisting spaces in the JAVA_PATH.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-173) by [Unito](https://www.unito.io/learn-more)
┆Fix Versions: Community 4.x

### CODE REVIEW

**Comment by SteveDonie** [comment]
Thanks for your pull request! The team will review this and add comments with a status update soon.

Can you supply details about how this has been tested so far?

**Comment by szandany** [comment]
> how this has been tested so far?
I tested this on a Windows machine that already has Liquibase installed and the JAVA_PATH set with spaces in the path.  For example, in CMD: `which java /c/Program Files (x86)/Common Files/Oracle/Java/javapath/java` 
Then, I ran in git bash: `liquibase --version` and got the following error:
`/c/apps/liquibase/liquibase: line 77: C:\Program: No such file or directory`
After applying the fix in this pull request (Added quotes around ${JAVA_PATH} in liquibase shell script), I got it resolved.

**Comment by mariochampion** [comment]
hey @szandany -- thanks for the update. Do you want this PR into master or 3.8.x?

**Comment by szandany** [comment]
> hey @szandany -- thanks for the update. Do you want this PR into master or 3.8.x?
No problem.  I'm not sure what is the best choice here (master or 3.8.x).

**Comment by mariochampion** [comment]
Well, the next 3.8.x release will come before the next Master release (altho likely by only a few weeks.) If you redirect this to a 3.8.x branch, we can see if it makes it in before next releases heads into final testing. 

I would choose 3.8.x, but up to you @szandany

**Pull request merged**
