### PR TITLE
Simplified expressions, removed redundant expressions, fixed javadocs

### PR DESCRIPTION
**Pull request by anton-erofeev**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by MalloD12 — APPROVED** [review]
**Approved**.

Even though there is no description of the changes done it is mostly what the PR summary says removing unused code, redundant expressions, fixed javadocs, unused imports, etc. No business logic code was made. 

Build and tests successfully executed (except functional tests which are failing due to un-related reasons).

**Review by filipelautert — APPROVED** [review]

**Comment by rberezen** [comment]
@anton-erofeev Could you kindly help resolve the conflict in the pull request?

**Review by suryaaki2 — APPROVED** [review]

**Comment by rberezen** [comment]
@anton-erofeev If you could spare a moment, your help in addressing the conflict within the pull request would be greatly appreciated. Thank you.

**Comment by filipelautert** [comment]
@MalloD12 could you resolve the conflicts here and then ping @rberezen ?

**Comment by MalloD12** [comment]
> @MalloD12 could you resolve the conflicts here and then ping @rberezen ?

Merge conflicts resolved.

cc: @rberezen

**Pull request merged**
