### PR TITLE
add support for the TRAN keyword (T-SQL)

### LINKED ISSUE #4098: The T-SQL keyword "TRAN" is not supported in liquibase splitstatmenets mssql
### Search first

- [X] I searched and no similar issues were found

### Description

Context: I have a Changeset with the endDelimiter:GO. (The endDelimiter does not really matter...)

The changeset creates a stored procedure, inside the procedure I create a transaction with "BEGIN TRAN".

With the "BEGIN TRAN" keyword liquibase does not detect the endDelimiter properly and does not split the Statment via the endDelimiter.

Therefore it tries to execute the whole script as one command. Since GO is not really a T-SQL command the changesets fails.  

## Workaround

Don't use the TRAN keyword, use TRANSACTION. 

### Steps To Reproduce

execute changeset on an "empty" sql-server database called test:

```sql
--liquibase formatted sql
--changeset a:1 
create table test.dbo.person (
    id int primary key not null,
    name varchar(50) not null,
    address1 varchar(50),
    address2 varchar(50),
    city varchar(30)
)
--rollback DROP TABLE person;

--changeset a:2 runOnChange:true endDelimiter:GO
CREATE OR ALTER PROCEDURE dbo.Test as 
BEGIN TRAN  
    TRUNCATE TABLE test.dbo.person;

    INSERT INTO test.dbo.person(id, name)    
    VALUES(1, 'Name1');
COMMIT

    INSERT INTO test.dbo.person(id, name)    
    VALUES(2, 'Name2');
GO

--some other stuff, that should be executed in the changeset which creates the procedure....
INSERT INTO test.dbo.person(id, name)    
VALUES(3, 'N');
```

### Expected/Desired Behavior

The changeset gets executed successfully. 

### Liquibase Version

4.20.0

### Database Vendor & Version

SQL-Server 2022

### Liquibase Integration

CLI

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

Ubuntu

## Log output 
```
Starting Liquibase at 07:39:09 (version 4.20.0 #7837 built at 2023-03-07 16:25+0000)
Liquibase Version: 4.20.0
Liquibase Open Source 4.20.0 by Liquibase
Running Changeset: example-changelog.sql::1::a
Running Changeset: example-changelog.sql::2::a

Unexpected error running Liquibase: Migration failed for changeset example-changelog.sql::2::a:
     Reason: liquibase.exception.DatabaseException: Incorrect syntax near 'GO'. [Failed SQL: (102) CREATE OR ALTER PROCEDURE dbo.Test as 
BEGIN TRAN  
    TRUNCATE TABLE test.dbo.person;

    INSERT INTO test.dbo.person(id, name)    
    VALUES(1, 'Name1');
COMMIT

    INSERT INTO test.dbo.person(id, name)    
    VALUES(2, 'Name2');
GO


INSERT INTO test.dbo.person(id, name)    
VALUES(3, 'N');]

For more information, please use the --log-level flag
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by AlexGruebel**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

This PR fixes #4098. It add support for the T-SQL Keyword "TRAN".

Currently liquibase splits sql statements only, if there are not between a "BEGIN" and "END" statement. Since most database start transactions with the "BEGIN TRANSACTION" command, the StringUtil class which is responsible for splitting statements, does ignore the "BEGIN" keyword if it is followed by the keyword "TRANSACTION". 

T-SQL (the sql dialect from mssql-server) also supports a shorter version for "TRANSACTION" => "TRAN". The current version of liquibase does not check for keyword "TRAN". This pull request adds support for this keyword. 

## Things to be aware of

- I just added the new keyword "TRAN" to the if statement, with intention to change as little as possible 

## Things to worry about
- the current code also supports the keyword "TRANS", I don't know any database which supports the keyword "TRANS" to start an transaction, maybe this was just a typo and can be removed. But I don't know maybe there is a reason for this:).

### CODE REVIEW

**Comment by nvoxland** [comment]
Initial review:

Change is what I'd expect. Thanks!

Things to be aware of:
- Nothing

Things to worry about:
- Nothing

**Review by filipelautert — APPROVED** [review]
Thanks for the fix @AlexGruebel

**Review by suryaaki2 — APPROVED** [review]

**Comment by XDelphiGrl** [comment]
Rerunning test harness here: [https://github.com/liquibase/liquibase-test-harness/actions/runs/4995573646](https://github.com/liquibase/liquibase-test-harness/actions/runs/4995573646)

**Review by XDelphiGrl — APPROVED** [review]
SQL Server supports the keyword `TRANSACTION` and the shorter variant, `TRAN`. This PR extends Liquibase to recognize `TRAN` and correctly apply delimiters. This prevents SQL execution errors due to improper "chunking" of SQL statements.
* New integration test added with `TRAN`.
* Functional and test harness executions passing.
* No additional testing required.

APPROVED

**Pull request merged**
