### PR TITLE
feat: FastCheck refactoring

### LINKED ISSUE #5784: AbstractUpdateCommandStep.upToDateFastCheck global cache does not detect DB recreation
### Search first

- [X] I searched and no similar issues were found

### Description

Hi,

We have a relatively unique case where we have a custom multi tenant datasource and we run liquibase when the tenant logs in.
We create and configure SpringLiquibase and invoke afterPropertiesSet.

Our QA jobs are recreating the DB between runs and the issue is that Liquibase is not applied again.

From what I understand, this is because Liquibase uses an internal cache. 
There is a singleton CommandFactory which holds an instance of all CommandSteps (including UpdateCommandStep)
https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/command/CommandFactory.java#L244

The AbstractUpdateCommandStep holds an upToDateFastCheck map that remembers if Liquibase was already applied (on that JDBC URL with these changesets, etc.):
https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/java/liquibase/command/core/AbstractUpdateCommandStep.java#L89

This cache exists as long as JVM is up.

Liquibase detects that the dbchangelog tables do not exist and recreate them. I believe this is the place to also invalidate all the upToDateFastCheck cache entries that are relevant to that URL.

### Steps To Reproduce

Attached a sample project.
1. Run failsOnSecondRun test once so it will create dbchangelog with checksums - it should pass.
2. Run failsOnSecondRun test again and it will fail.

[upToDateFastCheck.zip](https://github.com/liquibase/liquibase/files/14924175/upToDateFastCheck.zip)

### Expected/Desired Behavior

If Liquibase understands that databasechangelog tables are missing and creates them, it should also invalidate all the upToDateFastCheck cache entries that are relevant to that URL.

### Liquibase Version

4.24.0 and 4.26.0

### Database Vendor & Version

PostgreSQL

### Liquibase Integration

Custom spring boot

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

Ubuntu

### Additional Context

_No response_

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by filipelautert**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [X] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Fixes #5784 

Decouples fast check from AbstractUpdateCommandStep by moving it to a new Singleton service as it is becoming too big and confusing to be just a method

### CODE REVIEW

**Comment by filipelautert** [comment]
@MalloD12 do we still working on this one?

**Comment by MalloD12** [comment]
> @MalloD12 do we still working on this one?

I was talking a few mins ago with @tati-qalified about it. We need to see a way to add the test provided by the reporter of the issue, but that test is only working on Spring.

**Comment by rberezen** [comment]
@filipelautert @MalloD12 could you please check test failure? 
https://github.com/liquibase/liquibase/actions/runs/9518324183/job/26239445986?pr=5925

**Comment by filipelautert** [comment]
> @filipelautert @MalloD12 could you please check test failure? https://github.com/liquibase/liquibase/actions/runs/9518324183/job/26239445986?pr=5925

@rberezen whow, that's a real failure. Let me check.

**Comment by filipelautert** [comment]
> > @filipelautert @MalloD12 could you please check test failure? https://github.com/liquibase/liquibase/actions/runs/9518324183/job/26239445986?pr=5925
> 
> @rberezen whow, that's a real failure. Let me check.

@rberezen nah, just a broken test. Fixed!

**Review by rberezen — APPROVED** [review]

**Review by MalloD12 — APPROVED** [review]
Code changes look good to me. Thank you, @filipelautert!

**Pull request merged**
