### PR TITLE
Prevent Executors collision due to hash used as a Map's key part

### PR DESCRIPTION
**Pull request by Dasiu**
Addresses https://github.com/liquibase/liquibase/issues/3492

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description
Due to Database's hash code being included explicitly in HashMap's key. Hash collision could lead to different Database object being returned then the intended one.

No test covering this issue. I can not see a way to test this specific issue in robust and fast way.

## Things to be aware of

N/A

## Things to worry about

N/A

### CODE REVIEW

**Comment by Dasiu** [comment]
Could someone permit the Build? :)

**Comment by filipelautert** [comment]
Hello @Dasiu - sure, it's fine to build :)
Our open source team review it shortly and prioritize it. Thanks!

**Comment by Dasiu** [comment]
I see failed tests, changed to draft for now. Does each new build need to be accepted? I want to run tests for my new commit (and I can not do it locally) to verify my hypothesis. I suspect `Database`'s identity hash actually matters. In my first commit I used `Database#hashCode`. For `AbstractJdbcDatabase` it delegates to underlying `connection` and maybe that's the reason of failed tests / changed behavior.

**Comment by filipelautert** [comment]
Hi @Dasiu - yes, our current set up just runs builds for external branchs after someone approves it for security reasons. 
Maybe @nvoxland can give us a hint about the issue you are facing?

**Comment by Dasiu** [comment]
Thanks, looks like my hypothesis from my comment above is correct - tests are green. Could next build be accepted?

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Good to see the tests passing, thanks for working through them. The changes are isolated to Executor selection handling and not changing any external APIs.

Questions I have:
- None

Potential risks:
- None

What could make the full review difficult:
- Nothing

**Comment by Dasiu** [comment]
Would someone be able to make the full review soon? :)

**Review by filipelautert — APPROVED** [review]
All fine, changes the HashMap key to be more consistent in multi environment platforms. Thanks @Dasiu !

**Review by XDelphiGrl — APPROVED** [review]
This PR addresses a sneaky, intermittent concurrency bug in the ExecutorService class. PR author @Dasiu did some nice troubleshooting and analysis of log output to determine the root cause. The fix adds new safeguards against hash collisions during concurrent Liquibase executions.
* Functional and test harness executions passing.
* No new tests added but the code adds new, clean safegaurds that were not in place before.
* No additional testing required.

APPROVED

**Review by suryaaki2 — APPROVED** [review]

**Pull request merged**
