### PR TITLE
Moved saved_state/compareGenerateSql.. directory from java source to resources bundle

### LINKED ISSUE #5335: untracked files in `liquibase-standard/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets` after tests
### Search first

- [X] I searched and no similar issues were found

### Description

after running `maven install` (probably `maven test` would be enough) on a fresh clone of the repo git reports a lot of untracked files in `liquibase-standard/src/test/java/liquibase/verify/saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets/`.

### Steps To Reproduce

run `maven test` (i just ran `maven install` which includes this)

### Expected/Desired Behavior

since other files in there are checked in but they also get generated on the fly i'm not sure what your intention is:
* either they're always generated and don't need to be checked in, then you should remove them and add that folder to `.gitignore`
* or they should be checked in, in this case you need to add all the missing ones and commit them (and ensure that they're always being committed every time the underlying things (i don't know what's generating them) change

### Liquibase Version

commit 2abd351ab (current HEAD at time of build)

### Database Vendor & Version

_No response_

### Liquibase Integration

_No response_

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

_No response_

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by MalloD12**
As discussed recently to avoid confusion on people we have decided to move `saved_state/compareGeneratedSqlWithExpectedSqlForMinimalChangesets` SQL files from the java source directory and place them all in the resources bundle.

Fixes #5335 

## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Things to be aware of
- None

## Things to worry about
- None

### CODE REVIEW

**Comment by MalloD12** [comment]
@tati-qalified - @rursprung Guys when you have a chance, could you please try pulling this branch and then running either `mvn clean install` or `mvn test` and then run `git status` to see whether you are getting all these files untracked. After moving them to the `resources` bundle I don't see them changed after running any of these `mvn` commands.

Thanks,
Daniel.

**Comment by MalloD12** [comment]
> Hey @MalloD12 - don't you need to change the path at AbstractVerifyTest.java:39 to point to this new path?

Yeap, I think you are right @filipelautert. I didn't update it because all tests were successfully passing, but it makes total sense to update that path. I'll do it and make sure all tests keep passing.

Thanks,
Daniel.

**Comment by MalloD12** [comment]
> Hey @MalloD12 - don't you need to change the path at AbstractVerifyTest.java:39 to point to this new path?

Done!

**Comment by tati-qalified** [comment]
@MalloD12 tested - seems to work as expected!
Here's the output of running `mvn test` and `git status`:
image

**Comment by rursprung** [comment]
i guess in this case i don't need to try this as well since it should reproduce the same way for all of us? :)

**Review by filipelautert — APPROVED** [review]

**Pull request merged**
