### PR TITLE
Define and reuse constants. Use an empty array styles to convert a collection to an array.

### PR DESCRIPTION
**Pull request by arturobernalg**
## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [X ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Define and reuse constants. Use an empty array styles to convert a collection to an array.
There are two styles to convert a collection to an array:
 
A pre-sized array, for example, c.toArray(new String[c.size()])
An empty array, for example, c.toArray(new String[0])

In older Java versions, using a pre-sized array was recommended, as the reflection call necessary to create an array of proper size was quite slow.
However, from  OpenJDK 6, this call was intrinsified, making the performance of the empty array version the same, and sometimes even better, compared to the pre-sized version. 

## Things to be aware of

N/A

## Things to worry about

N/A

## Additional Context

N/A

### CODE REVIEW

**Comment by nvoxland** [comment]
**Initial/Pre-Review Thoughts**

Yes, changes make sense. Getting the size for an array is unnecessary nowadays and a shared constant is good.

Questions I have:

- Are the constants defined in the right spots? Maybe could put them on the interfaces they are an array of? Like Statement.EMPTY_STATEMENT_ARRAY and Change.EMPTY_CHANGE_ARRAY etc?

Potential risks:

- None, if it's just changing new Object[size] instantiations to constants.

What could make the full review difficult:

- Nothing

**Comment by MalloD12** [comment]
## Review and testing results:

This PR looks good to me. I have only applied a few minor changes of moving some constants from an abstract class to the related interfaces. From the Liquibase project, this looks ok (all tests passed), but before approving it I would wait until all checks are green.

Thanks again @arturobernalg for your contribution, I really like this kind of change to reuse lines of code and improve readability.

### Things to be aware of:
- None

### Things to worry about:
- None

**Review by MalloD12 — APPROVED** [review]
Approved!

**Comment by arturobernalg** [comment]
thank you all.

**Pull request merged**
