### PR TITLE
[CORE-3205] Change Log Parameters from Environment Variable

### PR DESCRIPTION
**Pull request by tomcruise81**
Proposal for implementation of [CORE-3205]

### CODE REVIEW

**Comment by tomcruise81** [comment]
What needs to be done in order to get someone to review this?

**Comment by tomcruise81** [comment]
@nvoxland - **THANK YOU SOOO MUCH!!**

**Comment by maksymgendin** [comment]
@tomcruise81 @nvoxland Hey guys, just wanted to tell you that I've lost almost one working day on tracing a breaking checksum validation in my environment.

On my local machine (Windows) a different checksum was generated than on an integration test machine (Linux). The reason for this was a `${os}` string in one of my SQL insert statements in the Liquibase changelog :)

`liquibase.changelog.ChangeLogParameters` replaced this with different values per operating system and this caused the validation error. This is kind of a breaking change and was not properly communicated in the release notes...

**Comment by maksymgendin** [comment]
I fixed it running this on startup:
```java
LiquibaseConfiguration.getInstance()
                      .getConfiguration(ChangeLogParserCofiguration.class)
                      .setSupportPropertyEscaping(true);
```
and replacing `${os}` with `${:os}` in my Liquibase changelog file.

**Pull request merged**
