### PR TITLE
fix loading clob data into postgres

### PR DESCRIPTION
**Pull request by jidma**
Data loaded from CLOB type columns is not loaded properly into PostgreSQL.
Instead of loading the content of the CLOB file, the filename is loaded.

See issue #1790 

When the data needs a prepared statement to be executed (example CLOB) and the database does not support batch mode (example PostgreSQL), the statement is executed as a normal statement and the the text string (the filename of the clob) is inserted instead of the content of the CLOB. 

## Environment
**Liquibase Version**:
4.4.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI and Spring boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
PostgreSQL

**Operating System Type & Version**:
Windows 10 (irrelevent)

## Pull Request Type

* [x] Bug fix (non-breaking change which fixes an issue.)
* [ ] Enhancement/New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
See issue #1790 

## Fast Track PR Acceptance Checklist:

* [x] Build is successful and all new and existing tests pass
* [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
* [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
* [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
* [ ] Documentation Updated

## Test Requirements (Internal Liquibase QA)
**Automated Functional Test Requirements**

* Add a functional regression test for Postgres
  * Replicate the steps and expected outcome listed in the Manual Test Requirements section.

**Manual Test Requirements**

For the following tests, use the attached changelog lb-1423.xml and  files lb-1423.txt and fake-data.txt.

_Verify update~~sql shows the contents of fake~~data.txt in the insert for the clob column._

_Verify update is successful._

_Verify the table1 has the contents of fake-data.txt in the clob column._

---

#### Links

- Fixed Issue: https://github.com/liquibase/liquibase/issues/1790
- Local Branch: https://github.com/liquibase/liquibase/tree/jidma-fix-loading-clob
- Unit Tests: https://github.com/liquibase/liquibase/pull/1791/checks
- Integration Tests: (shown in Unit Tests link above)
- Functional Tests: https://jenkins.datical.net/job/liquibase-pro/job/jidma-fix-loading-clob/

#### Testing

- Steps to Reproduce: https://github.com/liquibase/liquibase/issues/1790
- Guidance:
  - The fix had a lot of back and forth making sure it worked correctly by default, and also respected the usePreparedStatements flag. Read through the comments on this ticket as well.
  - Fix impacts postgresql primarily, but cleans up logic that is used by all databases.

#### Dev Verification

Did not save output, but did testing with postgresql, mysql, and oracle beyond what done with the automated tests.

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

┆Issue is synchronized with this [Jiraserver Story](https://datical.atlassian.net/browse/LB-1423) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by molivasdat** [comment]
Hi @jidma Thanks for writing up this fix.  Let us know when you are ready to pull it out of draft status and are finished with your fix.

**Comment by jidma** [comment]
> Hi @jidma Thanks for writing up this fix. Let us know when you are ready to pull it out of draft status and are finished with your fix.

Hi @molivasdat, the code I commited seems to solve the problem.
However I currently have some failing CI tests. I am not sure if my code breaks something elsewhere.
Can you please review and guide me to the right direction ?

**Comment by molivasdat** [comment]
Hi @jidma We have a new build process.  If those new builds fail I will take a look, if they succeed you should have a test fix for your issue.

**Comment by nvoxland** [comment]
It may have been a problem in master when you branched and/or fixed separately. I merged from master and pushed to your fork and will see what the build does next.

Otherwise, your changes look good. The rename of batchedStatements to preparedStatements helps with following the logic better. Thanks.

**Review by nvoxland — APPROVED** [review]

**Comment by nvoxland** [comment]
I think I found the problem with the failing tests. Postgresql's driver must be caching enum names -> ids somewhere/somehow and when our tests keep dropping/adding ones with the same names it gets confused. 

That was the original issue we were trying to address with #1446 which this PR had to undo to fix the clob functionality. I am forcing the connection to be closed in the integration tests which will hopefully fix the tests

**Review by suryaaki2 — APPROVED** [review]

**Comment by nvoxland** [comment]
The tests are continuing to fail. They are highlighting how we handle "we should use prepared statements" vs. "database doesn't support prepared statements".

I'll look into it more

**Comment by nvoxland** [comment]
I had accidentally pushed an unrelated change to your branch, so I force pushed a new version that builds directly off your original commit. Sorry about that.

I updated the "use prepared statements" logic a bit to make sure it respects usePreparedStatement=true|false primarily, and then falls back to "should we use them" logic as a backup. It also throws an exception if usePreparedStatements=false but we need to use a prepared statement instead of silently going against their wishes.

**Pull request merged**
