### PR TITLE
StringBuffer -> StringBuilder

### PR DESCRIPTION
**Pull request by asolntsev**
* also added unit-tests for some of changed code (which was not covered by unit-tests)
* in some places, I replaced StringBuffer by just constant String or String.format()

### CODE REVIEW

**Comment by asolntsev** [comment]
@nvoxland ping

**Comment by asolntsev** [comment]
@nvoxland @stupiddog1979 @mches @mattbertolini
Sorry for disturbing you, but can somebody review the PR?

**Comment by iherasymenko** [comment]
@asolntsev just out of curiosity. Does your PR fix some performance bottleneck?

**Comment by asolntsev** [comment]
@iherasymenko no. It's more about cleaning the code and increasing code coverage.

**Comment by nvoxland** [comment]
Thanks, it does help keep things more readable

**Pull request merged**
