### PR TITLE
Run expected integration tests, fix tests that were not run (DAT-13751)

### PR DESCRIPTION
**Pull request by abrackx**
## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description
Integration tests not marked with the suffix `IntegrationTest` are being ignored during our integration test workflow. This pr updates these tests to have the suffix and fixes `DiffChangelogIntegrationTest` which was failing locally but not in the pipeline, because it was not being executed.

### CODE REVIEW

**Review by wwillard7800 — APPROVED** [review]
Thanks for the fix!

**Review by StevenMassaro — APPROVED** [review]

**Review by filipelautert — APPROVED** [review]
After all tests passes it's ready to go!

**Review by filipelautert — APPROVED** [review]

**Review by StevenMassaro — APPROVED** [review]
Nice!

Do you think we should update the surefire plugin properties to also recognize files that end only in `Test`?

**Comment by StevenMassaro** [comment]
> > Nice!
> > Do you think we should update the surefire plugin properties to also recognize files that end only in `Test`?
> 
> I think we should examine other options (like using `@Category` or `@Tag` in junit5) to run the specific suites. That may simplify things going forward and we won't need any specific suffix to match.

I was thinking along the lines of ensuring that no developer needs to remember to do "something" in order for the tests to run. They can just write a test class, call it `WhateverTest.groovy` or `WhateverIntegrationTest.groovy` or `WhateverIT.groovy` and it'll get picked up automatically. Is that not within the realm of possibility? Maybe it has other undesirable side effects I'm not thinking of.

**Pull request merged**
