### PR TITLE
enable REPLACE OR EXISTS for procedures on DB2

### LINKED ISSUE #4388: DB2 supports REPLACE OR EXISTS for procedures
### Search first

- [X] I searched and no similar issues were found

### Description

Although DB2 supports "CREATE OR REPLACE PROCEDURE", I cannot configure this but get the error message 

> Unexpected error running Liquibase: Validation Failed:
     1 changes have validation failures
          replaceIfExists is not allowed on db2z, test.xml::xxx-1::a61kern

### Steps To Reproduce

Try to execute a ChangeSet with createProcedure and replaceIfExists="true".

### Expected/Desired Behavior

The ChangeSet is executed correctly.

### Liquibase Version

4.20

### Database Vendor & Version

DB2z 12.1

### Liquibase Integration

CLI

### Liquibase Extensions

_No response_

### OS and/or Infrastructure Type/Provider

Windows 10 Pro

### Additional Context

_No response_

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

### PR DESCRIPTION
**Pull request by MichaelKern-IVV**
## Impact

- [X, Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Fixes #4388

### CODE REVIEW

**Comment by filipelautert** [comment]
Hello @MichaelKern-IVV , seems we are missing an import at  liquibase-standard/src/main/java/liquibase/change/core/CreateProcedureChange.java?

**Comment by MichaelKern-IVV** [comment]
You are right, I added the missing import.

**Review by filipelautert — APPROVED** [review]
DB2 specific changes, thanks for another improvement @MichaelKern-IVV !

**Comment by suryaaki2** [comment]
Is it possible to write some tests?

**Comment by rberezen** [comment]
> Is it possible to write some tests?

Created a ticket [DAT-15523](https://datical.atlassian.net/browse/DAT-15523) to add a test into Test Harness.

**Review by rberezen — APPROVED** [review]
This pull request introduces support for createProcedure changeset with replaceIfExists="true" attribute for DB2 and DB2z platforms.

- Functional and test harness executions passing.
- Manual testing completed.
- Test in Test Harness will be added in scope of DAT-15523 

APPROVED

**Review by suryaaki2 — APPROVED** [review]

**Pull request merged**
