### PR TITLE
Fix load relative file

### LINKED ISSUE #2074: Child of #1277: Error loading relative file when logicalFilePath is set (Breaks migration from 3.x to 4.x)
## Environment

**Liquibase Version**: 4.4.3 (and all 4.x, not in 3.x)

**Liquibase Integration & Version**: any

**Liquibase Extension(s) & Version**:  liquibase-core

**Database Vendor & Version**: H2 (and all others)

**Operating System Type & Version**: Windows 10 (and all others)

## Description

In https://github.com/liquibase/liquibase/issues/1277 @darkcamper reported an error about loading sql scripts relative to a change log file whicht has a 'logicalFilePath' set.

This has been fixed in https://github.com/liquibase/liquibase/pull/1798 but it has been overlooked that the same error is present in
- `LoadDataChange`,
- `CreateProcedureChange` and 
- `CreateViewChange`

A PR to fix this can be found here: https://github.com/liquibase/liquibase/pull/2073

## Steps To Reproduce

See https://github.com/liquibase/liquibase/pull/2073

## Actual Behavior

See https://github.com/liquibase/liquibase/pull/2073

## Expected/Desired Behavior

See https://github.com/liquibase/liquibase/pull/2073

### PR DESCRIPTION
**Pull request by smainz**
## Environment
**Liquibase Version**: 4.4.3 (and all 4.x before)

**Liquibase Integration & Version**: any

**Liquibase Extension(s) & Version**:  liquibase-core

**Database Vendor & Version**: H2 (and all others)

**Operating System Type & Version**: Windows 10 (and all others)

## Pull Request Type
* \[x] Bug fix (non-breaking change which fixes an issue.) [https://github.com/liquibase/liquibase/pull/1798](https://github.com/liquibase/liquibase/pull/1798) fixed the problem of loading files relative for SQLFileChange, but not for LoadDataChange,  CreateProcedureChange or CreateViewChange. This PR solves this. closes #2074
* \[ ] Enhancement/New feature (non-breaking change which adds functionality)
* \[ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
See #1277, but for  LoadDataChange,  CreateProcedureChange or CreateViewChange.
Testcases showing the problem are included in this PR.

Same as [https://github.com/liquibase/liquibase/pull/2060](https://github.com/liquibase/liquibase/pull/2060) but with different branch name. My branch name had chars which broke the build.

## Steps To Reproduce
List the steps to reproduce the behavior.

* create a changelog file with these change sets

```java
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
				     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				     xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                      http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.10.xsd"
				     logicalFilePath="a-logical-file-path"
>
	  <changeSet id="1" author="author">
		  <loadData file="data/some_data.csv" tableName="a_tabe"
				   relativeToChangelogFile="true"></loadData>
	  </changeSet>

	  <changeSet id="2" author="author">
		  <createProcedure path="sql/proc.sql"
						   relativeToChangelogFile="true"></createProcedure>
	  </changeSet>

	  <changeSet id="3" author="author">
		  <createView path="sql/view.sql" viewName="a_view"
					  relativeToChangelogFile="true"></createView>
	  </changeSet>

</databaseChangeLog>
```

* Create these files  (may be empty)
  * `data/some_data.csv`
  * `sql/proc.sql`
  * `sql/view.sql`
* Run liquibase update against the db

```java
liquibase --driver=com.microsoft.sqlserver.jdbc.SQLServerDriver --url="jdbc:sqlserver://localhost:1433;database=the_database" --changeLogFile=changelog.xml  --username=the_username --password=thepassword --logLevel=debug update
```

* See it fail 
* Comment the changeset and repeat (fails for all three)

## Actual Behavior
Liquibase throws an exception complaining about missing file (a different one for each changeset):

```java
liquibase.exception.LiquibaseException: liquibase.exception.UnexpectedLiquibaseException: File 'data/some_data.csv' not found
```

## Expected/Desired Behavior
Liquibase does not complain about missing files and works flawlessly.

## Additional Context
Same bug has already been fixed in  [https://github.com/liquibase/liquibase/pull/1798](https://github.com/liquibase/liquibase/pull/1798) for a diffenent change. The changes above have been overlooked.

I had to fix an existing testcase which used a changeset not included in an changelog. 

## Fast Track PR Acceptance Checklist:
* \[x] Build is successful and all new and existing tests pass (all in liquibase.core)
* \[x] Added [Unit Test(s)] Enhanced existing unit tests 
* \[ ] Added [Integration Test(s)]
* \[ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
* \[ ] Documentation Updated

- - -
#### Links
* Fixed Issue: [https://github.com/liquibase/liquibase/issues/2074](https://github.com/liquibase/liquibase/issues/2074)
* Test Results: [https://github.com/liquibase/liquibase/pull/2073/checks](https://github.com/liquibase/liquibase/pull/2073/checks)

#### Testing
* Steps to Reproduce: [https://github.com/liquibase/liquibase/issues/2074](https://github.com/liquibase/liquibase/issues/2074)
* Guidance:
  * Impact: loadData, createProcedure, and createView change types

#### Dev Verification
Created a changeset with the above example changes and saw they failed in 4.6.2 with "cannot find file" errors. With the PR, they all correctly find the files.

## Test Requirements (Internal Liquibase QA)
* Create these files  (examples are attached)
  * `data/names.csv`
  * `sql/proc.sql`
  * `sql/view.sql`

**Manual Test Requirements**
_Verify update is successful with load relative files._

* `liquibase update --changelog-file lb-2179-changelog.xml`
* Update is executed successfully
* No exception is thrown
* Table `populated` exists
* table `populated` contains data from `names.csv`
* View `someview` exists
* Procedure `SomeProcedure` exists

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-2179) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by nvoxland** [comment]
I pushed the current version of master to your fork to fix the build issue.

**Comment by molivasdat** [comment]
Hi @smainz Thanks for creating this PR.

A member of the Liquibase team will take a look at your contribution and may suggest: 

- Changes based on [guidelines for PR submission](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core)
- Additional tests ([unit ](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)and/or [integration](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)) and/or [Test Harness Tests](https://github.com/liquibase/liquibase-test-harness/pulls)
- Provide other feedback, like requesting changes. 

The PR will be prioritized according to our internal development and testing capacity.

We’ll let you know when it’s ready to move to the next step or if any changes are needed.

**Comment by smainz** [comment]
Is there anything I can help to get this PR reviewed/approved?

**Review by nvoxland — APPROVED** [review]

**Comment by nvoxland** [comment]
Thanks you for the very good PR!

**Review by suryaaki2 — APPROVED** [review]

**Pull request merged**
