### PR TITLE
enable 'includeAll' directive to work with liquibase resources provided in OSGi bundle

### PR DESCRIPTION
**Pull request by ktor**
## Environment

**Liquibase Version**: 4.4.0

**Liquibase Integration & Version**: liquibase-core 4.4.0 as a bundle in Apache Felix OSGi container, Liferay portal 7.4

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Postgresql 11.4

**Operating System Type & Version**: Linux

## Pull Request Type

- [ ] Bug fix (non-breaking change which fixes an issue.)
- [x] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

I've succesfully used `liquibase-core` deployed as a bundle to Liferay Portal. Another sibling bundle provided `changelog.xml` together with BundleActivator code which executed the `changelog.xml` just fine.

I wanted to organize migration steps in separate files under a directory and used `includeAll` `changelog.xml` directive. The executor code however haven't found any of the migration files except for the entrypoint `changelog.xml` in which `includeAll` directive was declared.

`BundleActivator.java`:
```java
        ...
        ResourceAccessor resourceAccessor = new OSGIResourceAccessor(BundleActivator.class);
        try (Liquibase liquibase = new Liquibase("changelog.xml", resourceAccessor, database)) {
            LockServiceFactory.reset();
            liquibase.update(new Contexts());
        }
        ...
```

The pull requests contains modification of existing `OSGiResourceAccessor` class so that it supports traversing of an OSGi bundle directory structure which provides entrypoint `changelog.xml` and migration resources/paths declared in it.

## Steps To Reproduce

1. Prepare OSGi bundle with following `changelog.xml` resource:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd">

    <includeAll path="steps/" relativeToChangelogFile="true"/>

</databaseChangeLog>
```
2. Add migration step `steps/0001-init.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
    xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd">

    <changeSet id="1_add-initial-schema" author="ktor">
        <createTable tableName="test">
            <column name="id" type="uuid">
                <constraints primaryKey="true" nullable="false"/>
            </column>
        </createTable>
    </changeSet>
</databaseChangeLog>
```

## Actual Behavior
`changelog.xml` is read however no resources in `steps/` bundle directory are loaded. 

## Expected/Desired Behavior
`changelog.xml` is read and resources in `steps/` bundle directory are loaded. 

## Screenshots (if appropriate)
n/a

## Additional Context
n/a

## Fast Track PR Acceptance Checklist:

- [x] Build is successful and all new and existing tests pass
- [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
- [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
- [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
- [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

### CODE REVIEW

**Comment by filipelautert** [comment]
@ktor thanks for the patch and sorry for the delay to evaluate it. I donwloaded your branch and updated it with master, but I found out that we did some changes to ResourceAccessor inteface that broke your code. Basically search and getAll methods were added while list and openStream were deprecated.
image

Would you be able to update your code to implement those methods?  I'll keep the pr assigned to me so we can get it moving now. Thanks!

**Comment by ktor** [comment]
> Would you be able to update your code to implement those methods? I'll keep the pr assigned to me so we can get it moving now. Thanks!

Hi @filipelautert, I may get to it over the weekend.

**Comment by filipelautert** [comment]
Hi @ktor , do you think you can review it soon? If so we can make it into 4.18 release.

**Comment by nvoxland** [comment]
I think this was fixed as part of #3378 that went out in 4.21.0. 

If anyone is still having this problem, let us know.

**Pull request closed without merging**
