### PR TITLE
Fixed #3487 Provide precision and scale for currency database datatype and H2.

### LINKED ISSUE #3487: Mapping of CURRENCY datatype for the H2 database is missing precision and scale
As of H2 2.0.202, the DECIMAL datatype without parameters has scale 0, thus it cannot hold any value after the decimal point.

https://www.h2database.com/html/migration-to-v2.html

The Liquibase CURRENCY database is being mapped to a DECIMAL datatype with no precision and scale for H2, which causes the values to be stored a whole numbers rather than decimal numbers.

https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/datatype/core/CurrencyType.java

This was not an issue with H2 1.4.200

Using H2 1.4.200:
image

Using H2 2.1.214:
image

### PR DESCRIPTION
**Pull request by jccampanero**
## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Fixes #3487.

As explained in the companion issue, as of H2 2.0.202, the `DECIMAL` datatype without parameters has scale `0`, thus it cannot hold any value after the decimal point.

Liquibase maps the `CURRENCY` database type to `DECIMAL` with no precision and scale for H2, which causes the values to be stored as whole numbers rather than decimal numbers.

The proposed changes include such as precision and scale.

### CODE REVIEW

**Comment by nvoxland** [comment]
Initial review:

Changes make sense to me and is isolated to h2

Things to be aware of:
- Nothing

Things to worry about:
- Nothing

**Comment by jccampanero** [comment]
You are welcome @MalloD12 Daniel, my pleasure. And thank you very much for providing the unit tests for the changes proposed in the PR.

**Review by suryaaki2 — APPROVED** [review]

**Comment by XDelphiGrl** [comment]
Test harness execution started here: [https://github.com/liquibase/liquibase-test-harness/actions/runs/4853288812](https://github.com/liquibase/liquibase-test-harness/actions/runs/4853288812)

**Review by XDelphiGrl — APPROVED** [review]
The H2 update from 1.x to 2.x changed the default scale to zero for the NUMERIC and DECIMAL datatypes. When Liquibase is passed a changelog with datatype `CURRENCY`, and the database is H2, Liquibase "translates" `CURRENCY` to `DECIMAL`. In v2.x H2, this resulted in a `DECIMAL(0)` datatype and inserting data with digits beyond the decimal resulted in truncation of the data to include only digits preceding the decimal. This PR addresses the deficiency by "translating" `CURRENCY` to `DECIMAL(18,4)` for the H2 database.
* Validated this fix for H2 1.4.200 (no negative impact)
* Validated this fix for H2 2.1.214 (data is no longer truncated on insert).
* Test Harness execution passing.
* No additional testing required.

APPROVED

**Comment by jccampanero** [comment]
Thank you very much for merging this functionality.

**Comment by marwin1991** [comment]
@jccampanero 

hello,  I am wondering why 18,4 not 18,2 precission ?

**Comment by jccampanero** [comment]
> @jccampanero
> 
> hello, I am wondering why 18,4 not 18,2 precission ?

Thank you for the question @marwin1991 Peter.

I asked myself the same when I was implementing the change.

Initially I thought a precision of `2` would be indeed the right choice because a great amount of currencies, US dollar, euro, pound, to name some of them, have two fractions digits, i.e., they use cents or pence.

But in the end I used `4` because I think it could fit a broader amount of currencies such as cryptocurrencies.

In addition, in Liquibase other databases such as DB2 and Firebird use `4` as the default precision.

In any case, `2` is a perfect solution as well.

**Pull request merged**
